; Generated by sprout ir_lowering.sprout (M2 PR 2.3)
target triple = "unknown-unknown-unknown"
declare i64 @str_concat(i64, i64)
declare i1 @str_eq(ptr, ptr)
declare i64 @str_compare(i64, i64)
declare i64 @str_slice(i64, i64, i64)
declare i64 @int_to_string(i64)
declare i64 @char_to_string(i64)
declare i64 @sprout_gc_push_i64_root(ptr)
declare i64 @sprout_gc_pop_roots(i64)
declare i64 @sprout_gc_register_i64_root(ptr)
declare i64 @sprout_alloc_closure(i64, i64)
declare void @sprout_closure_arity_check(i64, i64)
declare i64 @sprout_alloc_tuple_blob(i64)
declare i64 @sprout_register_ctor(i64, ptr, i64, ptr)
declare i64 @sprout_tag(i64)
declare i64 @sprout_field(i64, i64)
declare void @sprout_abort_match() noreturn
declare i64 @panic(i64)
declare ptr @llvm.stacksave()
declare void @llvm.stackrestore(ptr)
declare { i64, i1 } @llvm.sadd.with.overflow.i64(i64, i64)
declare { i64, i1 } @llvm.ssub.with.overflow.i64(i64, i64)
declare { i64, i1 } @llvm.smul.with.overflow.i64(i64, i64)
declare i64 @sprout_alloc_obj(i64, i64)
declare { i64, i64 } @vector_get_unboxed(i64, i64)
declare { i64, i64 } @map_get_unboxed(i64, i64)
declare { i64, i64 } @map_nth_key_unboxed(i64, i64)
declare { i64, i64 } @map_nth_value_unboxed(i64, i64)
declare { i64, i64 } @bytes_get_unboxed(i64, i64)
declare { i64, i64 } @str_char_at_unboxed(i64, i64)
declare { i64, i64 } @argv_get_unboxed(i64)
declare { i64, i64 } @env_get_unboxed(i64)
declare i64 @print_str(ptr)
declare i64 @print_value(i64)
declare i64 @eprint_str(ptr)
declare i64 @argv_get(i64)
declare i64 @sprout_set_argv(i32, ptr)
declare i64 @analysis_check_source(ptr)
declare i64 @analysis_declared_names_in_source(ptr)
declare i64 @analysis_exported_names_in_source(ptr)
declare i64 @analysis_symbol_inventory_in_source(ptr)
declare i64 @analysis_diagnostics_in_source(ptr)
declare i64 @analysis_symbol_locations_in_source(ptr)
declare i64 @analysis_type_of_in_source(ptr, ptr)
declare i64 @analysis_eval_expr_in_source(ptr, ptr)
declare i64 @analysis_instances_in_source(ptr, ptr)
declare i64 @analysis_complete_in_state(ptr, ptr, ptr)

declare i64 @double_to_string(i64)
declare i64 @char_to_str(i64)
declare i64 @char_from_codepoint(i64)
declare i64 @to_double(i64)
declare i64 @string_concat_many(i64)
declare i64 @str_len(i64)
declare i64 @str_char_at(i64, i64)
declare i64 @str_find(i64, i64)
declare i64 @str_starts_with(i64, i64)
declare i64 @vector_empty()
declare i64 @vector_length(i64)
declare i64 @vector_get(i64, i64)
declare i64 @vector_set(i64, i64, i64)
declare i64 @vector_append(i64, i64)
declare i64 @vector_concat(i64, i64)
declare i64 @vector_from_list(i64)
declare i64 @map_empty()
declare i64 @map_get(i64, i64)
declare i64 @map_set(i64, i64, i64)
declare i64 @map_remove(i64, i64)
declare i64 @map_size(i64)
declare i64 @map_nth_key(i64, i64)
declare i64 @map_nth_value(i64, i64)
declare i64 @native_set_empty()
declare i64 @native_set_insert(i64, i64)
declare i64 @native_set_member(i64, i64)
declare i64 @native_set_to_list(i64)
declare i64 @native_set_size(i64)
declare i64 @ref_new(i64)
declare i64 @ref_read(i64)
declare i64 @ref_write(i64, i64)
declare i64 @double_to_bits(i64)
declare i64 @double_from_bits(i64)
declare i64 @term_clear()
declare i64 @term_move(i64, i64)
declare i64 @term_hide_cursor()
declare i64 @term_show_cursor()
declare i64 @term_is_interactive()
declare i64 @term_read_key()
declare i64 @term_read_line()
declare i64 @term_write(i64)
declare i64 @term_raw_enter()
declare i64 @term_raw_exit()
declare i64 @term_size()
declare i64 @term_read_avail(i64, i64)
@.str.0 = private unnamed_addr constant { i64, [20 x i8] } { i64 311306, [20 x i8] c"sin 60deg        : \00" }
@.str.1 = private unnamed_addr constant { i64, [2 x i8] } { i64 16394, [2 x i8] c"\0A\00" }
@.str.2 = private unnamed_addr constant { i64, [20 x i8] } { i64 311306, [20 x i8] c"60deg + 23.44deg : \00" }
@.str.3 = private unnamed_addr constant { i64, [2 x i8] } { i64 16394, [2 x i8] c"\0A\00" }
@.str.4 = private unnamed_addr constant { i64, [20 x i8] } { i64 311306, [20 x i8] c"1 AU in km       : \00" }
@.str.5 = private unnamed_addr constant { i64, [2 x i8] } { i64 16394, [2 x i8] c"\0A\00" }
@.str.6 = private unnamed_addr constant { i64, [55 x i8] } { i64 884746, [55 x i8] c"all three mistakes above are rejected at compile time\0A\00" }
@.cname.0 = private unnamed_addr constant [8 x i8] c"Nothing\00"
@.cfkinds.0 = private unnamed_addr constant [1 x i8] c"\00"
@.cname.1 = private unnamed_addr constant [5 x i8] c"Just\00"
@.cfkinds.1 = private unnamed_addr constant [2 x i8] c"_\00"
@.cname.2 = private unnamed_addr constant [12 x i8] c"TemplateLit\00"
@.cfkinds.2 = private unnamed_addr constant [2 x i8] c"s\00"
@.cname.3 = private unnamed_addr constant [15 x i8] c"TemplateInterp\00"
@.cfkinds.3 = private unnamed_addr constant [2 x i8] c"s\00"
@.cname.4 = private unnamed_addr constant [15 x i8] c"StringTemplate\00"
@.cfkinds.4 = private unnamed_addr constant [2 x i8] c"p\00"
@.cname.5 = private unnamed_addr constant [4 x i8] c"Nil\00"
@.cfkinds.5 = private unnamed_addr constant [1 x i8] c"\00"
@.cname.6 = private unnamed_addr constant [5 x i8] c"Cons\00"
@.cfkinds.6 = private unnamed_addr constant [3 x i8] c"_p\00"
@.cname.7 = private unnamed_addr constant [3 x i8] c"Ok\00"
@.cfkinds.7 = private unnamed_addr constant [2 x i8] c"_\00"
@.cname.8 = private unnamed_addr constant [4 x i8] c"Err\00"
@.cfkinds.8 = private unnamed_addr constant [2 x i8] c"_\00"
@.cname.9 = private unnamed_addr constant [10 x i8] c"DivByZero\00"
@.cfkinds.9 = private unnamed_addr constant [1 x i8] c"\00"
@.cname.10 = private unnamed_addr constant [4 x i8] c"Vec\00"
@.cfkinds.10 = private unnamed_addr constant [2 x i8] c"p\00"
@.cname.11 = private unnamed_addr constant [5 x i8] c"Dict\00"
@.cfkinds.11 = private unnamed_addr constant [2 x i8] c"p\00"
@.cname.12 = private unnamed_addr constant [4 x i8] c"Set\00"
@.cfkinds.12 = private unnamed_addr constant [2 x i8] c"p\00"
@.cname.13 = private unnamed_addr constant [9 x i8] c"IntRange\00"
@.cfkinds.13 = private unnamed_addr constant [4 x i8] c"iii\00"
@.cname.14 = private unnamed_addr constant [25 x i8] c"stdlib.terminal.TermSize\00"
@.cfkinds.14 = private unnamed_addr constant [3 x i8] c"ii\00"
@.cname.15 = private unnamed_addr constant [26 x i8] c"stdlib.terminal.TermBytes\00"
@.cfkinds.15 = private unnamed_addr constant [2 x i8] c"p\00"
@.cname.16 = private unnamed_addr constant [25 x i8] c"stdlib.terminal.TermIdle\00"
@.cfkinds.16 = private unnamed_addr constant [1 x i8] c"\00"
@.cname.17 = private unnamed_addr constant [28 x i8] c"stdlib.terminal.TermResized\00"
@.cfkinds.17 = private unnamed_addr constant [1 x i8] c"\00"
@.cname.18 = private unnamed_addr constant [24 x i8] c"stdlib.terminal.TermEof\00"
@.cfkinds.18 = private unnamed_addr constant [1 x i8] c"\00"
@.cname.19 = private unnamed_addr constant [27 x i8] c"stdlib.terminal.TermFailed\00"
@.cfkinds.19 = private unnamed_addr constant [2 x i8] c"s\00"
@.cname.20 = private unnamed_addr constant [32 x i8] c"examples.wrap_phantom_units.Deg\00"
@.cfkinds.20 = private unnamed_addr constant [1 x i8] c"\00"
@.cname.21 = private unnamed_addr constant [32 x i8] c"examples.wrap_phantom_units.Rad\00"
@.cfkinds.21 = private unnamed_addr constant [1 x i8] c"\00"
@.cname.22 = private unnamed_addr constant [31 x i8] c"examples.wrap_phantom_units.Km\00"
@.cfkinds.22 = private unnamed_addr constant [1 x i8] c"\00"
@.cname.23 = private unnamed_addr constant [31 x i8] c"examples.wrap_phantom_units.Au\00"
@.cfkinds.23 = private unnamed_addr constant [1 x i8] c"\00"
@list_builder_empty = global i64 zeroinitializer
@pow10_clamp = private constant i64 400
@max_int = private constant i64 9223372036854775807
@pow10_exact_max = private constant i64 22
@pow10_exact_unit = global i64 zeroinitializer
@pow10_finite_max = private constant i64 308
@stdlib.math.pi = global i64 zeroinitializer
@stdlib.math.two_pi = global i64 zeroinitializer
@stdlib.math.half_pi = global i64 zeroinitializer
@stdlib.math.two52 = global i64 zeroinitializer
@stdlib.math.two8 = global i64 zeroinitializer
@stdlib.math.two12 = global i64 zeroinitializer
@stdlib.math.two16 = global i64 zeroinitializer
@stdlib.math.two32 = global i64 zeroinitializer
@stdlib.math.two48 = global i64 zeroinitializer
@stdlib.math.two54 = global i64 zeroinitializer
@stdlib.math.two64 = global i64 zeroinitializer
@stdlib.math.two128 = global i64 zeroinitializer
@stdlib.math.two256 = global i64 zeroinitializer
@stdlib.math.two384 = global i64 zeroinitializer
@stdlib.math.two512 = global i64 zeroinitializer
@stdlib.math.inv_two8 = global i64 zeroinitializer
@stdlib.math.inv_two12 = global i64 zeroinitializer
@stdlib.math.inv_two16 = global i64 zeroinitializer
@stdlib.math.inv_two32 = global i64 zeroinitializer
@stdlib.math.inv_two48 = global i64 zeroinitializer
@stdlib.math.inv_two64 = global i64 zeroinitializer
@stdlib.math.inv_two128 = global i64 zeroinitializer
@stdlib.math.inv_two256 = global i64 zeroinitializer
@stdlib.math.inv_two384 = global i64 zeroinitializer
@stdlib.math.inv_two512 = global i64 zeroinitializer
@stdlib.math.exp_field_unit = private constant i64 4503599627370496
@stdlib.math.exp_bias = private constant i64 1023
@stdlib.math.exp_floor_bias = private constant i64 1074
@stdlib.math.nan = global i64 zeroinitializer
@stdlib.math.ln2 = global i64 zeroinitializer
@stdlib.math.ln10 = global i64 zeroinitializer
@stdlib.math.inv_ln2 = global i64 zeroinitializer
@stdlib.math.sqrt2 = global i64 zeroinitializer
@stdlib.math.inv_sqrt2 = global i64 zeroinitializer
@stdlib.math.inf = global i64 zeroinitializer
@stdlib.math.neg_zero = global i64 zeroinitializer
@stdlib.math.two52_bits = private constant i64 4841369599423283200
@stdlib.math.two63 = global i64 zeroinitializer
@stdlib.terminal.esc = global i64 zeroinitializer
@examples.wrap_phantom_units.km_per_au = global i64 zeroinitializer

define i64 @stdlib.math.sq(i64 %p$v) {
entry:
  %t$0$la = bitcast i64 %p$v to double
  %t$0$lb = bitcast i64 %p$v to double
  %t$0$fr = fmul double %t$0$la, %t$0$lb
  %t$0 = bitcast double %t$0$fr to i64
  ret i64 %t$0
}

define i64 @stdlib.math.round_nearest_pos(i64 %p$x) {
entry:
  %t$0 = load i64, ptr @stdlib.math.two52
  %t$1$fa = bitcast i64 %p$x to double
  %t$1$fb = bitcast i64 %t$0 to double
  %t$1 = fcmp oge double %t$1$fa, %t$1$fb
  %t$2 = zext i1 %t$1 to i64
  %t$9 = trunc i64 %t$2 to i1
  br i1 %t$9, label %then_3, label %else_3
then_3:
  br label %join_3
else_3:
  %t$5 = load i64, ptr @stdlib.math.two52
  %t$6$la = bitcast i64 %p$x to double
  %t$6$lb = bitcast i64 %t$5 to double
  %t$6$fr = fadd double %t$6$la, %t$6$lb
  %t$6 = bitcast double %t$6$fr to i64
  %t$7 = load i64, ptr @stdlib.math.two52
  %t$8$la = bitcast i64 %t$6 to double
  %t$8$lb = bitcast i64 %t$7 to double
  %t$8$fr = fsub double %t$8$la, %t$8$lb
  %t$8 = bitcast double %t$8$fr to i64
  br label %join_3
join_3:
  %t$4 = phi i64 [%p$x, %then_3], [%t$8, %else_3]
  ret i64 %t$4
}

define i64 @stdlib.math.round_nearest(i64 %p$x) {
entry:
  %t$0 = bitcast double 0.0 to i64
  %t$1$fa = bitcast i64 %p$x to double
  %t$1$fb = bitcast i64 %t$0 to double
  %t$1 = fcmp olt double %t$1$fa, %t$1$fb
  %t$2 = zext i1 %t$1 to i64
  %t$11 = trunc i64 %t$2 to i1
  br i1 %t$11, label %then_3, label %else_3
then_3:
  %t$5 = bitcast double 0.0 to i64
  %t$6 = bitcast double 0.0 to i64
  %t$7$la = bitcast i64 %t$6 to double
  %t$7$lb = bitcast i64 %p$x to double
  %t$7$fr = fsub double %t$7$la, %t$7$lb
  %t$7 = bitcast double %t$7$fr to i64
  %t$8 = call i64 @stdlib.math.round_nearest_pos(i64 %t$7)
  %t$9$la = bitcast i64 %t$5 to double
  %t$9$lb = bitcast i64 %t$8 to double
  %t$9$fr = fsub double %t$9$la, %t$9$lb
  %t$9 = bitcast double %t$9$fr to i64
  br label %join_3
else_3:
  %t$10 = call i64 @stdlib.math.round_nearest_pos(i64 %p$x)
  br label %join_3
join_3:
  %t$4 = phi i64 [%t$9, %then_3], [%t$10, %else_3]
  ret i64 %t$4
}

define i64 @stdlib.math.floor(i64 %p$x) {
entry:
  %t$0 = call i64 @stdlib.math.round_nearest(i64 %p$x)
  br label %arm_0_1
arm_0_1:
  %t$3 = bitcast double 0.0 to i64
  %t$4$fa = bitcast i64 %p$x to double
  %t$4$fb = bitcast i64 %t$3 to double
  %t$4 = fcmp oeq double %t$4$fa, %t$4$fb
  %t$5 = zext i1 %t$4 to i64
  %t$15 = trunc i64 %t$5 to i1
  br i1 %t$15, label %then_6, label %else_6
then_6:
  br label %join_6
else_6:
  %t$8$fa = bitcast i64 %t$0 to double
  %t$8$fb = bitcast i64 %p$x to double
  %t$8 = fcmp ogt double %t$8$fa, %t$8$fb
  %t$9 = zext i1 %t$8 to i64
  %t$14 = trunc i64 %t$9 to i1
  br i1 %t$14, label %then_10, label %else_10
then_10:
  %t$12 = bitcast double 1.0 to i64
  %t$13$la = bitcast i64 %t$0 to double
  %t$13$lb = bitcast i64 %t$12 to double
  %t$13$fr = fsub double %t$13$la, %t$13$lb
  %t$13 = bitcast double %t$13$fr to i64
  br label %join_10
else_10:
  br label %join_10
join_10:
  %t$11 = phi i64 [%t$13, %then_10], [%t$0, %else_10]
  br label %join_6
join_6:
  %t$7 = phi i64 [%p$x, %then_6], [%t$11, %join_10]
  br label %join_1
arm_1_1:
  call void @sprout_abort_match()
  unreachable
join_1:
  %t$2 = phi i64 [%t$7, %join_6]
  ret i64 %t$2
}

define i64 @stdlib.math.reduce(i64 %p$x) {
entry:
  %t$0 = load i64, ptr @stdlib.math.two_pi
  %t$1 = load i64, ptr @stdlib.math.pi
  %t$2$la = bitcast i64 %p$x to double
  %t$2$lb = bitcast i64 %t$1 to double
  %t$2$fr = fadd double %t$2$la, %t$2$lb
  %t$2 = bitcast double %t$2$fr to i64
  %t$3 = load i64, ptr @stdlib.math.two_pi
  %t$4$la = bitcast i64 %t$2 to double
  %t$4$lb = bitcast i64 %t$3 to double
  %t$4$fr = fdiv double %t$4$la, %t$4$lb
  %t$4 = bitcast double %t$4$fr to i64
  %t$5 = call i64 @stdlib.math.floor(i64 %t$4)
  %t$6$la = bitcast i64 %t$0 to double
  %t$6$lb = bitcast i64 %t$5 to double
  %t$6$fr = fmul double %t$6$la, %t$6$lb
  %t$6 = bitcast double %t$6$fr to i64
  %t$7$la = bitcast i64 %p$x to double
  %t$7$lb = bitcast i64 %t$6 to double
  %t$7$fr = fsub double %t$7$la, %t$7$lb
  %t$7 = bitcast double %t$7$fr to i64
  ret i64 %t$7
}

define i64 @stdlib.math.sin_series(i64 %p$r) {
entry:
  %t$0$la = bitcast i64 %p$r to double
  %t$0$lb = bitcast i64 %p$r to double
  %t$0$fr = fmul double %t$0$la, %t$0$lb
  %t$0 = bitcast double %t$0$fr to i64
  br label %arm_0_1
arm_0_1:
  %t$3 = bitcast double 1.0 to i64
  %t$4 = bitcast double 6.0 to i64
  %t$5$la = bitcast i64 %t$0 to double
  %t$5$lb = bitcast i64 %t$4 to double
  %t$5$fr = fdiv double %t$5$la, %t$5$lb
  %t$5 = bitcast double %t$5$fr to i64
  %t$6 = bitcast double 1.0 to i64
  %t$7 = bitcast double 20.0 to i64
  %t$8$la = bitcast i64 %t$0 to double
  %t$8$lb = bitcast i64 %t$7 to double
  %t$8$fr = fdiv double %t$8$la, %t$8$lb
  %t$8 = bitcast double %t$8$fr to i64
  %t$9 = bitcast double 1.0 to i64
  %t$10 = bitcast double 42.0 to i64
  %t$11$la = bitcast i64 %t$0 to double
  %t$11$lb = bitcast i64 %t$10 to double
  %t$11$fr = fdiv double %t$11$la, %t$11$lb
  %t$11 = bitcast double %t$11$fr to i64
  %t$12 = bitcast double 1.0 to i64
  %t$13 = bitcast double 72.0 to i64
  %t$14$la = bitcast i64 %t$0 to double
  %t$14$lb = bitcast i64 %t$13 to double
  %t$14$fr = fdiv double %t$14$la, %t$14$lb
  %t$14 = bitcast double %t$14$fr to i64
  %t$15 = bitcast double 1.0 to i64
  %t$16 = bitcast double 110.0 to i64
  %t$17$la = bitcast i64 %t$0 to double
  %t$17$lb = bitcast i64 %t$16 to double
  %t$17$fr = fdiv double %t$17$la, %t$17$lb
  %t$17 = bitcast double %t$17$fr to i64
  %t$18 = bitcast double 1.0 to i64
  %t$19 = bitcast double 156.0 to i64
  %t$20$la = bitcast i64 %t$0 to double
  %t$20$lb = bitcast i64 %t$19 to double
  %t$20$fr = fdiv double %t$20$la, %t$20$lb
  %t$20 = bitcast double %t$20$fr to i64
  %t$21 = bitcast double 1.0 to i64
  %t$22 = bitcast double 210.0 to i64
  %t$23$la = bitcast i64 %t$0 to double
  %t$23$lb = bitcast i64 %t$22 to double
  %t$23$fr = fdiv double %t$23$la, %t$23$lb
  %t$23 = bitcast double %t$23$fr to i64
  %t$24 = bitcast double 1.0 to i64
  %t$25 = bitcast double 272.0 to i64
  %t$26$la = bitcast i64 %t$0 to double
  %t$26$lb = bitcast i64 %t$25 to double
  %t$26$fr = fdiv double %t$26$la, %t$26$lb
  %t$26 = bitcast double %t$26$fr to i64
  %t$27$la = bitcast i64 %t$24 to double
  %t$27$lb = bitcast i64 %t$26 to double
  %t$27$fr = fsub double %t$27$la, %t$27$lb
  %t$27 = bitcast double %t$27$fr to i64
  %t$28$la = bitcast i64 %t$23 to double
  %t$28$lb = bitcast i64 %t$27 to double
  %t$28$fr = fmul double %t$28$la, %t$28$lb
  %t$28 = bitcast double %t$28$fr to i64
  %t$29$la = bitcast i64 %t$21 to double
  %t$29$lb = bitcast i64 %t$28 to double
  %t$29$fr = fsub double %t$29$la, %t$29$lb
  %t$29 = bitcast double %t$29$fr to i64
  %t$30$la = bitcast i64 %t$20 to double
  %t$30$lb = bitcast i64 %t$29 to double
  %t$30$fr = fmul double %t$30$la, %t$30$lb
  %t$30 = bitcast double %t$30$fr to i64
  %t$31$la = bitcast i64 %t$18 to double
  %t$31$lb = bitcast i64 %t$30 to double
  %t$31$fr = fsub double %t$31$la, %t$31$lb
  %t$31 = bitcast double %t$31$fr to i64
  %t$32$la = bitcast i64 %t$17 to double
  %t$32$lb = bitcast i64 %t$31 to double
  %t$32$fr = fmul double %t$32$la, %t$32$lb
  %t$32 = bitcast double %t$32$fr to i64
  %t$33$la = bitcast i64 %t$15 to double
  %t$33$lb = bitcast i64 %t$32 to double
  %t$33$fr = fsub double %t$33$la, %t$33$lb
  %t$33 = bitcast double %t$33$fr to i64
  %t$34$la = bitcast i64 %t$14 to double
  %t$34$lb = bitcast i64 %t$33 to double
  %t$34$fr = fmul double %t$34$la, %t$34$lb
  %t$34 = bitcast double %t$34$fr to i64
  %t$35$la = bitcast i64 %t$12 to double
  %t$35$lb = bitcast i64 %t$34 to double
  %t$35$fr = fsub double %t$35$la, %t$35$lb
  %t$35 = bitcast double %t$35$fr to i64
  %t$36$la = bitcast i64 %t$11 to double
  %t$36$lb = bitcast i64 %t$35 to double
  %t$36$fr = fmul double %t$36$la, %t$36$lb
  %t$36 = bitcast double %t$36$fr to i64
  %t$37$la = bitcast i64 %t$9 to double
  %t$37$lb = bitcast i64 %t$36 to double
  %t$37$fr = fsub double %t$37$la, %t$37$lb
  %t$37 = bitcast double %t$37$fr to i64
  %t$38$la = bitcast i64 %t$8 to double
  %t$38$lb = bitcast i64 %t$37 to double
  %t$38$fr = fmul double %t$38$la, %t$38$lb
  %t$38 = bitcast double %t$38$fr to i64
  %t$39$la = bitcast i64 %t$6 to double
  %t$39$lb = bitcast i64 %t$38 to double
  %t$39$fr = fsub double %t$39$la, %t$39$lb
  %t$39 = bitcast double %t$39$fr to i64
  %t$40$la = bitcast i64 %t$5 to double
  %t$40$lb = bitcast i64 %t$39 to double
  %t$40$fr = fmul double %t$40$la, %t$40$lb
  %t$40 = bitcast double %t$40$fr to i64
  %t$41$la = bitcast i64 %t$3 to double
  %t$41$lb = bitcast i64 %t$40 to double
  %t$41$fr = fsub double %t$41$la, %t$41$lb
  %t$41 = bitcast double %t$41$fr to i64
  %t$42$la = bitcast i64 %p$r to double
  %t$42$lb = bitcast i64 %t$41 to double
  %t$42$fr = fmul double %t$42$la, %t$42$lb
  %t$42 = bitcast double %t$42$fr to i64
  br label %join_1
arm_1_1:
  call void @sprout_abort_match()
  unreachable
join_1:
  %t$2 = phi i64 [%t$42, %arm_0_1]
  ret i64 %t$2
}

define i64 @stdlib.math.sin(i64 %p$x) {
entry:
  %t$0 = call i64 @stdlib.math.reduce(i64 %p$x)
  %t$1 = call i64 @stdlib.math.sin_series(i64 %t$0)
  ret i64 %t$1
}

define i64 @stdlib.math.radians(i64 %p$deg) {
entry:
  %t$0 = load i64, ptr @stdlib.math.pi
  %t$1$la = bitcast i64 %p$deg to double
  %t$1$lb = bitcast i64 %t$0 to double
  %t$1$fr = fmul double %t$1$la, %t$1$lb
  %t$1 = bitcast double %t$1$fr to i64
  %t$2 = bitcast double 180.0 to i64
  %t$3$la = bitcast i64 %t$1 to double
  %t$3$lb = bitcast i64 %t$2 to double
  %t$3$fr = fdiv double %t$3$la, %t$3$lb
  %t$3 = bitcast double %t$3$fr to i64
  ret i64 %t$3
}

define i64 @examples.wrap_phantom_units.degrees(i64 %p$d) {
entry:
  ret i64 %p$d
}

define i64 @examples.wrap_phantom_units.to_radians(i64 %p$a) {
entry:
  br label %arm_0_0
arm_0_0:
  br label %body_0_0
body_0_0:
  %t$2 = call i64 @stdlib.math.radians(i64 %p$a)
  br label %join_0
arm_1_0:
  call void @sprout_abort_match()
  unreachable
join_0:
  %t$1 = phi i64 [%t$2, %body_0_0]
  ret i64 %t$1
}

define i64 @examples.wrap_phantom_units.sine(i64 %p$a) {
entry:
  br label %arm_0_0
arm_0_0:
  br label %body_0_0
body_0_0:
  %t$2 = call i64 @stdlib.math.sin(i64 %p$a)
  br label %join_0
arm_1_0:
  call void @sprout_abort_match()
  unreachable
join_0:
  %t$1 = phi i64 [%t$2, %body_0_0]
  ret i64 %t$1
}

define i64 @examples.wrap_phantom_units.add(i64 %p$left, i64 %p$right) {
entry:
  br label %arm_0_0
arm_0_0:
  br label %body_0_0
body_0_0:
  br label %arm_0_2
arm_0_2:
  br label %body_0_2
body_0_2:
  %t$4$la = bitcast i64 %p$left to double
  %t$4$lb = bitcast i64 %p$right to double
  %t$4$fr = fadd double %t$4$la, %t$4$lb
  %t$4 = bitcast double %t$4$fr to i64
  br label %join_2
arm_1_2:
  call void @sprout_abort_match()
  unreachable
join_2:
  %t$3 = phi i64 [%t$4, %body_0_2]
  br label %join_0
arm_1_0:
  call void @sprout_abort_match()
  unreachable
join_0:
  %t$1 = phi i64 [%t$3, %join_2]
  ret i64 %t$1
}

define i64 @examples.wrap_phantom_units.angle_value(i64 %p$a) {
entry:
  br label %arm_0_0
arm_0_0:
  br label %body_0_0
body_0_0:
  br label %join_0
arm_1_0:
  call void @sprout_abort_match()
  unreachable
join_0:
  %t$1 = phi i64 [%p$a, %body_0_0]
  ret i64 %t$1
}

define i64 @examples.wrap_phantom_units.au(i64 %p$v) {
entry:
  ret i64 %p$v
}

define i64 @examples.wrap_phantom_units.to_km(i64 %p$l) {
entry:
  br label %arm_0_0
arm_0_0:
  br label %body_0_0
body_0_0:
  %t$2 = load i64, ptr @examples.wrap_phantom_units.km_per_au
  %t$3$la = bitcast i64 %p$l to double
  %t$3$lb = bitcast i64 %t$2 to double
  %t$3$fr = fmul double %t$3$la, %t$3$lb
  %t$3 = bitcast double %t$3$fr to i64
  br label %join_0
arm_1_0:
  call void @sprout_abort_match()
  unreachable
join_0:
  %t$1 = phi i64 [%t$3, %body_0_0]
  ret i64 %t$1
}

define i64 @examples.wrap_phantom_units.length_value(i64 %p$l) {
entry:
  br label %arm_0_0
arm_0_0:
  br label %body_0_0
body_0_0:
  br label %join_0
arm_1_0:
  call void @sprout_abort_match()
  unreachable
join_0:
  %t$1 = phi i64 [%p$l, %body_0_0]
  ret i64 %t$1
}

define i64 @__sprout_user_main() {
entry:
  %t$0 = bitcast double 60.0 to i64
  %t$1 = call i64 @examples.wrap_phantom_units.degrees(i64 %t$0)
  %t$2 = bitcast double 23.44 to i64
  %t$3 = call i64 @examples.wrap_phantom_units.degrees(i64 %t$2)
  %t$4 = getelementptr inbounds { i64, [20 x i8] }, ptr @.str.0, i64 0, i32 1, i64 0
  %t$5 = ptrtoint ptr %t$4 to i64
  %t$6 = call i64 @examples.wrap_phantom_units.to_radians(i64 %t$1)
  %t$7 = call i64 @examples.wrap_phantom_units.sine(i64 %t$6)
  %t$51 = alloca i64
  store i64 %t$1, ptr %t$51
  %t$52 = call i64 @sprout_gc_push_i64_root(ptr %t$51)
  %t$53 = alloca i64
  store i64 %t$3, ptr %t$53
  %t$54 = call i64 @sprout_gc_push_i64_root(ptr %t$53)
  %t$55 = alloca i64
  store i64 %t$5, ptr %t$55
  %t$56 = call i64 @sprout_gc_push_i64_root(ptr %t$55)
  %t$8 = call i64 @__tc_ToString_Double_to_string(i64 %t$7)
  %t$9 = call i64 @__tc_ToString_String_to_string(i64 %t$8)
  %t$10 = getelementptr inbounds { i64, [2 x i8] }, ptr @.str.1, i64 0, i32 1, i64 0
  %t$11 = ptrtoint ptr %t$10 to i64
  %t$57 = alloca i64
  store i64 %t$9, ptr %t$57
  %t$58 = call i64 @sprout_gc_push_i64_root(ptr %t$57)
  %t$59 = alloca i64
  store i64 %t$11, ptr %t$59
  %t$60 = call i64 @sprout_gc_push_i64_root(ptr %t$59)
  %t$12 = call i64 @sprout_alloc_obj(i64 5, i64 0)
  %t$61 = alloca i64
  store i64 %t$12, ptr %t$61
  %t$62 = call i64 @sprout_gc_push_i64_root(ptr %t$61)
  %t$13 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$13$ptr = inttoptr i64 %t$13 to ptr
  %t$13$f0 = getelementptr i64, ptr %t$13$ptr, i64 0
  store i64 %t$11, ptr %t$13$f0
  %t$13$f1 = getelementptr i64, ptr %t$13$ptr, i64 1
  store i64 %t$12, ptr %t$13$f1
  %t$63 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$64 = alloca i64
  store i64 %t$13, ptr %t$64
  %t$65 = call i64 @sprout_gc_push_i64_root(ptr %t$64)
  %t$14 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$14$ptr = inttoptr i64 %t$14 to ptr
  %t$14$f0 = getelementptr i64, ptr %t$14$ptr, i64 0
  store i64 %t$9, ptr %t$14$f0
  %t$14$f1 = getelementptr i64, ptr %t$14$ptr, i64 1
  store i64 %t$13, ptr %t$14$f1
  %t$66 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$67 = alloca i64
  store i64 %t$14, ptr %t$67
  %t$68 = call i64 @sprout_gc_push_i64_root(ptr %t$67)
  %t$15 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$15$ptr = inttoptr i64 %t$15 to ptr
  %t$15$f0 = getelementptr i64, ptr %t$15$ptr, i64 0
  store i64 %t$5, ptr %t$15$f0
  %t$15$f1 = getelementptr i64, ptr %t$15$ptr, i64 1
  store i64 %t$14, ptr %t$15$f1
  %t$69 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$70 = alloca i64
  store i64 %t$15, ptr %t$70
  %t$71 = call i64 @sprout_gc_push_i64_root(ptr %t$70)
  %t$16 = call i64 @string_concat_many(i64 %t$15)
  %t$72 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$73 = alloca i64
  store i64 %t$16, ptr %t$73
  %t$74 = call i64 @sprout_gc_push_i64_root(ptr %t$73)
  %t$17 = call i64 @term_write(i64 %t$16)
  %t$75 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$18 = getelementptr inbounds { i64, [20 x i8] }, ptr @.str.2, i64 0, i32 1, i64 0
  %t$19 = ptrtoint ptr %t$18 to i64
  %t$20 = call i64 @examples.wrap_phantom_units.add(i64 %t$1, i64 %t$3)
  %t$21 = call i64 @examples.wrap_phantom_units.angle_value(i64 %t$20)
  %t$76 = alloca i64
  store i64 %t$19, ptr %t$76
  %t$77 = call i64 @sprout_gc_push_i64_root(ptr %t$76)
  %t$22 = call i64 @__tc_ToString_Double_to_string(i64 %t$21)
  %t$23 = call i64 @__tc_ToString_String_to_string(i64 %t$22)
  %t$24 = getelementptr inbounds { i64, [2 x i8] }, ptr @.str.3, i64 0, i32 1, i64 0
  %t$25 = ptrtoint ptr %t$24 to i64
  %t$78 = alloca i64
  store i64 %t$23, ptr %t$78
  %t$79 = call i64 @sprout_gc_push_i64_root(ptr %t$78)
  %t$80 = alloca i64
  store i64 %t$25, ptr %t$80
  %t$81 = call i64 @sprout_gc_push_i64_root(ptr %t$80)
  %t$26 = call i64 @sprout_alloc_obj(i64 5, i64 0)
  %t$82 = alloca i64
  store i64 %t$26, ptr %t$82
  %t$83 = call i64 @sprout_gc_push_i64_root(ptr %t$82)
  %t$27 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$27$ptr = inttoptr i64 %t$27 to ptr
  %t$27$f0 = getelementptr i64, ptr %t$27$ptr, i64 0
  store i64 %t$25, ptr %t$27$f0
  %t$27$f1 = getelementptr i64, ptr %t$27$ptr, i64 1
  store i64 %t$26, ptr %t$27$f1
  %t$84 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$85 = alloca i64
  store i64 %t$27, ptr %t$85
  %t$86 = call i64 @sprout_gc_push_i64_root(ptr %t$85)
  %t$28 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$28$ptr = inttoptr i64 %t$28 to ptr
  %t$28$f0 = getelementptr i64, ptr %t$28$ptr, i64 0
  store i64 %t$23, ptr %t$28$f0
  %t$28$f1 = getelementptr i64, ptr %t$28$ptr, i64 1
  store i64 %t$27, ptr %t$28$f1
  %t$87 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$88 = alloca i64
  store i64 %t$28, ptr %t$88
  %t$89 = call i64 @sprout_gc_push_i64_root(ptr %t$88)
  %t$29 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$29$ptr = inttoptr i64 %t$29 to ptr
  %t$29$f0 = getelementptr i64, ptr %t$29$ptr, i64 0
  store i64 %t$19, ptr %t$29$f0
  %t$29$f1 = getelementptr i64, ptr %t$29$ptr, i64 1
  store i64 %t$28, ptr %t$29$f1
  %t$90 = call i64 @sprout_gc_pop_roots(i64 4)
  %t$91 = alloca i64
  store i64 %t$29, ptr %t$91
  %t$92 = call i64 @sprout_gc_push_i64_root(ptr %t$91)
  %t$30 = call i64 @string_concat_many(i64 %t$29)
  %t$93 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$94 = alloca i64
  store i64 %t$30, ptr %t$94
  %t$95 = call i64 @sprout_gc_push_i64_root(ptr %t$94)
  %t$31 = call i64 @term_write(i64 %t$30)
  %t$96 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$32 = getelementptr inbounds { i64, [20 x i8] }, ptr @.str.4, i64 0, i32 1, i64 0
  %t$33 = ptrtoint ptr %t$32 to i64
  %t$34 = bitcast double 1.0 to i64
  %t$35 = call i64 @examples.wrap_phantom_units.au(i64 %t$34)
  %t$36 = call i64 @examples.wrap_phantom_units.to_km(i64 %t$35)
  %t$37 = call i64 @examples.wrap_phantom_units.length_value(i64 %t$36)
  %t$97 = alloca i64
  store i64 %t$33, ptr %t$97
  %t$98 = call i64 @sprout_gc_push_i64_root(ptr %t$97)
  %t$38 = call i64 @__tc_ToString_Double_to_string(i64 %t$37)
  %t$39 = call i64 @__tc_ToString_String_to_string(i64 %t$38)
  %t$40 = getelementptr inbounds { i64, [2 x i8] }, ptr @.str.5, i64 0, i32 1, i64 0
  %t$41 = ptrtoint ptr %t$40 to i64
  %t$99 = alloca i64
  store i64 %t$39, ptr %t$99
  %t$100 = call i64 @sprout_gc_push_i64_root(ptr %t$99)
  %t$101 = alloca i64
  store i64 %t$41, ptr %t$101
  %t$102 = call i64 @sprout_gc_push_i64_root(ptr %t$101)
  %t$42 = call i64 @sprout_alloc_obj(i64 5, i64 0)
  %t$103 = alloca i64
  store i64 %t$42, ptr %t$103
  %t$104 = call i64 @sprout_gc_push_i64_root(ptr %t$103)
  %t$43 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$43$ptr = inttoptr i64 %t$43 to ptr
  %t$43$f0 = getelementptr i64, ptr %t$43$ptr, i64 0
  store i64 %t$41, ptr %t$43$f0
  %t$43$f1 = getelementptr i64, ptr %t$43$ptr, i64 1
  store i64 %t$42, ptr %t$43$f1
  %t$105 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$106 = alloca i64
  store i64 %t$43, ptr %t$106
  %t$107 = call i64 @sprout_gc_push_i64_root(ptr %t$106)
  %t$44 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$44$ptr = inttoptr i64 %t$44 to ptr
  %t$44$f0 = getelementptr i64, ptr %t$44$ptr, i64 0
  store i64 %t$39, ptr %t$44$f0
  %t$44$f1 = getelementptr i64, ptr %t$44$ptr, i64 1
  store i64 %t$43, ptr %t$44$f1
  %t$108 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$109 = alloca i64
  store i64 %t$44, ptr %t$109
  %t$110 = call i64 @sprout_gc_push_i64_root(ptr %t$109)
  %t$45 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$45$ptr = inttoptr i64 %t$45 to ptr
  %t$45$f0 = getelementptr i64, ptr %t$45$ptr, i64 0
  store i64 %t$33, ptr %t$45$f0
  %t$45$f1 = getelementptr i64, ptr %t$45$ptr, i64 1
  store i64 %t$44, ptr %t$45$f1
  %t$111 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$112 = alloca i64
  store i64 %t$45, ptr %t$112
  %t$113 = call i64 @sprout_gc_push_i64_root(ptr %t$112)
  %t$46 = call i64 @string_concat_many(i64 %t$45)
  %t$114 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$115 = alloca i64
  store i64 %t$46, ptr %t$115
  %t$116 = call i64 @sprout_gc_push_i64_root(ptr %t$115)
  %t$47 = call i64 @term_write(i64 %t$46)
  %t$117 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$48 = getelementptr inbounds { i64, [55 x i8] }, ptr @.str.6, i64 0, i32 1, i64 0
  %t$49 = ptrtoint ptr %t$48 to i64
  %t$118 = alloca i64
  store i64 %t$49, ptr %t$118
  %t$119 = call i64 @sprout_gc_push_i64_root(ptr %t$118)
  %t$50 = call i64 @term_write(i64 %t$49)
  %t$120 = call i64 @sprout_gc_pop_roots(i64 1)
  ret i64 %t$50
}

define i64 @__tc_ToString_Double_to_string(i64 %p$value) {
entry:
  %t$0 = call i64 @double_to_string(i64 %p$value)
  ret i64 %t$0
}

define i64 @__tc_ToString_String_to_string(i64 %p$value) {
entry:
  ret i64 %p$value
}

define void @__sprout_init_globals() {
entry:
  %t$0 = call i64 @sprout_alloc_obj(i64 5, i64 0)
  store i64 %t$0, ptr @list_builder_empty
  call i64 @sprout_gc_register_i64_root(ptr @list_builder_empty)
  %t$1 = bitcast double 10000000000000000000000.0 to i64
  store i64 %t$1, ptr @pow10_exact_unit
  %t$2 = bitcast double 3.141592653589793 to i64
  store i64 %t$2, ptr @stdlib.math.pi
  %t$3 = bitcast double 6.283185307179586 to i64
  store i64 %t$3, ptr @stdlib.math.two_pi
  %t$4 = bitcast double 1.5707963267948966 to i64
  store i64 %t$4, ptr @stdlib.math.half_pi
  %t$5 = bitcast double 4503599627370496.0 to i64
  store i64 %t$5, ptr @stdlib.math.two52
  %t$6 = bitcast double 256.0 to i64
  store i64 %t$6, ptr @stdlib.math.two8
  %t$7 = bitcast double 4096.0 to i64
  store i64 %t$7, ptr @stdlib.math.two12
  %t$8 = load i64, ptr @stdlib.math.two8
  %t$9 = call i64 @stdlib.math.sq(i64 %t$8)
  store i64 %t$9, ptr @stdlib.math.two16
  %t$10 = load i64, ptr @stdlib.math.two16
  %t$11 = call i64 @stdlib.math.sq(i64 %t$10)
  store i64 %t$11, ptr @stdlib.math.two32
  %t$12 = load i64, ptr @stdlib.math.two32
  %t$13 = load i64, ptr @stdlib.math.two16
  %t$14$la = bitcast i64 %t$12 to double
  %t$14$lb = bitcast i64 %t$13 to double
  %t$14$fr = fmul double %t$14$la, %t$14$lb
  %t$14 = bitcast double %t$14$fr to i64
  store i64 %t$14, ptr @stdlib.math.two48
  %t$15 = bitcast double 18014398509481984.0 to i64
  store i64 %t$15, ptr @stdlib.math.two54
  %t$16 = load i64, ptr @stdlib.math.two32
  %t$17 = call i64 @stdlib.math.sq(i64 %t$16)
  store i64 %t$17, ptr @stdlib.math.two64
  %t$18 = load i64, ptr @stdlib.math.two64
  %t$19 = call i64 @stdlib.math.sq(i64 %t$18)
  store i64 %t$19, ptr @stdlib.math.two128
  %t$20 = load i64, ptr @stdlib.math.two128
  %t$21 = call i64 @stdlib.math.sq(i64 %t$20)
  store i64 %t$21, ptr @stdlib.math.two256
  %t$22 = load i64, ptr @stdlib.math.two256
  %t$23 = load i64, ptr @stdlib.math.two128
  %t$24$la = bitcast i64 %t$22 to double
  %t$24$lb = bitcast i64 %t$23 to double
  %t$24$fr = fmul double %t$24$la, %t$24$lb
  %t$24 = bitcast double %t$24$fr to i64
  store i64 %t$24, ptr @stdlib.math.two384
  %t$25 = load i64, ptr @stdlib.math.two256
  %t$26 = call i64 @stdlib.math.sq(i64 %t$25)
  store i64 %t$26, ptr @stdlib.math.two512
  %t$27 = bitcast double 1.0 to i64
  %t$28 = load i64, ptr @stdlib.math.two8
  %t$29$la = bitcast i64 %t$27 to double
  %t$29$lb = bitcast i64 %t$28 to double
  %t$29$fr = fdiv double %t$29$la, %t$29$lb
  %t$29 = bitcast double %t$29$fr to i64
  store i64 %t$29, ptr @stdlib.math.inv_two8
  %t$30 = bitcast double 1.0 to i64
  %t$31 = load i64, ptr @stdlib.math.two12
  %t$32$la = bitcast i64 %t$30 to double
  %t$32$lb = bitcast i64 %t$31 to double
  %t$32$fr = fdiv double %t$32$la, %t$32$lb
  %t$32 = bitcast double %t$32$fr to i64
  store i64 %t$32, ptr @stdlib.math.inv_two12
  %t$33 = bitcast double 1.0 to i64
  %t$34 = load i64, ptr @stdlib.math.two16
  %t$35$la = bitcast i64 %t$33 to double
  %t$35$lb = bitcast i64 %t$34 to double
  %t$35$fr = fdiv double %t$35$la, %t$35$lb
  %t$35 = bitcast double %t$35$fr to i64
  store i64 %t$35, ptr @stdlib.math.inv_two16
  %t$36 = bitcast double 1.0 to i64
  %t$37 = load i64, ptr @stdlib.math.two32
  %t$38$la = bitcast i64 %t$36 to double
  %t$38$lb = bitcast i64 %t$37 to double
  %t$38$fr = fdiv double %t$38$la, %t$38$lb
  %t$38 = bitcast double %t$38$fr to i64
  store i64 %t$38, ptr @stdlib.math.inv_two32
  %t$39 = bitcast double 1.0 to i64
  %t$40 = load i64, ptr @stdlib.math.two48
  %t$41$la = bitcast i64 %t$39 to double
  %t$41$lb = bitcast i64 %t$40 to double
  %t$41$fr = fdiv double %t$41$la, %t$41$lb
  %t$41 = bitcast double %t$41$fr to i64
  store i64 %t$41, ptr @stdlib.math.inv_two48
  %t$42 = bitcast double 1.0 to i64
  %t$43 = load i64, ptr @stdlib.math.two64
  %t$44$la = bitcast i64 %t$42 to double
  %t$44$lb = bitcast i64 %t$43 to double
  %t$44$fr = fdiv double %t$44$la, %t$44$lb
  %t$44 = bitcast double %t$44$fr to i64
  store i64 %t$44, ptr @stdlib.math.inv_two64
  %t$45 = bitcast double 1.0 to i64
  %t$46 = load i64, ptr @stdlib.math.two128
  %t$47$la = bitcast i64 %t$45 to double
  %t$47$lb = bitcast i64 %t$46 to double
  %t$47$fr = fdiv double %t$47$la, %t$47$lb
  %t$47 = bitcast double %t$47$fr to i64
  store i64 %t$47, ptr @stdlib.math.inv_two128
  %t$48 = bitcast double 1.0 to i64
  %t$49 = load i64, ptr @stdlib.math.two256
  %t$50$la = bitcast i64 %t$48 to double
  %t$50$lb = bitcast i64 %t$49 to double
  %t$50$fr = fdiv double %t$50$la, %t$50$lb
  %t$50 = bitcast double %t$50$fr to i64
  store i64 %t$50, ptr @stdlib.math.inv_two256
  %t$51 = bitcast double 1.0 to i64
  %t$52 = load i64, ptr @stdlib.math.two384
  %t$53$la = bitcast i64 %t$51 to double
  %t$53$lb = bitcast i64 %t$52 to double
  %t$53$fr = fdiv double %t$53$la, %t$53$lb
  %t$53 = bitcast double %t$53$fr to i64
  store i64 %t$53, ptr @stdlib.math.inv_two384
  %t$54 = bitcast double 1.0 to i64
  %t$55 = load i64, ptr @stdlib.math.two512
  %t$56$la = bitcast i64 %t$54 to double
  %t$56$lb = bitcast i64 %t$55 to double
  %t$56$fr = fdiv double %t$56$la, %t$56$lb
  %t$56 = bitcast double %t$56$fr to i64
  store i64 %t$56, ptr @stdlib.math.inv_two512
  %t$57 = bitcast double 0.0 to i64
  %t$58 = bitcast double 0.0 to i64
  %t$59$la = bitcast i64 %t$57 to double
  %t$59$lb = bitcast i64 %t$58 to double
  %t$59$fr = fdiv double %t$59$la, %t$59$lb
  %t$59 = bitcast double %t$59$fr to i64
  store i64 %t$59, ptr @stdlib.math.nan
  %t$60 = bitcast double 0.6931471805599453 to i64
  store i64 %t$60, ptr @stdlib.math.ln2
  %t$61 = bitcast double 2.302585092994046 to i64
  store i64 %t$61, ptr @stdlib.math.ln10
  %t$62 = bitcast double 1.4426950408889634 to i64
  store i64 %t$62, ptr @stdlib.math.inv_ln2
  %t$63 = bitcast double 1.4142135623730951 to i64
  store i64 %t$63, ptr @stdlib.math.sqrt2
  %t$64 = bitcast double 0.7071067811865476 to i64
  store i64 %t$64, ptr @stdlib.math.inv_sqrt2
  %t$65 = bitcast double 1.0 to i64
  %t$66 = bitcast double 0.0 to i64
  %t$67$la = bitcast i64 %t$65 to double
  %t$67$lb = bitcast i64 %t$66 to double
  %t$67$fr = fdiv double %t$67$la, %t$67$lb
  %t$67 = bitcast double %t$67$fr to i64
  store i64 %t$67, ptr @stdlib.math.inf
  %t$68 = bitcast double 0.0 to i64
  %t$69$fa = bitcast i64 %t$68 to double
  %t$69$fr = fneg double %t$69$fa
  %t$69 = bitcast double %t$69$fr to i64
  store i64 %t$69, ptr @stdlib.math.neg_zero
  %t$70 = load i64, ptr @stdlib.math.two64
  %t$71 = bitcast double 2.0 to i64
  %t$72$la = bitcast i64 %t$70 to double
  %t$72$lb = bitcast i64 %t$71 to double
  %t$72$fr = fdiv double %t$72$la, %t$72$lb
  %t$72 = bitcast double %t$72$fr to i64
  store i64 %t$72, ptr @stdlib.math.two63
  %t$73 = add i64 0, 27
  %t$74 = call i64 @char_to_str(i64 %t$73)
  store i64 %t$74, ptr @stdlib.terminal.esc
  call i64 @sprout_gc_register_i64_root(ptr @stdlib.terminal.esc)
  %t$75 = bitcast double 149597870.7 to i64
  store i64 %t$75, ptr @examples.wrap_phantom_units.km_per_au
  ret void
}

define i32 @main(i32 %argc, ptr %argv) {
entry:
  %argv_set = call i64 @sprout_set_argv(i32 %argc, ptr %argv)
  %cname_ptr_0 = getelementptr inbounds [8 x i8], ptr @.cname.0, i64 0, i64 0
  %cfkinds_ptr_0 = getelementptr inbounds [1 x i8], ptr @.cfkinds.0, i64 0, i64 0
  %creg_0 = call i64 @sprout_register_ctor(i64 0, ptr %cname_ptr_0, i64 0, ptr %cfkinds_ptr_0)
  %cname_ptr_1 = getelementptr inbounds [5 x i8], ptr @.cname.1, i64 0, i64 0
  %cfkinds_ptr_1 = getelementptr inbounds [2 x i8], ptr @.cfkinds.1, i64 0, i64 0
  %creg_1 = call i64 @sprout_register_ctor(i64 1, ptr %cname_ptr_1, i64 1, ptr %cfkinds_ptr_1)
  %cname_ptr_2 = getelementptr inbounds [12 x i8], ptr @.cname.2, i64 0, i64 0
  %cfkinds_ptr_2 = getelementptr inbounds [2 x i8], ptr @.cfkinds.2, i64 0, i64 0
  %creg_2 = call i64 @sprout_register_ctor(i64 2, ptr %cname_ptr_2, i64 1, ptr %cfkinds_ptr_2)
  %cname_ptr_3 = getelementptr inbounds [15 x i8], ptr @.cname.3, i64 0, i64 0
  %cfkinds_ptr_3 = getelementptr inbounds [2 x i8], ptr @.cfkinds.3, i64 0, i64 0
  %creg_3 = call i64 @sprout_register_ctor(i64 3, ptr %cname_ptr_3, i64 1, ptr %cfkinds_ptr_3)
  %cname_ptr_4 = getelementptr inbounds [15 x i8], ptr @.cname.4, i64 0, i64 0
  %cfkinds_ptr_4 = getelementptr inbounds [2 x i8], ptr @.cfkinds.4, i64 0, i64 0
  %creg_4 = call i64 @sprout_register_ctor(i64 4, ptr %cname_ptr_4, i64 1, ptr %cfkinds_ptr_4)
  %cname_ptr_5 = getelementptr inbounds [4 x i8], ptr @.cname.5, i64 0, i64 0
  %cfkinds_ptr_5 = getelementptr inbounds [1 x i8], ptr @.cfkinds.5, i64 0, i64 0
  %creg_5 = call i64 @sprout_register_ctor(i64 5, ptr %cname_ptr_5, i64 0, ptr %cfkinds_ptr_5)
  %cname_ptr_6 = getelementptr inbounds [5 x i8], ptr @.cname.6, i64 0, i64 0
  %cfkinds_ptr_6 = getelementptr inbounds [3 x i8], ptr @.cfkinds.6, i64 0, i64 0
  %creg_6 = call i64 @sprout_register_ctor(i64 6, ptr %cname_ptr_6, i64 2, ptr %cfkinds_ptr_6)
  %cname_ptr_7 = getelementptr inbounds [3 x i8], ptr @.cname.7, i64 0, i64 0
  %cfkinds_ptr_7 = getelementptr inbounds [2 x i8], ptr @.cfkinds.7, i64 0, i64 0
  %creg_7 = call i64 @sprout_register_ctor(i64 7, ptr %cname_ptr_7, i64 1, ptr %cfkinds_ptr_7)
  %cname_ptr_8 = getelementptr inbounds [4 x i8], ptr @.cname.8, i64 0, i64 0
  %cfkinds_ptr_8 = getelementptr inbounds [2 x i8], ptr @.cfkinds.8, i64 0, i64 0
  %creg_8 = call i64 @sprout_register_ctor(i64 8, ptr %cname_ptr_8, i64 1, ptr %cfkinds_ptr_8)
  %cname_ptr_9 = getelementptr inbounds [10 x i8], ptr @.cname.9, i64 0, i64 0
  %cfkinds_ptr_9 = getelementptr inbounds [1 x i8], ptr @.cfkinds.9, i64 0, i64 0
  %creg_9 = call i64 @sprout_register_ctor(i64 9, ptr %cname_ptr_9, i64 0, ptr %cfkinds_ptr_9)
  %cname_ptr_10 = getelementptr inbounds [4 x i8], ptr @.cname.10, i64 0, i64 0
  %cfkinds_ptr_10 = getelementptr inbounds [2 x i8], ptr @.cfkinds.10, i64 0, i64 0
  %creg_10 = call i64 @sprout_register_ctor(i64 10, ptr %cname_ptr_10, i64 1, ptr %cfkinds_ptr_10)
  %cname_ptr_11 = getelementptr inbounds [5 x i8], ptr @.cname.11, i64 0, i64 0
  %cfkinds_ptr_11 = getelementptr inbounds [2 x i8], ptr @.cfkinds.11, i64 0, i64 0
  %creg_11 = call i64 @sprout_register_ctor(i64 11, ptr %cname_ptr_11, i64 1, ptr %cfkinds_ptr_11)
  %cname_ptr_12 = getelementptr inbounds [4 x i8], ptr @.cname.12, i64 0, i64 0
  %cfkinds_ptr_12 = getelementptr inbounds [2 x i8], ptr @.cfkinds.12, i64 0, i64 0
  %creg_12 = call i64 @sprout_register_ctor(i64 12, ptr %cname_ptr_12, i64 1, ptr %cfkinds_ptr_12)
  %cname_ptr_13 = getelementptr inbounds [9 x i8], ptr @.cname.13, i64 0, i64 0
  %cfkinds_ptr_13 = getelementptr inbounds [4 x i8], ptr @.cfkinds.13, i64 0, i64 0
  %creg_13 = call i64 @sprout_register_ctor(i64 13, ptr %cname_ptr_13, i64 3, ptr %cfkinds_ptr_13)
  %cname_ptr_14 = getelementptr inbounds [25 x i8], ptr @.cname.14, i64 0, i64 0
  %cfkinds_ptr_14 = getelementptr inbounds [3 x i8], ptr @.cfkinds.14, i64 0, i64 0
  %creg_14 = call i64 @sprout_register_ctor(i64 14, ptr %cname_ptr_14, i64 2, ptr %cfkinds_ptr_14)
  %cname_ptr_15 = getelementptr inbounds [26 x i8], ptr @.cname.15, i64 0, i64 0
  %cfkinds_ptr_15 = getelementptr inbounds [2 x i8], ptr @.cfkinds.15, i64 0, i64 0
  %creg_15 = call i64 @sprout_register_ctor(i64 15, ptr %cname_ptr_15, i64 1, ptr %cfkinds_ptr_15)
  %cname_ptr_16 = getelementptr inbounds [25 x i8], ptr @.cname.16, i64 0, i64 0
  %cfkinds_ptr_16 = getelementptr inbounds [1 x i8], ptr @.cfkinds.16, i64 0, i64 0
  %creg_16 = call i64 @sprout_register_ctor(i64 16, ptr %cname_ptr_16, i64 0, ptr %cfkinds_ptr_16)
  %cname_ptr_17 = getelementptr inbounds [28 x i8], ptr @.cname.17, i64 0, i64 0
  %cfkinds_ptr_17 = getelementptr inbounds [1 x i8], ptr @.cfkinds.17, i64 0, i64 0
  %creg_17 = call i64 @sprout_register_ctor(i64 17, ptr %cname_ptr_17, i64 0, ptr %cfkinds_ptr_17)
  %cname_ptr_18 = getelementptr inbounds [24 x i8], ptr @.cname.18, i64 0, i64 0
  %cfkinds_ptr_18 = getelementptr inbounds [1 x i8], ptr @.cfkinds.18, i64 0, i64 0
  %creg_18 = call i64 @sprout_register_ctor(i64 18, ptr %cname_ptr_18, i64 0, ptr %cfkinds_ptr_18)
  %cname_ptr_19 = getelementptr inbounds [27 x i8], ptr @.cname.19, i64 0, i64 0
  %cfkinds_ptr_19 = getelementptr inbounds [2 x i8], ptr @.cfkinds.19, i64 0, i64 0
  %creg_19 = call i64 @sprout_register_ctor(i64 19, ptr %cname_ptr_19, i64 1, ptr %cfkinds_ptr_19)
  %cname_ptr_20 = getelementptr inbounds [32 x i8], ptr @.cname.20, i64 0, i64 0
  %cfkinds_ptr_20 = getelementptr inbounds [1 x i8], ptr @.cfkinds.20, i64 0, i64 0
  %creg_20 = call i64 @sprout_register_ctor(i64 20, ptr %cname_ptr_20, i64 0, ptr %cfkinds_ptr_20)
  %cname_ptr_21 = getelementptr inbounds [32 x i8], ptr @.cname.21, i64 0, i64 0
  %cfkinds_ptr_21 = getelementptr inbounds [1 x i8], ptr @.cfkinds.21, i64 0, i64 0
  %creg_21 = call i64 @sprout_register_ctor(i64 21, ptr %cname_ptr_21, i64 0, ptr %cfkinds_ptr_21)
  %cname_ptr_22 = getelementptr inbounds [31 x i8], ptr @.cname.22, i64 0, i64 0
  %cfkinds_ptr_22 = getelementptr inbounds [1 x i8], ptr @.cfkinds.22, i64 0, i64 0
  %creg_22 = call i64 @sprout_register_ctor(i64 22, ptr %cname_ptr_22, i64 0, ptr %cfkinds_ptr_22)
  %cname_ptr_23 = getelementptr inbounds [31 x i8], ptr @.cname.23, i64 0, i64 0
  %cfkinds_ptr_23 = getelementptr inbounds [1 x i8], ptr @.cfkinds.23, i64 0, i64 0
  %creg_23 = call i64 @sprout_register_ctor(i64 23, ptr %cname_ptr_23, i64 0, ptr %cfkinds_ptr_23)
  call void @__sprout_init_globals()
  call i64 @__sprout_user_main()
  ret i32 0
}

