; Generated by sprout ir_lowering.sprout (M2 PR 2.3)
target triple = "unknown-unknown-unknown"
declare i64 @str_concat(i64, i64)
declare i1 @str_eq(ptr, ptr)
declare i64 @str_compare(i64, i64)
declare i64 @str_slice(i64, i64, i64)
declare i64 @int_to_string(i64)
declare i64 @char_to_string(i64)
declare i64 @sprout_gc_push_i64_root(ptr)
declare i64 @sprout_gc_pop_roots(i64)
declare i64 @sprout_gc_register_i64_root(ptr)
declare i64 @sprout_alloc_closure(i64, i64)
declare void @sprout_closure_arity_check(i64, i64)
declare i64 @sprout_alloc_tuple_blob(i64)
declare i64 @sprout_register_ctor(i64, ptr, i64, ptr)
declare i64 @sprout_tag(i64)
declare i64 @sprout_field(i64, i64)
declare void @sprout_abort_match() noreturn
declare i64 @panic(i64)
declare ptr @llvm.stacksave()
declare void @llvm.stackrestore(ptr)
declare i64 @sprout_alloc_obj(i64, i64)
declare { i64, i64 } @vector_get_unboxed(i64, i64)
declare { i64, i64 } @map_get_unboxed(i64, i64)
declare { i64, i64 } @map_nth_key_unboxed(i64, i64)
declare { i64, i64 } @map_nth_value_unboxed(i64, i64)
declare { i64, i64 } @bytes_get_unboxed(i64, i64)
declare { i64, i64 } @str_char_at_unboxed(i64, i64)
declare { i64, i64 } @argv_get_unboxed(i64)
declare { i64, i64 } @env_get_unboxed(i64)
declare i64 @print_str(ptr)
declare i64 @print_value(i64)
declare i64 @eprint_str(ptr)
declare i64 @argv_get(i64)
declare i64 @sprout_set_argv(i32, ptr)
declare i64 @analysis_check_source(ptr)
declare i64 @analysis_declared_names_in_source(ptr)
declare i64 @analysis_exported_names_in_source(ptr)
declare i64 @analysis_symbol_inventory_in_source(ptr)
declare i64 @analysis_diagnostics_in_source(ptr)
declare i64 @analysis_symbol_locations_in_source(ptr)
declare i64 @analysis_type_of_in_source(ptr, ptr)
declare i64 @analysis_eval_expr_in_source(ptr, ptr)
declare i64 @analysis_instances_in_source(ptr, ptr)
declare i64 @analysis_complete_in_state(ptr, ptr, ptr)

declare i64 @double_to_string(i64)
declare i64 @char_to_str(i64)
declare i64 @char_from_codepoint(i64)
declare i64 @to_double(i64)
declare i64 @string_concat_many(i64)
declare i64 @str_len(i64)
declare i64 @str_char_at(i64, i64)
declare i64 @str_find(i64, i64)
declare i64 @str_starts_with(i64, i64)
declare i64 @vector_empty()
declare i64 @vector_length(i64)
declare i64 @vector_get(i64, i64)
declare i64 @vector_set(i64, i64, i64)
declare i64 @vector_append(i64, i64)
declare i64 @vector_concat(i64, i64)
declare i64 @vector_from_list(i64)
declare i64 @map_empty()
declare i64 @map_get(i64, i64)
declare i64 @map_set(i64, i64, i64)
declare i64 @map_remove(i64, i64)
declare i64 @map_size(i64)
declare i64 @map_nth_key(i64, i64)
declare i64 @map_nth_value(i64, i64)
declare i64 @native_set_empty()
declare i64 @native_set_insert(i64, i64)
declare i64 @native_set_member(i64, i64)
declare i64 @native_set_to_list(i64)
declare i64 @native_set_size(i64)
declare i64 @ref_new(i64)
declare i64 @ref_read(i64)
declare i64 @ref_write(i64, i64)
declare i64 @regex_validate(i64)
declare i64 @regex_is_match(i64, i64)
declare i64 @regex_find_match(i64, i64)
declare i64 @regex_replace_all_literal(i64, i64, i64)
declare i64 @regex_escape(i64)
declare i64 @bytes_empty()
declare i64 @bytes_singleton(i64)
declare i64 @bytes_length(i64)
declare i64 @bytes_get(i64, i64)
declare i64 @bytes_slice(i64, i64, i64)
declare i64 @bytes_append(i64, i64)
declare i64 @bytes_from_utf8(i64)
declare i64 @bytes_to_utf8(i64)
declare i64 @bytes_builder_empty()
declare i64 @bytes_builder_bytes(i64)
declare i64 @bytes_builder_byte(i64)
declare i64 @bytes_builder_u16_be(i64)
declare i64 @bytes_builder_u32_be(i64)
declare i64 @bytes_builder_append(i64, i64)
declare i64 @bytes_builder_build(i64)
declare i64 @str_byte_len(i64)
declare i64 @str_slice_bytes(i64, i64, i64)
declare i64 @str_starts_with_at_byte(i64, i64, i64)
declare i64 @str_split_lines(i64)
declare i64 @split_words(i64)
@.str.0 = private unnamed_addr constant { i64, [9 x i8] } { i64 131082, [9 x i8] c"matched=\00" }
@.str.1 = private unnamed_addr constant { i64, [9 x i8] } { i64 131082, [9 x i8] c"|prefix=\00" }
@.str.2 = private unnamed_addr constant { i64, [9 x i8] } { i64 131082, [9 x i8] c"|suffix=\00" }
@.str.3 = private unnamed_addr constant { i64, [11 x i8] } { i64 163850, [11 x i8] c"|replaced=\00" }
@.str.4 = private unnamed_addr constant { i64, [10 x i8] } { i64 147466, [10 x i8] c"|escaped=\00" }
@.str.5 = private unnamed_addr constant { i64, [5 x i8] } { i64 65546, [5 x i8] c"<ID>\00" }
@.str.6 = private unnamed_addr constant { i64, [15 x i8] } { i64 229386, [15 x i8] c"literal [A-Z]+\00" }
@.str.7 = private unnamed_addr constant { i64, [27 x i8] } { i64 425994, [27 x i8] c"regex matched but no range\00" }
@.str.8 = private unnamed_addr constant { i64, [12 x i8] } { i64 180234, [12 x i8] c"no id found\00" }
@.str.9 = private unnamed_addr constant { i64, [18 x i8] } { i64 278538, [18 x i8] c"[A-Z][A-Z]-[0-9]+\00" }
@.str.10 = private unnamed_addr constant { i64, [18 x i8] } { i64 278538, [18 x i8] c"invalid pattern: \00" }
@.str.11 = private unnamed_addr constant { i64, [22 x i8] } { i64 344074, [22 x i8] c"unsupported pattern: \00" }
@.str.12 = private unnamed_addr constant { i64, [52 x i8] } { i64 835594, [52 x i8] c"usage: sprout run examples/regex_demo.sprout <text>\00" }
@.str.13 = private unnamed_addr constant { i64, [28 x i8] } { i64 442378, [28 x i8] c"unsupported regex feature: \00" }
@.cname.0 = private unnamed_addr constant [8 x i8] c"Nothing\00"
@.cfkinds.0 = private unnamed_addr constant [1 x i8] c"\00"
@.cname.1 = private unnamed_addr constant [5 x i8] c"Just\00"
@.cfkinds.1 = private unnamed_addr constant [2 x i8] c"_\00"
@.cname.2 = private unnamed_addr constant [12 x i8] c"TemplateLit\00"
@.cfkinds.2 = private unnamed_addr constant [2 x i8] c"s\00"
@.cname.3 = private unnamed_addr constant [15 x i8] c"TemplateInterp\00"
@.cfkinds.3 = private unnamed_addr constant [2 x i8] c"s\00"
@.cname.4 = private unnamed_addr constant [15 x i8] c"StringTemplate\00"
@.cfkinds.4 = private unnamed_addr constant [2 x i8] c"p\00"
@.cname.5 = private unnamed_addr constant [4 x i8] c"Nil\00"
@.cfkinds.5 = private unnamed_addr constant [1 x i8] c"\00"
@.cname.6 = private unnamed_addr constant [5 x i8] c"Cons\00"
@.cfkinds.6 = private unnamed_addr constant [3 x i8] c"_p\00"
@.cname.7 = private unnamed_addr constant [3 x i8] c"Ok\00"
@.cfkinds.7 = private unnamed_addr constant [2 x i8] c"_\00"
@.cname.8 = private unnamed_addr constant [4 x i8] c"Err\00"
@.cfkinds.8 = private unnamed_addr constant [2 x i8] c"_\00"
@.cname.9 = private unnamed_addr constant [10 x i8] c"DivByZero\00"
@.cfkinds.9 = private unnamed_addr constant [1 x i8] c"\00"
@.cname.10 = private unnamed_addr constant [4 x i8] c"Vec\00"
@.cfkinds.10 = private unnamed_addr constant [2 x i8] c"p\00"
@.cname.11 = private unnamed_addr constant [5 x i8] c"Dict\00"
@.cfkinds.11 = private unnamed_addr constant [2 x i8] c"p\00"
@.cname.12 = private unnamed_addr constant [4 x i8] c"Set\00"
@.cfkinds.12 = private unnamed_addr constant [2 x i8] c"p\00"
@.cname.13 = private unnamed_addr constant [9 x i8] c"IntRange\00"
@.cfkinds.13 = private unnamed_addr constant [4 x i8] c"iii\00"
@.cname.14 = private unnamed_addr constant [33 x i8] c"stdlib.regex.RegexInvalidPattern\00"
@.cfkinds.14 = private unnamed_addr constant [2 x i8] c"s\00"
@.cname.15 = private unnamed_addr constant [37 x i8] c"stdlib.regex.RegexUnsupportedFeature\00"
@.cfkinds.15 = private unnamed_addr constant [2 x i8] c"s\00"
@.cname.16 = private unnamed_addr constant [19 x i8] c"stdlib.regex.Regex\00"
@.cfkinds.16 = private unnamed_addr constant [2 x i8] c"s\00"
@.cname.17 = private unnamed_addr constant [19 x i8] c"stdlib.regex.Match\00"
@.cfkinds.17 = private unnamed_addr constant [3 x i8] c"ii\00"
@.cname.18 = private unnamed_addr constant [29 x i8] c"stdlib.bytes.Utf8DecodeError\00"
@.cfkinds.18 = private unnamed_addr constant [2 x i8] c"s\00"
@stdlib.regex.unsupported_prefix = global i64 zeroinitializer

define i64 @fold(i64 %step, i64 %init, i64 %xs, i64 %__tc_Foldable_0_fold_values) {
entry:
  %t$1 = alloca i64
  store i64 %xs, ptr %t$1
  %t$2 = call i64 @sprout_gc_push_i64_root(ptr %t$1)
  %t$3 = alloca i64
  store i64 %step, ptr %t$3
  %t$4 = call i64 @sprout_gc_push_i64_root(ptr %t$3)
  %t$5 = alloca i64
  store i64 %init, ptr %t$5
  %t$6 = call i64 @sprout_gc_push_i64_root(ptr %t$5)
  %t$7 = alloca i64
  store i64 %__tc_Foldable_0_fold_values, ptr %t$7
  %t$8 = call i64 @sprout_gc_push_i64_root(ptr %t$7)
  %t$0 = call i64 @__cm_Foldable_fold_values(i64 %step, i64 %init, i64 %xs, i64 %__tc_Foldable_0_fold_values)
  %t$9 = call i64 @sprout_gc_pop_roots(i64 4)
  ret i64 %t$0
}

define i64 @__sprout_ir_lambda_0(i64 %env$, i64 %acc, i64 %x) {
entry:
  %t$0$env_ptr = inttoptr i64 %env$ to ptr
  %t$0$slot_ptr = getelementptr i64, ptr %t$0$env_ptr, i64 1
  %t$0 = load i64, ptr %t$0$slot_ptr
  %t$7 = alloca i64
  store i64 %acc, ptr %t$7
  %t$8 = call i64 @sprout_gc_push_i64_root(ptr %t$7)
  call void @sprout_closure_arity_check(i64 %t$0, i64 1)
  %t$1$env_ptr = inttoptr i64 %t$0 to ptr
  %t$1$code = load ptr, ptr %t$1$env_ptr
  %t$1 = call i64 (i64, i64) %t$1$code(i64 %t$0, i64 %x)
  %t$6 = trunc i64 %t$1 to i1
  %t$9 = call i64 @sprout_gc_pop_roots(i64 1)
  br i1 %t$6, label %then_2, label %else_2
then_2:
  %t$4 = add i64 0, 1
  %t$5 = add i64 %acc, %t$4
  br label %join_2
else_2:
  br label %join_2
join_2:
  %t$3 = phi i64 [%t$5, %then_2], [%acc, %else_2]
  ret i64 %t$3
}

define i64 @count(i64 %pred, i64 %xs, i64 %__tc_Foldable_0_fold_values) {
entry:
  %t$3 = alloca i64
  store i64 %xs, ptr %t$3
  %t$4 = call i64 @sprout_gc_push_i64_root(ptr %t$3)
  %t$5 = alloca i64
  store i64 %pred, ptr %t$5
  %t$6 = call i64 @sprout_gc_push_i64_root(ptr %t$5)
  %t$7 = alloca i64
  store i64 %__tc_Foldable_0_fold_values, ptr %t$7
  %t$8 = call i64 @sprout_gc_push_i64_root(ptr %t$7)
  %t$0 = call i64 @sprout_alloc_closure(i64 16, i64 2)
  %t$0$raw = inttoptr i64 %t$0 to ptr
  store ptr @__sprout_ir_lambda_0, ptr %t$0$raw
  %t$0$raw$slot$1 = getelementptr i64, ptr %t$0$raw, i64 1
  store i64 %pred, ptr %t$0$raw$slot$1
  %t$1 = add i64 0, 0
  %t$9 = alloca i64
  store i64 %t$0, ptr %t$9
  %t$10 = call i64 @sprout_gc_push_i64_root(ptr %t$9)
  %t$2 = call i64 @fold(i64 %t$0, i64 %t$1, i64 %xs, i64 %__tc_Foldable_0_fold_values)
  %t$11 = call i64 @sprout_gc_pop_roots(i64 4)
  ret i64 %t$2
}

define i64 @stdlib.regex.raw_pattern(i64 %re) {
entry:
  %t$0 = call i64 @sprout_tag(i64 %re)
  br label %arm_0_1
arm_0_1:
  %t$3 = add i64 0, 16
  %t$4 = icmp eq i64 %t$0, %t$3
  br i1 %t$4, label %body_0_1, label %arm_1_1
body_0_1:
  %t$5 = call i64 @sprout_field(i64 %re, i64 0)
  br label %join_1
arm_1_1:
  call void @sprout_abort_match()
  unreachable
join_1:
  %t$2 = phi i64 [%t$5, %body_0_1]
  ret i64 %t$2
}

define i64 @stdlib.regex.unsupported_detail(i64 %msg) {
entry:
  %t$0 = load i64, ptr @stdlib.regex.unsupported_prefix
  %t$7 = alloca i64
  store i64 %msg, ptr %t$7
  %t$8 = call i64 @sprout_gc_push_i64_root(ptr %t$7)
  %t$1 = call i64 @str_len(i64 %t$0)
  %t$2 = call i64 @str_len(i64 %msg)
  %t$3 = load i64, ptr @stdlib.regex.unsupported_prefix
  %t$4 = call i64 @str_len(i64 %t$3)
  %t$5 = sub i64 %t$2, %t$4
  %t$6 = call i64 @str_slice(i64 %msg, i64 %t$1, i64 %t$5)
  %t$9 = call i64 @sprout_gc_pop_roots(i64 1)
  ret i64 %t$6
}

define i64 @stdlib.regex.classify_compile_error(i64 %msg) {
entry:
  %t$0 = load i64, ptr @stdlib.regex.unsupported_prefix
  %t$8 = alloca i64
  store i64 %msg, ptr %t$8
  %t$9 = call i64 @sprout_gc_push_i64_root(ptr %t$8)
  %t$1 = call i64 @str_starts_with(i64 %msg, i64 %t$0)
  %t$7 = trunc i64 %t$1 to i1
  %t$10 = call i64 @sprout_gc_pop_roots(i64 1)
  br i1 %t$7, label %then_2, label %else_2
then_2:
  %t$11 = alloca i64
  store i64 %msg, ptr %t$11
  %t$12 = call i64 @sprout_gc_push_i64_root(ptr %t$11)
  %t$4 = call i64 @stdlib.regex.unsupported_detail(i64 %msg)
  %t$13 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$14 = alloca i64
  store i64 %t$4, ptr %t$14
  %t$15 = call i64 @sprout_gc_push_i64_root(ptr %t$14)
  %t$5 = call i64 @sprout_alloc_obj(i64 15, i64 1)
  %t$5$ptr = inttoptr i64 %t$5 to ptr
  %t$5$f0 = getelementptr i64, ptr %t$5$ptr, i64 0
  store i64 %t$4, ptr %t$5$f0
  %t$16 = call i64 @sprout_gc_pop_roots(i64 1)
  br label %join_2
else_2:
  %t$17 = alloca i64
  store i64 %msg, ptr %t$17
  %t$18 = call i64 @sprout_gc_push_i64_root(ptr %t$17)
  %t$6 = call i64 @sprout_alloc_obj(i64 14, i64 1)
  %t$6$ptr = inttoptr i64 %t$6 to ptr
  %t$6$f0 = getelementptr i64, ptr %t$6$ptr, i64 0
  store i64 %msg, ptr %t$6$f0
  %t$19 = call i64 @sprout_gc_pop_roots(i64 1)
  br label %join_2
join_2:
  %t$3 = phi i64 [%t$5, %then_2], [%t$6, %else_2]
  ret i64 %t$3
}

define i64 @stdlib.regex.compile(i64 %pattern) {
entry:
  %t$12 = alloca i64
  store i64 %pattern, ptr %t$12
  %t$13 = call i64 @sprout_gc_push_i64_root(ptr %t$12)
  %t$0$st = call { i64, i64 } @regex_validate_worker(i64 %pattern)
  %t$0 = extractvalue { i64, i64 } %t$0$st, 0
  %t$1 = extractvalue { i64, i64 } %t$0$st, 1
  %t$14 = call i64 @sprout_gc_pop_roots(i64 1)
  br label %arm_0_2
arm_0_2:
  %t$4 = add i64 0, 7
  %t$5 = icmp eq i64 %t$0, %t$4
  br i1 %t$5, label %body_0_2, label %arm_1_2
body_0_2:
  %t$15 = alloca i64
  store i64 %pattern, ptr %t$15
  %t$16 = call i64 @sprout_gc_push_i64_root(ptr %t$15)
  %t$6 = call i64 @sprout_alloc_obj(i64 16, i64 1)
  %t$6$ptr = inttoptr i64 %t$6 to ptr
  %t$6$f0 = getelementptr i64, ptr %t$6$ptr, i64 0
  store i64 %pattern, ptr %t$6$f0
  %t$17 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$18 = alloca i64
  store i64 %t$6, ptr %t$18
  %t$19 = call i64 @sprout_gc_push_i64_root(ptr %t$18)
  %t$7 = call i64 @sprout_alloc_obj(i64 7, i64 1)
  %t$7$ptr = inttoptr i64 %t$7 to ptr
  %t$7$f0 = getelementptr i64, ptr %t$7$ptr, i64 0
  store i64 %t$6, ptr %t$7$f0
  %t$20 = call i64 @sprout_gc_pop_roots(i64 1)
  br label %join_2
arm_1_2:
  %t$8 = add i64 0, 8
  %t$9 = icmp eq i64 %t$0, %t$8
  br i1 %t$9, label %body_1_2, label %arm_2_2
body_1_2:
  %t$21 = alloca i64
  store i64 %t$1, ptr %t$21
  %t$22 = call i64 @sprout_gc_push_i64_root(ptr %t$21)
  %t$10 = call i64 @stdlib.regex.classify_compile_error(i64 %t$1)
  %t$23 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$24 = alloca i64
  store i64 %t$10, ptr %t$24
  %t$25 = call i64 @sprout_gc_push_i64_root(ptr %t$24)
  %t$11 = call i64 @sprout_alloc_obj(i64 8, i64 1)
  %t$11$ptr = inttoptr i64 %t$11 to ptr
  %t$11$f0 = getelementptr i64, ptr %t$11$ptr, i64 0
  store i64 %t$10, ptr %t$11$f0
  %t$26 = call i64 @sprout_gc_pop_roots(i64 1)
  br label %join_2
arm_2_2:
  call void @sprout_abort_match()
  unreachable
join_2:
  %t$3 = phi i64 [%t$7, %body_0_2], [%t$11, %body_1_2]
  ret i64 %t$3
}

define i64 @stdlib.regex.is_match(i64 %re, i64 %text) {
entry:
  %t$0 = call i64 @stdlib.regex.raw_pattern(i64 %re)
  %t$2 = alloca i64
  store i64 %text, ptr %t$2
  %t$3 = call i64 @sprout_gc_push_i64_root(ptr %t$2)
  %t$4 = alloca i64
  store i64 %t$0, ptr %t$4
  %t$5 = call i64 @sprout_gc_push_i64_root(ptr %t$4)
  %t$1 = call i64 @regex_is_match(i64 %t$0, i64 %text)
  %t$6 = call i64 @sprout_gc_pop_roots(i64 2)
  ret i64 %t$1
}

define i64 @stdlib.regex.find_first(i64 %re, i64 %text) {
entry:
  %t$0 = call i64 @stdlib.regex.raw_pattern(i64 %re)
  %t$2 = alloca i64
  store i64 %text, ptr %t$2
  %t$3 = call i64 @sprout_gc_push_i64_root(ptr %t$2)
  %t$4 = alloca i64
  store i64 %t$0, ptr %t$4
  %t$5 = call i64 @sprout_gc_push_i64_root(ptr %t$4)
  %t$1 = call i64 @regex_find_match(i64 %t$0, i64 %text)
  %t$6 = call i64 @sprout_gc_pop_roots(i64 2)
  ret i64 %t$1
}

define i64 @stdlib.regex.replace_all_literal(i64 %re, i64 %replacement, i64 %text) {
entry:
  %t$0 = call i64 @stdlib.regex.raw_pattern(i64 %re)
  %t$2 = alloca i64
  store i64 %text, ptr %t$2
  %t$3 = call i64 @sprout_gc_push_i64_root(ptr %t$2)
  %t$4 = alloca i64
  store i64 %replacement, ptr %t$4
  %t$5 = call i64 @sprout_gc_push_i64_root(ptr %t$4)
  %t$6 = alloca i64
  store i64 %t$0, ptr %t$6
  %t$7 = call i64 @sprout_gc_push_i64_root(ptr %t$6)
  %t$1 = call i64 @regex_replace_all_literal(i64 %t$0, i64 %replacement, i64 %text)
  %t$8 = call i64 @sprout_gc_pop_roots(i64 3)
  ret i64 %t$1
}

define i64 @stdlib.regex.escape(i64 %raw) {
entry:
  %t$1 = alloca i64
  store i64 %raw, ptr %t$1
  %t$2 = call i64 @sprout_gc_push_i64_root(ptr %t$1)
  %t$0 = call i64 @regex_escape(i64 %raw)
  %t$3 = call i64 @sprout_gc_pop_roots(i64 1)
  ret i64 %t$0
}

define i64 @stdlib.string.length(i64 %raw) {
entry:
  %t$1 = alloca i64
  store i64 %raw, ptr %t$1
  %t$2 = call i64 @sprout_gc_push_i64_root(ptr %t$1)
  %t$0 = call i64 @str_len(i64 %raw)
  %t$3 = call i64 @sprout_gc_pop_roots(i64 1)
  ret i64 %t$0
}

define i64 @stdlib.string.slice(i64 %raw, i64 %start, i64 %count) {
entry:
  %t$0 = call i64 @str_slice(i64 %raw, i64 %start, i64 %count)
  ret i64 %t$0
}

define i64 @examples.regex_demo.render_match(i64 %raw, i64 %start, i64 %end, i64 %replaced, i64 %escaped) {
entry:
  %t$0 = getelementptr inbounds { i64, [9 x i8] }, ptr @.str.0, i64 0, i32 1, i64 0
  %t$1 = ptrtoint ptr %t$0 to i64
  %t$2 = sub i64 %end, %start
  %t$26 = alloca i64
  store i64 %replaced, ptr %t$26
  %t$27 = call i64 @sprout_gc_push_i64_root(ptr %t$26)
  %t$28 = alloca i64
  store i64 %raw, ptr %t$28
  %t$29 = call i64 @sprout_gc_push_i64_root(ptr %t$28)
  %t$30 = alloca i64
  store i64 %escaped, ptr %t$30
  %t$31 = call i64 @sprout_gc_push_i64_root(ptr %t$30)
  %t$32 = alloca i64
  store i64 %t$1, ptr %t$32
  %t$33 = call i64 @sprout_gc_push_i64_root(ptr %t$32)
  %t$3 = call i64 @stdlib.string.slice(i64 %raw, i64 %start, i64 %t$2)
  %t$34 = alloca i64
  store i64 %t$3, ptr %t$34
  %t$35 = call i64 @sprout_gc_push_i64_root(ptr %t$34)
  %t$4 = call i64 @__tc_Semigroup_String_append(i64 %t$1, i64 %t$3)
  %t$36 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$5 = getelementptr inbounds { i64, [9 x i8] }, ptr @.str.1, i64 0, i32 1, i64 0
  %t$6 = ptrtoint ptr %t$5 to i64
  %t$37 = alloca i64
  store i64 %t$4, ptr %t$37
  %t$38 = call i64 @sprout_gc_push_i64_root(ptr %t$37)
  %t$39 = alloca i64
  store i64 %t$6, ptr %t$39
  %t$40 = call i64 @sprout_gc_push_i64_root(ptr %t$39)
  %t$7 = call i64 @__tc_Semigroup_String_append(i64 %t$4, i64 %t$6)
  %t$41 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$8 = add i64 0, 0
  %t$42 = alloca i64
  store i64 %t$7, ptr %t$42
  %t$43 = call i64 @sprout_gc_push_i64_root(ptr %t$42)
  %t$9 = call i64 @stdlib.string.slice(i64 %raw, i64 %t$8, i64 %start)
  %t$44 = alloca i64
  store i64 %t$9, ptr %t$44
  %t$45 = call i64 @sprout_gc_push_i64_root(ptr %t$44)
  %t$10 = call i64 @__tc_Semigroup_String_append(i64 %t$7, i64 %t$9)
  %t$46 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$11 = getelementptr inbounds { i64, [9 x i8] }, ptr @.str.2, i64 0, i32 1, i64 0
  %t$12 = ptrtoint ptr %t$11 to i64
  %t$47 = alloca i64
  store i64 %t$10, ptr %t$47
  %t$48 = call i64 @sprout_gc_push_i64_root(ptr %t$47)
  %t$49 = alloca i64
  store i64 %t$12, ptr %t$49
  %t$50 = call i64 @sprout_gc_push_i64_root(ptr %t$49)
  %t$13 = call i64 @__tc_Semigroup_String_append(i64 %t$10, i64 %t$12)
  %t$51 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$52 = alloca i64
  store i64 %t$13, ptr %t$52
  %t$53 = call i64 @sprout_gc_push_i64_root(ptr %t$52)
  %t$14 = call i64 @stdlib.string.length(i64 %raw)
  %t$15 = sub i64 %t$14, %end
  %t$16 = call i64 @stdlib.string.slice(i64 %raw, i64 %end, i64 %t$15)
  %t$54 = alloca i64
  store i64 %t$16, ptr %t$54
  %t$55 = call i64 @sprout_gc_push_i64_root(ptr %t$54)
  %t$17 = call i64 @__tc_Semigroup_String_append(i64 %t$13, i64 %t$16)
  %t$56 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$18 = getelementptr inbounds { i64, [11 x i8] }, ptr @.str.3, i64 0, i32 1, i64 0
  %t$19 = ptrtoint ptr %t$18 to i64
  %t$57 = alloca i64
  store i64 %t$17, ptr %t$57
  %t$58 = call i64 @sprout_gc_push_i64_root(ptr %t$57)
  %t$59 = alloca i64
  store i64 %t$19, ptr %t$59
  %t$60 = call i64 @sprout_gc_push_i64_root(ptr %t$59)
  %t$20 = call i64 @__tc_Semigroup_String_append(i64 %t$17, i64 %t$19)
  %t$61 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$62 = alloca i64
  store i64 %t$20, ptr %t$62
  %t$63 = call i64 @sprout_gc_push_i64_root(ptr %t$62)
  %t$21 = call i64 @__tc_Semigroup_String_append(i64 %t$20, i64 %replaced)
  %t$64 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$22 = getelementptr inbounds { i64, [10 x i8] }, ptr @.str.4, i64 0, i32 1, i64 0
  %t$23 = ptrtoint ptr %t$22 to i64
  %t$65 = alloca i64
  store i64 %t$21, ptr %t$65
  %t$66 = call i64 @sprout_gc_push_i64_root(ptr %t$65)
  %t$67 = alloca i64
  store i64 %t$23, ptr %t$67
  %t$68 = call i64 @sprout_gc_push_i64_root(ptr %t$67)
  %t$24 = call i64 @__tc_Semigroup_String_append(i64 %t$21, i64 %t$23)
  %t$69 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$70 = alloca i64
  store i64 %t$24, ptr %t$70
  %t$71 = call i64 @sprout_gc_push_i64_root(ptr %t$70)
  %t$25 = call i64 @__tc_Semigroup_String_append(i64 %t$24, i64 %escaped)
  %t$72 = call i64 @sprout_gc_pop_roots(i64 4)
  ret i64 %t$25
}

define i64 @examples.regex_demo.summarize_found(i64 %re, i64 %raw) {
entry:
  %t$29 = alloca i64
  store i64 %re, ptr %t$29
  %t$30 = call i64 @sprout_gc_push_i64_root(ptr %t$29)
  %t$31 = alloca i64
  store i64 %raw, ptr %t$31
  %t$32 = call i64 @sprout_gc_push_i64_root(ptr %t$31)
  %t$0 = call i64 @stdlib.regex.find_first(i64 %re, i64 %raw)
  %t$1 = call i64 @sprout_tag(i64 %t$0)
  %t$33 = call i64 @sprout_gc_pop_roots(i64 2)
  br label %arm_0_2
arm_0_2:
  %t$4 = add i64 0, 1
  %t$5 = icmp eq i64 %t$1, %t$4
  br i1 %t$5, label %body_0_2, label %arm_1_2
body_0_2:
  %t$6 = call i64 @sprout_field(i64 %t$0, i64 0)
  %t$7 = call i64 @sprout_tag(i64 %t$6)
  %t$8 = add i64 0, 17
  %t$9 = icmp eq i64 %t$7, %t$8
  br i1 %t$9, label %ntest_6, label %arm_1_2
ntest_6:
  %t$10 = call i64 @sprout_field(i64 %t$6, i64 0)
  %t$11 = call i64 @sprout_field(i64 %t$6, i64 1)
  %t$12 = getelementptr inbounds { i64, [5 x i8] }, ptr @.str.5, i64 0, i32 1, i64 0
  %t$13 = ptrtoint ptr %t$12 to i64
  %t$34 = alloca i64
  store i64 %re, ptr %t$34
  %t$35 = call i64 @sprout_gc_push_i64_root(ptr %t$34)
  %t$36 = alloca i64
  store i64 %raw, ptr %t$36
  %t$37 = call i64 @sprout_gc_push_i64_root(ptr %t$36)
  %t$38 = alloca i64
  store i64 %t$13, ptr %t$38
  %t$39 = call i64 @sprout_gc_push_i64_root(ptr %t$38)
  %t$14 = call i64 @stdlib.regex.replace_all_literal(i64 %re, i64 %t$13, i64 %raw)
  %t$40 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$15 = getelementptr inbounds { i64, [15 x i8] }, ptr @.str.6, i64 0, i32 1, i64 0
  %t$16 = ptrtoint ptr %t$15 to i64
  %t$41 = alloca i64
  store i64 %t$14, ptr %t$41
  %t$42 = call i64 @sprout_gc_push_i64_root(ptr %t$41)
  %t$43 = alloca i64
  store i64 %t$16, ptr %t$43
  %t$44 = call i64 @sprout_gc_push_i64_root(ptr %t$43)
  %t$17 = call i64 @stdlib.regex.escape(i64 %t$16)
  %t$45 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$46 = alloca i64
  store i64 %t$17, ptr %t$46
  %t$47 = call i64 @sprout_gc_push_i64_root(ptr %t$46)
  %t$18 = call i64 @examples.regex_demo.render_match(i64 %raw, i64 %t$10, i64 %t$11, i64 %t$14, i64 %t$17)
  %t$48 = call i64 @sprout_gc_pop_roots(i64 4)
  br label %join_2
arm_1_2:
  %t$19 = add i64 0, 0
  %t$20 = icmp eq i64 %t$1, %t$19
  br i1 %t$20, label %body_1_2, label %arm_2_2
body_1_2:
  %t$49 = alloca i64
  store i64 %re, ptr %t$49
  %t$50 = call i64 @sprout_gc_push_i64_root(ptr %t$49)
  %t$51 = alloca i64
  store i64 %raw, ptr %t$51
  %t$52 = call i64 @sprout_gc_push_i64_root(ptr %t$51)
  %t$21 = call i64 @stdlib.regex.is_match(i64 %re, i64 %raw)
  %t$53 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$28 = trunc i64 %t$21 to i1
  br i1 %t$28, label %then_22, label %else_22
then_22:
  %t$24 = getelementptr inbounds { i64, [27 x i8] }, ptr @.str.7, i64 0, i32 1, i64 0
  %t$25 = ptrtoint ptr %t$24 to i64
  br label %join_22
else_22:
  %t$26 = getelementptr inbounds { i64, [12 x i8] }, ptr @.str.8, i64 0, i32 1, i64 0
  %t$27 = ptrtoint ptr %t$26 to i64
  br label %join_22
join_22:
  %t$23 = phi i64 [%t$25, %then_22], [%t$27, %else_22]
  br label %join_2
arm_2_2:
  call void @sprout_abort_match()
  unreachable
join_2:
  %t$3 = phi i64 [%t$18, %ntest_6], [%t$23, %join_22]
  ret i64 %t$3
}

define i64 @examples.regex_demo.summarize(i64 %raw) {
entry:
  %t$0 = getelementptr inbounds { i64, [18 x i8] }, ptr @.str.9, i64 0, i32 1, i64 0
  %t$1 = ptrtoint ptr %t$0 to i64
  %t$26 = alloca i64
  store i64 %raw, ptr %t$26
  %t$27 = call i64 @sprout_gc_push_i64_root(ptr %t$26)
  %t$28 = alloca i64
  store i64 %t$1, ptr %t$28
  %t$29 = call i64 @sprout_gc_push_i64_root(ptr %t$28)
  %t$2$st = call { i64, i64 } @stdlib.regex.compile_worker(i64 %t$1)
  %t$2 = extractvalue { i64, i64 } %t$2$st, 0
  %t$3 = extractvalue { i64, i64 } %t$2$st, 1
  %t$30 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$31 = call i64 @sprout_gc_pop_roots(i64 1)
  br label %arm_0_4
arm_0_4:
  %t$6 = add i64 0, 7
  %t$7 = icmp eq i64 %t$2, %t$6
  br i1 %t$7, label %body_0_4, label %arm_1_4
body_0_4:
  %t$32 = alloca i64
  store i64 %t$3, ptr %t$32
  %t$33 = call i64 @sprout_gc_push_i64_root(ptr %t$32)
  %t$34 = alloca i64
  store i64 %raw, ptr %t$34
  %t$35 = call i64 @sprout_gc_push_i64_root(ptr %t$34)
  %t$8 = call i64 @examples.regex_demo.summarize_found(i64 %t$3, i64 %raw)
  %t$36 = call i64 @sprout_gc_pop_roots(i64 2)
  br label %join_4
arm_1_4:
  %t$9 = add i64 0, 8
  %t$10 = icmp eq i64 %t$2, %t$9
  br i1 %t$10, label %body_1_4, label %arm_2_4
body_1_4:
  %t$11 = call i64 @sprout_tag(i64 %t$3)
  br label %arm_0_12
arm_0_12:
  %t$14 = add i64 0, 14
  %t$15 = icmp eq i64 %t$11, %t$14
  br i1 %t$15, label %body_0_12, label %arm_1_12
body_0_12:
  %t$16 = call i64 @sprout_field(i64 %t$3, i64 0)
  %t$17 = getelementptr inbounds { i64, [18 x i8] }, ptr @.str.10, i64 0, i32 1, i64 0
  %t$18 = ptrtoint ptr %t$17 to i64
  %t$37 = alloca i64
  store i64 %t$16, ptr %t$37
  %t$38 = call i64 @sprout_gc_push_i64_root(ptr %t$37)
  %t$39 = alloca i64
  store i64 %t$18, ptr %t$39
  %t$40 = call i64 @sprout_gc_push_i64_root(ptr %t$39)
  %t$19 = call i64 @__tc_Semigroup_String_append(i64 %t$18, i64 %t$16)
  %t$41 = call i64 @sprout_gc_pop_roots(i64 2)
  br label %join_12
arm_1_12:
  %t$20 = add i64 0, 15
  %t$21 = icmp eq i64 %t$11, %t$20
  br i1 %t$21, label %body_1_12, label %arm_2_12
body_1_12:
  %t$22 = call i64 @sprout_field(i64 %t$3, i64 0)
  %t$23 = getelementptr inbounds { i64, [22 x i8] }, ptr @.str.11, i64 0, i32 1, i64 0
  %t$24 = ptrtoint ptr %t$23 to i64
  %t$42 = alloca i64
  store i64 %t$22, ptr %t$42
  %t$43 = call i64 @sprout_gc_push_i64_root(ptr %t$42)
  %t$44 = alloca i64
  store i64 %t$24, ptr %t$44
  %t$45 = call i64 @sprout_gc_push_i64_root(ptr %t$44)
  %t$25 = call i64 @__tc_Semigroup_String_append(i64 %t$24, i64 %t$22)
  %t$46 = call i64 @sprout_gc_pop_roots(i64 2)
  br label %join_12
arm_2_12:
  call void @sprout_abort_match()
  unreachable
join_12:
  %t$13 = phi i64 [%t$19, %body_0_12], [%t$25, %body_1_12]
  br label %join_4
arm_2_4:
  call void @sprout_abort_match()
  unreachable
join_4:
  %t$5 = phi i64 [%t$8, %body_0_4], [%t$13, %join_12]
  ret i64 %t$5
}

define i64 @__sprout_user_main() {
entry:
  %t$0 = add i64 0, 0
  %t$1$st = call { i64, i64 } @argv_get_unboxed(i64 %t$0)
  %t$1 = extractvalue { i64, i64 } %t$1$st, 0
  %t$2 = extractvalue { i64, i64 } %t$1$st, 1
  br label %arm_0_3
arm_0_3:
  %t$5 = add i64 0, 0
  %t$6 = icmp eq i64 %t$1, %t$5
  br i1 %t$6, label %body_0_3, label %arm_1_3
body_0_3:
  %t$7 = getelementptr inbounds { i64, [52 x i8] }, ptr @.str.12, i64 0, i32 1, i64 0
  %t$8 = ptrtoint ptr %t$7 to i64
  %t$9$ptr = inttoptr i64 %t$8 to ptr
  %t$9 = call i64 @print_str(ptr %t$9$ptr)
  br label %join_3
arm_1_3:
  %t$10 = add i64 0, 1
  %t$11 = icmp eq i64 %t$1, %t$10
  br i1 %t$11, label %body_1_3, label %arm_2_3
body_1_3:
  %t$14 = alloca i64
  store i64 %t$2, ptr %t$14
  %t$15 = call i64 @sprout_gc_push_i64_root(ptr %t$14)
  %t$12 = call i64 @examples.regex_demo.summarize(i64 %t$2)
  %t$16 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$13$ptr = inttoptr i64 %t$12 to ptr
  %t$13 = call i64 @print_str(ptr %t$13$ptr)
  br label %join_3
arm_2_3:
  call void @sprout_abort_match()
  unreachable
join_3:
  %t$4 = phi i64 [%t$9, %body_0_3], [%t$13, %body_1_3]
  ret i64 %t$4
}

define i64 @__cm_Foldable_fold_values(i64 %step, i64 %init, i64 %xs, i64 %__tc_Foldable_0_fold_values) {
entry:
  call void @sprout_closure_arity_check(i64 %__tc_Foldable_0_fold_values, i64 3)
  %t$0$env_ptr = inttoptr i64 %__tc_Foldable_0_fold_values to ptr
  %t$0$code = load ptr, ptr %t$0$env_ptr
  %t$0 = call i64 (i64, i64, i64, i64) %t$0$code(i64 %__tc_Foldable_0_fold_values, i64 %step, i64 %init, i64 %xs)
  ret i64 %t$0
}

define i64 @__tc_Semigroup_String_append(i64 %left, i64 %right) {
entry:
  %t$0 = call i64 @str_concat(i64 %left, i64 %right)
  ret i64 %t$0
}

define { i64, i64 } @regex_validate_worker(i64 %pattern) {
entry:
  %t$10 = alloca i64
  store i64 %pattern, ptr %t$10
  %t$11 = call i64 @sprout_gc_push_i64_root(ptr %t$10)
  %t$0 = call i64 @regex_validate(i64 %pattern)
  %t$12 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$1 = call i64 @sprout_tag(i64 %t$0)
  %t$2 = add i64 0, 7
  %t$3 = icmp eq i64 %t$1, %t$2
  br i1 %t$3, label %wrepack_hit_2, label %wrepack_next_2
wrepack_hit_2:
  %t$4 = call i64 @sprout_field(i64 %t$0, i64 0)
  %t$5$r0 = insertvalue { i64, i64 } undef, i64 %t$1, 0
  %t$5$r1 = insertvalue { i64, i64 } %t$5$r0, i64 %t$4, 1
  ret { i64, i64 } %t$5$r1
wrepack_next_2:
  %t$6 = add i64 0, 8
  %t$7 = icmp eq i64 %t$1, %t$6
  br i1 %t$7, label %wrepack_hit_6, label %wrepack_next_6
wrepack_hit_6:
  %t$8 = call i64 @sprout_field(i64 %t$0, i64 0)
  %t$9$r0 = insertvalue { i64, i64 } undef, i64 %t$1, 0
  %t$9$r1 = insertvalue { i64, i64 } %t$9$r0, i64 %t$8, 1
  ret { i64, i64 } %t$9$r1
wrepack_next_6:
  call void @sprout_abort_match()
  unreachable
}

define { i64, i64 } @stdlib.regex.compile_worker(i64 %pattern) {
entry:
  %t$21 = alloca i64
  store i64 %pattern, ptr %t$21
  %t$22 = call i64 @sprout_gc_push_i64_root(ptr %t$21)
  %t$0$st = call { i64, i64 } @regex_validate_worker(i64 %pattern)
  %t$0 = extractvalue { i64, i64 } %t$0$st, 0
  %t$1 = extractvalue { i64, i64 } %t$0$st, 1
  %t$23 = call i64 @sprout_gc_pop_roots(i64 1)
  br label %arm_0_2
arm_0_2:
  %t$4 = add i64 0, 7
  %t$5 = icmp eq i64 %t$0, %t$4
  br i1 %t$5, label %body_0_2, label %arm_1_2
body_0_2:
  %t$24 = alloca i64
  store i64 %pattern, ptr %t$24
  %t$25 = call i64 @sprout_gc_push_i64_root(ptr %t$24)
  %t$6 = call i64 @sprout_alloc_obj(i64 16, i64 1)
  %t$6$ptr = inttoptr i64 %t$6 to ptr
  %t$6$f0 = getelementptr i64, ptr %t$6$ptr, i64 0
  store i64 %pattern, ptr %t$6$f0
  %t$26 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$27 = alloca i64
  store i64 %t$6, ptr %t$27
  %t$28 = call i64 @sprout_gc_push_i64_root(ptr %t$27)
  %t$7 = call i64 @sprout_alloc_obj(i64 7, i64 1)
  %t$7$ptr = inttoptr i64 %t$7 to ptr
  %t$7$f0 = getelementptr i64, ptr %t$7$ptr, i64 0
  store i64 %t$6, ptr %t$7$f0
  %t$29 = call i64 @sprout_gc_pop_roots(i64 1)
  br label %join_2
arm_1_2:
  %t$8 = add i64 0, 8
  %t$9 = icmp eq i64 %t$0, %t$8
  br i1 %t$9, label %body_1_2, label %arm_2_2
body_1_2:
  %t$30 = alloca i64
  store i64 %t$1, ptr %t$30
  %t$31 = call i64 @sprout_gc_push_i64_root(ptr %t$30)
  %t$10 = call i64 @stdlib.regex.classify_compile_error(i64 %t$1)
  %t$32 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$33 = alloca i64
  store i64 %t$10, ptr %t$33
  %t$34 = call i64 @sprout_gc_push_i64_root(ptr %t$33)
  %t$11 = call i64 @sprout_alloc_obj(i64 8, i64 1)
  %t$11$ptr = inttoptr i64 %t$11 to ptr
  %t$11$f0 = getelementptr i64, ptr %t$11$ptr, i64 0
  store i64 %t$10, ptr %t$11$f0
  %t$35 = call i64 @sprout_gc_pop_roots(i64 1)
  br label %join_2
arm_2_2:
  call void @sprout_abort_match()
  unreachable
join_2:
  %t$3 = phi i64 [%t$7, %body_0_2], [%t$11, %body_1_2]
  %t$12 = call i64 @sprout_tag(i64 %t$3)
  %t$13 = add i64 0, 7
  %t$14 = icmp eq i64 %t$12, %t$13
  br i1 %t$14, label %wrepack_hit_13, label %wrepack_next_13
wrepack_hit_13:
  %t$15 = call i64 @sprout_field(i64 %t$3, i64 0)
  %t$16$r0 = insertvalue { i64, i64 } undef, i64 %t$12, 0
  %t$16$r1 = insertvalue { i64, i64 } %t$16$r0, i64 %t$15, 1
  ret { i64, i64 } %t$16$r1
wrepack_next_13:
  %t$17 = add i64 0, 8
  %t$18 = icmp eq i64 %t$12, %t$17
  br i1 %t$18, label %wrepack_hit_17, label %wrepack_next_17
wrepack_hit_17:
  %t$19 = call i64 @sprout_field(i64 %t$3, i64 0)
  %t$20$r0 = insertvalue { i64, i64 } undef, i64 %t$12, 0
  %t$20$r1 = insertvalue { i64, i64 } %t$20$r0, i64 %t$19, 1
  ret { i64, i64 } %t$20$r1
wrepack_next_17:
  call void @sprout_abort_match()
  unreachable
}

define void @__sprout_init_globals() {
entry:
  %t$0 = getelementptr inbounds { i64, [28 x i8] }, ptr @.str.13, i64 0, i32 1, i64 0
  %t$1 = ptrtoint ptr %t$0 to i64
  store i64 %t$1, ptr @stdlib.regex.unsupported_prefix
  call i64 @sprout_gc_register_i64_root(ptr @stdlib.regex.unsupported_prefix)
  ret void
}

define i32 @main(i32 %argc, ptr %argv) {
entry:
  %argv_set = call i64 @sprout_set_argv(i32 %argc, ptr %argv)
  %cname_ptr_0 = getelementptr inbounds [8 x i8], ptr @.cname.0, i64 0, i64 0
  %cfkinds_ptr_0 = getelementptr inbounds [1 x i8], ptr @.cfkinds.0, i64 0, i64 0
  %creg_0 = call i64 @sprout_register_ctor(i64 0, ptr %cname_ptr_0, i64 0, ptr %cfkinds_ptr_0)
  %cname_ptr_1 = getelementptr inbounds [5 x i8], ptr @.cname.1, i64 0, i64 0
  %cfkinds_ptr_1 = getelementptr inbounds [2 x i8], ptr @.cfkinds.1, i64 0, i64 0
  %creg_1 = call i64 @sprout_register_ctor(i64 1, ptr %cname_ptr_1, i64 1, ptr %cfkinds_ptr_1)
  %cname_ptr_2 = getelementptr inbounds [12 x i8], ptr @.cname.2, i64 0, i64 0
  %cfkinds_ptr_2 = getelementptr inbounds [2 x i8], ptr @.cfkinds.2, i64 0, i64 0
  %creg_2 = call i64 @sprout_register_ctor(i64 2, ptr %cname_ptr_2, i64 1, ptr %cfkinds_ptr_2)
  %cname_ptr_3 = getelementptr inbounds [15 x i8], ptr @.cname.3, i64 0, i64 0
  %cfkinds_ptr_3 = getelementptr inbounds [2 x i8], ptr @.cfkinds.3, i64 0, i64 0
  %creg_3 = call i64 @sprout_register_ctor(i64 3, ptr %cname_ptr_3, i64 1, ptr %cfkinds_ptr_3)
  %cname_ptr_4 = getelementptr inbounds [15 x i8], ptr @.cname.4, i64 0, i64 0
  %cfkinds_ptr_4 = getelementptr inbounds [2 x i8], ptr @.cfkinds.4, i64 0, i64 0
  %creg_4 = call i64 @sprout_register_ctor(i64 4, ptr %cname_ptr_4, i64 1, ptr %cfkinds_ptr_4)
  %cname_ptr_5 = getelementptr inbounds [4 x i8], ptr @.cname.5, i64 0, i64 0
  %cfkinds_ptr_5 = getelementptr inbounds [1 x i8], ptr @.cfkinds.5, i64 0, i64 0
  %creg_5 = call i64 @sprout_register_ctor(i64 5, ptr %cname_ptr_5, i64 0, ptr %cfkinds_ptr_5)
  %cname_ptr_6 = getelementptr inbounds [5 x i8], ptr @.cname.6, i64 0, i64 0
  %cfkinds_ptr_6 = getelementptr inbounds [3 x i8], ptr @.cfkinds.6, i64 0, i64 0
  %creg_6 = call i64 @sprout_register_ctor(i64 6, ptr %cname_ptr_6, i64 2, ptr %cfkinds_ptr_6)
  %cname_ptr_7 = getelementptr inbounds [3 x i8], ptr @.cname.7, i64 0, i64 0
  %cfkinds_ptr_7 = getelementptr inbounds [2 x i8], ptr @.cfkinds.7, i64 0, i64 0
  %creg_7 = call i64 @sprout_register_ctor(i64 7, ptr %cname_ptr_7, i64 1, ptr %cfkinds_ptr_7)
  %cname_ptr_8 = getelementptr inbounds [4 x i8], ptr @.cname.8, i64 0, i64 0
  %cfkinds_ptr_8 = getelementptr inbounds [2 x i8], ptr @.cfkinds.8, i64 0, i64 0
  %creg_8 = call i64 @sprout_register_ctor(i64 8, ptr %cname_ptr_8, i64 1, ptr %cfkinds_ptr_8)
  %cname_ptr_9 = getelementptr inbounds [10 x i8], ptr @.cname.9, i64 0, i64 0
  %cfkinds_ptr_9 = getelementptr inbounds [1 x i8], ptr @.cfkinds.9, i64 0, i64 0
  %creg_9 = call i64 @sprout_register_ctor(i64 9, ptr %cname_ptr_9, i64 0, ptr %cfkinds_ptr_9)
  %cname_ptr_10 = getelementptr inbounds [4 x i8], ptr @.cname.10, i64 0, i64 0
  %cfkinds_ptr_10 = getelementptr inbounds [2 x i8], ptr @.cfkinds.10, i64 0, i64 0
  %creg_10 = call i64 @sprout_register_ctor(i64 10, ptr %cname_ptr_10, i64 1, ptr %cfkinds_ptr_10)
  %cname_ptr_11 = getelementptr inbounds [5 x i8], ptr @.cname.11, i64 0, i64 0
  %cfkinds_ptr_11 = getelementptr inbounds [2 x i8], ptr @.cfkinds.11, i64 0, i64 0
  %creg_11 = call i64 @sprout_register_ctor(i64 11, ptr %cname_ptr_11, i64 1, ptr %cfkinds_ptr_11)
  %cname_ptr_12 = getelementptr inbounds [4 x i8], ptr @.cname.12, i64 0, i64 0
  %cfkinds_ptr_12 = getelementptr inbounds [2 x i8], ptr @.cfkinds.12, i64 0, i64 0
  %creg_12 = call i64 @sprout_register_ctor(i64 12, ptr %cname_ptr_12, i64 1, ptr %cfkinds_ptr_12)
  %cname_ptr_13 = getelementptr inbounds [9 x i8], ptr @.cname.13, i64 0, i64 0
  %cfkinds_ptr_13 = getelementptr inbounds [4 x i8], ptr @.cfkinds.13, i64 0, i64 0
  %creg_13 = call i64 @sprout_register_ctor(i64 13, ptr %cname_ptr_13, i64 3, ptr %cfkinds_ptr_13)
  %cname_ptr_14 = getelementptr inbounds [33 x i8], ptr @.cname.14, i64 0, i64 0
  %cfkinds_ptr_14 = getelementptr inbounds [2 x i8], ptr @.cfkinds.14, i64 0, i64 0
  %creg_14 = call i64 @sprout_register_ctor(i64 14, ptr %cname_ptr_14, i64 1, ptr %cfkinds_ptr_14)
  %cname_ptr_15 = getelementptr inbounds [37 x i8], ptr @.cname.15, i64 0, i64 0
  %cfkinds_ptr_15 = getelementptr inbounds [2 x i8], ptr @.cfkinds.15, i64 0, i64 0
  %creg_15 = call i64 @sprout_register_ctor(i64 15, ptr %cname_ptr_15, i64 1, ptr %cfkinds_ptr_15)
  %cname_ptr_16 = getelementptr inbounds [19 x i8], ptr @.cname.16, i64 0, i64 0
  %cfkinds_ptr_16 = getelementptr inbounds [2 x i8], ptr @.cfkinds.16, i64 0, i64 0
  %creg_16 = call i64 @sprout_register_ctor(i64 16, ptr %cname_ptr_16, i64 1, ptr %cfkinds_ptr_16)
  %cname_ptr_17 = getelementptr inbounds [19 x i8], ptr @.cname.17, i64 0, i64 0
  %cfkinds_ptr_17 = getelementptr inbounds [3 x i8], ptr @.cfkinds.17, i64 0, i64 0
  %creg_17 = call i64 @sprout_register_ctor(i64 17, ptr %cname_ptr_17, i64 2, ptr %cfkinds_ptr_17)
  %cname_ptr_18 = getelementptr inbounds [29 x i8], ptr @.cname.18, i64 0, i64 0
  %cfkinds_ptr_18 = getelementptr inbounds [2 x i8], ptr @.cfkinds.18, i64 0, i64 0
  %creg_18 = call i64 @sprout_register_ctor(i64 18, ptr %cname_ptr_18, i64 1, ptr %cfkinds_ptr_18)
  call void @__sprout_init_globals()
  call i64 @__sprout_user_main()
  ret i32 0
}

