; Generated by sprout ir_lowering.sprout (M2 PR 2.3)
target triple = "unknown-unknown-unknown"
declare i64 @str_concat(i64, i64)
declare i1 @str_eq(ptr, ptr)
declare i64 @str_compare(i64, i64)
declare i64 @str_slice(i64, i64, i64)
declare i64 @int_to_string(i64)
declare i64 @char_to_string(i64)
declare i64 @sprout_gc_push_i64_root(ptr)
declare i64 @sprout_gc_pop_roots(i64)
declare i64 @sprout_gc_register_i64_root(ptr)
declare i64 @sprout_alloc_closure(i64, i64)
declare void @sprout_closure_arity_check(i64, i64)
declare i64 @sprout_alloc_tuple_blob(i64)
declare i64 @sprout_register_ctor(i64, ptr, i64, ptr)
declare i64 @sprout_tag(i64)
declare i64 @sprout_field(i64, i64)
declare void @sprout_abort_match() noreturn
declare i64 @panic(i64)
declare ptr @llvm.stacksave()
declare void @llvm.stackrestore(ptr)
declare i64 @sprout_alloc_obj(i64, i64)
declare { i64, i64 } @vector_get_unboxed(i64, i64)
declare { i64, i64 } @map_get_unboxed(i64, i64)
declare { i64, i64 } @map_nth_key_unboxed(i64, i64)
declare { i64, i64 } @map_nth_value_unboxed(i64, i64)
declare { i64, i64 } @bytes_get_unboxed(i64, i64)
declare { i64, i64 } @str_char_at_unboxed(i64, i64)
declare { i64, i64 } @argv_get_unboxed(i64)
declare { i64, i64 } @env_get_unboxed(i64)
declare i64 @print_str(ptr)
declare i64 @print_value(i64)
declare i64 @eprint_str(ptr)
declare i64 @argv_get(i64)
declare i64 @sprout_set_argv(i32, ptr)
declare i64 @analysis_check_source(ptr)
declare i64 @analysis_declared_names_in_source(ptr)
declare i64 @analysis_exported_names_in_source(ptr)
declare i64 @analysis_symbol_inventory_in_source(ptr)
declare i64 @analysis_diagnostics_in_source(ptr)
declare i64 @analysis_symbol_locations_in_source(ptr)
declare i64 @analysis_type_of_in_source(ptr, ptr)
declare i64 @analysis_eval_expr_in_source(ptr, ptr)
declare i64 @analysis_instances_in_source(ptr, ptr)
declare i64 @analysis_complete_in_state(ptr, ptr, ptr)

declare i64 @double_to_string(i64)
declare i64 @char_to_str(i64)
declare i64 @char_from_codepoint(i64)
declare i64 @to_double(i64)
declare i64 @string_concat_many(i64)
declare i64 @str_len(i64)
declare i64 @str_char_at(i64, i64)
declare i64 @str_find(i64, i64)
declare i64 @str_starts_with(i64, i64)
declare i64 @vector_empty()
declare i64 @vector_length(i64)
declare i64 @vector_get(i64, i64)
declare i64 @vector_set(i64, i64, i64)
declare i64 @vector_append(i64, i64)
declare i64 @vector_concat(i64, i64)
declare i64 @vector_from_list(i64)
declare i64 @map_empty()
declare i64 @map_get(i64, i64)
declare i64 @map_set(i64, i64, i64)
declare i64 @map_remove(i64, i64)
declare i64 @map_size(i64)
declare i64 @map_nth_key(i64, i64)
declare i64 @map_nth_value(i64, i64)
declare i64 @native_set_empty()
declare i64 @native_set_insert(i64, i64)
declare i64 @native_set_member(i64, i64)
declare i64 @native_set_to_list(i64)
declare i64 @native_set_size(i64)
declare i64 @ref_new(i64)
declare i64 @ref_read(i64)
declare i64 @ref_write(i64, i64)
@.str.0 = private unnamed_addr constant { i64, [10 x i8] } { i64 147466, [10 x i8] c"localhost\00" }
@.str.1 = private unnamed_addr constant { i64, [16 x i8] } { i64 245770, [16 x i8] c"api.example.com\00" }
@.str.2 = private unnamed_addr constant { i64, [4 x i8] } { i64 49162, [4 x i8] c"env\00" }
@.str.3 = private unnamed_addr constant { i64, [2 x i8] } { i64 16394, [2 x i8] c":\00" }
@.str.4 = private unnamed_addr constant { i64, [8 x i8] } { i64 114698, [8 x i8] c" read<=\00" }
@.str.5 = private unnamed_addr constant { i64, [3 x i8] } { i64 32778, [3 x i8] c"ms\00" }
@.str.6 = private unnamed_addr constant { i64, [26 x i8] } { i64 409610, [26 x i8] c"rebuilt equals original? \00" }
@.str.7 = private unnamed_addr constant { i64, [12 x i8] } { i64 180234, [12 x i8] c" came from \00" }
@.str.8 = private unnamed_addr constant { i64, [5 x i8] } { i64 65546, [5 x i8] c"true\00" }
@.str.9 = private unnamed_addr constant { i64, [6 x i8] } { i64 81930, [6 x i8] c"false\00" }
@.str.10 = private unnamed_addr constant { i64, [10 x i8] } { i64 147466, [10 x i8] c"Timeouts(\00" }
@.str.11 = private unnamed_addr constant { i64, [14 x i8] } { i64 213002, [14 x i8] c"connect_ms = \00" }
@.str.12 = private unnamed_addr constant { i64, [3 x i8] } { i64 32778, [3 x i8] c", \00" }
@.str.13 = private unnamed_addr constant { i64, [11 x i8] } { i64 163850, [11 x i8] c"read_ms = \00" }
@.str.14 = private unnamed_addr constant { i64, [2 x i8] } { i64 16394, [2 x i8] c")\00" }
@.cname.0 = private unnamed_addr constant [8 x i8] c"Nothing\00"
@.cfkinds.0 = private unnamed_addr constant [1 x i8] c"\00"
@.cname.1 = private unnamed_addr constant [5 x i8] c"Just\00"
@.cfkinds.1 = private unnamed_addr constant [2 x i8] c"_\00"
@.cname.2 = private unnamed_addr constant [12 x i8] c"TemplateLit\00"
@.cfkinds.2 = private unnamed_addr constant [2 x i8] c"s\00"
@.cname.3 = private unnamed_addr constant [15 x i8] c"TemplateInterp\00"
@.cfkinds.3 = private unnamed_addr constant [2 x i8] c"s\00"
@.cname.4 = private unnamed_addr constant [15 x i8] c"StringTemplate\00"
@.cfkinds.4 = private unnamed_addr constant [2 x i8] c"p\00"
@.cname.5 = private unnamed_addr constant [4 x i8] c"Nil\00"
@.cfkinds.5 = private unnamed_addr constant [1 x i8] c"\00"
@.cname.6 = private unnamed_addr constant [5 x i8] c"Cons\00"
@.cfkinds.6 = private unnamed_addr constant [3 x i8] c"_p\00"
@.cname.7 = private unnamed_addr constant [3 x i8] c"Ok\00"
@.cfkinds.7 = private unnamed_addr constant [2 x i8] c"_\00"
@.cname.8 = private unnamed_addr constant [4 x i8] c"Err\00"
@.cfkinds.8 = private unnamed_addr constant [2 x i8] c"_\00"
@.cname.9 = private unnamed_addr constant [10 x i8] c"DivByZero\00"
@.cfkinds.9 = private unnamed_addr constant [1 x i8] c"\00"
@.cname.10 = private unnamed_addr constant [4 x i8] c"Vec\00"
@.cfkinds.10 = private unnamed_addr constant [2 x i8] c"p\00"
@.cname.11 = private unnamed_addr constant [5 x i8] c"Dict\00"
@.cfkinds.11 = private unnamed_addr constant [2 x i8] c"p\00"
@.cname.12 = private unnamed_addr constant [4 x i8] c"Set\00"
@.cfkinds.12 = private unnamed_addr constant [2 x i8] c"p\00"
@.cname.13 = private unnamed_addr constant [9 x i8] c"IntRange\00"
@.cfkinds.13 = private unnamed_addr constant [4 x i8] c"iii\00"

define i64 @examples.records_demo.dev_server() {
entry:
  %t$0 = getelementptr inbounds { i64, [10 x i8] }, ptr @.str.0, i64 0, i32 1, i64 0
  %t$1 = ptrtoint ptr %t$0 to i64
  %t$2 = add i64 0, 8080
  %t$3 = add i64 0, 500
  %t$4 = add i64 0, 2000
  %t$7 = alloca i64
  store i64 %t$1, ptr %t$7
  %t$8 = call i64 @sprout_gc_push_i64_root(ptr %t$7)
  %t$5 = call i64 @sprout_alloc_obj(i64 14, i64 2)
  %t$5$ptr = inttoptr i64 %t$5 to ptr
  %t$5$f0 = getelementptr i64, ptr %t$5$ptr, i64 0
  store i64 %t$3, ptr %t$5$f0
  %t$5$f1 = getelementptr i64, ptr %t$5$ptr, i64 1
  store i64 %t$4, ptr %t$5$f1
  %t$9 = alloca i64
  store i64 %t$5, ptr %t$9
  %t$10 = call i64 @sprout_gc_push_i64_root(ptr %t$9)
  %t$6 = call i64 @sprout_alloc_obj(i64 15, i64 3)
  %t$6$ptr = inttoptr i64 %t$6 to ptr
  %t$6$f0 = getelementptr i64, ptr %t$6$ptr, i64 0
  store i64 %t$1, ptr %t$6$f0
  %t$6$f1 = getelementptr i64, ptr %t$6$ptr, i64 1
  store i64 %t$2, ptr %t$6$f1
  %t$6$f2 = getelementptr i64, ptr %t$6$ptr, i64 2
  store i64 %t$5, ptr %t$6$f2
  %t$11 = call i64 @sprout_gc_pop_roots(i64 2)
  ret i64 %t$6
}

define i64 @examples.records_demo.read_budget_ms(i64 %s) {
entry:
  %t$0 = call i64 @sprout_field(i64 %s, i64 2)
  %t$1 = call i64 @sprout_field(i64 %t$0, i64 1)
  ret i64 %t$1
}

define i64 @examples.records_demo.promote(i64 %s) {
entry:
  %t$0 = getelementptr inbounds { i64, [16 x i8] }, ptr @.str.1, i64 0, i32 1, i64 0
  %t$1 = ptrtoint ptr %t$0 to i64
  %t$2 = add i64 0, 443
  %t$3 = call i64 @sprout_field(i64 %s, i64 2)
  %t$5 = alloca i64
  store i64 %t$1, ptr %t$5
  %t$6 = call i64 @sprout_gc_push_i64_root(ptr %t$5)
  %t$7 = alloca i64
  store i64 %t$3, ptr %t$7
  %t$8 = call i64 @sprout_gc_push_i64_root(ptr %t$7)
  %t$4 = call i64 @sprout_alloc_obj(i64 15, i64 3)
  %t$4$ptr = inttoptr i64 %t$4 to ptr
  %t$4$f0 = getelementptr i64, ptr %t$4$ptr, i64 0
  store i64 %t$1, ptr %t$4$f0
  %t$4$f1 = getelementptr i64, ptr %t$4$ptr, i64 1
  store i64 %t$2, ptr %t$4$f1
  %t$4$f2 = getelementptr i64, ptr %t$4$ptr, i64 2
  store i64 %t$3, ptr %t$4$f2
  %t$9 = call i64 @sprout_gc_pop_roots(i64 2)
  ret i64 %t$4
}

define i64 @examples.records_demo.relax_read_budget(i64 %s) {
entry:
  %t$0 = call i64 @sprout_field(i64 %s, i64 0)
  %t$1 = call i64 @sprout_field(i64 %s, i64 1)
  %t$2 = call i64 @sprout_field(i64 %s, i64 2)
  %t$3 = call i64 @sprout_field(i64 %t$2, i64 0)
  %t$4 = call i64 @sprout_field(i64 %s, i64 2)
  %t$5 = call i64 @sprout_field(i64 %t$4, i64 1)
  %t$6 = add i64 0, 2
  %t$7 = mul i64 %t$5, %t$6
  %t$10 = alloca i64
  store i64 %t$0, ptr %t$10
  %t$11 = call i64 @sprout_gc_push_i64_root(ptr %t$10)
  %t$8 = call i64 @sprout_alloc_obj(i64 14, i64 2)
  %t$8$ptr = inttoptr i64 %t$8 to ptr
  %t$8$f0 = getelementptr i64, ptr %t$8$ptr, i64 0
  store i64 %t$3, ptr %t$8$f0
  %t$8$f1 = getelementptr i64, ptr %t$8$ptr, i64 1
  store i64 %t$7, ptr %t$8$f1
  %t$12 = alloca i64
  store i64 %t$8, ptr %t$12
  %t$13 = call i64 @sprout_gc_push_i64_root(ptr %t$12)
  %t$9 = call i64 @sprout_alloc_obj(i64 15, i64 3)
  %t$9$ptr = inttoptr i64 %t$9 to ptr
  %t$9$f0 = getelementptr i64, ptr %t$9$ptr, i64 0
  store i64 %t$0, ptr %t$9$f0
  %t$9$f1 = getelementptr i64, ptr %t$9$ptr, i64 1
  store i64 %t$1, ptr %t$9$f1
  %t$9$f2 = getelementptr i64, ptr %t$9$ptr, i64 2
  store i64 %t$8, ptr %t$9$f2
  %t$14 = call i64 @sprout_gc_pop_roots(i64 2)
  ret i64 %t$9
}

define i64 @examples.records_demo.tag_env(i64 %value) {
entry:
  %t$0 = getelementptr inbounds { i64, [4 x i8] }, ptr @.str.2, i64 0, i32 1, i64 0
  %t$1 = ptrtoint ptr %t$0 to i64
  %t$3 = alloca i64
  store i64 %value, ptr %t$3
  %t$4 = call i64 @sprout_gc_push_i64_root(ptr %t$3)
  %t$5 = alloca i64
  store i64 %t$1, ptr %t$5
  %t$6 = call i64 @sprout_gc_push_i64_root(ptr %t$5)
  %t$2 = call i64 @sprout_alloc_obj(i64 16, i64 2)
  %t$2$ptr = inttoptr i64 %t$2 to ptr
  %t$2$f0 = getelementptr i64, ptr %t$2$ptr, i64 0
  store i64 %value, ptr %t$2$f0
  %t$2$f1 = getelementptr i64, ptr %t$2$ptr, i64 1
  store i64 %t$1, ptr %t$2$f1
  %t$7 = call i64 @sprout_gc_pop_roots(i64 2)
  ret i64 %t$2
}

define i64 @examples.records_demo.describe(i64 %s) {
entry:
  %t$0 = call i64 @sprout_field(i64 %s, i64 0)
  %t$1 = call i64 @__tc_ToString_String_to_string(i64 %t$0)
  %t$2 = getelementptr inbounds { i64, [2 x i8] }, ptr @.str.3, i64 0, i32 1, i64 0
  %t$3 = ptrtoint ptr %t$2 to i64
  %t$4 = call i64 @sprout_field(i64 %s, i64 1)
  %t$22 = alloca i64
  store i64 %s, ptr %t$22
  %t$23 = call i64 @sprout_gc_push_i64_root(ptr %t$22)
  %t$24 = alloca i64
  store i64 %t$1, ptr %t$24
  %t$25 = call i64 @sprout_gc_push_i64_root(ptr %t$24)
  %t$26 = alloca i64
  store i64 %t$3, ptr %t$26
  %t$27 = call i64 @sprout_gc_push_i64_root(ptr %t$26)
  %t$5 = call i64 @__tc_ToString_Int_to_string(i64 %t$4)
  %t$6 = call i64 @__tc_ToString_String_to_string(i64 %t$5)
  %t$7 = getelementptr inbounds { i64, [8 x i8] }, ptr @.str.4, i64 0, i32 1, i64 0
  %t$8 = ptrtoint ptr %t$7 to i64
  %t$9 = call i64 @examples.records_demo.read_budget_ms(i64 %s)
  %t$28 = alloca i64
  store i64 %t$6, ptr %t$28
  %t$29 = call i64 @sprout_gc_push_i64_root(ptr %t$28)
  %t$30 = alloca i64
  store i64 %t$8, ptr %t$30
  %t$31 = call i64 @sprout_gc_push_i64_root(ptr %t$30)
  %t$10 = call i64 @__tc_ToString_Int_to_string(i64 %t$9)
  %t$11 = call i64 @__tc_ToString_String_to_string(i64 %t$10)
  %t$12 = getelementptr inbounds { i64, [3 x i8] }, ptr @.str.5, i64 0, i32 1, i64 0
  %t$13 = ptrtoint ptr %t$12 to i64
  %t$32 = alloca i64
  store i64 %t$11, ptr %t$32
  %t$33 = call i64 @sprout_gc_push_i64_root(ptr %t$32)
  %t$34 = alloca i64
  store i64 %t$13, ptr %t$34
  %t$35 = call i64 @sprout_gc_push_i64_root(ptr %t$34)
  %t$14 = call i64 @sprout_alloc_obj(i64 5, i64 0)
  %t$36 = alloca i64
  store i64 %t$14, ptr %t$36
  %t$37 = call i64 @sprout_gc_push_i64_root(ptr %t$36)
  %t$15 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$15$ptr = inttoptr i64 %t$15 to ptr
  %t$15$f0 = getelementptr i64, ptr %t$15$ptr, i64 0
  store i64 %t$13, ptr %t$15$f0
  %t$15$f1 = getelementptr i64, ptr %t$15$ptr, i64 1
  store i64 %t$14, ptr %t$15$f1
  %t$38 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$39 = alloca i64
  store i64 %t$15, ptr %t$39
  %t$40 = call i64 @sprout_gc_push_i64_root(ptr %t$39)
  %t$16 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$16$ptr = inttoptr i64 %t$16 to ptr
  %t$16$f0 = getelementptr i64, ptr %t$16$ptr, i64 0
  store i64 %t$11, ptr %t$16$f0
  %t$16$f1 = getelementptr i64, ptr %t$16$ptr, i64 1
  store i64 %t$15, ptr %t$16$f1
  %t$41 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$42 = alloca i64
  store i64 %t$16, ptr %t$42
  %t$43 = call i64 @sprout_gc_push_i64_root(ptr %t$42)
  %t$17 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$17$ptr = inttoptr i64 %t$17 to ptr
  %t$17$f0 = getelementptr i64, ptr %t$17$ptr, i64 0
  store i64 %t$8, ptr %t$17$f0
  %t$17$f1 = getelementptr i64, ptr %t$17$ptr, i64 1
  store i64 %t$16, ptr %t$17$f1
  %t$44 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$45 = alloca i64
  store i64 %t$17, ptr %t$45
  %t$46 = call i64 @sprout_gc_push_i64_root(ptr %t$45)
  %t$18 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$18$ptr = inttoptr i64 %t$18 to ptr
  %t$18$f0 = getelementptr i64, ptr %t$18$ptr, i64 0
  store i64 %t$6, ptr %t$18$f0
  %t$18$f1 = getelementptr i64, ptr %t$18$ptr, i64 1
  store i64 %t$17, ptr %t$18$f1
  %t$47 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$48 = alloca i64
  store i64 %t$18, ptr %t$48
  %t$49 = call i64 @sprout_gc_push_i64_root(ptr %t$48)
  %t$19 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$19$ptr = inttoptr i64 %t$19 to ptr
  %t$19$f0 = getelementptr i64, ptr %t$19$ptr, i64 0
  store i64 %t$3, ptr %t$19$f0
  %t$19$f1 = getelementptr i64, ptr %t$19$ptr, i64 1
  store i64 %t$18, ptr %t$19$f1
  %t$50 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$51 = alloca i64
  store i64 %t$19, ptr %t$51
  %t$52 = call i64 @sprout_gc_push_i64_root(ptr %t$51)
  %t$20 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$20$ptr = inttoptr i64 %t$20 to ptr
  %t$20$f0 = getelementptr i64, ptr %t$20$ptr, i64 0
  store i64 %t$1, ptr %t$20$f0
  %t$20$f1 = getelementptr i64, ptr %t$20$ptr, i64 1
  store i64 %t$19, ptr %t$20$f1
  %t$53 = call i64 @sprout_gc_pop_roots(i64 3)
  %t$54 = alloca i64
  store i64 %t$20, ptr %t$54
  %t$55 = call i64 @sprout_gc_push_i64_root(ptr %t$54)
  %t$21 = call i64 @string_concat_many(i64 %t$20)
  %t$56 = call i64 @sprout_gc_pop_roots(i64 1)
  ret i64 %t$21
}

define i64 @__sprout_user_main() {
entry:
  %t$0 = call i64 @examples.records_demo.dev_server()
  %t$40 = alloca i64
  store i64 %t$0, ptr %t$40
  %t$41 = call i64 @sprout_gc_push_i64_root(ptr %t$40)
  %t$1 = call i64 @examples.records_demo.describe(i64 %t$0)
  %t$2$ptr = inttoptr i64 %t$1 to ptr
  %t$2 = call i64 @print_str(ptr %t$2$ptr)
  %t$3 = call i64 @examples.records_demo.promote(i64 %t$0)
  %t$42 = alloca i64
  store i64 %t$3, ptr %t$42
  %t$43 = call i64 @sprout_gc_push_i64_root(ptr %t$42)
  %t$4 = call i64 @examples.records_demo.describe(i64 %t$3)
  %t$44 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$5$ptr = inttoptr i64 %t$4 to ptr
  %t$5 = call i64 @print_str(ptr %t$5$ptr)
  %t$6 = call i64 @examples.records_demo.relax_read_budget(i64 %t$0)
  %t$45 = alloca i64
  store i64 %t$6, ptr %t$45
  %t$46 = call i64 @sprout_gc_push_i64_root(ptr %t$45)
  %t$7 = call i64 @examples.records_demo.describe(i64 %t$6)
  %t$47 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$8$ptr = inttoptr i64 %t$7 to ptr
  %t$8 = call i64 @print_str(ptr %t$8$ptr)
  %t$9 = call i64 @examples.records_demo.describe(i64 %t$0)
  %t$10$ptr = inttoptr i64 %t$9 to ptr
  %t$10 = call i64 @print_str(ptr %t$10$ptr)
  %t$11 = call i64 @sprout_field(i64 %t$0, i64 2)
  %t$48 = alloca i64
  store i64 %t$11, ptr %t$48
  %t$49 = call i64 @sprout_gc_push_i64_root(ptr %t$48)
  %t$12 = call i64 @__tc_ToString_examples_records_demo_Timeouts_to_string(i64 %t$11)
  %t$50 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$13$ptr = inttoptr i64 %t$12 to ptr
  %t$13 = call i64 @print_str(ptr %t$13$ptr)
  %t$14 = getelementptr inbounds { i64, [26 x i8] }, ptr @.str.6, i64 0, i32 1, i64 0
  %t$15 = ptrtoint ptr %t$14 to i64
  %t$51 = alloca i64
  store i64 %t$15, ptr %t$51
  %t$52 = call i64 @sprout_gc_push_i64_root(ptr %t$51)
  %t$16 = call i64 @examples.records_demo.dev_server()
  %t$17 = call i64 @__tc_Eq_examples_records_demo_Server_eq(i64 %t$0, i64 %t$16)
  %t$18 = call i64 @__tc_ToString_Bool_to_string(i64 %t$17)
  %t$19 = call i64 @__tc_ToString_String_to_string(i64 %t$18)
  %t$53 = alloca i64
  store i64 %t$19, ptr %t$53
  %t$54 = call i64 @sprout_gc_push_i64_root(ptr %t$53)
  %t$20 = call i64 @sprout_alloc_obj(i64 5, i64 0)
  %t$55 = alloca i64
  store i64 %t$20, ptr %t$55
  %t$56 = call i64 @sprout_gc_push_i64_root(ptr %t$55)
  %t$21 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$21$ptr = inttoptr i64 %t$21 to ptr
  %t$21$f0 = getelementptr i64, ptr %t$21$ptr, i64 0
  store i64 %t$19, ptr %t$21$f0
  %t$21$f1 = getelementptr i64, ptr %t$21$ptr, i64 1
  store i64 %t$20, ptr %t$21$f1
  %t$57 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$58 = alloca i64
  store i64 %t$21, ptr %t$58
  %t$59 = call i64 @sprout_gc_push_i64_root(ptr %t$58)
  %t$22 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$22$ptr = inttoptr i64 %t$22 to ptr
  %t$22$f0 = getelementptr i64, ptr %t$22$ptr, i64 0
  store i64 %t$15, ptr %t$22$f0
  %t$22$f1 = getelementptr i64, ptr %t$22$ptr, i64 1
  store i64 %t$21, ptr %t$22$f1
  %t$60 = call i64 @sprout_gc_pop_roots(i64 3)
  %t$61 = alloca i64
  store i64 %t$22, ptr %t$61
  %t$62 = call i64 @sprout_gc_push_i64_root(ptr %t$61)
  %t$23 = call i64 @string_concat_many(i64 %t$22)
  %t$63 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$24$ptr = inttoptr i64 %t$23 to ptr
  %t$24 = call i64 @print_str(ptr %t$24$ptr)
  %t$25 = add i64 0, 8080
  %t$26 = call i64 @examples.records_demo.tag_env(i64 %t$25)
  %t$27 = call i64 @sprout_field(i64 %t$26, i64 0)
  %t$64 = alloca i64
  store i64 %t$26, ptr %t$64
  %t$65 = call i64 @sprout_gc_push_i64_root(ptr %t$64)
  %t$66 = alloca i64
  store i64 %t$27, ptr %t$66
  %t$67 = call i64 @sprout_gc_push_i64_root(ptr %t$66)
  %t$28 = call i64 @__tc_ToString_Int_to_string(i64 %t$27)
  %t$68 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$29 = call i64 @__tc_ToString_String_to_string(i64 %t$28)
  %t$30 = getelementptr inbounds { i64, [12 x i8] }, ptr @.str.7, i64 0, i32 1, i64 0
  %t$31 = ptrtoint ptr %t$30 to i64
  %t$32 = call i64 @sprout_field(i64 %t$26, i64 1)
  %t$33 = call i64 @__tc_ToString_String_to_string(i64 %t$32)
  %t$69 = alloca i64
  store i64 %t$29, ptr %t$69
  %t$70 = call i64 @sprout_gc_push_i64_root(ptr %t$69)
  %t$71 = alloca i64
  store i64 %t$31, ptr %t$71
  %t$72 = call i64 @sprout_gc_push_i64_root(ptr %t$71)
  %t$73 = alloca i64
  store i64 %t$33, ptr %t$73
  %t$74 = call i64 @sprout_gc_push_i64_root(ptr %t$73)
  %t$34 = call i64 @sprout_alloc_obj(i64 5, i64 0)
  %t$75 = alloca i64
  store i64 %t$34, ptr %t$75
  %t$76 = call i64 @sprout_gc_push_i64_root(ptr %t$75)
  %t$35 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$35$ptr = inttoptr i64 %t$35 to ptr
  %t$35$f0 = getelementptr i64, ptr %t$35$ptr, i64 0
  store i64 %t$33, ptr %t$35$f0
  %t$35$f1 = getelementptr i64, ptr %t$35$ptr, i64 1
  store i64 %t$34, ptr %t$35$f1
  %t$77 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$78 = alloca i64
  store i64 %t$35, ptr %t$78
  %t$79 = call i64 @sprout_gc_push_i64_root(ptr %t$78)
  %t$36 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$36$ptr = inttoptr i64 %t$36 to ptr
  %t$36$f0 = getelementptr i64, ptr %t$36$ptr, i64 0
  store i64 %t$31, ptr %t$36$f0
  %t$36$f1 = getelementptr i64, ptr %t$36$ptr, i64 1
  store i64 %t$35, ptr %t$36$f1
  %t$80 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$81 = alloca i64
  store i64 %t$36, ptr %t$81
  %t$82 = call i64 @sprout_gc_push_i64_root(ptr %t$81)
  %t$37 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$37$ptr = inttoptr i64 %t$37 to ptr
  %t$37$f0 = getelementptr i64, ptr %t$37$ptr, i64 0
  store i64 %t$29, ptr %t$37$f0
  %t$37$f1 = getelementptr i64, ptr %t$37$ptr, i64 1
  store i64 %t$36, ptr %t$37$f1
  %t$83 = call i64 @sprout_gc_pop_roots(i64 3)
  %t$84 = alloca i64
  store i64 %t$37, ptr %t$84
  %t$85 = call i64 @sprout_gc_push_i64_root(ptr %t$84)
  %t$38 = call i64 @string_concat_many(i64 %t$37)
  %t$86 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$39$ptr = inttoptr i64 %t$38 to ptr
  %t$39 = call i64 @print_str(ptr %t$39$ptr)
  ret i64 %t$39
}

define i64 @__tc_Semigroup_String_append(i64 %left, i64 %right) {
entry:
  %t$0 = call i64 @str_concat(i64 %left, i64 %right)
  ret i64 %t$0
}

define i64 @__tc_Eq_Int_eq(i64 %left, i64 %right) {
entry:
  %t$0 = icmp eq i64 %left, %right
  %t$1 = zext i1 %t$0 to i64
  ret i64 %t$1
}

define i64 @__tc_Eq_String_eq(i64 %left, i64 %right) {
entry:
  %t$0$lptr = inttoptr i64 %left to ptr
  %t$0$rptr = inttoptr i64 %right to ptr
  %t$0$i1 = call i1 @str_eq(ptr %t$0$lptr, ptr %t$0$rptr)
  %t$0 = zext i1 %t$0$i1 to i64
  ret i64 %t$0
}

define i64 @__tc_ToString_Int_to_string(i64 %value) {
entry:
  %t$0 = call i64 @int_to_string(i64 %value)
  ret i64 %t$0
}

define i64 @__tc_ToString_Bool_to_string(i64 %value) {
entry:
  %t$6 = trunc i64 %value to i1
  br i1 %t$6, label %then_0, label %else_0
then_0:
  %t$2 = getelementptr inbounds { i64, [5 x i8] }, ptr @.str.8, i64 0, i32 1, i64 0
  %t$3 = ptrtoint ptr %t$2 to i64
  br label %join_0
else_0:
  %t$4 = getelementptr inbounds { i64, [6 x i8] }, ptr @.str.9, i64 0, i32 1, i64 0
  %t$5 = ptrtoint ptr %t$4 to i64
  br label %join_0
join_0:
  %t$1 = phi i64 [%t$3, %then_0], [%t$5, %else_0]
  ret i64 %t$1
}

define i64 @__tc_ToString_String_to_string(i64 %value) {
entry:
  ret i64 %value
}

define i64 @__tc_Eq_examples_records_demo_Timeouts_eq(i64 %left, i64 %right) {
entry:
  %t$0 = call i64 @sprout_field(i64 %left, i64 0)
  %t$1 = call i64 @sprout_field(i64 %right, i64 0)
  %t$2 = call i64 @__tc_Eq_Int_eq(i64 %t$0, i64 %t$1)
  %t$9 = trunc i64 %t$2 to i1
  br i1 %t$9, label %then_3, label %else_3
then_3:
  %t$5 = call i64 @sprout_field(i64 %left, i64 1)
  %t$6 = call i64 @sprout_field(i64 %right, i64 1)
  %t$7 = call i64 @__tc_Eq_Int_eq(i64 %t$5, i64 %t$6)
  br label %join_3
else_3:
  %t$8 = add i64 0, 0
  br label %join_3
join_3:
  %t$4 = phi i64 [%t$7, %then_3], [%t$8, %else_3]
  ret i64 %t$4
}

define i64 @__tc_ToString_examples_records_demo_Timeouts_to_string(i64 %value) {
entry:
  %t$0 = getelementptr inbounds { i64, [10 x i8] }, ptr @.str.10, i64 0, i32 1, i64 0
  %t$1 = ptrtoint ptr %t$0 to i64
  %t$2 = getelementptr inbounds { i64, [14 x i8] }, ptr @.str.11, i64 0, i32 1, i64 0
  %t$3 = ptrtoint ptr %t$2 to i64
  %t$4 = call i64 @sprout_field(i64 %value, i64 0)
  %t$20 = alloca i64
  store i64 %value, ptr %t$20
  %t$21 = call i64 @sprout_gc_push_i64_root(ptr %t$20)
  %t$22 = alloca i64
  store i64 %t$1, ptr %t$22
  %t$23 = call i64 @sprout_gc_push_i64_root(ptr %t$22)
  %t$24 = alloca i64
  store i64 %t$3, ptr %t$24
  %t$25 = call i64 @sprout_gc_push_i64_root(ptr %t$24)
  %t$5 = call i64 @__tc_ToString_Int_to_string(i64 %t$4)
  %t$26 = alloca i64
  store i64 %t$5, ptr %t$26
  %t$27 = call i64 @sprout_gc_push_i64_root(ptr %t$26)
  %t$6 = call i64 @__tc_Semigroup_String_append(i64 %t$3, i64 %t$5)
  %t$28 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$7 = getelementptr inbounds { i64, [3 x i8] }, ptr @.str.12, i64 0, i32 1, i64 0
  %t$8 = ptrtoint ptr %t$7 to i64
  %t$9 = getelementptr inbounds { i64, [11 x i8] }, ptr @.str.13, i64 0, i32 1, i64 0
  %t$10 = ptrtoint ptr %t$9 to i64
  %t$11 = call i64 @sprout_field(i64 %value, i64 1)
  %t$29 = alloca i64
  store i64 %t$6, ptr %t$29
  %t$30 = call i64 @sprout_gc_push_i64_root(ptr %t$29)
  %t$31 = alloca i64
  store i64 %t$8, ptr %t$31
  %t$32 = call i64 @sprout_gc_push_i64_root(ptr %t$31)
  %t$33 = alloca i64
  store i64 %t$10, ptr %t$33
  %t$34 = call i64 @sprout_gc_push_i64_root(ptr %t$33)
  %t$12 = call i64 @__tc_ToString_Int_to_string(i64 %t$11)
  %t$35 = alloca i64
  store i64 %t$12, ptr %t$35
  %t$36 = call i64 @sprout_gc_push_i64_root(ptr %t$35)
  %t$13 = call i64 @__tc_Semigroup_String_append(i64 %t$10, i64 %t$12)
  %t$37 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$38 = alloca i64
  store i64 %t$13, ptr %t$38
  %t$39 = call i64 @sprout_gc_push_i64_root(ptr %t$38)
  %t$14 = call i64 @__tc_Semigroup_String_append(i64 %t$8, i64 %t$13)
  %t$40 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$41 = alloca i64
  store i64 %t$14, ptr %t$41
  %t$42 = call i64 @sprout_gc_push_i64_root(ptr %t$41)
  %t$15 = call i64 @__tc_Semigroup_String_append(i64 %t$6, i64 %t$14)
  %t$43 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$44 = alloca i64
  store i64 %t$15, ptr %t$44
  %t$45 = call i64 @sprout_gc_push_i64_root(ptr %t$44)
  %t$16 = call i64 @__tc_Semigroup_String_append(i64 %t$1, i64 %t$15)
  %t$46 = call i64 @sprout_gc_pop_roots(i64 3)
  %t$17 = getelementptr inbounds { i64, [2 x i8] }, ptr @.str.14, i64 0, i32 1, i64 0
  %t$18 = ptrtoint ptr %t$17 to i64
  %t$47 = alloca i64
  store i64 %t$16, ptr %t$47
  %t$48 = call i64 @sprout_gc_push_i64_root(ptr %t$47)
  %t$49 = alloca i64
  store i64 %t$18, ptr %t$49
  %t$50 = call i64 @sprout_gc_push_i64_root(ptr %t$49)
  %t$19 = call i64 @__tc_Semigroup_String_append(i64 %t$16, i64 %t$18)
  %t$51 = call i64 @sprout_gc_pop_roots(i64 2)
  ret i64 %t$19
}

define i64 @__tc_Eq_examples_records_demo_Server_eq(i64 %left, i64 %right) {
entry:
  %t$0 = call i64 @sprout_field(i64 %left, i64 0)
  %t$1 = call i64 @sprout_field(i64 %right, i64 0)
  %t$2 = call i64 @__tc_Eq_String_eq(i64 %t$0, i64 %t$1)
  %t$9 = trunc i64 %t$2 to i1
  br i1 %t$9, label %then_3, label %else_3
then_3:
  %t$5 = call i64 @sprout_field(i64 %left, i64 1)
  %t$6 = call i64 @sprout_field(i64 %right, i64 1)
  %t$7 = call i64 @__tc_Eq_Int_eq(i64 %t$5, i64 %t$6)
  br label %join_3
else_3:
  %t$8 = add i64 0, 0
  br label %join_3
join_3:
  %t$4 = phi i64 [%t$7, %then_3], [%t$8, %else_3]
  %t$16 = trunc i64 %t$4 to i1
  br i1 %t$16, label %then_10, label %else_10
then_10:
  %t$12 = call i64 @sprout_field(i64 %left, i64 2)
  %t$13 = call i64 @sprout_field(i64 %right, i64 2)
  %t$14 = call i64 @__tc_Eq_examples_records_demo_Timeouts_eq(i64 %t$12, i64 %t$13)
  br label %join_10
else_10:
  %t$15 = add i64 0, 0
  br label %join_10
join_10:
  %t$11 = phi i64 [%t$14, %then_10], [%t$15, %else_10]
  ret i64 %t$11
}

define i32 @main(i32 %argc, ptr %argv) {
entry:
  %argv_set = call i64 @sprout_set_argv(i32 %argc, ptr %argv)
  %cname_ptr_0 = getelementptr inbounds [8 x i8], ptr @.cname.0, i64 0, i64 0
  %cfkinds_ptr_0 = getelementptr inbounds [1 x i8], ptr @.cfkinds.0, i64 0, i64 0
  %creg_0 = call i64 @sprout_register_ctor(i64 0, ptr %cname_ptr_0, i64 0, ptr %cfkinds_ptr_0)
  %cname_ptr_1 = getelementptr inbounds [5 x i8], ptr @.cname.1, i64 0, i64 0
  %cfkinds_ptr_1 = getelementptr inbounds [2 x i8], ptr @.cfkinds.1, i64 0, i64 0
  %creg_1 = call i64 @sprout_register_ctor(i64 1, ptr %cname_ptr_1, i64 1, ptr %cfkinds_ptr_1)
  %cname_ptr_2 = getelementptr inbounds [12 x i8], ptr @.cname.2, i64 0, i64 0
  %cfkinds_ptr_2 = getelementptr inbounds [2 x i8], ptr @.cfkinds.2, i64 0, i64 0
  %creg_2 = call i64 @sprout_register_ctor(i64 2, ptr %cname_ptr_2, i64 1, ptr %cfkinds_ptr_2)
  %cname_ptr_3 = getelementptr inbounds [15 x i8], ptr @.cname.3, i64 0, i64 0
  %cfkinds_ptr_3 = getelementptr inbounds [2 x i8], ptr @.cfkinds.3, i64 0, i64 0
  %creg_3 = call i64 @sprout_register_ctor(i64 3, ptr %cname_ptr_3, i64 1, ptr %cfkinds_ptr_3)
  %cname_ptr_4 = getelementptr inbounds [15 x i8], ptr @.cname.4, i64 0, i64 0
  %cfkinds_ptr_4 = getelementptr inbounds [2 x i8], ptr @.cfkinds.4, i64 0, i64 0
  %creg_4 = call i64 @sprout_register_ctor(i64 4, ptr %cname_ptr_4, i64 1, ptr %cfkinds_ptr_4)
  %cname_ptr_5 = getelementptr inbounds [4 x i8], ptr @.cname.5, i64 0, i64 0
  %cfkinds_ptr_5 = getelementptr inbounds [1 x i8], ptr @.cfkinds.5, i64 0, i64 0
  %creg_5 = call i64 @sprout_register_ctor(i64 5, ptr %cname_ptr_5, i64 0, ptr %cfkinds_ptr_5)
  %cname_ptr_6 = getelementptr inbounds [5 x i8], ptr @.cname.6, i64 0, i64 0
  %cfkinds_ptr_6 = getelementptr inbounds [3 x i8], ptr @.cfkinds.6, i64 0, i64 0
  %creg_6 = call i64 @sprout_register_ctor(i64 6, ptr %cname_ptr_6, i64 2, ptr %cfkinds_ptr_6)
  %cname_ptr_7 = getelementptr inbounds [3 x i8], ptr @.cname.7, i64 0, i64 0
  %cfkinds_ptr_7 = getelementptr inbounds [2 x i8], ptr @.cfkinds.7, i64 0, i64 0
  %creg_7 = call i64 @sprout_register_ctor(i64 7, ptr %cname_ptr_7, i64 1, ptr %cfkinds_ptr_7)
  %cname_ptr_8 = getelementptr inbounds [4 x i8], ptr @.cname.8, i64 0, i64 0
  %cfkinds_ptr_8 = getelementptr inbounds [2 x i8], ptr @.cfkinds.8, i64 0, i64 0
  %creg_8 = call i64 @sprout_register_ctor(i64 8, ptr %cname_ptr_8, i64 1, ptr %cfkinds_ptr_8)
  %cname_ptr_9 = getelementptr inbounds [10 x i8], ptr @.cname.9, i64 0, i64 0
  %cfkinds_ptr_9 = getelementptr inbounds [1 x i8], ptr @.cfkinds.9, i64 0, i64 0
  %creg_9 = call i64 @sprout_register_ctor(i64 9, ptr %cname_ptr_9, i64 0, ptr %cfkinds_ptr_9)
  %cname_ptr_10 = getelementptr inbounds [4 x i8], ptr @.cname.10, i64 0, i64 0
  %cfkinds_ptr_10 = getelementptr inbounds [2 x i8], ptr @.cfkinds.10, i64 0, i64 0
  %creg_10 = call i64 @sprout_register_ctor(i64 10, ptr %cname_ptr_10, i64 1, ptr %cfkinds_ptr_10)
  %cname_ptr_11 = getelementptr inbounds [5 x i8], ptr @.cname.11, i64 0, i64 0
  %cfkinds_ptr_11 = getelementptr inbounds [2 x i8], ptr @.cfkinds.11, i64 0, i64 0
  %creg_11 = call i64 @sprout_register_ctor(i64 11, ptr %cname_ptr_11, i64 1, ptr %cfkinds_ptr_11)
  %cname_ptr_12 = getelementptr inbounds [4 x i8], ptr @.cname.12, i64 0, i64 0
  %cfkinds_ptr_12 = getelementptr inbounds [2 x i8], ptr @.cfkinds.12, i64 0, i64 0
  %creg_12 = call i64 @sprout_register_ctor(i64 12, ptr %cname_ptr_12, i64 1, ptr %cfkinds_ptr_12)
  %cname_ptr_13 = getelementptr inbounds [9 x i8], ptr @.cname.13, i64 0, i64 0
  %cfkinds_ptr_13 = getelementptr inbounds [4 x i8], ptr @.cfkinds.13, i64 0, i64 0
  %creg_13 = call i64 @sprout_register_ctor(i64 13, ptr %cname_ptr_13, i64 3, ptr %cfkinds_ptr_13)
  call i64 @__sprout_user_main()
  ret i32 0
}

