; Generated by sprout ir_lowering.sprout (M2 PR 2.3)
target triple = "unknown-unknown-unknown"
declare i64 @str_concat(i64, i64)
declare i1 @str_eq(ptr, ptr)
declare i64 @str_compare(i64, i64)
declare i64 @str_slice(i64, i64, i64)
declare i64 @int_to_string(i64)
declare i64 @char_to_string(i64)
declare i64 @sprout_gc_push_i64_root(ptr)
declare i64 @sprout_gc_pop_roots(i64)
declare i64 @sprout_gc_register_i64_root(ptr)
declare i64 @sprout_alloc_closure(i64, i64)
declare void @sprout_closure_arity_check(i64, i64)
declare i64 @sprout_alloc_tuple_blob(i64)
declare i64 @sprout_register_ctor(i64, ptr, i64, ptr)
declare i64 @sprout_tag(i64)
declare i64 @sprout_field(i64, i64)
declare void @sprout_abort_match() noreturn
declare i64 @panic(i64)
declare ptr @llvm.stacksave()
declare void @llvm.stackrestore(ptr)
declare i64 @sprout_alloc_obj(i64, i64)
declare { i64, i64 } @vector_get_unboxed(i64, i64)
declare { i64, i64 } @map_get_unboxed(i64, i64)
declare { i64, i64 } @map_nth_key_unboxed(i64, i64)
declare { i64, i64 } @map_nth_value_unboxed(i64, i64)
declare { i64, i64 } @bytes_get_unboxed(i64, i64)
declare { i64, i64 } @str_char_at_unboxed(i64, i64)
declare { i64, i64 } @argv_get_unboxed(i64)
declare { i64, i64 } @env_get_unboxed(i64)
declare i64 @print_str(ptr)
declare i64 @print_value(i64)
declare i64 @eprint_str(ptr)
declare i64 @argv_get(i64)
declare i64 @sprout_set_argv(i32, ptr)
declare i64 @analysis_check_source(ptr)
declare i64 @analysis_declared_names_in_source(ptr)
declare i64 @analysis_exported_names_in_source(ptr)
declare i64 @analysis_symbol_inventory_in_source(ptr)
declare i64 @analysis_diagnostics_in_source(ptr)
declare i64 @analysis_symbol_locations_in_source(ptr)
declare i64 @analysis_type_of_in_source(ptr, ptr)
declare i64 @analysis_eval_expr_in_source(ptr, ptr)
declare i64 @analysis_instances_in_source(ptr, ptr)
declare i64 @analysis_complete_in_state(ptr, ptr, ptr)

declare i64 @double_to_string(i64)
declare i64 @char_to_str(i64)
declare i64 @char_from_codepoint(i64)
declare i64 @to_double(i64)
declare i64 @string_concat_many(i64)
declare i64 @str_len(i64)
declare i64 @str_char_at(i64, i64)
declare i64 @str_find(i64, i64)
declare i64 @str_starts_with(i64, i64)
declare i64 @vector_empty()
declare i64 @vector_length(i64)
declare i64 @vector_get(i64, i64)
declare i64 @vector_set(i64, i64, i64)
declare i64 @vector_append(i64, i64)
declare i64 @vector_concat(i64, i64)
declare i64 @vector_from_list(i64)
declare i64 @map_empty()
declare i64 @map_get(i64, i64)
declare i64 @map_set(i64, i64, i64)
declare i64 @map_remove(i64, i64)
declare i64 @map_size(i64)
declare i64 @map_nth_key(i64, i64)
declare i64 @map_nth_value(i64, i64)
declare i64 @native_set_empty()
declare i64 @native_set_insert(i64, i64)
declare i64 @native_set_member(i64, i64)
declare i64 @native_set_to_list(i64)
declare i64 @native_set_size(i64)
declare i64 @ref_new(i64)
declare i64 @ref_read(i64)
declare i64 @ref_write(i64, i64)
@.str.0 = private unnamed_addr constant { i64, [7 x i8] } { i64 98314, [7 x i8] c"count=\00" }
@.str.1 = private unnamed_addr constant { i64, [2 x i8] } { i64 16394, [2 x i8] c".\00" }
@.str.2 = private unnamed_addr constant { i64, [6 x i8] } { i64 81930, [6 x i8] c"buf=\22\00" }
@.str.3 = private unnamed_addr constant { i64, [2 x i8] } { i64 16394, [2 x i8] c"\22\00" }
@.str.4 = private unnamed_addr constant { i64, [1 x i8] } { i64 10, [1 x i8] c"\00" }
@.cname.0 = private unnamed_addr constant [8 x i8] c"Nothing\00"
@.cfkinds.0 = private unnamed_addr constant [1 x i8] c"\00"
@.cname.1 = private unnamed_addr constant [5 x i8] c"Just\00"
@.cfkinds.1 = private unnamed_addr constant [2 x i8] c"_\00"
@.cname.2 = private unnamed_addr constant [12 x i8] c"TemplateLit\00"
@.cfkinds.2 = private unnamed_addr constant [2 x i8] c"s\00"
@.cname.3 = private unnamed_addr constant [15 x i8] c"TemplateInterp\00"
@.cfkinds.3 = private unnamed_addr constant [2 x i8] c"s\00"
@.cname.4 = private unnamed_addr constant [15 x i8] c"StringTemplate\00"
@.cfkinds.4 = private unnamed_addr constant [2 x i8] c"p\00"
@.cname.5 = private unnamed_addr constant [4 x i8] c"Nil\00"
@.cfkinds.5 = private unnamed_addr constant [1 x i8] c"\00"
@.cname.6 = private unnamed_addr constant [5 x i8] c"Cons\00"
@.cfkinds.6 = private unnamed_addr constant [3 x i8] c"_p\00"
@.cname.7 = private unnamed_addr constant [3 x i8] c"Ok\00"
@.cfkinds.7 = private unnamed_addr constant [2 x i8] c"_\00"
@.cname.8 = private unnamed_addr constant [4 x i8] c"Err\00"
@.cfkinds.8 = private unnamed_addr constant [2 x i8] c"_\00"
@.cname.9 = private unnamed_addr constant [10 x i8] c"DivByZero\00"
@.cfkinds.9 = private unnamed_addr constant [1 x i8] c"\00"
@.cname.10 = private unnamed_addr constant [4 x i8] c"Vec\00"
@.cfkinds.10 = private unnamed_addr constant [2 x i8] c"p\00"
@.cname.11 = private unnamed_addr constant [5 x i8] c"Dict\00"
@.cfkinds.11 = private unnamed_addr constant [2 x i8] c"p\00"
@.cname.12 = private unnamed_addr constant [4 x i8] c"Set\00"
@.cfkinds.12 = private unnamed_addr constant [2 x i8] c"p\00"
@.cname.13 = private unnamed_addr constant [9 x i8] c"IntRange\00"
@.cfkinds.13 = private unnamed_addr constant [4 x i8] c"iii\00"
@.cname.15 = private unnamed_addr constant [35 x i8] c"examples.existential_widget.Widget\00"
@.cfkinds.15 = private unnamed_addr constant [2 x i8] c"p\00"

define i64 @list_each_go(i64 %f$in, i64 %xs$in) {
entry:
  %t$12 = alloca i64
  store i64 %f$in, ptr %t$12
  %t$13 = alloca i64
  store i64 %xs$in, ptr %t$13
  %t$14 = call ptr @llvm.stacksave()
  br label %tco_loop
tco_loop:
  %f = load i64, ptr %t$12
  %xs = load i64, ptr %t$13
  %t$0 = call i64 @sprout_tag(i64 %xs)
  br label %arm_0_1
arm_0_1:
  %t$3 = add i64 0, 5
  %t$4 = icmp eq i64 %t$0, %t$3
  br i1 %t$4, label %body_0_1, label %arm_1_1
body_0_1:
  %t$5 = add i64 0, 0
  br label %join_1
arm_1_1:
  %t$6 = add i64 0, 6
  %t$7 = icmp eq i64 %t$0, %t$6
  br i1 %t$7, label %body_1_1, label %arm_2_1
body_1_1:
  %t$8 = call i64 @sprout_field(i64 %xs, i64 0)
  %t$9 = call i64 @sprout_field(i64 %xs, i64 1)
  %t$15 = alloca i64
  store i64 %f, ptr %t$15
  %t$16 = call i64 @sprout_gc_push_i64_root(ptr %t$15)
  %t$17 = alloca i64
  store i64 %t$9, ptr %t$17
  %t$18 = call i64 @sprout_gc_push_i64_root(ptr %t$17)
  call void @sprout_closure_arity_check(i64 %f, i64 1)
  %t$10$env_ptr = inttoptr i64 %f to ptr
  %t$10$code = load ptr, ptr %t$10$env_ptr
  %t$10 = call i64 (i64, i64) %t$10$code(i64 %f, i64 %t$8)
  %t$19 = call i64 @sprout_gc_pop_roots(i64 2)
  store i64 %f, ptr %t$12
  store i64 %t$9, ptr %t$13
  call void @llvm.stackrestore(ptr %t$14)
  br label %tco_loop
arm_2_1:
  call void @sprout_abort_match()
  unreachable
join_1:
  %t$2 = phi i64 [%t$5, %body_0_1]
  ret i64 %t$2
}

define i64 @list_each(i64 %f, i64 %xs) {
entry:
  %t$1 = alloca i64
  store i64 %xs, ptr %t$1
  %t$2 = call i64 @sprout_gc_push_i64_root(ptr %t$1)
  %t$3 = alloca i64
  store i64 %f, ptr %t$3
  %t$4 = call i64 @sprout_gc_push_i64_root(ptr %t$3)
  %t$0 = call i64 @list_each_go(i64 %f, i64 %xs)
  %t$5 = call i64 @sprout_gc_pop_roots(i64 2)
  ret i64 %t$0
}

define i64 @examples.existential_widget.count_up(i64 %n) {
entry:
  %t$0 = add i64 0, 1
  %t$1 = add i64 %n, %t$0
  ret i64 %t$1
}

define i64 @examples.existential_widget.show_count(i64 %n) {
entry:
  %t$0 = getelementptr inbounds { i64, [7 x i8] }, ptr @.str.0, i64 0, i32 1, i64 0
  %t$1 = ptrtoint ptr %t$0 to i64
  %t$8 = alloca i64
  store i64 %t$1, ptr %t$8
  %t$9 = call i64 @sprout_gc_push_i64_root(ptr %t$8)
  %t$2 = call i64 @int_to_string(i64 %n)
  %t$3 = call i64 @__tc_ToString_String_to_string(i64 %t$2)
  %t$10 = alloca i64
  store i64 %t$3, ptr %t$10
  %t$11 = call i64 @sprout_gc_push_i64_root(ptr %t$10)
  %t$4 = call i64 @sprout_alloc_obj(i64 5, i64 0)
  %t$12 = alloca i64
  store i64 %t$4, ptr %t$12
  %t$13 = call i64 @sprout_gc_push_i64_root(ptr %t$12)
  %t$5 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$5$ptr = inttoptr i64 %t$5 to ptr
  %t$5$f0 = getelementptr i64, ptr %t$5$ptr, i64 0
  store i64 %t$3, ptr %t$5$f0
  %t$5$f1 = getelementptr i64, ptr %t$5$ptr, i64 1
  store i64 %t$4, ptr %t$5$f1
  %t$14 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$15 = alloca i64
  store i64 %t$5, ptr %t$15
  %t$16 = call i64 @sprout_gc_push_i64_root(ptr %t$15)
  %t$6 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$6$ptr = inttoptr i64 %t$6 to ptr
  %t$6$f0 = getelementptr i64, ptr %t$6$ptr, i64 0
  store i64 %t$1, ptr %t$6$f0
  %t$6$f1 = getelementptr i64, ptr %t$6$ptr, i64 1
  store i64 %t$5, ptr %t$6$f1
  %t$17 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$18 = alloca i64
  store i64 %t$6, ptr %t$18
  %t$19 = call i64 @sprout_gc_push_i64_root(ptr %t$18)
  %t$7 = call i64 @string_concat_many(i64 %t$6)
  %t$20 = call i64 @sprout_gc_pop_roots(i64 1)
  ret i64 %t$7
}

define i64 @examples.existential_widget.add_dot(i64 %buf) {
entry:
  %t$0 = getelementptr inbounds { i64, [2 x i8] }, ptr @.str.1, i64 0, i32 1, i64 0
  %t$1 = ptrtoint ptr %t$0 to i64
  %t$3 = alloca i64
  store i64 %buf, ptr %t$3
  %t$4 = call i64 @sprout_gc_push_i64_root(ptr %t$3)
  %t$5 = alloca i64
  store i64 %t$1, ptr %t$5
  %t$6 = call i64 @sprout_gc_push_i64_root(ptr %t$5)
  %t$2 = call i64 @__tc_Semigroup_String_append(i64 %buf, i64 %t$1)
  %t$7 = call i64 @sprout_gc_pop_roots(i64 2)
  ret i64 %t$2
}

define i64 @examples.existential_widget.show_buf(i64 %buf) {
entry:
  %t$0 = getelementptr inbounds { i64, [6 x i8] }, ptr @.str.2, i64 0, i32 1, i64 0
  %t$1 = ptrtoint ptr %t$0 to i64
  %t$2 = call i64 @__tc_ToString_String_to_string(i64 %buf)
  %t$3 = getelementptr inbounds { i64, [2 x i8] }, ptr @.str.3, i64 0, i32 1, i64 0
  %t$4 = ptrtoint ptr %t$3 to i64
  %t$10 = alloca i64
  store i64 %t$1, ptr %t$10
  %t$11 = call i64 @sprout_gc_push_i64_root(ptr %t$10)
  %t$12 = alloca i64
  store i64 %t$2, ptr %t$12
  %t$13 = call i64 @sprout_gc_push_i64_root(ptr %t$12)
  %t$14 = alloca i64
  store i64 %t$4, ptr %t$14
  %t$15 = call i64 @sprout_gc_push_i64_root(ptr %t$14)
  %t$5 = call i64 @sprout_alloc_obj(i64 5, i64 0)
  %t$16 = alloca i64
  store i64 %t$5, ptr %t$16
  %t$17 = call i64 @sprout_gc_push_i64_root(ptr %t$16)
  %t$6 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$6$ptr = inttoptr i64 %t$6 to ptr
  %t$6$f0 = getelementptr i64, ptr %t$6$ptr, i64 0
  store i64 %t$4, ptr %t$6$f0
  %t$6$f1 = getelementptr i64, ptr %t$6$ptr, i64 1
  store i64 %t$5, ptr %t$6$f1
  %t$18 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$19 = alloca i64
  store i64 %t$6, ptr %t$19
  %t$20 = call i64 @sprout_gc_push_i64_root(ptr %t$19)
  %t$7 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$7$ptr = inttoptr i64 %t$7 to ptr
  %t$7$f0 = getelementptr i64, ptr %t$7$ptr, i64 0
  store i64 %t$2, ptr %t$7$f0
  %t$7$f1 = getelementptr i64, ptr %t$7$ptr, i64 1
  store i64 %t$6, ptr %t$7$f1
  %t$21 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$22 = alloca i64
  store i64 %t$7, ptr %t$22
  %t$23 = call i64 @sprout_gc_push_i64_root(ptr %t$22)
  %t$8 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$8$ptr = inttoptr i64 %t$8 to ptr
  %t$8$f0 = getelementptr i64, ptr %t$8$ptr, i64 0
  store i64 %t$1, ptr %t$8$f0
  %t$8$f1 = getelementptr i64, ptr %t$8$ptr, i64 1
  store i64 %t$7, ptr %t$8$f1
  %t$24 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$25 = alloca i64
  store i64 %t$8, ptr %t$25
  %t$26 = call i64 @sprout_gc_push_i64_root(ptr %t$25)
  %t$9 = call i64 @string_concat_many(i64 %t$8)
  %t$27 = call i64 @sprout_gc_pop_roots(i64 1)
  ret i64 %t$9
}

define i64 @examples.existential_widget.run(i64 %w, i64 %n) {
entry:
  %t$0 = call i64 @sprout_tag(i64 %w)
  br label %arm_0_1
arm_0_1:
  %t$3 = add i64 0, 15
  %t$4 = icmp eq i64 %t$0, %t$3
  br i1 %t$4, label %body_0_1, label %arm_1_1
body_0_1:
  %t$5 = call i64 @sprout_field(i64 %w, i64 0)
  %t$6 = call i64 @sprout_field(i64 %t$5, i64 2)
  %t$7 = call i64 @sprout_field(i64 %t$5, i64 1)
  %t$8 = call i64 @sprout_field(i64 %t$5, i64 0)
  %t$11 = alloca i64
  store i64 %t$6, ptr %t$11
  %t$12 = call i64 @sprout_gc_push_i64_root(ptr %t$11)
  %t$13 = alloca i64
  store i64 %t$7, ptr %t$13
  %t$14 = call i64 @sprout_gc_push_i64_root(ptr %t$13)
  %t$15 = alloca i64
  store i64 %t$8, ptr %t$15
  %t$16 = call i64 @sprout_gc_push_i64_root(ptr %t$15)
  %t$9 = call i64 @examples.existential_widget.step_n(i64 %t$7, i64 %t$8, i64 %n)
  %t$17 = call i64 @sprout_gc_pop_roots(i64 2)
  call void @sprout_closure_arity_check(i64 %t$6, i64 1)
  %t$10$env_ptr = inttoptr i64 %t$6 to ptr
  %t$10$code = load ptr, ptr %t$10$env_ptr
  %t$10 = call i64 (i64, i64) %t$10$code(i64 %t$6, i64 %t$9)
  %t$18 = call i64 @sprout_gc_pop_roots(i64 1)
  br label %join_1
arm_1_1:
  call void @sprout_abort_match()
  unreachable
join_1:
  %t$2 = phi i64 [%t$10, %body_0_1]
  ret i64 %t$2
}

define i64 @examples.existential_widget.step_n(i64 %step$in, i64 %st$in, i64 %n$in) {
entry:
  %t$10 = alloca i64
  store i64 %step$in, ptr %t$10
  %t$11 = alloca i64
  store i64 %st$in, ptr %t$11
  %t$12 = alloca i64
  store i64 %n$in, ptr %t$12
  %t$13 = call ptr @llvm.stacksave()
  br label %tco_loop
tco_loop:
  %step = load i64, ptr %t$10
  %st = load i64, ptr %t$11
  %n = load i64, ptr %t$12
  %t$0 = add i64 0, 0
  %t$1 = icmp sle i64 %n, %t$0
  %t$2 = zext i1 %t$1 to i64
  %t$9 = trunc i64 %t$2 to i1
  br i1 %t$9, label %then_3, label %else_3
then_3:
  br label %join_3
else_3:
  %t$14 = alloca i64
  store i64 %step, ptr %t$14
  %t$15 = call i64 @sprout_gc_push_i64_root(ptr %t$14)
  call void @sprout_closure_arity_check(i64 %step, i64 1)
  %t$5$env_ptr = inttoptr i64 %step to ptr
  %t$5$code = load ptr, ptr %t$5$env_ptr
  %t$5 = call i64 (i64, i64) %t$5$code(i64 %step, i64 %st)
  %t$6 = add i64 0, 1
  %t$7 = sub i64 %n, %t$6
  %t$16 = call i64 @sprout_gc_pop_roots(i64 1)
  store i64 %step, ptr %t$10
  store i64 %t$5, ptr %t$11
  store i64 %t$7, ptr %t$12
  call void @llvm.stackrestore(ptr %t$13)
  br label %tco_loop
join_3:
  %t$4 = phi i64 [%st, %then_3]
  ret i64 %t$4
}

define i64 @__sprout_ir_eta_examples.existential_widget.count_up_0(i64 %env$, i64 %a0) {
entry:
  %ret = call i64 @examples.existential_widget.count_up(i64 %a0)
  ret i64 %ret
}

define i64 @__sprout_ir_eta_examples.existential_widget.show_count_1(i64 %env$, i64 %a0) {
entry:
  %t$0 = alloca i64
  store i64 %a0, ptr %t$0
  %t$1 = call i64 @sprout_gc_push_i64_root(ptr %t$0)
  %ret = call i64 @examples.existential_widget.show_count(i64 %a0)
  %t$2 = call i64 @sprout_gc_pop_roots(i64 1)
  ret i64 %ret
}

define i64 @__sprout_ir_eta_examples.existential_widget.add_dot_2(i64 %env$, i64 %a0) {
entry:
  %t$0 = alloca i64
  store i64 %a0, ptr %t$0
  %t$1 = call i64 @sprout_gc_push_i64_root(ptr %t$0)
  %ret = call i64 @examples.existential_widget.add_dot(i64 %a0)
  %t$2 = call i64 @sprout_gc_pop_roots(i64 1)
  ret i64 %ret
}

define i64 @__sprout_ir_eta_examples.existential_widget.show_buf_3(i64 %env$, i64 %a0) {
entry:
  %t$0 = alloca i64
  store i64 %a0, ptr %t$0
  %t$1 = call i64 @sprout_gc_push_i64_root(ptr %t$0)
  %ret = call i64 @examples.existential_widget.show_buf(i64 %a0)
  %t$2 = call i64 @sprout_gc_pop_roots(i64 1)
  ret i64 %ret
}

define i64 @examples.existential_widget.widgets() {
entry:
  %t$0 = add i64 0, 0
  %t$1 = call i64 @sprout_alloc_closure(i64 8, i64 1)
  %t$1$raw = inttoptr i64 %t$1 to ptr
  store ptr @__sprout_ir_eta_examples.existential_widget.count_up_0, ptr %t$1$raw
  %t$14 = alloca i64
  store i64 %t$1, ptr %t$14
  %t$15 = call i64 @sprout_gc_push_i64_root(ptr %t$14)
  %t$2 = call i64 @sprout_alloc_closure(i64 8, i64 1)
  %t$2$raw = inttoptr i64 %t$2 to ptr
  store ptr @__sprout_ir_eta_examples.existential_widget.show_count_1, ptr %t$2$raw
  %t$16 = alloca i64
  store i64 %t$2, ptr %t$16
  %t$17 = call i64 @sprout_gc_push_i64_root(ptr %t$16)
  %t$3 = call i64 @sprout_alloc_obj(i64 14, i64 3)
  %t$3$ptr = inttoptr i64 %t$3 to ptr
  %t$3$f0 = getelementptr i64, ptr %t$3$ptr, i64 0
  store i64 %t$0, ptr %t$3$f0
  %t$3$f1 = getelementptr i64, ptr %t$3$ptr, i64 1
  store i64 %t$1, ptr %t$3$f1
  %t$3$f2 = getelementptr i64, ptr %t$3$ptr, i64 2
  store i64 %t$2, ptr %t$3$f2
  %t$18 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$19 = alloca i64
  store i64 %t$3, ptr %t$19
  %t$20 = call i64 @sprout_gc_push_i64_root(ptr %t$19)
  %t$4 = call i64 @sprout_alloc_obj(i64 15, i64 1)
  %t$4$ptr = inttoptr i64 %t$4 to ptr
  %t$4$f0 = getelementptr i64, ptr %t$4$ptr, i64 0
  store i64 %t$3, ptr %t$4$f0
  %t$21 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$5 = getelementptr inbounds { i64, [1 x i8] }, ptr @.str.4, i64 0, i32 1, i64 0
  %t$6 = ptrtoint ptr %t$5 to i64
  %t$22 = alloca i64
  store i64 %t$4, ptr %t$22
  %t$23 = call i64 @sprout_gc_push_i64_root(ptr %t$22)
  %t$24 = alloca i64
  store i64 %t$6, ptr %t$24
  %t$25 = call i64 @sprout_gc_push_i64_root(ptr %t$24)
  %t$7 = call i64 @sprout_alloc_closure(i64 8, i64 1)
  %t$7$raw = inttoptr i64 %t$7 to ptr
  store ptr @__sprout_ir_eta_examples.existential_widget.add_dot_2, ptr %t$7$raw
  %t$26 = alloca i64
  store i64 %t$7, ptr %t$26
  %t$27 = call i64 @sprout_gc_push_i64_root(ptr %t$26)
  %t$8 = call i64 @sprout_alloc_closure(i64 8, i64 1)
  %t$8$raw = inttoptr i64 %t$8 to ptr
  store ptr @__sprout_ir_eta_examples.existential_widget.show_buf_3, ptr %t$8$raw
  %t$28 = alloca i64
  store i64 %t$8, ptr %t$28
  %t$29 = call i64 @sprout_gc_push_i64_root(ptr %t$28)
  %t$9 = call i64 @sprout_alloc_obj(i64 14, i64 3)
  %t$9$ptr = inttoptr i64 %t$9 to ptr
  %t$9$f0 = getelementptr i64, ptr %t$9$ptr, i64 0
  store i64 %t$6, ptr %t$9$f0
  %t$9$f1 = getelementptr i64, ptr %t$9$ptr, i64 1
  store i64 %t$7, ptr %t$9$f1
  %t$9$f2 = getelementptr i64, ptr %t$9$ptr, i64 2
  store i64 %t$8, ptr %t$9$f2
  %t$30 = call i64 @sprout_gc_pop_roots(i64 3)
  %t$31 = alloca i64
  store i64 %t$9, ptr %t$31
  %t$32 = call i64 @sprout_gc_push_i64_root(ptr %t$31)
  %t$10 = call i64 @sprout_alloc_obj(i64 15, i64 1)
  %t$10$ptr = inttoptr i64 %t$10 to ptr
  %t$10$f0 = getelementptr i64, ptr %t$10$ptr, i64 0
  store i64 %t$9, ptr %t$10$f0
  %t$33 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$34 = alloca i64
  store i64 %t$10, ptr %t$34
  %t$35 = call i64 @sprout_gc_push_i64_root(ptr %t$34)
  %t$11 = call i64 @sprout_alloc_obj(i64 5, i64 0)
  %t$36 = alloca i64
  store i64 %t$11, ptr %t$36
  %t$37 = call i64 @sprout_gc_push_i64_root(ptr %t$36)
  %t$12 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$12$ptr = inttoptr i64 %t$12 to ptr
  %t$12$f0 = getelementptr i64, ptr %t$12$ptr, i64 0
  store i64 %t$10, ptr %t$12$f0
  %t$12$f1 = getelementptr i64, ptr %t$12$ptr, i64 1
  store i64 %t$11, ptr %t$12$f1
  %t$38 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$39 = alloca i64
  store i64 %t$12, ptr %t$39
  %t$40 = call i64 @sprout_gc_push_i64_root(ptr %t$39)
  %t$13 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$13$ptr = inttoptr i64 %t$13 to ptr
  %t$13$f0 = getelementptr i64, ptr %t$13$ptr, i64 0
  store i64 %t$4, ptr %t$13$f0
  %t$13$f1 = getelementptr i64, ptr %t$13$ptr, i64 1
  store i64 %t$12, ptr %t$13$f1
  %t$41 = call i64 @sprout_gc_pop_roots(i64 2)
  ret i64 %t$13
}

define i64 @__sprout_ir_lambda_4(i64 %env$, i64 %w) {
entry:
  %t$0 = add i64 0, 3
  %t$3 = alloca i64
  store i64 %w, ptr %t$3
  %t$4 = call i64 @sprout_gc_push_i64_root(ptr %t$3)
  %t$1 = call i64 @examples.existential_widget.run(i64 %w, i64 %t$0)
  %t$5 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$2$ptr = inttoptr i64 %t$1 to ptr
  %t$2 = call i64 @print_str(ptr %t$2$ptr)
  ret i64 %t$2
}

define i64 @__sprout_user_main() {
entry:
  %t$0 = call i64 @sprout_alloc_closure(i64 8, i64 1)
  %t$0$raw = inttoptr i64 %t$0 to ptr
  store ptr @__sprout_ir_lambda_4, ptr %t$0$raw
  %t$3 = alloca i64
  store i64 %t$0, ptr %t$3
  %t$4 = call i64 @sprout_gc_push_i64_root(ptr %t$3)
  %t$1 = call i64 @examples.existential_widget.widgets()
  %t$5 = alloca i64
  store i64 %t$1, ptr %t$5
  %t$6 = call i64 @sprout_gc_push_i64_root(ptr %t$5)
  %t$2 = call i64 @list_each(i64 %t$0, i64 %t$1)
  %t$7 = call i64 @sprout_gc_pop_roots(i64 2)
  ret i64 %t$2
}

define i64 @__tc_Semigroup_String_append(i64 %left, i64 %right) {
entry:
  %t$0 = call i64 @str_concat(i64 %left, i64 %right)
  ret i64 %t$0
}

define i64 @__tc_ToString_String_to_string(i64 %value) {
entry:
  ret i64 %value
}

define i32 @main(i32 %argc, ptr %argv) {
entry:
  %argv_set = call i64 @sprout_set_argv(i32 %argc, ptr %argv)
  %cname_ptr_0 = getelementptr inbounds [8 x i8], ptr @.cname.0, i64 0, i64 0
  %cfkinds_ptr_0 = getelementptr inbounds [1 x i8], ptr @.cfkinds.0, i64 0, i64 0
  %creg_0 = call i64 @sprout_register_ctor(i64 0, ptr %cname_ptr_0, i64 0, ptr %cfkinds_ptr_0)
  %cname_ptr_1 = getelementptr inbounds [5 x i8], ptr @.cname.1, i64 0, i64 0
  %cfkinds_ptr_1 = getelementptr inbounds [2 x i8], ptr @.cfkinds.1, i64 0, i64 0
  %creg_1 = call i64 @sprout_register_ctor(i64 1, ptr %cname_ptr_1, i64 1, ptr %cfkinds_ptr_1)
  %cname_ptr_2 = getelementptr inbounds [12 x i8], ptr @.cname.2, i64 0, i64 0
  %cfkinds_ptr_2 = getelementptr inbounds [2 x i8], ptr @.cfkinds.2, i64 0, i64 0
  %creg_2 = call i64 @sprout_register_ctor(i64 2, ptr %cname_ptr_2, i64 1, ptr %cfkinds_ptr_2)
  %cname_ptr_3 = getelementptr inbounds [15 x i8], ptr @.cname.3, i64 0, i64 0
  %cfkinds_ptr_3 = getelementptr inbounds [2 x i8], ptr @.cfkinds.3, i64 0, i64 0
  %creg_3 = call i64 @sprout_register_ctor(i64 3, ptr %cname_ptr_3, i64 1, ptr %cfkinds_ptr_3)
  %cname_ptr_4 = getelementptr inbounds [15 x i8], ptr @.cname.4, i64 0, i64 0
  %cfkinds_ptr_4 = getelementptr inbounds [2 x i8], ptr @.cfkinds.4, i64 0, i64 0
  %creg_4 = call i64 @sprout_register_ctor(i64 4, ptr %cname_ptr_4, i64 1, ptr %cfkinds_ptr_4)
  %cname_ptr_5 = getelementptr inbounds [4 x i8], ptr @.cname.5, i64 0, i64 0
  %cfkinds_ptr_5 = getelementptr inbounds [1 x i8], ptr @.cfkinds.5, i64 0, i64 0
  %creg_5 = call i64 @sprout_register_ctor(i64 5, ptr %cname_ptr_5, i64 0, ptr %cfkinds_ptr_5)
  %cname_ptr_6 = getelementptr inbounds [5 x i8], ptr @.cname.6, i64 0, i64 0
  %cfkinds_ptr_6 = getelementptr inbounds [3 x i8], ptr @.cfkinds.6, i64 0, i64 0
  %creg_6 = call i64 @sprout_register_ctor(i64 6, ptr %cname_ptr_6, i64 2, ptr %cfkinds_ptr_6)
  %cname_ptr_7 = getelementptr inbounds [3 x i8], ptr @.cname.7, i64 0, i64 0
  %cfkinds_ptr_7 = getelementptr inbounds [2 x i8], ptr @.cfkinds.7, i64 0, i64 0
  %creg_7 = call i64 @sprout_register_ctor(i64 7, ptr %cname_ptr_7, i64 1, ptr %cfkinds_ptr_7)
  %cname_ptr_8 = getelementptr inbounds [4 x i8], ptr @.cname.8, i64 0, i64 0
  %cfkinds_ptr_8 = getelementptr inbounds [2 x i8], ptr @.cfkinds.8, i64 0, i64 0
  %creg_8 = call i64 @sprout_register_ctor(i64 8, ptr %cname_ptr_8, i64 1, ptr %cfkinds_ptr_8)
  %cname_ptr_9 = getelementptr inbounds [10 x i8], ptr @.cname.9, i64 0, i64 0
  %cfkinds_ptr_9 = getelementptr inbounds [1 x i8], ptr @.cfkinds.9, i64 0, i64 0
  %creg_9 = call i64 @sprout_register_ctor(i64 9, ptr %cname_ptr_9, i64 0, ptr %cfkinds_ptr_9)
  %cname_ptr_10 = getelementptr inbounds [4 x i8], ptr @.cname.10, i64 0, i64 0
  %cfkinds_ptr_10 = getelementptr inbounds [2 x i8], ptr @.cfkinds.10, i64 0, i64 0
  %creg_10 = call i64 @sprout_register_ctor(i64 10, ptr %cname_ptr_10, i64 1, ptr %cfkinds_ptr_10)
  %cname_ptr_11 = getelementptr inbounds [5 x i8], ptr @.cname.11, i64 0, i64 0
  %cfkinds_ptr_11 = getelementptr inbounds [2 x i8], ptr @.cfkinds.11, i64 0, i64 0
  %creg_11 = call i64 @sprout_register_ctor(i64 11, ptr %cname_ptr_11, i64 1, ptr %cfkinds_ptr_11)
  %cname_ptr_12 = getelementptr inbounds [4 x i8], ptr @.cname.12, i64 0, i64 0
  %cfkinds_ptr_12 = getelementptr inbounds [2 x i8], ptr @.cfkinds.12, i64 0, i64 0
  %creg_12 = call i64 @sprout_register_ctor(i64 12, ptr %cname_ptr_12, i64 1, ptr %cfkinds_ptr_12)
  %cname_ptr_13 = getelementptr inbounds [9 x i8], ptr @.cname.13, i64 0, i64 0
  %cfkinds_ptr_13 = getelementptr inbounds [4 x i8], ptr @.cfkinds.13, i64 0, i64 0
  %creg_13 = call i64 @sprout_register_ctor(i64 13, ptr %cname_ptr_13, i64 3, ptr %cfkinds_ptr_13)
  %cname_ptr_15 = getelementptr inbounds [35 x i8], ptr @.cname.15, i64 0, i64 0
  %cfkinds_ptr_15 = getelementptr inbounds [2 x i8], ptr @.cfkinds.15, i64 0, i64 0
  %creg_15 = call i64 @sprout_register_ctor(i64 15, ptr %cname_ptr_15, i64 1, ptr %cfkinds_ptr_15)
  call i64 @__sprout_user_main()
  ret i32 0
}

