; Generated by sprout ir_lowering.sprout (M2 PR 2.3)
target triple = "unknown-unknown-unknown"
declare i64 @str_concat(i64, i64)
declare i1 @str_eq(ptr, ptr)
declare i64 @str_compare(i64, i64)
declare i64 @str_slice(i64, i64, i64)
declare i64 @int_to_string(i64)
declare i64 @char_to_string(i64)
declare i64 @sprout_gc_push_i64_root(ptr)
declare i64 @sprout_gc_pop_roots(i64)
declare i64 @sprout_gc_register_i64_root(ptr)
declare i64 @sprout_alloc_closure(i64, i64)
declare void @sprout_closure_arity_check(i64, i64)
declare i64 @sprout_alloc_tuple_blob(i64)
declare i64 @sprout_register_ctor(i64, ptr, i64, ptr)
declare i64 @sprout_tag(i64)
declare i64 @sprout_field(i64, i64)
declare void @sprout_abort_match() noreturn
declare i64 @panic(i64)
declare ptr @llvm.stacksave()
declare void @llvm.stackrestore(ptr)
declare i64 @sprout_alloc_obj(i64, i64)
declare { i64, i64 } @vector_get_unboxed(i64, i64)
declare { i64, i64 } @map_get_unboxed(i64, i64)
declare { i64, i64 } @map_nth_key_unboxed(i64, i64)
declare { i64, i64 } @map_nth_value_unboxed(i64, i64)
declare { i64, i64 } @bytes_get_unboxed(i64, i64)
declare { i64, i64 } @str_char_at_unboxed(i64, i64)
declare { i64, i64 } @argv_get_unboxed(i64)
declare { i64, i64 } @env_get_unboxed(i64)
declare i64 @print_str(ptr)
declare i64 @print_value(i64)
declare i64 @eprint_str(ptr)
declare i64 @argv_get(i64)
declare i64 @sprout_set_argv(i32, ptr)
declare i64 @analysis_check_source(ptr)
declare i64 @analysis_declared_names_in_source(ptr)
declare i64 @analysis_exported_names_in_source(ptr)
declare i64 @analysis_symbol_inventory_in_source(ptr)
declare i64 @analysis_diagnostics_in_source(ptr)
declare i64 @analysis_symbol_locations_in_source(ptr)
declare i64 @analysis_type_of_in_source(ptr, ptr)
declare i64 @analysis_eval_expr_in_source(ptr, ptr)
declare i64 @analysis_instances_in_source(ptr, ptr)
declare i64 @analysis_complete_in_state(ptr, ptr, ptr)

declare i64 @double_to_string(i64)
declare i64 @char_to_str(i64)
declare i64 @char_from_codepoint(i64)
declare i64 @to_double(i64)
declare i64 @string_concat_many(i64)
declare i64 @str_len(i64)
declare i64 @str_char_at(i64, i64)
declare i64 @str_find(i64, i64)
declare i64 @str_starts_with(i64, i64)
declare i64 @vector_empty()
declare i64 @vector_length(i64)
declare i64 @vector_get(i64, i64)
declare i64 @vector_set(i64, i64, i64)
declare i64 @vector_append(i64, i64)
declare i64 @vector_concat(i64, i64)
declare i64 @vector_from_list(i64)
declare i64 @map_empty()
declare i64 @map_get(i64, i64)
declare i64 @map_set(i64, i64, i64)
declare i64 @map_remove(i64, i64)
declare i64 @map_size(i64)
declare i64 @map_nth_key(i64, i64)
declare i64 @map_nth_value(i64, i64)
declare i64 @native_set_empty()
declare i64 @native_set_insert(i64, i64)
declare i64 @native_set_member(i64, i64)
declare i64 @native_set_to_list(i64)
declare i64 @native_set_size(i64)
declare i64 @ref_new(i64)
declare i64 @ref_read(i64)
declare i64 @ref_write(i64, i64)
declare i64 @bytes_empty()
declare i64 @bytes_singleton(i64)
declare i64 @bytes_length(i64)
declare i64 @bytes_get(i64, i64)
declare i64 @bytes_slice(i64, i64, i64)
declare i64 @bytes_append(i64, i64)
declare i64 @bytes_from_utf8(i64)
declare i64 @bytes_to_utf8(i64)
declare i64 @bytes_builder_empty()
declare i64 @bytes_builder_bytes(i64)
declare i64 @bytes_builder_byte(i64)
declare i64 @bytes_builder_u16_be(i64)
declare i64 @bytes_builder_u32_be(i64)
declare i64 @bytes_builder_append(i64, i64)
declare i64 @bytes_builder_build(i64)
declare i64 @time_now_micros()
declare i64 @wall_time_micros()
declare i64 @tcp_listen(i64)
declare i64 @tcp_accept(i64)
declare i64 @tcp_write(i64, i64)
declare i64 @tcp_connect(i64, i64)
declare i64 @tcp_wait(i64, i64, i64)
declare i64 @tcp_write_some(i64, i64, i64)
declare i64 @tcp_read_some(i64, i64)
declare i64 @tcp_read_exact(i64, i64)
declare i64 @tcp_write_all(i64, i64)
declare i64 @tcp_write_all_timeout(i64, i64, i64)
declare i64 @tcp_close(i64)
declare i64 @tcp_close_listener(i64)
declare i64 @term_clear()
declare i64 @term_move(i64, i64)
declare i64 @term_hide_cursor()
declare i64 @term_show_cursor()
declare i64 @term_is_interactive()
declare i64 @term_read_key()
declare i64 @term_read_line()
declare i64 @term_write(i64)
@.str.0 = private unnamed_addr constant { i64, [15 x i8] } { i64 229386, [15 x i8] c"invalid handle\00" }
@.str.1 = private unnamed_addr constant { i64, [14 x i8] } { i64 213002, [14 x i8] c"end of stream\00" }
@.str.2 = private unnamed_addr constant { i64, [10 x i8] } { i64 147466, [10 x i8] c"timed out\00" }
@.str.3 = private unnamed_addr constant { i64, [12 x i8] } { i64 180234, [12 x i8] c"would block\00" }
@.str.4 = private unnamed_addr constant { i64, [17 x i8] } { i64 262154, [17 x i8] c"division by zero\00" }
@.str.5 = private unnamed_addr constant { i64, [8 x i8] } { i64 114698, [8 x i8] c"echoed \00" }
@.str.6 = private unnamed_addr constant { i64, [8 x i8] } { i64 114698, [8 x i8] c" bytes\0A\00" }
@.str.7 = private unnamed_addr constant { i64, [15 x i8] } { i64 229386, [15 x i8] c"write failed: \00" }
@.str.8 = private unnamed_addr constant { i64, [2 x i8] } { i64 16394, [2 x i8] c"\0A\00" }
@.str.9 = private unnamed_addr constant { i64, [14 x i8] } { i64 213002, [14 x i8] c"read failed: \00" }
@.str.10 = private unnamed_addr constant { i64, [2 x i8] } { i64 16394, [2 x i8] c"\0A\00" }
@.str.11 = private unnamed_addr constant { i64, [16 x i8] } { i64 245770, [16 x i8] c"accept failed: \00" }
@.str.12 = private unnamed_addr constant { i64, [2 x i8] } { i64 16394, [2 x i8] c"\0A\00" }
@.cname.0 = private unnamed_addr constant [8 x i8] c"Nothing\00"
@.cfkinds.0 = private unnamed_addr constant [1 x i8] c"\00"
@.cname.1 = private unnamed_addr constant [5 x i8] c"Just\00"
@.cfkinds.1 = private unnamed_addr constant [2 x i8] c"_\00"
@.cname.2 = private unnamed_addr constant [12 x i8] c"TemplateLit\00"
@.cfkinds.2 = private unnamed_addr constant [2 x i8] c"s\00"
@.cname.3 = private unnamed_addr constant [15 x i8] c"TemplateInterp\00"
@.cfkinds.3 = private unnamed_addr constant [2 x i8] c"s\00"
@.cname.4 = private unnamed_addr constant [15 x i8] c"StringTemplate\00"
@.cfkinds.4 = private unnamed_addr constant [2 x i8] c"p\00"
@.cname.5 = private unnamed_addr constant [4 x i8] c"Nil\00"
@.cfkinds.5 = private unnamed_addr constant [1 x i8] c"\00"
@.cname.6 = private unnamed_addr constant [5 x i8] c"Cons\00"
@.cfkinds.6 = private unnamed_addr constant [3 x i8] c"_p\00"
@.cname.7 = private unnamed_addr constant [3 x i8] c"Ok\00"
@.cfkinds.7 = private unnamed_addr constant [2 x i8] c"_\00"
@.cname.8 = private unnamed_addr constant [4 x i8] c"Err\00"
@.cfkinds.8 = private unnamed_addr constant [2 x i8] c"_\00"
@.cname.9 = private unnamed_addr constant [10 x i8] c"DivByZero\00"
@.cfkinds.9 = private unnamed_addr constant [1 x i8] c"\00"
@.cname.10 = private unnamed_addr constant [4 x i8] c"Vec\00"
@.cfkinds.10 = private unnamed_addr constant [2 x i8] c"p\00"
@.cname.11 = private unnamed_addr constant [5 x i8] c"Dict\00"
@.cfkinds.11 = private unnamed_addr constant [2 x i8] c"p\00"
@.cname.12 = private unnamed_addr constant [4 x i8] c"Set\00"
@.cfkinds.12 = private unnamed_addr constant [2 x i8] c"p\00"
@.cname.13 = private unnamed_addr constant [9 x i8] c"IntRange\00"
@.cfkinds.13 = private unnamed_addr constant [4 x i8] c"iii\00"
@.cname.14 = private unnamed_addr constant [29 x i8] c"stdlib.bytes.Utf8DecodeError\00"
@.cfkinds.14 = private unnamed_addr constant [2 x i8] c"s\00"
@.cname.15 = private unnamed_addr constant [30 x i8] c"stdlib.net.TcpInvalidArgument\00"
@.cfkinds.15 = private unnamed_addr constant [2 x i8] c"s\00"
@.cname.16 = private unnamed_addr constant [28 x i8] c"stdlib.net.TcpInvalidHandle\00"
@.cfkinds.16 = private unnamed_addr constant [1 x i8] c"\00"
@.cname.17 = private unnamed_addr constant [28 x i8] c"stdlib.net.TcpConnectFailed\00"
@.cfkinds.17 = private unnamed_addr constant [2 x i8] c"s\00"
@.cname.18 = private unnamed_addr constant [25 x i8] c"stdlib.net.TcpReadFailed\00"
@.cfkinds.18 = private unnamed_addr constant [2 x i8] c"s\00"
@.cname.19 = private unnamed_addr constant [26 x i8] c"stdlib.net.TcpWriteFailed\00"
@.cfkinds.19 = private unnamed_addr constant [2 x i8] c"s\00"
@.cname.20 = private unnamed_addr constant [26 x i8] c"stdlib.net.TcpEndOfStream\00"
@.cfkinds.20 = private unnamed_addr constant [1 x i8] c"\00"
@.cname.21 = private unnamed_addr constant [22 x i8] c"stdlib.net.TcpTimeout\00"
@.cfkinds.21 = private unnamed_addr constant [1 x i8] c"\00"
@.cname.22 = private unnamed_addr constant [25 x i8] c"stdlib.net.TcpWouldBlock\00"
@.cfkinds.22 = private unnamed_addr constant [1 x i8] c"\00"
@.cname.23 = private unnamed_addr constant [27 x i8] c"stdlib.net.TcpAcceptFailed\00"
@.cfkinds.23 = private unnamed_addr constant [2 x i8] c"s\00"
@.cname.24 = private unnamed_addr constant [25 x i8] c"stdlib.net.TcpConnection\00"
@.cfkinds.24 = private unnamed_addr constant [2 x i8] c"i\00"
@.cname.25 = private unnamed_addr constant [23 x i8] c"stdlib.net.TcpListener\00"
@.cfkinds.25 = private unnamed_addr constant [2 x i8] c"i\00"
@stdlib.net.poll_write = private constant i64 2
@stdlib.net.poll_read = private constant i64 1
@stdlib.net.read_chunk = private constant i64 65536
@stdlib.terminal.esc = global i64 zeroinitializer

define i64 @stdlib.time.now_micros() {
entry:
  %t$0 = call i64 @time_now_micros()
  ret i64 %t$0
}

define i64 @stdlib.net.tcp_error_message(i64 %err) {
entry:
  %t$0 = call i64 @sprout_tag(i64 %err)
  br label %arm_0_1
arm_0_1:
  %t$3 = add i64 0, 15
  %t$4 = icmp eq i64 %t$0, %t$3
  br i1 %t$4, label %body_0_1, label %arm_1_1
body_0_1:
  %t$5 = call i64 @sprout_field(i64 %err, i64 0)
  br label %join_1
arm_1_1:
  %t$6 = add i64 0, 16
  %t$7 = icmp eq i64 %t$0, %t$6
  br i1 %t$7, label %body_1_1, label %arm_2_1
body_1_1:
  %t$8 = getelementptr inbounds { i64, [15 x i8] }, ptr @.str.0, i64 0, i32 1, i64 0
  %t$9 = ptrtoint ptr %t$8 to i64
  br label %join_1
arm_2_1:
  %t$10 = add i64 0, 17
  %t$11 = icmp eq i64 %t$0, %t$10
  br i1 %t$11, label %body_2_1, label %arm_3_1
body_2_1:
  %t$12 = call i64 @sprout_field(i64 %err, i64 0)
  br label %join_1
arm_3_1:
  %t$13 = add i64 0, 18
  %t$14 = icmp eq i64 %t$0, %t$13
  br i1 %t$14, label %body_3_1, label %arm_4_1
body_3_1:
  %t$15 = call i64 @sprout_field(i64 %err, i64 0)
  br label %join_1
arm_4_1:
  %t$16 = add i64 0, 19
  %t$17 = icmp eq i64 %t$0, %t$16
  br i1 %t$17, label %body_4_1, label %arm_5_1
body_4_1:
  %t$18 = call i64 @sprout_field(i64 %err, i64 0)
  br label %join_1
arm_5_1:
  %t$19 = add i64 0, 20
  %t$20 = icmp eq i64 %t$0, %t$19
  br i1 %t$20, label %body_5_1, label %arm_6_1
body_5_1:
  %t$21 = getelementptr inbounds { i64, [14 x i8] }, ptr @.str.1, i64 0, i32 1, i64 0
  %t$22 = ptrtoint ptr %t$21 to i64
  br label %join_1
arm_6_1:
  %t$23 = add i64 0, 21
  %t$24 = icmp eq i64 %t$0, %t$23
  br i1 %t$24, label %body_6_1, label %arm_7_1
body_6_1:
  %t$25 = getelementptr inbounds { i64, [10 x i8] }, ptr @.str.2, i64 0, i32 1, i64 0
  %t$26 = ptrtoint ptr %t$25 to i64
  br label %join_1
arm_7_1:
  %t$27 = add i64 0, 22
  %t$28 = icmp eq i64 %t$0, %t$27
  br i1 %t$28, label %body_7_1, label %arm_8_1
body_7_1:
  %t$29 = getelementptr inbounds { i64, [12 x i8] }, ptr @.str.3, i64 0, i32 1, i64 0
  %t$30 = ptrtoint ptr %t$29 to i64
  br label %join_1
arm_8_1:
  %t$31 = add i64 0, 23
  %t$32 = icmp eq i64 %t$0, %t$31
  br i1 %t$32, label %body_8_1, label %arm_9_1
body_8_1:
  %t$33 = call i64 @sprout_field(i64 %err, i64 0)
  br label %join_1
arm_9_1:
  call void @sprout_abort_match()
  unreachable
join_1:
  %t$2 = phi i64 [%t$5, %body_0_1], [%t$9, %body_1_1], [%t$12, %body_2_1], [%t$15, %body_3_1], [%t$18, %body_4_1], [%t$22, %body_5_1], [%t$26, %body_6_1], [%t$30, %body_7_1], [%t$33, %body_8_1]
  ret i64 %t$2
}

define i64 @stdlib.net.tcp_connection_handle(i64 %conn) {
entry:
  %t$0 = call i64 @sprout_tag(i64 %conn)
  br label %arm_0_1
arm_0_1:
  %t$3 = add i64 0, 24
  %t$4 = icmp eq i64 %t$0, %t$3
  br i1 %t$4, label %body_0_1, label %arm_1_1
body_0_1:
  %t$5 = call i64 @sprout_field(i64 %conn, i64 0)
  br label %join_1
arm_1_1:
  call void @sprout_abort_match()
  unreachable
join_1:
  %t$2 = phi i64 [%t$5, %body_0_1]
  ret i64 %t$2
}

define i64 @stdlib.net.tcp_listener_handle(i64 %listener) {
entry:
  %t$0 = call i64 @sprout_tag(i64 %listener)
  br label %arm_0_1
arm_0_1:
  %t$3 = add i64 0, 25
  %t$4 = icmp eq i64 %t$0, %t$3
  br i1 %t$4, label %body_0_1, label %arm_1_1
body_0_1:
  %t$5 = call i64 @sprout_field(i64 %listener, i64 0)
  br label %join_1
arm_1_1:
  call void @sprout_abort_match()
  unreachable
join_1:
  %t$2 = phi i64 [%t$5, %body_0_1]
  ret i64 %t$2
}

define i64 @stdlib.net.write_all(i64 %conn, i64 %payload) {
entry:
  %t$0 = call i64 @stdlib.net.tcp_connection_handle(i64 %conn)
  %t$2 = alloca i64
  store i64 %payload, ptr %t$2
  %t$3 = call i64 @sprout_gc_push_i64_root(ptr %t$2)
  %t$1 = call i64 @tcp_write_all(i64 %t$0, i64 %payload)
  %t$4 = call i64 @sprout_gc_pop_roots(i64 1)
  ret i64 %t$1
}

define i64 @stdlib.net.read_avail_go(i64 %handle, i64 %deadline_us) {
entry:
  %t$0 = load i64, ptr @stdlib.net.read_chunk
  %t$1 = call i64 @tcp_read_some(i64 %handle, i64 %t$0)
  %t$2 = call i64 @sprout_tag(i64 %t$1)
  br label %arm_0_3
arm_0_3:
  %t$5 = add i64 0, 7
  %t$6 = icmp eq i64 %t$2, %t$5
  br i1 %t$6, label %body_0_3, label %arm_1_3
body_0_3:
  %t$7 = call i64 @sprout_field(i64 %t$1, i64 0)
  %t$20 = alloca i64
  store i64 %t$7, ptr %t$20
  %t$21 = call i64 @sprout_gc_push_i64_root(ptr %t$20)
  %t$8 = call i64 @sprout_alloc_obj(i64 7, i64 1)
  %t$8$ptr = inttoptr i64 %t$8 to ptr
  %t$8$f0 = getelementptr i64, ptr %t$8$ptr, i64 0
  store i64 %t$7, ptr %t$8$f0
  %t$22 = call i64 @sprout_gc_pop_roots(i64 1)
  br label %join_3
arm_1_3:
  %t$9 = add i64 0, 8
  %t$10 = icmp eq i64 %t$2, %t$9
  br i1 %t$10, label %body_1_3, label %arm_2_3
body_1_3:
  %t$11 = call i64 @sprout_field(i64 %t$1, i64 0)
  %t$12 = call i64 @sprout_tag(i64 %t$11)
  %t$13 = add i64 0, 22
  %t$14 = icmp eq i64 %t$12, %t$13
  br i1 %t$14, label %ntest_11, label %arm_2_3
ntest_11:
  %t$15 = musttail call i64 @stdlib.net.read_avail_wait(i64 %handle, i64 %deadline_us)
  ret i64 %t$15
arm_2_3:
  %t$16 = add i64 0, 8
  %t$17 = icmp eq i64 %t$2, %t$16
  br i1 %t$17, label %body_2_3, label %arm_3_3
body_2_3:
  %t$18 = call i64 @sprout_field(i64 %t$1, i64 0)
  %t$23 = alloca i64
  store i64 %t$18, ptr %t$23
  %t$24 = call i64 @sprout_gc_push_i64_root(ptr %t$23)
  %t$19 = call i64 @sprout_alloc_obj(i64 8, i64 1)
  %t$19$ptr = inttoptr i64 %t$19 to ptr
  %t$19$f0 = getelementptr i64, ptr %t$19$ptr, i64 0
  store i64 %t$18, ptr %t$19$f0
  %t$25 = call i64 @sprout_gc_pop_roots(i64 1)
  br label %join_3
arm_3_3:
  call void @sprout_abort_match()
  unreachable
join_3:
  %t$4 = phi i64 [%t$8, %body_0_3], [%t$19, %body_2_3]
  ret i64 %t$4
}

define i64 @stdlib.net.read_avail_wait(i64 %handle, i64 %deadline_us) {
entry:
  %t$0 = call i64 @stdlib.time.now_micros()
  %t$1 = load i64, ptr @stdlib.net.poll_read
  %t$2 = sub i64 %deadline_us, %t$0
  %t$3 = add i64 0, 1000
  %t$4 = icmp eq i64 %t$3, 0
  br i1 %t$4, label %divpanic_4, label %divok_4
divpanic_4:
  %t$5 = getelementptr inbounds { i64, [17 x i8] }, ptr @.str.4, i64 0, i32 1, i64 0
  %t$6 = ptrtoint ptr %t$5 to i64
  call i64 @panic(i64 %t$6)
  unreachable
divok_4:
  %t$7 = sdiv i64 %t$2, %t$3
  %t$8$st = call { i64, i64 } @tcp_wait_worker(i64 %handle, i64 %t$1, i64 %t$7)
  %t$8 = extractvalue { i64, i64 } %t$8$st, 0
  %t$9 = extractvalue { i64, i64 } %t$8$st, 1
  %t$10 = add i64 0, 8
  %t$11 = icmp eq i64 %t$8, %t$10
  br i1 %t$11, label %do_short_10, label %do_cont_10
do_short_10:
  %t$24 = alloca i64
  store i64 %t$9, ptr %t$24
  %t$25 = call i64 @sprout_gc_push_i64_root(ptr %t$24)
  %t$13 = call i64 @sprout_alloc_obj(i64 8, i64 1)
  %t$13$ptr = inttoptr i64 %t$13 to ptr
  %t$13$f0 = getelementptr i64, ptr %t$13$ptr, i64 0
  store i64 %t$9, ptr %t$13$f0
  %t$26 = call i64 @sprout_gc_pop_roots(i64 1)
  br label %do_done_10
do_cont_10:
  %t$14 = add i64 0, 1
  %t$15 = icmp eq i64 %t$9, %t$14
  %t$16 = zext i1 %t$15 to i64
  %t$22 = trunc i64 %t$16 to i1
  br i1 %t$22, label %then_17, label %else_17
then_17:
  %t$19 = musttail call i64 @stdlib.net.read_avail_go(i64 %handle, i64 %deadline_us)
  ret i64 %t$19
else_17:
  %t$20 = call i64 @sprout_alloc_obj(i64 21, i64 0)
  %t$27 = alloca i64
  store i64 %t$20, ptr %t$27
  %t$28 = call i64 @sprout_gc_push_i64_root(ptr %t$27)
  %t$21 = call i64 @sprout_alloc_obj(i64 8, i64 1)
  %t$21$ptr = inttoptr i64 %t$21 to ptr
  %t$21$f0 = getelementptr i64, ptr %t$21$ptr, i64 0
  store i64 %t$20, ptr %t$21$f0
  %t$29 = call i64 @sprout_gc_pop_roots(i64 1)
  br label %join_17
join_17:
  %t$18 = phi i64 [%t$21, %else_17]
  br label %do_done_10
do_done_10:
  %t$23 = phi i64 [%t$13, %do_short_10], [%t$18, %join_17]
  ret i64 %t$23
}

define i64 @stdlib.net.read_avail_timeout(i64 %conn, i64 %timeout_ms) {
entry:
  %t$6 = alloca i64
  store i64 %conn, ptr %t$6
  %t$7 = call i64 @sprout_gc_push_i64_root(ptr %t$6)
  %t$0 = call i64 @stdlib.time.now_micros()
  %t$1 = call i64 @stdlib.net.tcp_connection_handle(i64 %conn)
  %t$2 = add i64 0, 1000
  %t$3 = mul i64 %timeout_ms, %t$2
  %t$4 = add i64 %t$0, %t$3
  %t$5 = call i64 @stdlib.net.read_avail_go(i64 %t$1, i64 %t$4)
  %t$8 = call i64 @sprout_gc_pop_roots(i64 1)
  ret i64 %t$5
}

define i64 @stdlib.net.close(i64 %conn) {
entry:
  %t$0 = call i64 @sprout_tag(i64 %conn)
  br label %arm_0_1
arm_0_1:
  %t$3 = add i64 0, 24
  %t$4 = icmp eq i64 %t$0, %t$3
  br i1 %t$4, label %body_0_1, label %arm_1_1
body_0_1:
  %t$5 = call i64 @sprout_field(i64 %conn, i64 0)
  %t$6 = call i64 @tcp_close(i64 %t$5)
  br label %join_1
arm_1_1:
  call void @sprout_abort_match()
  unreachable
join_1:
  %t$2 = phi i64 [%t$6, %body_0_1]
  ret i64 %t$2
}

define i64 @stdlib.net.listen_local(i64 %port) {
entry:
  %t$0 = call i64 @tcp_listen(i64 %port)
  %t$1 = call i64 @sprout_alloc_obj(i64 25, i64 1)
  %t$1$ptr = inttoptr i64 %t$1 to ptr
  %t$1$f0 = getelementptr i64, ptr %t$1$ptr, i64 0
  store i64 %t$0, ptr %t$1$f0
  ret i64 %t$1
}

define i64 @stdlib.net.accept(i64 %listener) {
entry:
  %t$0 = call i64 @stdlib.net.tcp_listener_handle(i64 %listener)
  %t$1$st = call { i64, i64 } @tcp_accept_worker(i64 %t$0)
  %t$1 = extractvalue { i64, i64 } %t$1$st, 0
  %t$2 = extractvalue { i64, i64 } %t$1$st, 1
  %t$3 = add i64 0, 8
  %t$4 = icmp eq i64 %t$1, %t$3
  br i1 %t$4, label %do_short_3, label %do_cont_3
do_short_3:
  %t$10 = alloca i64
  store i64 %t$2, ptr %t$10
  %t$11 = call i64 @sprout_gc_push_i64_root(ptr %t$10)
  %t$6 = call i64 @sprout_alloc_obj(i64 8, i64 1)
  %t$6$ptr = inttoptr i64 %t$6 to ptr
  %t$6$f0 = getelementptr i64, ptr %t$6$ptr, i64 0
  store i64 %t$2, ptr %t$6$f0
  %t$12 = call i64 @sprout_gc_pop_roots(i64 1)
  br label %do_done_3
do_cont_3:
  %t$13 = alloca i64
  store i64 %t$2, ptr %t$13
  %t$14 = call i64 @sprout_gc_push_i64_root(ptr %t$13)
  %t$7 = call i64 @sprout_alloc_obj(i64 24, i64 1)
  %t$7$ptr = inttoptr i64 %t$7 to ptr
  %t$7$f0 = getelementptr i64, ptr %t$7$ptr, i64 0
  store i64 %t$2, ptr %t$7$f0
  %t$15 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$16 = alloca i64
  store i64 %t$7, ptr %t$16
  %t$17 = call i64 @sprout_gc_push_i64_root(ptr %t$16)
  %t$8 = call i64 @sprout_alloc_obj(i64 7, i64 1)
  %t$8$ptr = inttoptr i64 %t$8 to ptr
  %t$8$f0 = getelementptr i64, ptr %t$8$ptr, i64 0
  store i64 %t$7, ptr %t$8$f0
  %t$18 = call i64 @sprout_gc_pop_roots(i64 1)
  br label %do_done_3
do_done_3:
  %t$9 = phi i64 [%t$6, %do_short_3], [%t$8, %do_cont_3]
  ret i64 %t$9
}

define i64 @stdlib.net.close_listener(i64 %listener) {
entry:
  %t$0 = call i64 @sprout_tag(i64 %listener)
  br label %arm_0_1
arm_0_1:
  %t$3 = add i64 0, 25
  %t$4 = icmp eq i64 %t$0, %t$3
  br i1 %t$4, label %body_0_1, label %arm_1_1
body_0_1:
  %t$5 = call i64 @sprout_field(i64 %listener, i64 0)
  %t$6 = call i64 @tcp_close_listener(i64 %t$5)
  br label %join_1
arm_1_1:
  call void @sprout_abort_match()
  unreachable
join_1:
  %t$2 = phi i64 [%t$6, %body_0_1]
  ret i64 %t$2
}

define i64 @stdlib.terminal.write(i64 %text) {
entry:
  %t$1 = alloca i64
  store i64 %text, ptr %t$1
  %t$2 = call i64 @sprout_gc_push_i64_root(ptr %t$1)
  %t$0 = call i64 @term_write(i64 %text)
  %t$3 = call i64 @sprout_gc_pop_roots(i64 1)
  ret i64 %t$0
}

define i64 @examples.tcp_echo_once.echo(i64 %conn) {
entry:
  %t$0 = add i64 0, 30000
  %t$54 = alloca i64
  store i64 %conn, ptr %t$54
  %t$55 = call i64 @sprout_gc_push_i64_root(ptr %t$54)
  %t$1$st = call { i64, i64 } @stdlib.net.read_avail_timeout_worker(i64 %conn, i64 %t$0)
  %t$1 = extractvalue { i64, i64 } %t$1$st, 0
  %t$2 = extractvalue { i64, i64 } %t$1$st, 1
  %t$56 = call i64 @sprout_gc_pop_roots(i64 1)
  br label %arm_0_3
arm_0_3:
  %t$5 = add i64 0, 7
  %t$6 = icmp eq i64 %t$1, %t$5
  br i1 %t$6, label %body_0_3, label %arm_1_3
body_0_3:
  %t$57 = alloca i64
  store i64 %t$2, ptr %t$57
  %t$58 = call i64 @sprout_gc_push_i64_root(ptr %t$57)
  %t$59 = alloca i64
  store i64 %conn, ptr %t$59
  %t$60 = call i64 @sprout_gc_push_i64_root(ptr %t$59)
  %t$7$st = call { i64, i64 } @stdlib.net.write_all_worker(i64 %conn, i64 %t$2)
  %t$7 = extractvalue { i64, i64 } %t$7$st, 0
  %t$8 = extractvalue { i64, i64 } %t$7$st, 1
  %t$61 = call i64 @sprout_gc_pop_roots(i64 2)
  br label %arm_0_9
arm_0_9:
  %t$11 = add i64 0, 7
  %t$12 = icmp eq i64 %t$7, %t$11
  br i1 %t$12, label %body_0_9, label %arm_1_9
body_0_9:
  %t$13 = getelementptr inbounds { i64, [8 x i8] }, ptr @.str.5, i64 0, i32 1, i64 0
  %t$14 = ptrtoint ptr %t$13 to i64
  %t$62 = alloca i64
  store i64 %conn, ptr %t$62
  %t$63 = call i64 @sprout_gc_push_i64_root(ptr %t$62)
  %t$64 = alloca i64
  store i64 %t$14, ptr %t$64
  %t$65 = call i64 @sprout_gc_push_i64_root(ptr %t$64)
  %t$15 = call i64 @int_to_string(i64 %t$8)
  %t$16 = call i64 @__tc_ToString_String_to_string(i64 %t$15)
  %t$17 = getelementptr inbounds { i64, [8 x i8] }, ptr @.str.6, i64 0, i32 1, i64 0
  %t$18 = ptrtoint ptr %t$17 to i64
  %t$66 = alloca i64
  store i64 %t$16, ptr %t$66
  %t$67 = call i64 @sprout_gc_push_i64_root(ptr %t$66)
  %t$68 = alloca i64
  store i64 %t$18, ptr %t$68
  %t$69 = call i64 @sprout_gc_push_i64_root(ptr %t$68)
  %t$19 = call i64 @sprout_alloc_obj(i64 5, i64 0)
  %t$70 = alloca i64
  store i64 %t$19, ptr %t$70
  %t$71 = call i64 @sprout_gc_push_i64_root(ptr %t$70)
  %t$20 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$20$ptr = inttoptr i64 %t$20 to ptr
  %t$20$f0 = getelementptr i64, ptr %t$20$ptr, i64 0
  store i64 %t$18, ptr %t$20$f0
  %t$20$f1 = getelementptr i64, ptr %t$20$ptr, i64 1
  store i64 %t$19, ptr %t$20$f1
  %t$72 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$73 = alloca i64
  store i64 %t$20, ptr %t$73
  %t$74 = call i64 @sprout_gc_push_i64_root(ptr %t$73)
  %t$21 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$21$ptr = inttoptr i64 %t$21 to ptr
  %t$21$f0 = getelementptr i64, ptr %t$21$ptr, i64 0
  store i64 %t$16, ptr %t$21$f0
  %t$21$f1 = getelementptr i64, ptr %t$21$ptr, i64 1
  store i64 %t$20, ptr %t$21$f1
  %t$75 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$76 = alloca i64
  store i64 %t$21, ptr %t$76
  %t$77 = call i64 @sprout_gc_push_i64_root(ptr %t$76)
  %t$22 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$22$ptr = inttoptr i64 %t$22 to ptr
  %t$22$f0 = getelementptr i64, ptr %t$22$ptr, i64 0
  store i64 %t$14, ptr %t$22$f0
  %t$22$f1 = getelementptr i64, ptr %t$22$ptr, i64 1
  store i64 %t$21, ptr %t$22$f1
  %t$78 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$79 = alloca i64
  store i64 %t$22, ptr %t$79
  %t$80 = call i64 @sprout_gc_push_i64_root(ptr %t$79)
  %t$23 = call i64 @string_concat_many(i64 %t$22)
  %t$81 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$82 = alloca i64
  store i64 %t$23, ptr %t$82
  %t$83 = call i64 @sprout_gc_push_i64_root(ptr %t$82)
  %t$24 = call i64 @stdlib.terminal.write(i64 %t$23)
  %t$84 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$85 = call i64 @sprout_gc_pop_roots(i64 1)
  br label %join_9
arm_1_9:
  %t$25 = add i64 0, 8
  %t$26 = icmp eq i64 %t$7, %t$25
  br i1 %t$26, label %body_1_9, label %arm_2_9
body_1_9:
  %t$27 = getelementptr inbounds { i64, [15 x i8] }, ptr @.str.7, i64 0, i32 1, i64 0
  %t$28 = ptrtoint ptr %t$27 to i64
  %t$29 = call i64 @stdlib.net.tcp_error_message(i64 %t$8)
  %t$30 = call i64 @__tc_ToString_String_to_string(i64 %t$29)
  %t$31 = getelementptr inbounds { i64, [2 x i8] }, ptr @.str.8, i64 0, i32 1, i64 0
  %t$32 = ptrtoint ptr %t$31 to i64
  %t$86 = alloca i64
  store i64 %conn, ptr %t$86
  %t$87 = call i64 @sprout_gc_push_i64_root(ptr %t$86)
  %t$88 = alloca i64
  store i64 %t$28, ptr %t$88
  %t$89 = call i64 @sprout_gc_push_i64_root(ptr %t$88)
  %t$90 = alloca i64
  store i64 %t$30, ptr %t$90
  %t$91 = call i64 @sprout_gc_push_i64_root(ptr %t$90)
  %t$92 = alloca i64
  store i64 %t$32, ptr %t$92
  %t$93 = call i64 @sprout_gc_push_i64_root(ptr %t$92)
  %t$33 = call i64 @sprout_alloc_obj(i64 5, i64 0)
  %t$94 = alloca i64
  store i64 %t$33, ptr %t$94
  %t$95 = call i64 @sprout_gc_push_i64_root(ptr %t$94)
  %t$34 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$34$ptr = inttoptr i64 %t$34 to ptr
  %t$34$f0 = getelementptr i64, ptr %t$34$ptr, i64 0
  store i64 %t$32, ptr %t$34$f0
  %t$34$f1 = getelementptr i64, ptr %t$34$ptr, i64 1
  store i64 %t$33, ptr %t$34$f1
  %t$96 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$97 = alloca i64
  store i64 %t$34, ptr %t$97
  %t$98 = call i64 @sprout_gc_push_i64_root(ptr %t$97)
  %t$35 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$35$ptr = inttoptr i64 %t$35 to ptr
  %t$35$f0 = getelementptr i64, ptr %t$35$ptr, i64 0
  store i64 %t$30, ptr %t$35$f0
  %t$35$f1 = getelementptr i64, ptr %t$35$ptr, i64 1
  store i64 %t$34, ptr %t$35$f1
  %t$99 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$100 = alloca i64
  store i64 %t$35, ptr %t$100
  %t$101 = call i64 @sprout_gc_push_i64_root(ptr %t$100)
  %t$36 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$36$ptr = inttoptr i64 %t$36 to ptr
  %t$36$f0 = getelementptr i64, ptr %t$36$ptr, i64 0
  store i64 %t$28, ptr %t$36$f0
  %t$36$f1 = getelementptr i64, ptr %t$36$ptr, i64 1
  store i64 %t$35, ptr %t$36$f1
  %t$102 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$103 = alloca i64
  store i64 %t$36, ptr %t$103
  %t$104 = call i64 @sprout_gc_push_i64_root(ptr %t$103)
  %t$37 = call i64 @string_concat_many(i64 %t$36)
  %t$105 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$106 = alloca i64
  store i64 %t$37, ptr %t$106
  %t$107 = call i64 @sprout_gc_push_i64_root(ptr %t$106)
  %t$38 = call i64 @stdlib.terminal.write(i64 %t$37)
  %t$108 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$109 = call i64 @sprout_gc_pop_roots(i64 1)
  br label %join_9
arm_2_9:
  call void @sprout_abort_match()
  unreachable
join_9:
  %t$10 = phi i64 [%t$24, %body_0_9], [%t$38, %body_1_9]
  br label %join_3
arm_1_3:
  %t$39 = add i64 0, 8
  %t$40 = icmp eq i64 %t$1, %t$39
  br i1 %t$40, label %body_1_3, label %arm_2_3
body_1_3:
  %t$41 = getelementptr inbounds { i64, [14 x i8] }, ptr @.str.9, i64 0, i32 1, i64 0
  %t$42 = ptrtoint ptr %t$41 to i64
  %t$43 = call i64 @stdlib.net.tcp_error_message(i64 %t$2)
  %t$44 = call i64 @__tc_ToString_String_to_string(i64 %t$43)
  %t$45 = getelementptr inbounds { i64, [2 x i8] }, ptr @.str.10, i64 0, i32 1, i64 0
  %t$46 = ptrtoint ptr %t$45 to i64
  %t$110 = alloca i64
  store i64 %conn, ptr %t$110
  %t$111 = call i64 @sprout_gc_push_i64_root(ptr %t$110)
  %t$112 = alloca i64
  store i64 %t$42, ptr %t$112
  %t$113 = call i64 @sprout_gc_push_i64_root(ptr %t$112)
  %t$114 = alloca i64
  store i64 %t$44, ptr %t$114
  %t$115 = call i64 @sprout_gc_push_i64_root(ptr %t$114)
  %t$116 = alloca i64
  store i64 %t$46, ptr %t$116
  %t$117 = call i64 @sprout_gc_push_i64_root(ptr %t$116)
  %t$47 = call i64 @sprout_alloc_obj(i64 5, i64 0)
  %t$118 = alloca i64
  store i64 %t$47, ptr %t$118
  %t$119 = call i64 @sprout_gc_push_i64_root(ptr %t$118)
  %t$48 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$48$ptr = inttoptr i64 %t$48 to ptr
  %t$48$f0 = getelementptr i64, ptr %t$48$ptr, i64 0
  store i64 %t$46, ptr %t$48$f0
  %t$48$f1 = getelementptr i64, ptr %t$48$ptr, i64 1
  store i64 %t$47, ptr %t$48$f1
  %t$120 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$121 = alloca i64
  store i64 %t$48, ptr %t$121
  %t$122 = call i64 @sprout_gc_push_i64_root(ptr %t$121)
  %t$49 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$49$ptr = inttoptr i64 %t$49 to ptr
  %t$49$f0 = getelementptr i64, ptr %t$49$ptr, i64 0
  store i64 %t$44, ptr %t$49$f0
  %t$49$f1 = getelementptr i64, ptr %t$49$ptr, i64 1
  store i64 %t$48, ptr %t$49$f1
  %t$123 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$124 = alloca i64
  store i64 %t$49, ptr %t$124
  %t$125 = call i64 @sprout_gc_push_i64_root(ptr %t$124)
  %t$50 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$50$ptr = inttoptr i64 %t$50 to ptr
  %t$50$f0 = getelementptr i64, ptr %t$50$ptr, i64 0
  store i64 %t$42, ptr %t$50$f0
  %t$50$f1 = getelementptr i64, ptr %t$50$ptr, i64 1
  store i64 %t$49, ptr %t$50$f1
  %t$126 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$127 = alloca i64
  store i64 %t$50, ptr %t$127
  %t$128 = call i64 @sprout_gc_push_i64_root(ptr %t$127)
  %t$51 = call i64 @string_concat_many(i64 %t$50)
  %t$129 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$130 = alloca i64
  store i64 %t$51, ptr %t$130
  %t$131 = call i64 @sprout_gc_push_i64_root(ptr %t$130)
  %t$52 = call i64 @stdlib.terminal.write(i64 %t$51)
  %t$132 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$133 = call i64 @sprout_gc_pop_roots(i64 1)
  br label %join_3
arm_2_3:
  call void @sprout_abort_match()
  unreachable
join_3:
  %t$4 = phi i64 [%t$10, %join_9], [%t$52, %body_1_3]
  %t$134 = alloca i64
  store i64 %conn, ptr %t$134
  %t$135 = call i64 @sprout_gc_push_i64_root(ptr %t$134)
  %t$53 = call i64 @stdlib.net.close(i64 %conn)
  %t$136 = call i64 @sprout_gc_pop_roots(i64 1)
  ret i64 %t$53
}

define i64 @__sprout_user_main() {
entry:
  %t$0 = add i64 0, 8081
  %t$1 = call i64 @stdlib.net.listen_local(i64 %t$0)
  %t$24 = alloca i64
  store i64 %t$1, ptr %t$24
  %t$25 = call i64 @sprout_gc_push_i64_root(ptr %t$24)
  %t$2$st = call { i64, i64 } @stdlib.net.accept_worker(i64 %t$1)
  %t$2 = extractvalue { i64, i64 } %t$2$st, 0
  %t$3 = extractvalue { i64, i64 } %t$2$st, 1
  %t$26 = call i64 @sprout_gc_pop_roots(i64 1)
  br label %arm_0_4
arm_0_4:
  %t$6 = add i64 0, 7
  %t$7 = icmp eq i64 %t$2, %t$6
  br i1 %t$7, label %body_0_4, label %arm_1_4
body_0_4:
  %t$27 = alloca i64
  store i64 %t$3, ptr %t$27
  %t$28 = call i64 @sprout_gc_push_i64_root(ptr %t$27)
  %t$29 = alloca i64
  store i64 %t$1, ptr %t$29
  %t$30 = call i64 @sprout_gc_push_i64_root(ptr %t$29)
  %t$8 = call i64 @examples.tcp_echo_once.echo(i64 %t$3)
  %t$31 = call i64 @sprout_gc_pop_roots(i64 2)
  br label %join_4
arm_1_4:
  %t$9 = add i64 0, 8
  %t$10 = icmp eq i64 %t$2, %t$9
  br i1 %t$10, label %body_1_4, label %arm_2_4
body_1_4:
  %t$11 = getelementptr inbounds { i64, [16 x i8] }, ptr @.str.11, i64 0, i32 1, i64 0
  %t$12 = ptrtoint ptr %t$11 to i64
  %t$13 = call i64 @stdlib.net.tcp_error_message(i64 %t$3)
  %t$14 = call i64 @__tc_ToString_String_to_string(i64 %t$13)
  %t$15 = getelementptr inbounds { i64, [2 x i8] }, ptr @.str.12, i64 0, i32 1, i64 0
  %t$16 = ptrtoint ptr %t$15 to i64
  %t$32 = alloca i64
  store i64 %t$1, ptr %t$32
  %t$33 = call i64 @sprout_gc_push_i64_root(ptr %t$32)
  %t$34 = alloca i64
  store i64 %t$12, ptr %t$34
  %t$35 = call i64 @sprout_gc_push_i64_root(ptr %t$34)
  %t$36 = alloca i64
  store i64 %t$14, ptr %t$36
  %t$37 = call i64 @sprout_gc_push_i64_root(ptr %t$36)
  %t$38 = alloca i64
  store i64 %t$16, ptr %t$38
  %t$39 = call i64 @sprout_gc_push_i64_root(ptr %t$38)
  %t$17 = call i64 @sprout_alloc_obj(i64 5, i64 0)
  %t$40 = alloca i64
  store i64 %t$17, ptr %t$40
  %t$41 = call i64 @sprout_gc_push_i64_root(ptr %t$40)
  %t$18 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$18$ptr = inttoptr i64 %t$18 to ptr
  %t$18$f0 = getelementptr i64, ptr %t$18$ptr, i64 0
  store i64 %t$16, ptr %t$18$f0
  %t$18$f1 = getelementptr i64, ptr %t$18$ptr, i64 1
  store i64 %t$17, ptr %t$18$f1
  %t$42 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$43 = alloca i64
  store i64 %t$18, ptr %t$43
  %t$44 = call i64 @sprout_gc_push_i64_root(ptr %t$43)
  %t$19 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$19$ptr = inttoptr i64 %t$19 to ptr
  %t$19$f0 = getelementptr i64, ptr %t$19$ptr, i64 0
  store i64 %t$14, ptr %t$19$f0
  %t$19$f1 = getelementptr i64, ptr %t$19$ptr, i64 1
  store i64 %t$18, ptr %t$19$f1
  %t$45 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$46 = alloca i64
  store i64 %t$19, ptr %t$46
  %t$47 = call i64 @sprout_gc_push_i64_root(ptr %t$46)
  %t$20 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$20$ptr = inttoptr i64 %t$20 to ptr
  %t$20$f0 = getelementptr i64, ptr %t$20$ptr, i64 0
  store i64 %t$12, ptr %t$20$f0
  %t$20$f1 = getelementptr i64, ptr %t$20$ptr, i64 1
  store i64 %t$19, ptr %t$20$f1
  %t$48 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$49 = alloca i64
  store i64 %t$20, ptr %t$49
  %t$50 = call i64 @sprout_gc_push_i64_root(ptr %t$49)
  %t$21 = call i64 @string_concat_many(i64 %t$20)
  %t$51 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$52 = alloca i64
  store i64 %t$21, ptr %t$52
  %t$53 = call i64 @sprout_gc_push_i64_root(ptr %t$52)
  %t$22 = call i64 @stdlib.terminal.write(i64 %t$21)
  %t$54 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$55 = call i64 @sprout_gc_pop_roots(i64 1)
  br label %join_4
arm_2_4:
  call void @sprout_abort_match()
  unreachable
join_4:
  %t$5 = phi i64 [%t$8, %body_0_4], [%t$22, %body_1_4]
  %t$56 = alloca i64
  store i64 %t$1, ptr %t$56
  %t$57 = call i64 @sprout_gc_push_i64_root(ptr %t$56)
  %t$23 = call i64 @stdlib.net.close_listener(i64 %t$1)
  %t$58 = call i64 @sprout_gc_pop_roots(i64 1)
  ret i64 %t$23
}

define i64 @__tc_ToString_String_to_string(i64 %value) {
entry:
  ret i64 %value
}

define { i64, i64 } @stdlib.net.accept_worker(i64 %listener) {
entry:
  %t$0 = call i64 @stdlib.net.tcp_listener_handle(i64 %listener)
  %t$1$st = call { i64, i64 } @tcp_accept_worker(i64 %t$0)
  %t$1 = extractvalue { i64, i64 } %t$1$st, 0
  %t$2 = extractvalue { i64, i64 } %t$1$st, 1
  %t$3 = add i64 0, 8
  %t$4 = icmp eq i64 %t$1, %t$3
  br i1 %t$4, label %do_short_3, label %do_cont_3
do_short_3:
  %t$19 = alloca i64
  store i64 %t$2, ptr %t$19
  %t$20 = call i64 @sprout_gc_push_i64_root(ptr %t$19)
  %t$6 = call i64 @sprout_alloc_obj(i64 8, i64 1)
  %t$6$ptr = inttoptr i64 %t$6 to ptr
  %t$6$f0 = getelementptr i64, ptr %t$6$ptr, i64 0
  store i64 %t$2, ptr %t$6$f0
  %t$21 = call i64 @sprout_gc_pop_roots(i64 1)
  br label %do_done_3
do_cont_3:
  %t$22 = alloca i64
  store i64 %t$2, ptr %t$22
  %t$23 = call i64 @sprout_gc_push_i64_root(ptr %t$22)
  %t$7 = call i64 @sprout_alloc_obj(i64 24, i64 1)
  %t$7$ptr = inttoptr i64 %t$7 to ptr
  %t$7$f0 = getelementptr i64, ptr %t$7$ptr, i64 0
  store i64 %t$2, ptr %t$7$f0
  %t$24 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$25 = alloca i64
  store i64 %t$7, ptr %t$25
  %t$26 = call i64 @sprout_gc_push_i64_root(ptr %t$25)
  %t$8 = call i64 @sprout_alloc_obj(i64 7, i64 1)
  %t$8$ptr = inttoptr i64 %t$8 to ptr
  %t$8$f0 = getelementptr i64, ptr %t$8$ptr, i64 0
  store i64 %t$7, ptr %t$8$f0
  %t$27 = call i64 @sprout_gc_pop_roots(i64 1)
  br label %do_done_3
do_done_3:
  %t$9 = phi i64 [%t$6, %do_short_3], [%t$8, %do_cont_3]
  %t$10 = call i64 @sprout_tag(i64 %t$9)
  %t$11 = add i64 0, 7
  %t$12 = icmp eq i64 %t$10, %t$11
  br i1 %t$12, label %wrepack_hit_11, label %wrepack_next_11
wrepack_hit_11:
  %t$13 = call i64 @sprout_field(i64 %t$9, i64 0)
  %t$14$r0 = insertvalue { i64, i64 } undef, i64 %t$10, 0
  %t$14$r1 = insertvalue { i64, i64 } %t$14$r0, i64 %t$13, 1
  ret { i64, i64 } %t$14$r1
wrepack_next_11:
  %t$15 = add i64 0, 8
  %t$16 = icmp eq i64 %t$10, %t$15
  br i1 %t$16, label %wrepack_hit_15, label %wrepack_next_15
wrepack_hit_15:
  %t$17 = call i64 @sprout_field(i64 %t$9, i64 0)
  %t$18$r0 = insertvalue { i64, i64 } undef, i64 %t$10, 0
  %t$18$r1 = insertvalue { i64, i64 } %t$18$r0, i64 %t$17, 1
  ret { i64, i64 } %t$18$r1
wrepack_next_15:
  call void @sprout_abort_match()
  unreachable
}

define { i64, i64 } @stdlib.net.read_avail_timeout_worker(i64 %conn, i64 %timeout_ms) {
entry:
  %t$15 = alloca i64
  store i64 %conn, ptr %t$15
  %t$16 = call i64 @sprout_gc_push_i64_root(ptr %t$15)
  %t$0 = call i64 @stdlib.time.now_micros()
  %t$1 = call i64 @stdlib.net.tcp_connection_handle(i64 %conn)
  %t$2 = add i64 0, 1000
  %t$3 = mul i64 %timeout_ms, %t$2
  %t$4 = add i64 %t$0, %t$3
  %t$5 = call i64 @stdlib.net.read_avail_go(i64 %t$1, i64 %t$4)
  %t$17 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$6 = call i64 @sprout_tag(i64 %t$5)
  %t$7 = add i64 0, 7
  %t$8 = icmp eq i64 %t$6, %t$7
  br i1 %t$8, label %wrepack_hit_7, label %wrepack_next_7
wrepack_hit_7:
  %t$9 = call i64 @sprout_field(i64 %t$5, i64 0)
  %t$10$r0 = insertvalue { i64, i64 } undef, i64 %t$6, 0
  %t$10$r1 = insertvalue { i64, i64 } %t$10$r0, i64 %t$9, 1
  ret { i64, i64 } %t$10$r1
wrepack_next_7:
  %t$11 = add i64 0, 8
  %t$12 = icmp eq i64 %t$6, %t$11
  br i1 %t$12, label %wrepack_hit_11, label %wrepack_next_11
wrepack_hit_11:
  %t$13 = call i64 @sprout_field(i64 %t$5, i64 0)
  %t$14$r0 = insertvalue { i64, i64 } undef, i64 %t$6, 0
  %t$14$r1 = insertvalue { i64, i64 } %t$14$r0, i64 %t$13, 1
  ret { i64, i64 } %t$14$r1
wrepack_next_11:
  call void @sprout_abort_match()
  unreachable
}

define { i64, i64 } @stdlib.net.write_all_worker(i64 %conn, i64 %payload) {
entry:
  %t$0 = call i64 @stdlib.net.tcp_connection_handle(i64 %conn)
  %t$11 = alloca i64
  store i64 %payload, ptr %t$11
  %t$12 = call i64 @sprout_gc_push_i64_root(ptr %t$11)
  %t$1 = call i64 @tcp_write_all(i64 %t$0, i64 %payload)
  %t$13 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$2 = call i64 @sprout_tag(i64 %t$1)
  %t$3 = add i64 0, 7
  %t$4 = icmp eq i64 %t$2, %t$3
  br i1 %t$4, label %wrepack_hit_3, label %wrepack_next_3
wrepack_hit_3:
  %t$5 = call i64 @sprout_field(i64 %t$1, i64 0)
  %t$6$r0 = insertvalue { i64, i64 } undef, i64 %t$2, 0
  %t$6$r1 = insertvalue { i64, i64 } %t$6$r0, i64 %t$5, 1
  ret { i64, i64 } %t$6$r1
wrepack_next_3:
  %t$7 = add i64 0, 8
  %t$8 = icmp eq i64 %t$2, %t$7
  br i1 %t$8, label %wrepack_hit_7, label %wrepack_next_7
wrepack_hit_7:
  %t$9 = call i64 @sprout_field(i64 %t$1, i64 0)
  %t$10$r0 = insertvalue { i64, i64 } undef, i64 %t$2, 0
  %t$10$r1 = insertvalue { i64, i64 } %t$10$r0, i64 %t$9, 1
  ret { i64, i64 } %t$10$r1
wrepack_next_7:
  call void @sprout_abort_match()
  unreachable
}

define { i64, i64 } @tcp_accept_worker(i64 %listener) {
entry:
  %t$0 = call i64 @tcp_accept(i64 %listener)
  %t$1 = call i64 @sprout_tag(i64 %t$0)
  %t$2 = add i64 0, 7
  %t$3 = icmp eq i64 %t$1, %t$2
  br i1 %t$3, label %wrepack_hit_2, label %wrepack_next_2
wrepack_hit_2:
  %t$4 = call i64 @sprout_field(i64 %t$0, i64 0)
  %t$5$r0 = insertvalue { i64, i64 } undef, i64 %t$1, 0
  %t$5$r1 = insertvalue { i64, i64 } %t$5$r0, i64 %t$4, 1
  ret { i64, i64 } %t$5$r1
wrepack_next_2:
  %t$6 = add i64 0, 8
  %t$7 = icmp eq i64 %t$1, %t$6
  br i1 %t$7, label %wrepack_hit_6, label %wrepack_next_6
wrepack_hit_6:
  %t$8 = call i64 @sprout_field(i64 %t$0, i64 0)
  %t$9$r0 = insertvalue { i64, i64 } undef, i64 %t$1, 0
  %t$9$r1 = insertvalue { i64, i64 } %t$9$r0, i64 %t$8, 1
  ret { i64, i64 } %t$9$r1
wrepack_next_6:
  call void @sprout_abort_match()
  unreachable
}

define { i64, i64 } @tcp_wait_worker(i64 %conn, i64 %interest, i64 %ms) {
entry:
  %t$0 = call i64 @tcp_wait(i64 %conn, i64 %interest, i64 %ms)
  %t$1 = call i64 @sprout_tag(i64 %t$0)
  %t$2 = add i64 0, 7
  %t$3 = icmp eq i64 %t$1, %t$2
  br i1 %t$3, label %wrepack_hit_2, label %wrepack_next_2
wrepack_hit_2:
  %t$4 = call i64 @sprout_field(i64 %t$0, i64 0)
  %t$5$r0 = insertvalue { i64, i64 } undef, i64 %t$1, 0
  %t$5$r1 = insertvalue { i64, i64 } %t$5$r0, i64 %t$4, 1
  ret { i64, i64 } %t$5$r1
wrepack_next_2:
  %t$6 = add i64 0, 8
  %t$7 = icmp eq i64 %t$1, %t$6
  br i1 %t$7, label %wrepack_hit_6, label %wrepack_next_6
wrepack_hit_6:
  %t$8 = call i64 @sprout_field(i64 %t$0, i64 0)
  %t$9$r0 = insertvalue { i64, i64 } undef, i64 %t$1, 0
  %t$9$r1 = insertvalue { i64, i64 } %t$9$r0, i64 %t$8, 1
  ret { i64, i64 } %t$9$r1
wrepack_next_6:
  call void @sprout_abort_match()
  unreachable
}

define void @__sprout_init_globals() {
entry:
  %t$0 = add i64 0, 27
  %t$1 = call i64 @char_to_str(i64 %t$0)
  store i64 %t$1, ptr @stdlib.terminal.esc
  call i64 @sprout_gc_register_i64_root(ptr @stdlib.terminal.esc)
  ret void
}

define i32 @main(i32 %argc, ptr %argv) {
entry:
  %argv_set = call i64 @sprout_set_argv(i32 %argc, ptr %argv)
  %cname_ptr_0 = getelementptr inbounds [8 x i8], ptr @.cname.0, i64 0, i64 0
  %cfkinds_ptr_0 = getelementptr inbounds [1 x i8], ptr @.cfkinds.0, i64 0, i64 0
  %creg_0 = call i64 @sprout_register_ctor(i64 0, ptr %cname_ptr_0, i64 0, ptr %cfkinds_ptr_0)
  %cname_ptr_1 = getelementptr inbounds [5 x i8], ptr @.cname.1, i64 0, i64 0
  %cfkinds_ptr_1 = getelementptr inbounds [2 x i8], ptr @.cfkinds.1, i64 0, i64 0
  %creg_1 = call i64 @sprout_register_ctor(i64 1, ptr %cname_ptr_1, i64 1, ptr %cfkinds_ptr_1)
  %cname_ptr_2 = getelementptr inbounds [12 x i8], ptr @.cname.2, i64 0, i64 0
  %cfkinds_ptr_2 = getelementptr inbounds [2 x i8], ptr @.cfkinds.2, i64 0, i64 0
  %creg_2 = call i64 @sprout_register_ctor(i64 2, ptr %cname_ptr_2, i64 1, ptr %cfkinds_ptr_2)
  %cname_ptr_3 = getelementptr inbounds [15 x i8], ptr @.cname.3, i64 0, i64 0
  %cfkinds_ptr_3 = getelementptr inbounds [2 x i8], ptr @.cfkinds.3, i64 0, i64 0
  %creg_3 = call i64 @sprout_register_ctor(i64 3, ptr %cname_ptr_3, i64 1, ptr %cfkinds_ptr_3)
  %cname_ptr_4 = getelementptr inbounds [15 x i8], ptr @.cname.4, i64 0, i64 0
  %cfkinds_ptr_4 = getelementptr inbounds [2 x i8], ptr @.cfkinds.4, i64 0, i64 0
  %creg_4 = call i64 @sprout_register_ctor(i64 4, ptr %cname_ptr_4, i64 1, ptr %cfkinds_ptr_4)
  %cname_ptr_5 = getelementptr inbounds [4 x i8], ptr @.cname.5, i64 0, i64 0
  %cfkinds_ptr_5 = getelementptr inbounds [1 x i8], ptr @.cfkinds.5, i64 0, i64 0
  %creg_5 = call i64 @sprout_register_ctor(i64 5, ptr %cname_ptr_5, i64 0, ptr %cfkinds_ptr_5)
  %cname_ptr_6 = getelementptr inbounds [5 x i8], ptr @.cname.6, i64 0, i64 0
  %cfkinds_ptr_6 = getelementptr inbounds [3 x i8], ptr @.cfkinds.6, i64 0, i64 0
  %creg_6 = call i64 @sprout_register_ctor(i64 6, ptr %cname_ptr_6, i64 2, ptr %cfkinds_ptr_6)
  %cname_ptr_7 = getelementptr inbounds [3 x i8], ptr @.cname.7, i64 0, i64 0
  %cfkinds_ptr_7 = getelementptr inbounds [2 x i8], ptr @.cfkinds.7, i64 0, i64 0
  %creg_7 = call i64 @sprout_register_ctor(i64 7, ptr %cname_ptr_7, i64 1, ptr %cfkinds_ptr_7)
  %cname_ptr_8 = getelementptr inbounds [4 x i8], ptr @.cname.8, i64 0, i64 0
  %cfkinds_ptr_8 = getelementptr inbounds [2 x i8], ptr @.cfkinds.8, i64 0, i64 0
  %creg_8 = call i64 @sprout_register_ctor(i64 8, ptr %cname_ptr_8, i64 1, ptr %cfkinds_ptr_8)
  %cname_ptr_9 = getelementptr inbounds [10 x i8], ptr @.cname.9, i64 0, i64 0
  %cfkinds_ptr_9 = getelementptr inbounds [1 x i8], ptr @.cfkinds.9, i64 0, i64 0
  %creg_9 = call i64 @sprout_register_ctor(i64 9, ptr %cname_ptr_9, i64 0, ptr %cfkinds_ptr_9)
  %cname_ptr_10 = getelementptr inbounds [4 x i8], ptr @.cname.10, i64 0, i64 0
  %cfkinds_ptr_10 = getelementptr inbounds [2 x i8], ptr @.cfkinds.10, i64 0, i64 0
  %creg_10 = call i64 @sprout_register_ctor(i64 10, ptr %cname_ptr_10, i64 1, ptr %cfkinds_ptr_10)
  %cname_ptr_11 = getelementptr inbounds [5 x i8], ptr @.cname.11, i64 0, i64 0
  %cfkinds_ptr_11 = getelementptr inbounds [2 x i8], ptr @.cfkinds.11, i64 0, i64 0
  %creg_11 = call i64 @sprout_register_ctor(i64 11, ptr %cname_ptr_11, i64 1, ptr %cfkinds_ptr_11)
  %cname_ptr_12 = getelementptr inbounds [4 x i8], ptr @.cname.12, i64 0, i64 0
  %cfkinds_ptr_12 = getelementptr inbounds [2 x i8], ptr @.cfkinds.12, i64 0, i64 0
  %creg_12 = call i64 @sprout_register_ctor(i64 12, ptr %cname_ptr_12, i64 1, ptr %cfkinds_ptr_12)
  %cname_ptr_13 = getelementptr inbounds [9 x i8], ptr @.cname.13, i64 0, i64 0
  %cfkinds_ptr_13 = getelementptr inbounds [4 x i8], ptr @.cfkinds.13, i64 0, i64 0
  %creg_13 = call i64 @sprout_register_ctor(i64 13, ptr %cname_ptr_13, i64 3, ptr %cfkinds_ptr_13)
  %cname_ptr_14 = getelementptr inbounds [29 x i8], ptr @.cname.14, i64 0, i64 0
  %cfkinds_ptr_14 = getelementptr inbounds [2 x i8], ptr @.cfkinds.14, i64 0, i64 0
  %creg_14 = call i64 @sprout_register_ctor(i64 14, ptr %cname_ptr_14, i64 1, ptr %cfkinds_ptr_14)
  %cname_ptr_15 = getelementptr inbounds [30 x i8], ptr @.cname.15, i64 0, i64 0
  %cfkinds_ptr_15 = getelementptr inbounds [2 x i8], ptr @.cfkinds.15, i64 0, i64 0
  %creg_15 = call i64 @sprout_register_ctor(i64 15, ptr %cname_ptr_15, i64 1, ptr %cfkinds_ptr_15)
  %cname_ptr_16 = getelementptr inbounds [28 x i8], ptr @.cname.16, i64 0, i64 0
  %cfkinds_ptr_16 = getelementptr inbounds [1 x i8], ptr @.cfkinds.16, i64 0, i64 0
  %creg_16 = call i64 @sprout_register_ctor(i64 16, ptr %cname_ptr_16, i64 0, ptr %cfkinds_ptr_16)
  %cname_ptr_17 = getelementptr inbounds [28 x i8], ptr @.cname.17, i64 0, i64 0
  %cfkinds_ptr_17 = getelementptr inbounds [2 x i8], ptr @.cfkinds.17, i64 0, i64 0
  %creg_17 = call i64 @sprout_register_ctor(i64 17, ptr %cname_ptr_17, i64 1, ptr %cfkinds_ptr_17)
  %cname_ptr_18 = getelementptr inbounds [25 x i8], ptr @.cname.18, i64 0, i64 0
  %cfkinds_ptr_18 = getelementptr inbounds [2 x i8], ptr @.cfkinds.18, i64 0, i64 0
  %creg_18 = call i64 @sprout_register_ctor(i64 18, ptr %cname_ptr_18, i64 1, ptr %cfkinds_ptr_18)
  %cname_ptr_19 = getelementptr inbounds [26 x i8], ptr @.cname.19, i64 0, i64 0
  %cfkinds_ptr_19 = getelementptr inbounds [2 x i8], ptr @.cfkinds.19, i64 0, i64 0
  %creg_19 = call i64 @sprout_register_ctor(i64 19, ptr %cname_ptr_19, i64 1, ptr %cfkinds_ptr_19)
  %cname_ptr_20 = getelementptr inbounds [26 x i8], ptr @.cname.20, i64 0, i64 0
  %cfkinds_ptr_20 = getelementptr inbounds [1 x i8], ptr @.cfkinds.20, i64 0, i64 0
  %creg_20 = call i64 @sprout_register_ctor(i64 20, ptr %cname_ptr_20, i64 0, ptr %cfkinds_ptr_20)
  %cname_ptr_21 = getelementptr inbounds [22 x i8], ptr @.cname.21, i64 0, i64 0
  %cfkinds_ptr_21 = getelementptr inbounds [1 x i8], ptr @.cfkinds.21, i64 0, i64 0
  %creg_21 = call i64 @sprout_register_ctor(i64 21, ptr %cname_ptr_21, i64 0, ptr %cfkinds_ptr_21)
  %cname_ptr_22 = getelementptr inbounds [25 x i8], ptr @.cname.22, i64 0, i64 0
  %cfkinds_ptr_22 = getelementptr inbounds [1 x i8], ptr @.cfkinds.22, i64 0, i64 0
  %creg_22 = call i64 @sprout_register_ctor(i64 22, ptr %cname_ptr_22, i64 0, ptr %cfkinds_ptr_22)
  %cname_ptr_23 = getelementptr inbounds [27 x i8], ptr @.cname.23, i64 0, i64 0
  %cfkinds_ptr_23 = getelementptr inbounds [2 x i8], ptr @.cfkinds.23, i64 0, i64 0
  %creg_23 = call i64 @sprout_register_ctor(i64 23, ptr %cname_ptr_23, i64 1, ptr %cfkinds_ptr_23)
  %cname_ptr_24 = getelementptr inbounds [25 x i8], ptr @.cname.24, i64 0, i64 0
  %cfkinds_ptr_24 = getelementptr inbounds [2 x i8], ptr @.cfkinds.24, i64 0, i64 0
  %creg_24 = call i64 @sprout_register_ctor(i64 24, ptr %cname_ptr_24, i64 1, ptr %cfkinds_ptr_24)
  %cname_ptr_25 = getelementptr inbounds [23 x i8], ptr @.cname.25, i64 0, i64 0
  %cfkinds_ptr_25 = getelementptr inbounds [2 x i8], ptr @.cfkinds.25, i64 0, i64 0
  %creg_25 = call i64 @sprout_register_ctor(i64 25, ptr %cname_ptr_25, i64 1, ptr %cfkinds_ptr_25)
  call void @__sprout_init_globals()
  call i64 @__sprout_user_main()
  ret i32 0
}

