; Generated by sprout ir_lowering.sprout (M2 PR 2.3)
target triple = "unknown-unknown-unknown"
declare i64 @str_concat(i64, i64)
declare i1 @str_eq(ptr, ptr)
declare i64 @str_compare(i64, i64)
declare i64 @str_slice(i64, i64, i64)
declare i64 @int_to_string(i64)
declare i64 @char_to_string(i64)
declare i64 @sprout_gc_push_i64_root(ptr)
declare i64 @sprout_gc_pop_roots(i64)
declare i64 @sprout_gc_register_i64_root(ptr)
declare i64 @sprout_alloc_closure(i64, i64)
declare void @sprout_closure_arity_check(i64, i64)
declare i64 @sprout_alloc_tuple_blob(i64)
declare i64 @sprout_register_ctor(i64, ptr, i64, ptr)
declare i64 @sprout_tag(i64)
declare i64 @sprout_field(i64, i64)
declare void @sprout_abort_match() noreturn
declare i64 @panic(i64)
declare ptr @llvm.stacksave()
declare void @llvm.stackrestore(ptr)
declare i64 @sprout_alloc_obj(i64, i64)
declare { i64, i64 } @vector_get_unboxed(i64, i64)
declare { i64, i64 } @map_get_unboxed(i64, i64)
declare { i64, i64 } @map_nth_key_unboxed(i64, i64)
declare { i64, i64 } @map_nth_value_unboxed(i64, i64)
declare { i64, i64 } @bytes_get_unboxed(i64, i64)
declare { i64, i64 } @str_char_at_unboxed(i64, i64)
declare { i64, i64 } @argv_get_unboxed(i64)
declare { i64, i64 } @env_get_unboxed(i64)
declare i64 @print_str(ptr)
declare i64 @print_value(i64)
declare i64 @eprint_str(ptr)
declare i64 @argv_get(i64)
declare i64 @sprout_set_argv(i32, ptr)
declare i64 @analysis_check_source(ptr)
declare i64 @analysis_declared_names_in_source(ptr)
declare i64 @analysis_exported_names_in_source(ptr)
declare i64 @analysis_symbol_inventory_in_source(ptr)
declare i64 @analysis_diagnostics_in_source(ptr)
declare i64 @analysis_symbol_locations_in_source(ptr)
declare i64 @analysis_type_of_in_source(ptr, ptr)
declare i64 @analysis_eval_expr_in_source(ptr, ptr)
declare i64 @analysis_instances_in_source(ptr, ptr)
declare i64 @analysis_complete_in_state(ptr, ptr, ptr)

declare i64 @double_to_string(i64)
declare i64 @char_to_str(i64)
declare i64 @char_from_codepoint(i64)
declare i64 @to_double(i64)
declare i64 @string_concat_many(i64)
declare i64 @str_len(i64)
declare i64 @str_char_at(i64, i64)
declare i64 @str_find(i64, i64)
declare i64 @str_starts_with(i64, i64)
declare i64 @vector_empty()
declare i64 @vector_length(i64)
declare i64 @vector_get(i64, i64)
declare i64 @vector_set(i64, i64, i64)
declare i64 @vector_append(i64, i64)
declare i64 @vector_concat(i64, i64)
declare i64 @vector_from_list(i64)
declare i64 @map_empty()
declare i64 @map_get(i64, i64)
declare i64 @map_set(i64, i64, i64)
declare i64 @map_remove(i64, i64)
declare i64 @map_size(i64)
declare i64 @map_nth_key(i64, i64)
declare i64 @map_nth_value(i64, i64)
declare i64 @native_set_empty()
declare i64 @native_set_insert(i64, i64)
declare i64 @native_set_member(i64, i64)
declare i64 @native_set_to_list(i64)
declare i64 @native_set_size(i64)
declare i64 @ref_new(i64)
declare i64 @ref_read(i64)
declare i64 @ref_write(i64, i64)
declare i64 @__scope_open()
declare i64 @__scope_join(i64)
declare i64 @__scope_spawn(i64, i64)
declare i64 @__task_fork(i64, i64)
declare i64 @__task_await(i64)
declare i64 @__scope_cancel(i64)
declare i64 @__task_sleep(i64)
declare i64 @__await_deadline(i64, i64, i64)
declare i64 @__task_stop_reason()
declare i64 @task_yield()
declare i64 @bytes_empty()
declare i64 @bytes_singleton(i64)
declare i64 @bytes_length(i64)
declare i64 @bytes_get(i64, i64)
declare i64 @bytes_slice(i64, i64, i64)
declare i64 @bytes_append(i64, i64)
declare i64 @bytes_from_utf8(i64)
declare i64 @bytes_to_utf8(i64)
declare i64 @bytes_builder_empty()
declare i64 @bytes_builder_bytes(i64)
declare i64 @bytes_builder_byte(i64)
declare i64 @bytes_builder_u16_be(i64)
declare i64 @bytes_builder_u32_be(i64)
declare i64 @bytes_builder_append(i64, i64)
declare i64 @bytes_builder_build(i64)
declare i64 @str_byte_len(i64)
declare i64 @str_slice_bytes(i64, i64, i64)
declare i64 @str_starts_with_at_byte(i64, i64, i64)
declare i64 @str_split_lines(i64)
declare i64 @split_words(i64)
@.str.0 = private unnamed_addr constant { i64, [8 x i8] } { i64 114698, [8 x i8] c" step 1\00" }
@.str.1 = private unnamed_addr constant { i64, [8 x i8] } { i64 114698, [8 x i8] c" step 2\00" }
@.str.2 = private unnamed_addr constant { i64, [8 x i8] } { i64 114698, [8 x i8] c" step 3\00" }
@.str.3 = private unnamed_addr constant { i64, [6 x i8] } { i64 81930, [6 x i8] c"alice\00" }
@.str.4 = private unnamed_addr constant { i64, [4 x i8] } { i64 49162, [4 x i8] c"bob\00" }
@.str.5 = private unnamed_addr constant { i64, [15 x i8] } { i64 229386, [15 x i8] c"scope: opening\00" }
@.str.6 = private unnamed_addr constant { i64, [24 x i8] } { i64 376842, [24 x i8] c"scope: all tasks joined\00" }
@.cname.0 = private unnamed_addr constant [8 x i8] c"Nothing\00"
@.cfkinds.0 = private unnamed_addr constant [1 x i8] c"\00"
@.cname.1 = private unnamed_addr constant [5 x i8] c"Just\00"
@.cfkinds.1 = private unnamed_addr constant [2 x i8] c"_\00"
@.cname.2 = private unnamed_addr constant [12 x i8] c"TemplateLit\00"
@.cfkinds.2 = private unnamed_addr constant [2 x i8] c"s\00"
@.cname.3 = private unnamed_addr constant [15 x i8] c"TemplateInterp\00"
@.cfkinds.3 = private unnamed_addr constant [2 x i8] c"s\00"
@.cname.4 = private unnamed_addr constant [15 x i8] c"StringTemplate\00"
@.cfkinds.4 = private unnamed_addr constant [2 x i8] c"p\00"
@.cname.5 = private unnamed_addr constant [4 x i8] c"Nil\00"
@.cfkinds.5 = private unnamed_addr constant [1 x i8] c"\00"
@.cname.6 = private unnamed_addr constant [5 x i8] c"Cons\00"
@.cfkinds.6 = private unnamed_addr constant [3 x i8] c"_p\00"
@.cname.7 = private unnamed_addr constant [3 x i8] c"Ok\00"
@.cfkinds.7 = private unnamed_addr constant [2 x i8] c"_\00"
@.cname.8 = private unnamed_addr constant [4 x i8] c"Err\00"
@.cfkinds.8 = private unnamed_addr constant [2 x i8] c"_\00"
@.cname.9 = private unnamed_addr constant [10 x i8] c"DivByZero\00"
@.cfkinds.9 = private unnamed_addr constant [1 x i8] c"\00"
@.cname.10 = private unnamed_addr constant [4 x i8] c"Vec\00"
@.cfkinds.10 = private unnamed_addr constant [2 x i8] c"p\00"
@.cname.11 = private unnamed_addr constant [5 x i8] c"Dict\00"
@.cfkinds.11 = private unnamed_addr constant [2 x i8] c"p\00"
@.cname.12 = private unnamed_addr constant [4 x i8] c"Set\00"
@.cfkinds.12 = private unnamed_addr constant [2 x i8] c"p\00"
@.cname.13 = private unnamed_addr constant [9 x i8] c"IntRange\00"
@.cfkinds.13 = private unnamed_addr constant [4 x i8] c"iii\00"
@.cname.14 = private unnamed_addr constant [18 x i8] c"stdlib.task.Scope\00"
@.cfkinds.14 = private unnamed_addr constant [2 x i8] c"i\00"
@.cname.15 = private unnamed_addr constant [17 x i8] c"stdlib.task.Task\00"
@.cfkinds.15 = private unnamed_addr constant [2 x i8] c"i\00"
@.cname.16 = private unnamed_addr constant [22 x i8] c"stdlib.task.Completed\00"
@.cfkinds.16 = private unnamed_addr constant [2 x i8] c"_\00"
@.cname.17 = private unnamed_addr constant [20 x i8] c"stdlib.task.Expired\00"
@.cfkinds.17 = private unnamed_addr constant [1 x i8] c"\00"
@.cname.18 = private unnamed_addr constant [20 x i8] c"stdlib.task.Running\00"
@.cfkinds.18 = private unnamed_addr constant [1 x i8] c"\00"
@.cname.19 = private unnamed_addr constant [22 x i8] c"stdlib.task.Cancelled\00"
@.cfkinds.19 = private unnamed_addr constant [1 x i8] c"\00"
@.cname.20 = private unnamed_addr constant [21 x i8] c"stdlib.task.TimedOut\00"
@.cfkinds.20 = private unnamed_addr constant [1 x i8] c"\00"
@.cname.21 = private unnamed_addr constant [29 x i8] c"stdlib.bytes.Utf8DecodeError\00"
@.cfkinds.21 = private unnamed_addr constant [2 x i8] c"s\00"

define i64 @stdlib.task.with_scope(i64 %body) {
entry:
  %t$4 = alloca i64
  store i64 %body, ptr %t$4
  %t$5 = call i64 @sprout_gc_push_i64_root(ptr %t$4)
  %t$0 = call i64 @__scope_open()
  %t$1 = call i64 @sprout_alloc_obj(i64 14, i64 1)
  %t$1$ptr = inttoptr i64 %t$1 to ptr
  %t$1$f0 = getelementptr i64, ptr %t$1$ptr, i64 0
  store i64 %t$0, ptr %t$1$f0
  call void @sprout_closure_arity_check(i64 %body, i64 1)
  %t$2$env_ptr = inttoptr i64 %body to ptr
  %t$2$code = load ptr, ptr %t$2$env_ptr
  %t$2 = call i64 (i64, i64) %t$2$code(i64 %body, i64 %t$1)
  %t$6 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$7 = alloca i64
  store i64 %t$2, ptr %t$7
  %t$8 = call i64 @sprout_gc_push_i64_root(ptr %t$7)
  %t$3 = call i64 @__scope_join(i64 %t$0)
  %t$9 = call i64 @sprout_gc_pop_roots(i64 1)
  ret i64 %t$2
}

define i64 @stdlib.task.task_spawn(i64 %scope, i64 %work) {
entry:
  %t$0 = call i64 @sprout_tag(i64 %scope)
  br label %arm_0_1
arm_0_1:
  %t$3 = add i64 0, 14
  %t$4 = icmp eq i64 %t$0, %t$3
  br i1 %t$4, label %body_0_1, label %arm_1_1
body_0_1:
  %t$5 = call i64 @sprout_field(i64 %scope, i64 0)
  %t$7 = alloca i64
  store i64 %work, ptr %t$7
  %t$8 = call i64 @sprout_gc_push_i64_root(ptr %t$7)
  %t$6 = call i64 @__scope_spawn(i64 %t$5, i64 %work)
  %t$9 = call i64 @sprout_gc_pop_roots(i64 1)
  br label %join_1
arm_1_1:
  call void @sprout_abort_match()
  unreachable
join_1:
  %t$2 = phi i64 [%t$6, %body_0_1]
  ret i64 %t$2
}

define i64 @stdlib.string.concat(i64 %left, i64 %right) {
entry:
  %t$0 = call i64 @str_concat(i64 %left, i64 %right)
  ret i64 %t$0
}

define i64 @$entry.worker(i64 %name) {
entry:
  %t$0 = getelementptr inbounds { i64, [8 x i8] }, ptr @.str.0, i64 0, i32 1, i64 0
  %t$1 = ptrtoint ptr %t$0 to i64
  %t$14 = alloca i64
  store i64 %name, ptr %t$14
  %t$15 = call i64 @sprout_gc_push_i64_root(ptr %t$14)
  %t$16 = alloca i64
  store i64 %t$1, ptr %t$16
  %t$17 = call i64 @sprout_gc_push_i64_root(ptr %t$16)
  %t$2 = call i64 @stdlib.string.concat(i64 %name, i64 %t$1)
  %t$18 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$3$ptr = inttoptr i64 %t$2 to ptr
  %t$3 = call i64 @print_str(ptr %t$3$ptr)
  %t$4 = call i64 @task_yield()
  %t$5 = getelementptr inbounds { i64, [8 x i8] }, ptr @.str.1, i64 0, i32 1, i64 0
  %t$6 = ptrtoint ptr %t$5 to i64
  %t$19 = alloca i64
  store i64 %t$6, ptr %t$19
  %t$20 = call i64 @sprout_gc_push_i64_root(ptr %t$19)
  %t$7 = call i64 @stdlib.string.concat(i64 %name, i64 %t$6)
  %t$21 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$8$ptr = inttoptr i64 %t$7 to ptr
  %t$8 = call i64 @print_str(ptr %t$8$ptr)
  %t$9 = call i64 @task_yield()
  %t$10 = getelementptr inbounds { i64, [8 x i8] }, ptr @.str.2, i64 0, i32 1, i64 0
  %t$11 = ptrtoint ptr %t$10 to i64
  %t$22 = alloca i64
  store i64 %t$11, ptr %t$22
  %t$23 = call i64 @sprout_gc_push_i64_root(ptr %t$22)
  %t$12 = call i64 @stdlib.string.concat(i64 %name, i64 %t$11)
  %t$24 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$13$ptr = inttoptr i64 %t$12 to ptr
  %t$13 = call i64 @print_str(ptr %t$13$ptr)
  ret i64 %t$13
}

define i64 @__sprout_ir_lambda_0(i64 %env$, i64 %_) {
entry:
  %t$0 = getelementptr inbounds { i64, [6 x i8] }, ptr @.str.3, i64 0, i32 1, i64 0
  %t$1 = ptrtoint ptr %t$0 to i64
  %t$3 = alloca i64
  store i64 %t$1, ptr %t$3
  %t$4 = call i64 @sprout_gc_push_i64_root(ptr %t$3)
  %t$2 = call i64 @$entry.worker(i64 %t$1)
  %t$5 = call i64 @sprout_gc_pop_roots(i64 1)
  ret i64 %t$2
}

define i64 @__sprout_ir_lambda_1(i64 %env$, i64 %_) {
entry:
  %t$0 = getelementptr inbounds { i64, [4 x i8] }, ptr @.str.4, i64 0, i32 1, i64 0
  %t$1 = ptrtoint ptr %t$0 to i64
  %t$3 = alloca i64
  store i64 %t$1, ptr %t$3
  %t$4 = call i64 @sprout_gc_push_i64_root(ptr %t$3)
  %t$2 = call i64 @$entry.worker(i64 %t$1)
  %t$5 = call i64 @sprout_gc_pop_roots(i64 1)
  ret i64 %t$2
}

define i64 @$entry.spawn_workers(i64 %s) {
entry:
  %t$4 = alloca i64
  store i64 %s, ptr %t$4
  %t$5 = call i64 @sprout_gc_push_i64_root(ptr %t$4)
  %t$0 = call i64 @sprout_alloc_closure(i64 8, i64 1)
  %t$0$raw = inttoptr i64 %t$0 to ptr
  store ptr @__sprout_ir_lambda_0, ptr %t$0$raw
  %t$6 = alloca i64
  store i64 %t$0, ptr %t$6
  %t$7 = call i64 @sprout_gc_push_i64_root(ptr %t$6)
  %t$1 = call i64 @stdlib.task.task_spawn(i64 %s, i64 %t$0)
  %t$8 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$2 = call i64 @sprout_alloc_closure(i64 8, i64 1)
  %t$2$raw = inttoptr i64 %t$2 to ptr
  store ptr @__sprout_ir_lambda_1, ptr %t$2$raw
  %t$9 = alloca i64
  store i64 %t$2, ptr %t$9
  %t$10 = call i64 @sprout_gc_push_i64_root(ptr %t$9)
  %t$3 = call i64 @stdlib.task.task_spawn(i64 %s, i64 %t$2)
  %t$11 = call i64 @sprout_gc_pop_roots(i64 2)
  ret i64 %t$3
}

define i64 @__sprout_ir_lambda_2(i64 %env$, i64 %s) {
entry:
  %t$1 = alloca i64
  store i64 %s, ptr %t$1
  %t$2 = call i64 @sprout_gc_push_i64_root(ptr %t$1)
  %t$0 = call i64 @$entry.spawn_workers(i64 %s)
  %t$3 = call i64 @sprout_gc_pop_roots(i64 1)
  ret i64 %t$0
}

define i64 @__sprout_user_main() {
entry:
  %t$0 = getelementptr inbounds { i64, [15 x i8] }, ptr @.str.5, i64 0, i32 1, i64 0
  %t$1 = ptrtoint ptr %t$0 to i64
  %t$2$ptr = inttoptr i64 %t$1 to ptr
  %t$2 = call i64 @print_str(ptr %t$2$ptr)
  %t$3 = call i64 @sprout_alloc_closure(i64 8, i64 1)
  %t$3$raw = inttoptr i64 %t$3 to ptr
  store ptr @__sprout_ir_lambda_2, ptr %t$3$raw
  %t$8 = alloca i64
  store i64 %t$3, ptr %t$8
  %t$9 = call i64 @sprout_gc_push_i64_root(ptr %t$8)
  %t$4 = call i64 @stdlib.task.with_scope(i64 %t$3)
  %t$10 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$5 = getelementptr inbounds { i64, [24 x i8] }, ptr @.str.6, i64 0, i32 1, i64 0
  %t$6 = ptrtoint ptr %t$5 to i64
  %t$7$ptr = inttoptr i64 %t$6 to ptr
  %t$7 = call i64 @print_str(ptr %t$7$ptr)
  ret i64 %t$7
}

define i32 @main(i32 %argc, ptr %argv) {
entry:
  %argv_set = call i64 @sprout_set_argv(i32 %argc, ptr %argv)
  %cname_ptr_0 = getelementptr inbounds [8 x i8], ptr @.cname.0, i64 0, i64 0
  %cfkinds_ptr_0 = getelementptr inbounds [1 x i8], ptr @.cfkinds.0, i64 0, i64 0
  %creg_0 = call i64 @sprout_register_ctor(i64 0, ptr %cname_ptr_0, i64 0, ptr %cfkinds_ptr_0)
  %cname_ptr_1 = getelementptr inbounds [5 x i8], ptr @.cname.1, i64 0, i64 0
  %cfkinds_ptr_1 = getelementptr inbounds [2 x i8], ptr @.cfkinds.1, i64 0, i64 0
  %creg_1 = call i64 @sprout_register_ctor(i64 1, ptr %cname_ptr_1, i64 1, ptr %cfkinds_ptr_1)
  %cname_ptr_2 = getelementptr inbounds [12 x i8], ptr @.cname.2, i64 0, i64 0
  %cfkinds_ptr_2 = getelementptr inbounds [2 x i8], ptr @.cfkinds.2, i64 0, i64 0
  %creg_2 = call i64 @sprout_register_ctor(i64 2, ptr %cname_ptr_2, i64 1, ptr %cfkinds_ptr_2)
  %cname_ptr_3 = getelementptr inbounds [15 x i8], ptr @.cname.3, i64 0, i64 0
  %cfkinds_ptr_3 = getelementptr inbounds [2 x i8], ptr @.cfkinds.3, i64 0, i64 0
  %creg_3 = call i64 @sprout_register_ctor(i64 3, ptr %cname_ptr_3, i64 1, ptr %cfkinds_ptr_3)
  %cname_ptr_4 = getelementptr inbounds [15 x i8], ptr @.cname.4, i64 0, i64 0
  %cfkinds_ptr_4 = getelementptr inbounds [2 x i8], ptr @.cfkinds.4, i64 0, i64 0
  %creg_4 = call i64 @sprout_register_ctor(i64 4, ptr %cname_ptr_4, i64 1, ptr %cfkinds_ptr_4)
  %cname_ptr_5 = getelementptr inbounds [4 x i8], ptr @.cname.5, i64 0, i64 0
  %cfkinds_ptr_5 = getelementptr inbounds [1 x i8], ptr @.cfkinds.5, i64 0, i64 0
  %creg_5 = call i64 @sprout_register_ctor(i64 5, ptr %cname_ptr_5, i64 0, ptr %cfkinds_ptr_5)
  %cname_ptr_6 = getelementptr inbounds [5 x i8], ptr @.cname.6, i64 0, i64 0
  %cfkinds_ptr_6 = getelementptr inbounds [3 x i8], ptr @.cfkinds.6, i64 0, i64 0
  %creg_6 = call i64 @sprout_register_ctor(i64 6, ptr %cname_ptr_6, i64 2, ptr %cfkinds_ptr_6)
  %cname_ptr_7 = getelementptr inbounds [3 x i8], ptr @.cname.7, i64 0, i64 0
  %cfkinds_ptr_7 = getelementptr inbounds [2 x i8], ptr @.cfkinds.7, i64 0, i64 0
  %creg_7 = call i64 @sprout_register_ctor(i64 7, ptr %cname_ptr_7, i64 1, ptr %cfkinds_ptr_7)
  %cname_ptr_8 = getelementptr inbounds [4 x i8], ptr @.cname.8, i64 0, i64 0
  %cfkinds_ptr_8 = getelementptr inbounds [2 x i8], ptr @.cfkinds.8, i64 0, i64 0
  %creg_8 = call i64 @sprout_register_ctor(i64 8, ptr %cname_ptr_8, i64 1, ptr %cfkinds_ptr_8)
  %cname_ptr_9 = getelementptr inbounds [10 x i8], ptr @.cname.9, i64 0, i64 0
  %cfkinds_ptr_9 = getelementptr inbounds [1 x i8], ptr @.cfkinds.9, i64 0, i64 0
  %creg_9 = call i64 @sprout_register_ctor(i64 9, ptr %cname_ptr_9, i64 0, ptr %cfkinds_ptr_9)
  %cname_ptr_10 = getelementptr inbounds [4 x i8], ptr @.cname.10, i64 0, i64 0
  %cfkinds_ptr_10 = getelementptr inbounds [2 x i8], ptr @.cfkinds.10, i64 0, i64 0
  %creg_10 = call i64 @sprout_register_ctor(i64 10, ptr %cname_ptr_10, i64 1, ptr %cfkinds_ptr_10)
  %cname_ptr_11 = getelementptr inbounds [5 x i8], ptr @.cname.11, i64 0, i64 0
  %cfkinds_ptr_11 = getelementptr inbounds [2 x i8], ptr @.cfkinds.11, i64 0, i64 0
  %creg_11 = call i64 @sprout_register_ctor(i64 11, ptr %cname_ptr_11, i64 1, ptr %cfkinds_ptr_11)
  %cname_ptr_12 = getelementptr inbounds [4 x i8], ptr @.cname.12, i64 0, i64 0
  %cfkinds_ptr_12 = getelementptr inbounds [2 x i8], ptr @.cfkinds.12, i64 0, i64 0
  %creg_12 = call i64 @sprout_register_ctor(i64 12, ptr %cname_ptr_12, i64 1, ptr %cfkinds_ptr_12)
  %cname_ptr_13 = getelementptr inbounds [9 x i8], ptr @.cname.13, i64 0, i64 0
  %cfkinds_ptr_13 = getelementptr inbounds [4 x i8], ptr @.cfkinds.13, i64 0, i64 0
  %creg_13 = call i64 @sprout_register_ctor(i64 13, ptr %cname_ptr_13, i64 3, ptr %cfkinds_ptr_13)
  %cname_ptr_14 = getelementptr inbounds [18 x i8], ptr @.cname.14, i64 0, i64 0
  %cfkinds_ptr_14 = getelementptr inbounds [2 x i8], ptr @.cfkinds.14, i64 0, i64 0
  %creg_14 = call i64 @sprout_register_ctor(i64 14, ptr %cname_ptr_14, i64 1, ptr %cfkinds_ptr_14)
  %cname_ptr_15 = getelementptr inbounds [17 x i8], ptr @.cname.15, i64 0, i64 0
  %cfkinds_ptr_15 = getelementptr inbounds [2 x i8], ptr @.cfkinds.15, i64 0, i64 0
  %creg_15 = call i64 @sprout_register_ctor(i64 15, ptr %cname_ptr_15, i64 1, ptr %cfkinds_ptr_15)
  %cname_ptr_16 = getelementptr inbounds [22 x i8], ptr @.cname.16, i64 0, i64 0
  %cfkinds_ptr_16 = getelementptr inbounds [2 x i8], ptr @.cfkinds.16, i64 0, i64 0
  %creg_16 = call i64 @sprout_register_ctor(i64 16, ptr %cname_ptr_16, i64 1, ptr %cfkinds_ptr_16)
  %cname_ptr_17 = getelementptr inbounds [20 x i8], ptr @.cname.17, i64 0, i64 0
  %cfkinds_ptr_17 = getelementptr inbounds [1 x i8], ptr @.cfkinds.17, i64 0, i64 0
  %creg_17 = call i64 @sprout_register_ctor(i64 17, ptr %cname_ptr_17, i64 0, ptr %cfkinds_ptr_17)
  %cname_ptr_18 = getelementptr inbounds [20 x i8], ptr @.cname.18, i64 0, i64 0
  %cfkinds_ptr_18 = getelementptr inbounds [1 x i8], ptr @.cfkinds.18, i64 0, i64 0
  %creg_18 = call i64 @sprout_register_ctor(i64 18, ptr %cname_ptr_18, i64 0, ptr %cfkinds_ptr_18)
  %cname_ptr_19 = getelementptr inbounds [22 x i8], ptr @.cname.19, i64 0, i64 0
  %cfkinds_ptr_19 = getelementptr inbounds [1 x i8], ptr @.cfkinds.19, i64 0, i64 0
  %creg_19 = call i64 @sprout_register_ctor(i64 19, ptr %cname_ptr_19, i64 0, ptr %cfkinds_ptr_19)
  %cname_ptr_20 = getelementptr inbounds [21 x i8], ptr @.cname.20, i64 0, i64 0
  %cfkinds_ptr_20 = getelementptr inbounds [1 x i8], ptr @.cfkinds.20, i64 0, i64 0
  %creg_20 = call i64 @sprout_register_ctor(i64 20, ptr %cname_ptr_20, i64 0, ptr %cfkinds_ptr_20)
  %cname_ptr_21 = getelementptr inbounds [29 x i8], ptr @.cname.21, i64 0, i64 0
  %cfkinds_ptr_21 = getelementptr inbounds [2 x i8], ptr @.cfkinds.21, i64 0, i64 0
  %creg_21 = call i64 @sprout_register_ctor(i64 21, ptr %cname_ptr_21, i64 1, ptr %cfkinds_ptr_21)
  call i64 @__sprout_user_main()
  ret i32 0
}

