; Generated by sprout ir_lowering.sprout (M2 PR 2.3)
target triple = "unknown-unknown-unknown"
declare i64 @str_concat(i64, i64)
declare i1 @str_eq(ptr, ptr)
declare i64 @str_compare(i64, i64)
declare i64 @str_slice(i64, i64, i64)
declare i64 @int_to_string(i64)
declare i64 @char_to_string(i64)
declare i64 @sprout_gc_push_i64_root(ptr)
declare i64 @sprout_gc_pop_roots(i64)
declare i64 @sprout_gc_register_i64_root(ptr)
declare i64 @sprout_alloc_closure_env(i64)
declare i64 @sprout_alloc_tuple_blob(i64)
declare i64 @sprout_register_ctor(i64, ptr, i64, ptr)
declare i64 @sprout_tag(i64)
declare i64 @sprout_field(i64, i64)
declare void @sprout_abort_match() noreturn
declare i64 @panic(i64)
declare ptr @llvm.stacksave()
declare void @llvm.stackrestore(ptr)
declare i64 @sprout_make0(i64)
declare i64 @sprout_make1(i64, i64)
declare i64 @sprout_make2(i64, i64, i64)
declare i64 @sprout_make3(i64, i64, i64, i64)
declare i64 @sprout_make4(i64, i64, i64, i64, i64)
declare i64 @sprout_make5(i64, i64, i64, i64, i64, i64)
declare i64 @sprout_make6(i64, i64, i64, i64, i64, i64, i64)
declare i64 @sprout_make7(i64, i64, i64, i64, i64, i64, i64, i64)
declare i64 @sprout_make8(i64, i64, i64, i64, i64, i64, i64, i64, i64)
declare i64 @sprout_make9(i64, i64, i64, i64, i64, i64, i64, i64, i64, i64)
declare i64 @sprout_make10(i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64)
declare { i64, i64 } @vector_get_unboxed(i64, i64)
declare { i64, i64 } @map_get_unboxed(i64, i64)
declare { i64, i64 } @map_nth_key_unboxed(i64, i64)
declare { i64, i64 } @map_nth_value_unboxed(i64, i64)
declare { i64, i64 } @bytes_get_unboxed(i64, i64)
declare { i64, i64 } @str_char_at_unboxed(i64, i64)
declare { i64, i64 } @regex_find_range_unboxed(i64, i64)
declare { i64, i64 } @argv_get_unboxed(i64)
declare { i64, i64 } @env_get_unboxed(i64)
declare { i64, i64 } @term_read_line_unboxed()
declare i64 @print_str(ptr)
declare i64 @print_value(i64)
declare i64 @eprint_str(ptr)
declare i64 @argv_get(i64)
declare i64 @sprout_set_argv(i32, ptr)
declare i64 @int_range(i64, i64)
declare i64 @analysis_check_source(ptr)
declare i64 @analysis_declared_names_in_source(ptr)
declare i64 @analysis_exported_names_in_source(ptr)
declare i64 @analysis_symbol_inventory_in_source(ptr)
declare i64 @analysis_diagnostics_in_source(ptr)
declare i64 @analysis_symbol_locations_in_source(ptr)
declare i64 @analysis_type_of_in_source(ptr, ptr)
declare i64 @analysis_eval_expr_in_source(ptr, ptr)
declare i64 @analysis_instances_in_source(ptr, ptr)
declare i64 @analysis_complete_in_state(ptr, ptr, ptr)

define i64 @fact(i64 %n) {
entry:
  %t$0 = add i64 0, 0
  %t$1 = icmp eq i64 %n, %t$0
  %t$2 = zext i1 %t$1 to i64
  %t$10 = trunc i64 %t$2 to i1
  br i1 %t$10, label %then_3, label %else_3
then_3:
  %t$5 = add i64 0, 1
  br label %join_3
else_3:
  %t$6 = add i64 0, 1
  %t$7 = sub i64 %n, %t$6
  %t$8 = call i64 @fact(i64 %t$7)
  %t$9 = mul i64 %n, %t$8
  br label %join_3
join_3:
  %t$4 = phi i64 [%t$5, %then_3], [%t$9, %else_3]
  ret i64 %t$4
}

define i64 @__sprout_user_main() {
entry:
  %t$0 = add i64 0, 5
  %t$1 = call i64 @fact(i64 %t$0)
  %t$2 = call i64 @print_value(i64 %t$1)
  ret i64 %t$2
}

define i32 @main(i32 %argc, ptr %argv) {
entry:
  %argv_set = call i64 @sprout_set_argv(i32 %argc, ptr %argv)
  call i64 @__sprout_user_main()
  ret i32 0
}

