; Generated by sprout ir_lowering.sprout (M2 PR 2.3)
target triple = "unknown-unknown-unknown"
declare i64 @str_concat(i64, i64)
declare i1 @str_eq(ptr, ptr)
declare i64 @str_compare(i64, i64)
declare i64 @str_slice(i64, i64, i64)
declare i64 @int_to_string(i64)
declare i64 @char_to_string(i64)
declare i64 @sprout_gc_push_i64_root(ptr)
declare i64 @sprout_gc_pop_roots(i64)
declare i64 @sprout_alloc_closure_env(i64)
declare i64 @sprout_alloc_tuple_blob(i64)
declare i64 @sprout_register_ctor(i64, ptr, i64, ptr)
declare i64 @sprout_tag(i64)
declare i64 @sprout_field(i64, i64)
declare void @sprout_abort_match() noreturn
declare i64 @sprout_make0(i64)
declare i64 @sprout_make1(i64, i64)
declare i64 @sprout_make2(i64, i64, i64)
declare i64 @sprout_make3(i64, i64, i64, i64)
declare i64 @sprout_make4(i64, i64, i64, i64, i64)
declare i64 @sprout_make5(i64, i64, i64, i64, i64, i64)
declare i64 @sprout_make6(i64, i64, i64, i64, i64, i64, i64)
declare i64 @sprout_make7(i64, i64, i64, i64, i64, i64, i64, i64)
declare i64 @sprout_make8(i64, i64, i64, i64, i64, i64, i64, i64, i64)
declare i64 @sprout_make9(i64, i64, i64, i64, i64, i64, i64, i64, i64, i64)
declare i64 @print_str(ptr)
declare i64 @print_value(i64)
declare i64 @eprint_str(ptr)
declare i64 @argv_get(i64)
declare i64 @int_range(i64, i64)
declare i64 @analysis_check_source(ptr)
declare i64 @analysis_declared_names_in_source(ptr)
declare i64 @analysis_exported_names_in_source(ptr)
declare i64 @analysis_symbol_inventory_in_source(ptr)
declare i64 @analysis_diagnostics_in_source(ptr)
declare i64 @analysis_symbol_locations_in_source(ptr)
declare i64 @analysis_type_of_in_source(ptr, ptr)
declare i64 @analysis_eval_expr_in_source(ptr, ptr)
declare i64 @analysis_instances_in_source(ptr, ptr)
declare i64 @analysis_complete_in_state(ptr, ptr, ptr)

@.str.0 = private unnamed_addr constant [9 x i8] c"FizzBuzz\00"
@.str.1 = private unnamed_addr constant [5 x i8] c"Fizz\00"
@.str.2 = private unnamed_addr constant [5 x i8] c"Buzz\00"
@.str.3 = private unnamed_addr constant [7 x i8] c"Number\00"

define i64 @rem(i64 %n, i64 %m) {
entry:
  %t$0 = sdiv i64 %n, %m
  %t$1 = mul i64 %t$0, %m
  %t$2 = sub i64 %n, %t$1
  ret i64 %t$2
}

define i64 @fizzbuzz(i64 %n) {
entry:
  %t$0 = add i64 0, 15
  %t$1 = call i64 @rem(i64 %n, i64 %t$0)
  %t$2 = add i64 0, 0
  %t$3 = icmp eq i64 %t$1, %t$2
  %t$4 = zext i1 %t$3 to i64
  %t$31 = trunc i64 %t$4 to i1
  br i1 %t$31, label %then_5, label %else_5
then_5:
  %t$7 = getelementptr inbounds [9 x i8], ptr @.str.0, i64 0, i64 0
  %t$8 = ptrtoint ptr %t$7 to i64
  br label %join_5
else_5:
  %t$9 = add i64 0, 3
  %t$10 = call i64 @rem(i64 %n, i64 %t$9)
  %t$11 = add i64 0, 0
  %t$12 = icmp eq i64 %t$10, %t$11
  %t$13 = zext i1 %t$12 to i64
  %t$30 = trunc i64 %t$13 to i1
  br i1 %t$30, label %then_14, label %else_14
then_14:
  %t$16 = getelementptr inbounds [5 x i8], ptr @.str.1, i64 0, i64 0
  %t$17 = ptrtoint ptr %t$16 to i64
  br label %join_14
else_14:
  %t$18 = add i64 0, 5
  %t$19 = call i64 @rem(i64 %n, i64 %t$18)
  %t$20 = add i64 0, 0
  %t$21 = icmp eq i64 %t$19, %t$20
  %t$22 = zext i1 %t$21 to i64
  %t$29 = trunc i64 %t$22 to i1
  br i1 %t$29, label %then_23, label %else_23
then_23:
  %t$25 = getelementptr inbounds [5 x i8], ptr @.str.2, i64 0, i64 0
  %t$26 = ptrtoint ptr %t$25 to i64
  br label %join_23
else_23:
  %t$27 = getelementptr inbounds [7 x i8], ptr @.str.3, i64 0, i64 0
  %t$28 = ptrtoint ptr %t$27 to i64
  br label %join_23
join_23:
  %t$24 = phi i64 [%t$26, %then_23], [%t$28, %else_23]
  br label %join_14
join_14:
  %t$15 = phi i64 [%t$17, %then_14], [%t$24, %join_23]
  br label %join_5
join_5:
  %t$6 = phi i64 [%t$8, %then_5], [%t$15, %join_14]
  ret i64 %t$6
}

define i64 @__sprout_user_main() {
entry:
  %t$0 = add i64 0, 15
  %t$1 = call i64 @fizzbuzz(i64 %t$0)
  %t$2$ptr = inttoptr i64 %t$1 to ptr
  %t$2 = call i64 @print_str(ptr %t$2$ptr)
  ret i64 %t$2
}

define i32 @main(i32 %argc, ptr %argv) {
entry:
  call i64 @__sprout_user_main()
  ret i32 0
}

