; Generated by sprout ir_lowering.sprout (M2 PR 2.3)
target triple = "unknown-unknown-unknown"
declare i64 @str_concat(i64, i64)
declare i1 @str_eq(ptr, ptr)
declare i64 @str_compare(i64, i64)
declare i64 @str_slice(i64, i64, i64)
declare i64 @int_to_string(i64)
declare i64 @char_to_string(i64)
declare i64 @sprout_gc_push_i64_root(ptr)
declare i64 @sprout_gc_pop_roots(i64)
declare i64 @sprout_gc_register_i64_root(ptr)
declare i64 @sprout_alloc_closure(i64, i64)
declare void @sprout_closure_arity_check(i64, i64)
declare i64 @sprout_alloc_tuple_blob(i64)
declare i64 @sprout_register_ctor(i64, ptr, i64, ptr)
declare i64 @sprout_tag(i64)
declare i64 @sprout_field(i64, i64)
declare void @sprout_abort_match() noreturn
declare i64 @panic(i64)
declare ptr @llvm.stacksave()
declare void @llvm.stackrestore(ptr)
declare i64 @sprout_alloc_obj(i64, i64)
declare { i64, i64 } @vector_get_unboxed(i64, i64)
declare { i64, i64 } @map_get_unboxed(i64, i64)
declare { i64, i64 } @map_nth_key_unboxed(i64, i64)
declare { i64, i64 } @map_nth_value_unboxed(i64, i64)
declare { i64, i64 } @bytes_get_unboxed(i64, i64)
declare { i64, i64 } @str_char_at_unboxed(i64, i64)
declare { i64, i64 } @argv_get_unboxed(i64)
declare { i64, i64 } @env_get_unboxed(i64)
declare i64 @print_str(ptr)
declare i64 @print_value(i64)
declare i64 @eprint_str(ptr)
declare i64 @argv_get(i64)
declare i64 @sprout_set_argv(i32, ptr)
declare i64 @analysis_check_source(ptr)
declare i64 @analysis_declared_names_in_source(ptr)
declare i64 @analysis_exported_names_in_source(ptr)
declare i64 @analysis_symbol_inventory_in_source(ptr)
declare i64 @analysis_diagnostics_in_source(ptr)
declare i64 @analysis_symbol_locations_in_source(ptr)
declare i64 @analysis_type_of_in_source(ptr, ptr)
declare i64 @analysis_eval_expr_in_source(ptr, ptr)
declare i64 @analysis_instances_in_source(ptr, ptr)
declare i64 @analysis_complete_in_state(ptr, ptr, ptr)

declare i64 @double_to_string(i64)
declare i64 @char_to_str(i64)
declare i64 @char_from_codepoint(i64)
declare i64 @to_double(i64)
declare i64 @string_concat_many(i64)
declare i64 @str_len(i64)
declare i64 @str_char_at(i64, i64)
declare i64 @str_find(i64, i64)
declare i64 @str_starts_with(i64, i64)
declare i64 @vector_empty()
declare i64 @vector_length(i64)
declare i64 @vector_get(i64, i64)
declare i64 @vector_set(i64, i64, i64)
declare i64 @vector_append(i64, i64)
declare i64 @vector_concat(i64, i64)
declare i64 @vector_from_list(i64)
declare i64 @map_empty()
declare i64 @map_get(i64, i64)
declare i64 @map_set(i64, i64, i64)
declare i64 @map_remove(i64, i64)
declare i64 @map_size(i64)
declare i64 @map_nth_key(i64, i64)
declare i64 @map_nth_value(i64, i64)
declare i64 @native_set_empty()
declare i64 @native_set_insert(i64, i64)
declare i64 @native_set_member(i64, i64)
declare i64 @native_set_to_list(i64)
declare i64 @native_set_size(i64)
declare i64 @ref_new(i64)
declare i64 @ref_read(i64)
declare i64 @ref_write(i64, i64)
declare i64 @vec_make_filled(i64, i64)
declare i64 @vector_mutset(i64, i64, i64)
declare i64 @vector_get_direct(i64, i64)
declare i64 @vector_push(i64, i64)
@.str.0 = private unnamed_addr constant { i64, [17 x i8] } { i64 262154, [17 x i8] c"division by zero\00" }
@.str.1 = private unnamed_addr constant { i64, [7 x i8] } { i64 98314, [7 x i8] c"epoch \00" }
@.str.2 = private unnamed_addr constant { i64, [7 x i8] } { i64 98314, [7 x i8] c"  mse \00" }
@.str.3 = private unnamed_addr constant { i64, [34 x i8] } { i64 540682, [34 x i8] c"XOR predictions (expect 0 1 1 0):\00" }
@.cname.0 = private unnamed_addr constant [8 x i8] c"Nothing\00"
@.cfkinds.0 = private unnamed_addr constant [1 x i8] c"\00"
@.cname.1 = private unnamed_addr constant [5 x i8] c"Just\00"
@.cfkinds.1 = private unnamed_addr constant [2 x i8] c"_\00"
@.cname.2 = private unnamed_addr constant [12 x i8] c"TemplateLit\00"
@.cfkinds.2 = private unnamed_addr constant [2 x i8] c"s\00"
@.cname.3 = private unnamed_addr constant [15 x i8] c"TemplateInterp\00"
@.cfkinds.3 = private unnamed_addr constant [2 x i8] c"s\00"
@.cname.4 = private unnamed_addr constant [15 x i8] c"StringTemplate\00"
@.cfkinds.4 = private unnamed_addr constant [2 x i8] c"p\00"
@.cname.5 = private unnamed_addr constant [4 x i8] c"Nil\00"
@.cfkinds.5 = private unnamed_addr constant [1 x i8] c"\00"
@.cname.6 = private unnamed_addr constant [5 x i8] c"Cons\00"
@.cfkinds.6 = private unnamed_addr constant [3 x i8] c"_p\00"
@.cname.7 = private unnamed_addr constant [3 x i8] c"Ok\00"
@.cfkinds.7 = private unnamed_addr constant [2 x i8] c"_\00"
@.cname.8 = private unnamed_addr constant [4 x i8] c"Err\00"
@.cfkinds.8 = private unnamed_addr constant [2 x i8] c"_\00"
@.cname.9 = private unnamed_addr constant [10 x i8] c"DivByZero\00"
@.cfkinds.9 = private unnamed_addr constant [1 x i8] c"\00"
@.cname.10 = private unnamed_addr constant [4 x i8] c"Vec\00"
@.cfkinds.10 = private unnamed_addr constant [2 x i8] c"p\00"
@.cname.11 = private unnamed_addr constant [5 x i8] c"Dict\00"
@.cfkinds.11 = private unnamed_addr constant [2 x i8] c"p\00"
@.cname.12 = private unnamed_addr constant [4 x i8] c"Set\00"
@.cfkinds.12 = private unnamed_addr constant [2 x i8] c"p\00"
@.cname.13 = private unnamed_addr constant [9 x i8] c"IntRange\00"
@.cfkinds.13 = private unnamed_addr constant [4 x i8] c"iii\00"
@.cname.14 = private unnamed_addr constant [22 x i8] c"stdlib.mutable.MutVec\00"
@.cfkinds.14 = private unnamed_addr constant [2 x i8] c"p\00"
@.cname.15 = private unnamed_addr constant [25 x i8] c"stdlib.mutable.MutMatrix\00"
@.cfkinds.15 = private unnamed_addr constant [4 x i8] c"iip\00"

define i64 @stdlib.mutable.mutvec_raw(i64 %v) {
entry:
  %t$0 = call i64 @sprout_tag(i64 %v)
  br label %arm_0_1
arm_0_1:
  %t$3 = add i64 0, 14
  %t$4 = icmp eq i64 %t$0, %t$3
  br i1 %t$4, label %body_0_1, label %arm_1_1
body_0_1:
  %t$5 = call i64 @sprout_field(i64 %v, i64 0)
  br label %join_1
arm_1_1:
  call void @sprout_abort_match()
  unreachable
join_1:
  %t$2 = phi i64 [%t$5, %body_0_1]
  ret i64 %t$2
}

define i64 @stdlib.mutable.mutvec_new(i64 %n, i64 %val) {
entry:
  %t$2 = alloca i64
  store i64 %val, ptr %t$2
  %t$3 = call i64 @sprout_gc_push_i64_root(ptr %t$2)
  %t$0 = call i64 @vec_make_filled(i64 %n, i64 %val)
  %t$4 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$5 = alloca i64
  store i64 %t$0, ptr %t$5
  %t$6 = call i64 @sprout_gc_push_i64_root(ptr %t$5)
  %t$1 = call i64 @sprout_alloc_obj(i64 14, i64 1)
  %t$1$ptr = inttoptr i64 %t$1 to ptr
  %t$1$f0 = getelementptr i64, ptr %t$1$ptr, i64 0
  store i64 %t$0, ptr %t$1$f0
  %t$7 = call i64 @sprout_gc_pop_roots(i64 1)
  ret i64 %t$1
}

define i64 @stdlib.mutable.mutvec_at(i64 %v, i64 %i) {
entry:
  %t$0 = call i64 @stdlib.mutable.mutvec_raw(i64 %v)
  %t$1 = call i64 @vector_get_direct(i64 %t$0, i64 %i)
  ret i64 %t$1
}

define i64 @stdlib.mutable.mutvec_set(i64 %v, i64 %i, i64 %val) {
entry:
  %t$0 = call i64 @stdlib.mutable.mutvec_raw(i64 %v)
  %t$1 = call i64 @vector_mutset(i64 %t$0, i64 %i, i64 %val)
  ret i64 %t$1
}

define i64 @examples.neural_network_train_xor.idx_w1(i64 %j, i64 %i) {
entry:
  %t$0 = add i64 0, 2
  %t$1 = mul i64 %j, %t$0
  %t$2 = add i64 %t$1, %i
  ret i64 %t$2
}

define i64 @examples.neural_network_train_xor.idx_b1(i64 %j) {
entry:
  %t$0 = add i64 0, 4
  %t$1 = add i64 %t$0, %j
  ret i64 %t$1
}

define i64 @examples.neural_network_train_xor.idx_w2(i64 %j) {
entry:
  %t$0 = add i64 0, 6
  %t$1 = add i64 %t$0, %j
  ret i64 %t$1
}

define i64 @examples.neural_network_train_xor.idx_b2() {
entry:
  %t$0 = add i64 0, 8
  ret i64 %t$0
}

define i64 @examples.neural_network_train_xor.dabs(i64 %x) {
entry:
  %t$0 = bitcast double 0.0 to i64
  %t$1$fa = bitcast i64 %x to double
  %t$1$fb = bitcast i64 %t$0 to double
  %t$1 = fcmp olt double %t$1$fa, %t$1$fb
  %t$2 = zext i1 %t$1 to i64
  %t$6 = trunc i64 %t$2 to i1
  br i1 %t$6, label %then_3, label %else_3
then_3:
  %t$5$fa = bitcast i64 %x to double
  %t$5$fr = fneg double %t$5$fa
  %t$5 = bitcast double %t$5$fr to i64
  br label %join_3
else_3:
  br label %join_3
join_3:
  %t$4 = phi i64 [%t$5, %then_3], [%x, %else_3]
  ret i64 %t$4
}

define i64 @examples.neural_network_train_xor.softsign(i64 %x) {
entry:
  %t$0 = bitcast double 1.0 to i64
  %t$1 = call i64 @examples.neural_network_train_xor.dabs(i64 %x)
  %t$2$la = bitcast i64 %t$0 to double
  %t$2$lb = bitcast i64 %t$1 to double
  %t$2$fr = fadd double %t$2$la, %t$2$lb
  %t$2 = bitcast double %t$2$fr to i64
  %t$3$la = bitcast i64 %x to double
  %t$3$lb = bitcast i64 %t$2 to double
  %t$3$fr = fdiv double %t$3$la, %t$3$lb
  %t$3 = bitcast double %t$3$fr to i64
  ret i64 %t$3
}

define i64 @examples.neural_network_train_xor.softsign_deriv_from_out(i64 %s) {
entry:
  %t$0 = bitcast double 1.0 to i64
  %t$1 = call i64 @examples.neural_network_train_xor.dabs(i64 %s)
  %t$2$la = bitcast i64 %t$0 to double
  %t$2$lb = bitcast i64 %t$1 to double
  %t$2$fr = fsub double %t$2$la, %t$2$lb
  %t$2 = bitcast double %t$2$fr to i64
  %t$3 = bitcast double 1.0 to i64
  %t$4 = call i64 @examples.neural_network_train_xor.dabs(i64 %s)
  %t$5$la = bitcast i64 %t$3 to double
  %t$5$lb = bitcast i64 %t$4 to double
  %t$5$fr = fsub double %t$5$la, %t$5$lb
  %t$5 = bitcast double %t$5$fr to i64
  %t$6$la = bitcast i64 %t$2 to double
  %t$6$lb = bitcast i64 %t$5 to double
  %t$6$fr = fmul double %t$6$la, %t$6$lb
  %t$6 = bitcast double %t$6$fr to i64
  ret i64 %t$6
}

define i64 @examples.neural_network_train_xor.mod_int(i64 %a, i64 %m) {
entry:
  %t$0 = icmp eq i64 %m, 0
  br i1 %t$0, label %divpanic_0, label %divok_0
divpanic_0:
  %t$1 = getelementptr inbounds { i64, [17 x i8] }, ptr @.str.0, i64 0, i32 1, i64 0
  %t$2 = ptrtoint ptr %t$1 to i64
  call i64 @panic(i64 %t$2)
  unreachable
divok_0:
  %t$3 = sdiv i64 %a, %m
  %t$4 = mul i64 %t$3, %m
  %t$5 = sub i64 %a, %t$4
  ret i64 %t$5
}

define i64 @examples.neural_network_train_xor.lcg_next(i64 %state) {
entry:
  %t$0 = add i64 0, 1664525
  %t$1 = mul i64 %t$0, %state
  %t$2 = add i64 0, 1013904223
  %t$3 = add i64 %t$1, %t$2
  %t$4 = add i64 0, 2147483648
  %t$5 = call i64 @examples.neural_network_train_xor.mod_int(i64 %t$3, i64 %t$4)
  ret i64 %t$5
}

define i64 @examples.neural_network_train_xor.lcg_to_weight(i64 %state) {
entry:
  %t$0 = add i64 0, 2000
  %t$1 = call i64 @examples.neural_network_train_xor.mod_int(i64 %state, i64 %t$0)
  %t$2 = add i64 0, 1000
  %t$3 = sub i64 %t$1, %t$2
  %t$4$fr = sitofp i64 %t$3 to double
  %t$4 = bitcast double %t$4$fr to i64
  %t$5 = bitcast double 1000.0 to i64
  %t$6$la = bitcast i64 %t$4 to double
  %t$6$lb = bitcast i64 %t$5 to double
  %t$6$fr = fdiv double %t$6$la, %t$6$lb
  %t$6 = bitcast double %t$6$fr to i64
  ret i64 %t$6
}

define i64 @examples.neural_network_train_xor.hidden_out(i64 %w, i64 %j, i64 %x1, i64 %x2) {
entry:
  %t$0 = add i64 0, 0
  %t$1 = call i64 @examples.neural_network_train_xor.idx_w1(i64 %j, i64 %t$0)
  %t$2 = call i64 @stdlib.mutable.mutvec_at(i64 %w, i64 %t$1)
  %t$3 = add i64 0, 1
  %t$4 = call i64 @examples.neural_network_train_xor.idx_w1(i64 %j, i64 %t$3)
  %t$5 = call i64 @stdlib.mutable.mutvec_at(i64 %w, i64 %t$4)
  %t$6 = call i64 @examples.neural_network_train_xor.idx_b1(i64 %j)
  %t$7 = call i64 @stdlib.mutable.mutvec_at(i64 %w, i64 %t$6)
  %t$8$la = bitcast i64 %t$2 to double
  %t$8$lb = bitcast i64 %x1 to double
  %t$8$fr = fmul double %t$8$la, %t$8$lb
  %t$8 = bitcast double %t$8$fr to i64
  %t$9$la = bitcast i64 %t$5 to double
  %t$9$lb = bitcast i64 %x2 to double
  %t$9$fr = fmul double %t$9$la, %t$9$lb
  %t$9 = bitcast double %t$9$fr to i64
  %t$10$la = bitcast i64 %t$8 to double
  %t$10$lb = bitcast i64 %t$9 to double
  %t$10$fr = fadd double %t$10$la, %t$10$lb
  %t$10 = bitcast double %t$10$fr to i64
  %t$11$la = bitcast i64 %t$10 to double
  %t$11$lb = bitcast i64 %t$7 to double
  %t$11$fr = fadd double %t$11$la, %t$11$lb
  %t$11 = bitcast double %t$11$fr to i64
  %t$12 = call i64 @examples.neural_network_train_xor.softsign(i64 %t$11)
  ret i64 %t$12
}

define i64 @examples.neural_network_train_xor.forward(i64 %w, i64 %x1, i64 %x2) {
entry:
  %t$0 = add i64 0, 0
  %t$1 = call i64 @examples.neural_network_train_xor.hidden_out(i64 %w, i64 %t$0, i64 %x1, i64 %x2)
  %t$2 = add i64 0, 1
  %t$3 = call i64 @examples.neural_network_train_xor.hidden_out(i64 %w, i64 %t$2, i64 %x1, i64 %x2)
  %t$4 = add i64 0, 0
  %t$5 = call i64 @examples.neural_network_train_xor.idx_w2(i64 %t$4)
  %t$6 = call i64 @stdlib.mutable.mutvec_at(i64 %w, i64 %t$5)
  %t$7 = add i64 0, 1
  %t$8 = call i64 @examples.neural_network_train_xor.idx_w2(i64 %t$7)
  %t$9 = call i64 @stdlib.mutable.mutvec_at(i64 %w, i64 %t$8)
  %t$10 = call i64 @examples.neural_network_train_xor.idx_b2()
  %t$11 = call i64 @stdlib.mutable.mutvec_at(i64 %w, i64 %t$10)
  %t$12$la = bitcast i64 %t$6 to double
  %t$12$lb = bitcast i64 %t$1 to double
  %t$12$fr = fmul double %t$12$la, %t$12$lb
  %t$12 = bitcast double %t$12$fr to i64
  %t$13$la = bitcast i64 %t$9 to double
  %t$13$lb = bitcast i64 %t$3 to double
  %t$13$fr = fmul double %t$13$la, %t$13$lb
  %t$13 = bitcast double %t$13$fr to i64
  %t$14$la = bitcast i64 %t$12 to double
  %t$14$lb = bitcast i64 %t$13 to double
  %t$14$fr = fadd double %t$14$la, %t$14$lb
  %t$14 = bitcast double %t$14$fr to i64
  %t$15$la = bitcast i64 %t$14 to double
  %t$15$lb = bitcast i64 %t$11 to double
  %t$15$fr = fadd double %t$15$la, %t$15$lb
  %t$15 = bitcast double %t$15$fr to i64
  ret i64 %t$15
}

define i64 @examples.neural_network_train_xor.accum(i64 %g, i64 %i, i64 %delta) {
entry:
  %t$0 = call i64 @stdlib.mutable.mutvec_at(i64 %g, i64 %i)
  %t$1$la = bitcast i64 %t$0 to double
  %t$1$lb = bitcast i64 %delta to double
  %t$1$fr = fadd double %t$1$la, %t$1$lb
  %t$1 = bitcast double %t$1$fr to i64
  %t$2 = call i64 @stdlib.mutable.mutvec_set(i64 %g, i64 %i, i64 %t$1)
  %t$3 = add i64 0, 0
  ret i64 %t$3
}

define i64 @examples.neural_network_train_xor.accum_hidden(i64 %w, i64 %g, i64 %j, i64 %w2_j, i64 %h_j, i64 %d, i64 %x1, i64 %x2) {
entry:
  %t$0$la = bitcast i64 %d to double
  %t$0$lb = bitcast i64 %w2_j to double
  %t$0$fr = fmul double %t$0$la, %t$0$lb
  %t$0 = bitcast double %t$0$fr to i64
  %t$1 = call i64 @examples.neural_network_train_xor.softsign_deriv_from_out(i64 %h_j)
  %t$2$la = bitcast i64 %t$0 to double
  %t$2$lb = bitcast i64 %t$1 to double
  %t$2$fr = fmul double %t$2$la, %t$2$lb
  %t$2 = bitcast double %t$2$fr to i64
  %t$3 = add i64 0, 0
  %t$4 = call i64 @examples.neural_network_train_xor.idx_w1(i64 %j, i64 %t$3)
  %t$5$la = bitcast i64 %t$2 to double
  %t$5$lb = bitcast i64 %x1 to double
  %t$5$fr = fmul double %t$5$la, %t$5$lb
  %t$5 = bitcast double %t$5$fr to i64
  %t$6 = call i64 @examples.neural_network_train_xor.accum(i64 %g, i64 %t$4, i64 %t$5)
  %t$7 = add i64 0, 1
  %t$8 = call i64 @examples.neural_network_train_xor.idx_w1(i64 %j, i64 %t$7)
  %t$9$la = bitcast i64 %t$2 to double
  %t$9$lb = bitcast i64 %x2 to double
  %t$9$fr = fmul double %t$9$la, %t$9$lb
  %t$9 = bitcast double %t$9$fr to i64
  %t$10 = call i64 @examples.neural_network_train_xor.accum(i64 %g, i64 %t$8, i64 %t$9)
  %t$11 = call i64 @examples.neural_network_train_xor.idx_b1(i64 %j)
  %t$12 = call i64 @examples.neural_network_train_xor.accum(i64 %g, i64 %t$11, i64 %t$2)
  %t$13 = add i64 0, 0
  ret i64 %t$13
}

define i64 @examples.neural_network_train_xor.accum_sample_grad(i64 %w, i64 %g, i64 %x1, i64 %x2, i64 %target) {
entry:
  %t$0 = add i64 0, 0
  %t$1 = call i64 @examples.neural_network_train_xor.hidden_out(i64 %w, i64 %t$0, i64 %x1, i64 %x2)
  %t$2 = add i64 0, 1
  %t$3 = call i64 @examples.neural_network_train_xor.hidden_out(i64 %w, i64 %t$2, i64 %x1, i64 %x2)
  %t$4 = call i64 @examples.neural_network_train_xor.forward(i64 %w, i64 %x1, i64 %x2)
  %t$5 = bitcast double 2.0 to i64
  %t$6$la = bitcast i64 %t$4 to double
  %t$6$lb = bitcast i64 %target to double
  %t$6$fr = fsub double %t$6$la, %t$6$lb
  %t$6 = bitcast double %t$6$fr to i64
  %t$7$la = bitcast i64 %t$5 to double
  %t$7$lb = bitcast i64 %t$6 to double
  %t$7$fr = fmul double %t$7$la, %t$7$lb
  %t$7 = bitcast double %t$7$fr to i64
  %t$8 = add i64 0, 0
  %t$9 = call i64 @examples.neural_network_train_xor.idx_w2(i64 %t$8)
  %t$10$la = bitcast i64 %t$7 to double
  %t$10$lb = bitcast i64 %t$1 to double
  %t$10$fr = fmul double %t$10$la, %t$10$lb
  %t$10 = bitcast double %t$10$fr to i64
  %t$11 = call i64 @examples.neural_network_train_xor.accum(i64 %g, i64 %t$9, i64 %t$10)
  %t$12 = add i64 0, 1
  %t$13 = call i64 @examples.neural_network_train_xor.idx_w2(i64 %t$12)
  %t$14$la = bitcast i64 %t$7 to double
  %t$14$lb = bitcast i64 %t$3 to double
  %t$14$fr = fmul double %t$14$la, %t$14$lb
  %t$14 = bitcast double %t$14$fr to i64
  %t$15 = call i64 @examples.neural_network_train_xor.accum(i64 %g, i64 %t$13, i64 %t$14)
  %t$16 = call i64 @examples.neural_network_train_xor.idx_b2()
  %t$17 = call i64 @examples.neural_network_train_xor.accum(i64 %g, i64 %t$16, i64 %t$7)
  %t$18 = add i64 0, 0
  %t$19 = call i64 @examples.neural_network_train_xor.idx_w2(i64 %t$18)
  %t$20 = call i64 @stdlib.mutable.mutvec_at(i64 %w, i64 %t$19)
  %t$21 = add i64 0, 1
  %t$22 = call i64 @examples.neural_network_train_xor.idx_w2(i64 %t$21)
  %t$23 = call i64 @stdlib.mutable.mutvec_at(i64 %w, i64 %t$22)
  %t$24 = add i64 0, 0
  %t$25 = call i64 @examples.neural_network_train_xor.accum_hidden(i64 %w, i64 %g, i64 %t$24, i64 %t$20, i64 %t$1, i64 %t$7, i64 %x1, i64 %x2)
  %t$26 = add i64 0, 1
  %t$27 = call i64 @examples.neural_network_train_xor.accum_hidden(i64 %w, i64 %g, i64 %t$26, i64 %t$23, i64 %t$3, i64 %t$7, i64 %x1, i64 %x2)
  %t$28 = add i64 0, 0
  ret i64 %t$28
}

define i64 @examples.neural_network_train_xor.zero_grads(i64 %g$in, i64 %i$in) {
entry:
  %t$12 = alloca i64
  store i64 %g$in, ptr %t$12
  %t$13 = alloca i64
  store i64 %i$in, ptr %t$13
  %t$14 = call ptr @llvm.stacksave()
  br label %tco_loop
tco_loop:
  %g = load i64, ptr %t$12
  %i = load i64, ptr %t$13
  %t$0 = add i64 0, 9
  %t$1 = icmp sge i64 %i, %t$0
  %t$2 = zext i1 %t$1 to i64
  %t$11 = trunc i64 %t$2 to i1
  br i1 %t$11, label %then_3, label %else_3
then_3:
  %t$5 = add i64 0, 0
  br label %join_3
else_3:
  %t$6 = bitcast double 0.0 to i64
  %t$7 = call i64 @stdlib.mutable.mutvec_set(i64 %g, i64 %i, i64 %t$6)
  %t$8 = add i64 0, 1
  %t$9 = add i64 %i, %t$8
  store i64 %g, ptr %t$12
  store i64 %t$9, ptr %t$13
  call void @llvm.stackrestore(ptr %t$14)
  br label %tco_loop
join_3:
  %t$4 = phi i64 [%t$5, %then_3]
  ret i64 %t$4
}

define i64 @examples.neural_network_train_xor.apply_update(i64 %w$in, i64 %g$in, i64 %lr$in, i64 %i$in) {
entry:
  %t$15 = alloca i64
  store i64 %w$in, ptr %t$15
  %t$16 = alloca i64
  store i64 %g$in, ptr %t$16
  %t$17 = alloca i64
  store i64 %lr$in, ptr %t$17
  %t$18 = alloca i64
  store i64 %i$in, ptr %t$18
  %t$19 = call ptr @llvm.stacksave()
  br label %tco_loop
tco_loop:
  %w = load i64, ptr %t$15
  %g = load i64, ptr %t$16
  %lr = load i64, ptr %t$17
  %i = load i64, ptr %t$18
  %t$0 = add i64 0, 9
  %t$1 = icmp sge i64 %i, %t$0
  %t$2 = zext i1 %t$1 to i64
  %t$14 = trunc i64 %t$2 to i1
  br i1 %t$14, label %then_3, label %else_3
then_3:
  %t$5 = add i64 0, 0
  br label %join_3
else_3:
  %t$6 = call i64 @stdlib.mutable.mutvec_at(i64 %w, i64 %i)
  %t$7 = call i64 @stdlib.mutable.mutvec_at(i64 %g, i64 %i)
  %t$8$la = bitcast i64 %lr to double
  %t$8$lb = bitcast i64 %t$7 to double
  %t$8$fr = fmul double %t$8$la, %t$8$lb
  %t$8 = bitcast double %t$8$fr to i64
  %t$9$la = bitcast i64 %t$6 to double
  %t$9$lb = bitcast i64 %t$8 to double
  %t$9$fr = fsub double %t$9$la, %t$9$lb
  %t$9 = bitcast double %t$9$fr to i64
  %t$10 = call i64 @stdlib.mutable.mutvec_set(i64 %w, i64 %i, i64 %t$9)
  %t$11 = add i64 0, 1
  %t$12 = add i64 %i, %t$11
  store i64 %w, ptr %t$15
  store i64 %g, ptr %t$16
  store i64 %lr, ptr %t$17
  store i64 %t$12, ptr %t$18
  call void @llvm.stackrestore(ptr %t$19)
  br label %tco_loop
join_3:
  %t$4 = phi i64 [%t$5, %then_3]
  ret i64 %t$4
}

define i64 @examples.neural_network_train_xor.sq_err(i64 %w, i64 %x1, i64 %x2, i64 %target) {
entry:
  %t$0 = call i64 @examples.neural_network_train_xor.forward(i64 %w, i64 %x1, i64 %x2)
  %t$1$la = bitcast i64 %t$0 to double
  %t$1$lb = bitcast i64 %target to double
  %t$1$fr = fsub double %t$1$la, %t$1$lb
  %t$1 = bitcast double %t$1$fr to i64
  %t$2$la = bitcast i64 %t$0 to double
  %t$2$lb = bitcast i64 %target to double
  %t$2$fr = fsub double %t$2$la, %t$2$lb
  %t$2 = bitcast double %t$2$fr to i64
  %t$3$la = bitcast i64 %t$1 to double
  %t$3$lb = bitcast i64 %t$2 to double
  %t$3$fr = fmul double %t$3$la, %t$3$lb
  %t$3 = bitcast double %t$3$fr to i64
  ret i64 %t$3
}

define i64 @examples.neural_network_train_xor.mse(i64 %w) {
entry:
  %t$0 = bitcast double 0.0 to i64
  %t$1 = bitcast double 0.0 to i64
  %t$2 = bitcast double 0.0 to i64
  %t$3 = call i64 @examples.neural_network_train_xor.sq_err(i64 %w, i64 %t$0, i64 %t$1, i64 %t$2)
  %t$4 = bitcast double 0.0 to i64
  %t$5 = bitcast double 1.0 to i64
  %t$6 = bitcast double 1.0 to i64
  %t$7 = call i64 @examples.neural_network_train_xor.sq_err(i64 %w, i64 %t$4, i64 %t$5, i64 %t$6)
  %t$8 = bitcast double 1.0 to i64
  %t$9 = bitcast double 0.0 to i64
  %t$10 = bitcast double 1.0 to i64
  %t$11 = call i64 @examples.neural_network_train_xor.sq_err(i64 %w, i64 %t$8, i64 %t$9, i64 %t$10)
  %t$12 = bitcast double 1.0 to i64
  %t$13 = bitcast double 1.0 to i64
  %t$14 = bitcast double 0.0 to i64
  %t$15 = call i64 @examples.neural_network_train_xor.sq_err(i64 %w, i64 %t$12, i64 %t$13, i64 %t$14)
  %t$16$la = bitcast i64 %t$3 to double
  %t$16$lb = bitcast i64 %t$7 to double
  %t$16$fr = fadd double %t$16$la, %t$16$lb
  %t$16 = bitcast double %t$16$fr to i64
  %t$17$la = bitcast i64 %t$16 to double
  %t$17$lb = bitcast i64 %t$11 to double
  %t$17$fr = fadd double %t$17$la, %t$17$lb
  %t$17 = bitcast double %t$17$fr to i64
  %t$18$la = bitcast i64 %t$17 to double
  %t$18$lb = bitcast i64 %t$15 to double
  %t$18$fr = fadd double %t$18$la, %t$18$lb
  %t$18 = bitcast double %t$18$fr to i64
  %t$19 = bitcast double 4.0 to i64
  %t$20$la = bitcast i64 %t$18 to double
  %t$20$lb = bitcast i64 %t$19 to double
  %t$20$fr = fdiv double %t$20$la, %t$20$lb
  %t$20 = bitcast double %t$20$fr to i64
  ret i64 %t$20
}

define i64 @examples.neural_network_train_xor.train_epoch(i64 %w, i64 %g, i64 %lr) {
entry:
  %t$0 = add i64 0, 0
  %t$1 = call i64 @examples.neural_network_train_xor.zero_grads(i64 %g, i64 %t$0)
  %t$2 = bitcast double 0.0 to i64
  %t$3 = bitcast double 0.0 to i64
  %t$4 = bitcast double 0.0 to i64
  %t$5 = call i64 @examples.neural_network_train_xor.accum_sample_grad(i64 %w, i64 %g, i64 %t$2, i64 %t$3, i64 %t$4)
  %t$6 = bitcast double 0.0 to i64
  %t$7 = bitcast double 1.0 to i64
  %t$8 = bitcast double 1.0 to i64
  %t$9 = call i64 @examples.neural_network_train_xor.accum_sample_grad(i64 %w, i64 %g, i64 %t$6, i64 %t$7, i64 %t$8)
  %t$10 = bitcast double 1.0 to i64
  %t$11 = bitcast double 0.0 to i64
  %t$12 = bitcast double 1.0 to i64
  %t$13 = call i64 @examples.neural_network_train_xor.accum_sample_grad(i64 %w, i64 %g, i64 %t$10, i64 %t$11, i64 %t$12)
  %t$14 = bitcast double 1.0 to i64
  %t$15 = bitcast double 1.0 to i64
  %t$16 = bitcast double 0.0 to i64
  %t$17 = call i64 @examples.neural_network_train_xor.accum_sample_grad(i64 %w, i64 %g, i64 %t$14, i64 %t$15, i64 %t$16)
  %t$18 = add i64 0, 0
  %t$19 = call i64 @examples.neural_network_train_xor.apply_update(i64 %w, i64 %g, i64 %lr, i64 %t$18)
  ret i64 %t$19
}

define i64 @examples.neural_network_train_xor.train_verbose(i64 %w$in, i64 %g$in, i64 %lr$in, i64 %epoch$in, i64 %total$in, i64 %band$in) {
entry:
  %t$11 = alloca i64
  store i64 %w$in, ptr %t$11
  %t$12 = alloca i64
  store i64 %g$in, ptr %t$12
  %t$13 = alloca i64
  store i64 %lr$in, ptr %t$13
  %t$14 = alloca i64
  store i64 %epoch$in, ptr %t$14
  %t$15 = alloca i64
  store i64 %total$in, ptr %t$15
  %t$16 = alloca i64
  store i64 %band$in, ptr %t$16
  %t$17 = call ptr @llvm.stacksave()
  br label %tco_loop
tco_loop:
  %w = load i64, ptr %t$11
  %g = load i64, ptr %t$12
  %lr = load i64, ptr %t$13
  %epoch = load i64, ptr %t$14
  %total = load i64, ptr %t$15
  %band = load i64, ptr %t$16
  %t$0 = icmp sgt i64 %epoch, %total
  %t$1 = zext i1 %t$0 to i64
  %t$10 = trunc i64 %t$1 to i1
  br i1 %t$10, label %then_2, label %else_2
then_2:
  %t$4 = add i64 0, 0
  br label %join_2
else_2:
  %t$18 = alloca i64
  store i64 %w, ptr %t$18
  %t$19 = call i64 @sprout_gc_push_i64_root(ptr %t$18)
  %t$20 = alloca i64
  store i64 %g, ptr %t$20
  %t$21 = call i64 @sprout_gc_push_i64_root(ptr %t$20)
  %t$5 = call i64 @examples.neural_network_train_xor.report_loss(i64 %w, i64 %epoch, i64 %band)
  %t$6 = call i64 @examples.neural_network_train_xor.train_epoch(i64 %w, i64 %g, i64 %lr)
  %t$7 = add i64 0, 1
  %t$8 = add i64 %epoch, %t$7
  %t$22 = call i64 @sprout_gc_pop_roots(i64 2)
  store i64 %w, ptr %t$11
  store i64 %g, ptr %t$12
  store i64 %lr, ptr %t$13
  store i64 %t$8, ptr %t$14
  store i64 %total, ptr %t$15
  store i64 %band, ptr %t$16
  call void @llvm.stackrestore(ptr %t$17)
  br label %tco_loop
join_2:
  %t$3 = phi i64 [%t$4, %then_2]
  ret i64 %t$3
}

define i64 @examples.neural_network_train_xor.report_loss(i64 %w, i64 %epoch, i64 %band) {
entry:
  %t$0 = call i64 @examples.neural_network_train_xor.mod_int(i64 %epoch, i64 %band)
  %t$1 = add i64 0, 0
  %t$2 = icmp eq i64 %t$0, %t$1
  %t$3 = zext i1 %t$2 to i64
  %t$19 = trunc i64 %t$3 to i1
  br i1 %t$19, label %then_4, label %else_4
then_4:
  %t$6 = call i64 @examples.neural_network_train_xor.mse(i64 %w)
  %t$7 = getelementptr inbounds { i64, [7 x i8] }, ptr @.str.1, i64 0, i32 1, i64 0
  %t$8 = ptrtoint ptr %t$7 to i64
  %t$20 = alloca i64
  store i64 %t$8, ptr %t$20
  %t$21 = call i64 @sprout_gc_push_i64_root(ptr %t$20)
  %t$9 = call i64 @__tc_ToString_Int_to_string(i64 %epoch)
  %t$22 = alloca i64
  store i64 %t$9, ptr %t$22
  %t$23 = call i64 @sprout_gc_push_i64_root(ptr %t$22)
  %t$10 = call i64 @__tc_Semigroup_String_append(i64 %t$8, i64 %t$9)
  %t$24 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$11 = getelementptr inbounds { i64, [7 x i8] }, ptr @.str.2, i64 0, i32 1, i64 0
  %t$12 = ptrtoint ptr %t$11 to i64
  %t$25 = alloca i64
  store i64 %t$10, ptr %t$25
  %t$26 = call i64 @sprout_gc_push_i64_root(ptr %t$25)
  %t$27 = alloca i64
  store i64 %t$12, ptr %t$27
  %t$28 = call i64 @sprout_gc_push_i64_root(ptr %t$27)
  %t$13 = call i64 @__tc_Semigroup_String_append(i64 %t$10, i64 %t$12)
  %t$29 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$30 = alloca i64
  store i64 %t$13, ptr %t$30
  %t$31 = call i64 @sprout_gc_push_i64_root(ptr %t$30)
  %t$14 = call i64 @__tc_ToString_Double_to_string(i64 %t$6)
  %t$32 = alloca i64
  store i64 %t$14, ptr %t$32
  %t$33 = call i64 @sprout_gc_push_i64_root(ptr %t$32)
  %t$15 = call i64 @__tc_Semigroup_String_append(i64 %t$13, i64 %t$14)
  %t$34 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$16$ptr = inttoptr i64 %t$15 to ptr
  %t$16 = call i64 @print_str(ptr %t$16$ptr)
  %t$17 = add i64 0, 0
  br label %join_4
else_4:
  %t$18 = add i64 0, 0
  br label %join_4
join_4:
  %t$5 = phi i64 [%t$17, %then_4], [%t$18, %else_4]
  ret i64 %t$5
}

define i64 @examples.neural_network_train_xor.init_weights(i64 %w$in, i64 %i$in, i64 %state$in) {
entry:
  %t$13 = alloca i64
  store i64 %w$in, ptr %t$13
  %t$14 = alloca i64
  store i64 %i$in, ptr %t$14
  %t$15 = alloca i64
  store i64 %state$in, ptr %t$15
  %t$16 = call ptr @llvm.stacksave()
  br label %tco_loop
tco_loop:
  %w = load i64, ptr %t$13
  %i = load i64, ptr %t$14
  %state = load i64, ptr %t$15
  %t$0 = add i64 0, 9
  %t$1 = icmp sge i64 %i, %t$0
  %t$2 = zext i1 %t$1 to i64
  %t$12 = trunc i64 %t$2 to i1
  br i1 %t$12, label %then_3, label %else_3
then_3:
  %t$5 = add i64 0, 0
  br label %join_3
else_3:
  %t$6 = call i64 @examples.neural_network_train_xor.lcg_to_weight(i64 %state)
  %t$7 = call i64 @stdlib.mutable.mutvec_set(i64 %w, i64 %i, i64 %t$6)
  %t$8 = add i64 0, 1
  %t$9 = add i64 %i, %t$8
  %t$10 = call i64 @examples.neural_network_train_xor.lcg_next(i64 %state)
  store i64 %w, ptr %t$13
  store i64 %t$9, ptr %t$14
  store i64 %t$10, ptr %t$15
  call void @llvm.stackrestore(ptr %t$16)
  br label %tco_loop
join_3:
  %t$4 = phi i64 [%t$5, %then_3]
  ret i64 %t$4
}

define i64 @examples.neural_network_train_xor.predict(i64 %w, i64 %x1, i64 %x2) {
entry:
  %t$0 = call i64 @examples.neural_network_train_xor.forward(i64 %w, i64 %x1, i64 %x2)
  %t$1 = bitcast double 0.5 to i64
  %t$2$fa = bitcast i64 %t$0 to double
  %t$2$fb = bitcast i64 %t$1 to double
  %t$2 = fcmp ogt double %t$2$fa, %t$2$fb
  %t$3 = zext i1 %t$2 to i64
  %t$8 = trunc i64 %t$3 to i1
  br i1 %t$8, label %then_4, label %else_4
then_4:
  %t$6 = add i64 0, 1
  br label %join_4
else_4:
  %t$7 = add i64 0, 0
  br label %join_4
join_4:
  %t$5 = phi i64 [%t$6, %then_4], [%t$7, %else_4]
  ret i64 %t$5
}

define i64 @__sprout_user_main() {
entry:
  %t$0 = add i64 0, 9
  %t$1 = bitcast double 0.0 to i64
  %t$2 = call i64 @stdlib.mutable.mutvec_new(i64 %t$0, i64 %t$1)
  %t$3 = add i64 0, 9
  %t$4 = bitcast double 0.0 to i64
  %t$33 = alloca i64
  store i64 %t$2, ptr %t$33
  %t$34 = call i64 @sprout_gc_push_i64_root(ptr %t$33)
  %t$5 = call i64 @stdlib.mutable.mutvec_new(i64 %t$3, i64 %t$4)
  %t$6 = add i64 0, 0
  %t$7 = add i64 0, 12345
  %t$8 = call i64 @examples.neural_network_train_xor.init_weights(i64 %t$2, i64 %t$6, i64 %t$7)
  %t$9 = bitcast double 0.1 to i64
  %t$10 = add i64 0, 0
  %t$11 = add i64 0, 5000
  %t$12 = add i64 0, 1000
  %t$35 = alloca i64
  store i64 %t$5, ptr %t$35
  %t$36 = call i64 @sprout_gc_push_i64_root(ptr %t$35)
  %t$13 = call i64 @examples.neural_network_train_xor.train_verbose(i64 %t$2, i64 %t$5, i64 %t$9, i64 %t$10, i64 %t$11, i64 %t$12)
  %t$37 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$14 = getelementptr inbounds { i64, [34 x i8] }, ptr @.str.3, i64 0, i32 1, i64 0
  %t$15 = ptrtoint ptr %t$14 to i64
  %t$16$ptr = inttoptr i64 %t$15 to ptr
  %t$16 = call i64 @print_str(ptr %t$16$ptr)
  %t$17 = bitcast double 0.0 to i64
  %t$18 = bitcast double 0.0 to i64
  %t$19 = call i64 @examples.neural_network_train_xor.predict(i64 %t$2, i64 %t$17, i64 %t$18)
  %t$20 = call i64 @print_value(i64 %t$19)
  %t$21 = bitcast double 0.0 to i64
  %t$22 = bitcast double 1.0 to i64
  %t$23 = call i64 @examples.neural_network_train_xor.predict(i64 %t$2, i64 %t$21, i64 %t$22)
  %t$24 = call i64 @print_value(i64 %t$23)
  %t$25 = bitcast double 1.0 to i64
  %t$26 = bitcast double 0.0 to i64
  %t$27 = call i64 @examples.neural_network_train_xor.predict(i64 %t$2, i64 %t$25, i64 %t$26)
  %t$28 = call i64 @print_value(i64 %t$27)
  %t$29 = bitcast double 1.0 to i64
  %t$30 = bitcast double 1.0 to i64
  %t$31 = call i64 @examples.neural_network_train_xor.predict(i64 %t$2, i64 %t$29, i64 %t$30)
  %t$32 = call i64 @print_value(i64 %t$31)
  %t$38 = call i64 @sprout_gc_pop_roots(i64 1)
  ret i64 %t$32
}

define i64 @__tc_Semigroup_String_append(i64 %left, i64 %right) {
entry:
  %t$0 = call i64 @str_concat(i64 %left, i64 %right)
  ret i64 %t$0
}

define i64 @__tc_ToString_Double_to_string(i64 %value) {
entry:
  %t$0 = call i64 @double_to_string(i64 %value)
  ret i64 %t$0
}

define i64 @__tc_ToString_Int_to_string(i64 %value) {
entry:
  %t$0 = call i64 @int_to_string(i64 %value)
  ret i64 %t$0
}

define i32 @main(i32 %argc, ptr %argv) {
entry:
  %argv_set = call i64 @sprout_set_argv(i32 %argc, ptr %argv)
  %cname_ptr_0 = getelementptr inbounds [8 x i8], ptr @.cname.0, i64 0, i64 0
  %cfkinds_ptr_0 = getelementptr inbounds [1 x i8], ptr @.cfkinds.0, i64 0, i64 0
  %creg_0 = call i64 @sprout_register_ctor(i64 0, ptr %cname_ptr_0, i64 0, ptr %cfkinds_ptr_0)
  %cname_ptr_1 = getelementptr inbounds [5 x i8], ptr @.cname.1, i64 0, i64 0
  %cfkinds_ptr_1 = getelementptr inbounds [2 x i8], ptr @.cfkinds.1, i64 0, i64 0
  %creg_1 = call i64 @sprout_register_ctor(i64 1, ptr %cname_ptr_1, i64 1, ptr %cfkinds_ptr_1)
  %cname_ptr_2 = getelementptr inbounds [12 x i8], ptr @.cname.2, i64 0, i64 0
  %cfkinds_ptr_2 = getelementptr inbounds [2 x i8], ptr @.cfkinds.2, i64 0, i64 0
  %creg_2 = call i64 @sprout_register_ctor(i64 2, ptr %cname_ptr_2, i64 1, ptr %cfkinds_ptr_2)
  %cname_ptr_3 = getelementptr inbounds [15 x i8], ptr @.cname.3, i64 0, i64 0
  %cfkinds_ptr_3 = getelementptr inbounds [2 x i8], ptr @.cfkinds.3, i64 0, i64 0
  %creg_3 = call i64 @sprout_register_ctor(i64 3, ptr %cname_ptr_3, i64 1, ptr %cfkinds_ptr_3)
  %cname_ptr_4 = getelementptr inbounds [15 x i8], ptr @.cname.4, i64 0, i64 0
  %cfkinds_ptr_4 = getelementptr inbounds [2 x i8], ptr @.cfkinds.4, i64 0, i64 0
  %creg_4 = call i64 @sprout_register_ctor(i64 4, ptr %cname_ptr_4, i64 1, ptr %cfkinds_ptr_4)
  %cname_ptr_5 = getelementptr inbounds [4 x i8], ptr @.cname.5, i64 0, i64 0
  %cfkinds_ptr_5 = getelementptr inbounds [1 x i8], ptr @.cfkinds.5, i64 0, i64 0
  %creg_5 = call i64 @sprout_register_ctor(i64 5, ptr %cname_ptr_5, i64 0, ptr %cfkinds_ptr_5)
  %cname_ptr_6 = getelementptr inbounds [5 x i8], ptr @.cname.6, i64 0, i64 0
  %cfkinds_ptr_6 = getelementptr inbounds [3 x i8], ptr @.cfkinds.6, i64 0, i64 0
  %creg_6 = call i64 @sprout_register_ctor(i64 6, ptr %cname_ptr_6, i64 2, ptr %cfkinds_ptr_6)
  %cname_ptr_7 = getelementptr inbounds [3 x i8], ptr @.cname.7, i64 0, i64 0
  %cfkinds_ptr_7 = getelementptr inbounds [2 x i8], ptr @.cfkinds.7, i64 0, i64 0
  %creg_7 = call i64 @sprout_register_ctor(i64 7, ptr %cname_ptr_7, i64 1, ptr %cfkinds_ptr_7)
  %cname_ptr_8 = getelementptr inbounds [4 x i8], ptr @.cname.8, i64 0, i64 0
  %cfkinds_ptr_8 = getelementptr inbounds [2 x i8], ptr @.cfkinds.8, i64 0, i64 0
  %creg_8 = call i64 @sprout_register_ctor(i64 8, ptr %cname_ptr_8, i64 1, ptr %cfkinds_ptr_8)
  %cname_ptr_9 = getelementptr inbounds [10 x i8], ptr @.cname.9, i64 0, i64 0
  %cfkinds_ptr_9 = getelementptr inbounds [1 x i8], ptr @.cfkinds.9, i64 0, i64 0
  %creg_9 = call i64 @sprout_register_ctor(i64 9, ptr %cname_ptr_9, i64 0, ptr %cfkinds_ptr_9)
  %cname_ptr_10 = getelementptr inbounds [4 x i8], ptr @.cname.10, i64 0, i64 0
  %cfkinds_ptr_10 = getelementptr inbounds [2 x i8], ptr @.cfkinds.10, i64 0, i64 0
  %creg_10 = call i64 @sprout_register_ctor(i64 10, ptr %cname_ptr_10, i64 1, ptr %cfkinds_ptr_10)
  %cname_ptr_11 = getelementptr inbounds [5 x i8], ptr @.cname.11, i64 0, i64 0
  %cfkinds_ptr_11 = getelementptr inbounds [2 x i8], ptr @.cfkinds.11, i64 0, i64 0
  %creg_11 = call i64 @sprout_register_ctor(i64 11, ptr %cname_ptr_11, i64 1, ptr %cfkinds_ptr_11)
  %cname_ptr_12 = getelementptr inbounds [4 x i8], ptr @.cname.12, i64 0, i64 0
  %cfkinds_ptr_12 = getelementptr inbounds [2 x i8], ptr @.cfkinds.12, i64 0, i64 0
  %creg_12 = call i64 @sprout_register_ctor(i64 12, ptr %cname_ptr_12, i64 1, ptr %cfkinds_ptr_12)
  %cname_ptr_13 = getelementptr inbounds [9 x i8], ptr @.cname.13, i64 0, i64 0
  %cfkinds_ptr_13 = getelementptr inbounds [4 x i8], ptr @.cfkinds.13, i64 0, i64 0
  %creg_13 = call i64 @sprout_register_ctor(i64 13, ptr %cname_ptr_13, i64 3, ptr %cfkinds_ptr_13)
  %cname_ptr_14 = getelementptr inbounds [22 x i8], ptr @.cname.14, i64 0, i64 0
  %cfkinds_ptr_14 = getelementptr inbounds [2 x i8], ptr @.cfkinds.14, i64 0, i64 0
  %creg_14 = call i64 @sprout_register_ctor(i64 14, ptr %cname_ptr_14, i64 1, ptr %cfkinds_ptr_14)
  %cname_ptr_15 = getelementptr inbounds [25 x i8], ptr @.cname.15, i64 0, i64 0
  %cfkinds_ptr_15 = getelementptr inbounds [4 x i8], ptr @.cfkinds.15, i64 0, i64 0
  %creg_15 = call i64 @sprout_register_ctor(i64 15, ptr %cname_ptr_15, i64 3, ptr %cfkinds_ptr_15)
  call i64 @__sprout_user_main()
  ret i32 0
}

