; Generated by sprout ir_lowering.sprout (M2 PR 2.3)
target triple = "unknown-unknown-unknown"
declare i64 @str_concat(i64, i64)
declare i1 @str_eq(ptr, ptr)
declare i64 @str_compare(i64, i64)
declare i64 @str_slice(i64, i64, i64)
declare i64 @int_to_string(i64)
declare i64 @char_to_string(i64)
declare i64 @sprout_gc_push_i64_root(ptr)
declare i64 @sprout_gc_pop_roots(i64)
declare i64 @sprout_gc_register_i64_root(ptr)
declare i64 @sprout_alloc_closure(i64, i64)
declare void @sprout_closure_arity_check(i64, i64)
declare i64 @sprout_alloc_tuple_blob(i64)
declare i64 @sprout_register_ctor(i64, ptr, i64, ptr)
declare i64 @sprout_tag(i64)
declare i64 @sprout_field(i64, i64)
declare void @sprout_abort_match() noreturn
declare i64 @panic(i64)
declare ptr @llvm.stacksave()
declare void @llvm.stackrestore(ptr)
declare i64 @sprout_alloc_obj(i64, i64)
declare { i64, i64 } @vector_get_unboxed(i64, i64)
declare { i64, i64 } @map_get_unboxed(i64, i64)
declare { i64, i64 } @map_nth_key_unboxed(i64, i64)
declare { i64, i64 } @map_nth_value_unboxed(i64, i64)
declare { i64, i64 } @bytes_get_unboxed(i64, i64)
declare { i64, i64 } @str_char_at_unboxed(i64, i64)
declare { i64, i64 } @argv_get_unboxed(i64)
declare { i64, i64 } @env_get_unboxed(i64)
declare i64 @print_str(ptr)
declare i64 @print_value(i64)
declare i64 @eprint_str(ptr)
declare i64 @argv_get(i64)
declare i64 @sprout_set_argv(i32, ptr)
declare i64 @analysis_check_source(ptr)
declare i64 @analysis_declared_names_in_source(ptr)
declare i64 @analysis_exported_names_in_source(ptr)
declare i64 @analysis_symbol_inventory_in_source(ptr)
declare i64 @analysis_diagnostics_in_source(ptr)
declare i64 @analysis_symbol_locations_in_source(ptr)
declare i64 @analysis_type_of_in_source(ptr, ptr)
declare i64 @analysis_eval_expr_in_source(ptr, ptr)
declare i64 @analysis_instances_in_source(ptr, ptr)
declare i64 @analysis_complete_in_state(ptr, ptr, ptr)

declare i64 @double_to_string(i64)
declare i64 @char_to_str(i64)
declare i64 @char_from_codepoint(i64)
declare i64 @to_double(i64)
declare i64 @string_concat_many(i64)
declare i64 @str_len(i64)
declare i64 @str_char_at(i64, i64)
declare i64 @str_find(i64, i64)
declare i64 @str_starts_with(i64, i64)
declare i64 @vector_empty()
declare i64 @vector_length(i64)
declare i64 @vector_get(i64, i64)
declare i64 @vector_set(i64, i64, i64)
declare i64 @vector_append(i64, i64)
declare i64 @vector_concat(i64, i64)
declare i64 @vector_from_list(i64)
declare i64 @map_empty()
declare i64 @map_get(i64, i64)
declare i64 @map_set(i64, i64, i64)
declare i64 @map_remove(i64, i64)
declare i64 @map_size(i64)
declare i64 @map_nth_key(i64, i64)
declare i64 @map_nth_value(i64, i64)
declare i64 @native_set_empty()
declare i64 @native_set_insert(i64, i64)
declare i64 @native_set_member(i64, i64)
declare i64 @native_set_to_list(i64)
declare i64 @native_set_size(i64)
declare i64 @ref_new(i64)
declare i64 @ref_read(i64)
declare i64 @ref_write(i64, i64)
declare i64 @bytes_empty()
declare i64 @bytes_singleton(i64)
declare i64 @bytes_length(i64)
declare i64 @bytes_get(i64, i64)
declare i64 @bytes_slice(i64, i64, i64)
declare i64 @bytes_append(i64, i64)
declare i64 @bytes_from_utf8(i64)
declare i64 @bytes_to_utf8(i64)
declare i64 @bytes_builder_empty()
declare i64 @bytes_builder_bytes(i64)
declare i64 @bytes_builder_byte(i64)
declare i64 @bytes_builder_u16_be(i64)
declare i64 @bytes_builder_u32_be(i64)
declare i64 @bytes_builder_append(i64, i64)
declare i64 @bytes_builder_build(i64)
declare i64 @str_byte_len(i64)
declare i64 @str_slice_bytes(i64, i64, i64)
declare i64 @str_starts_with_at_byte(i64, i64, i64)
declare i64 @str_split_lines(i64)
declare i64 @split_words(i64)
declare i64 @env_get(i64)
@.str.0 = private unnamed_addr constant { i64, [1 x i8] } { i64 10, [1 x i8] c"\00" }
@.str.1 = private unnamed_addr constant { i64, [1 x i8] } { i64 10, [1 x i8] c"\00" }
@.str.2 = private unnamed_addr constant { i64, [12 x i8] } { i64 180234, [12 x i8] c"do:io-maybe\00" }
@.str.3 = private unnamed_addr constant { i64, [20 x i8] } { i64 311306, [20 x i8] c"reading SPROUT_NAME\00" }
@.str.4 = private unnamed_addr constant { i64, [12 x i8] } { i64 180234, [12 x i8] c"SPROUT_NAME\00" }
@.str.5 = private unnamed_addr constant { i64, [12 x i8] } { i64 180234, [12 x i8] c"io-do:name=\00" }
@.str.6 = private unnamed_addr constant { i64, [21 x i8] } { i64 327690, [21 x i8] c"io-do:name=anonymous\00" }
@.str.7 = private unnamed_addr constant { i64, [12 x i8] } { i64 180234, [12 x i8] c"do:io-maybe\00" }
@.str.8 = private unnamed_addr constant { i64, [20 x i8] } { i64 311306, [20 x i8] c"reading SPROUT_NAME\00" }
@.str.9 = private unnamed_addr constant { i64, [12 x i8] } { i64 180234, [12 x i8] c"SPROUT_NAME\00" }
@.cname.0 = private unnamed_addr constant [8 x i8] c"Nothing\00"
@.cfkinds.0 = private unnamed_addr constant [1 x i8] c"\00"
@.cname.1 = private unnamed_addr constant [5 x i8] c"Just\00"
@.cfkinds.1 = private unnamed_addr constant [2 x i8] c"_\00"
@.cname.2 = private unnamed_addr constant [12 x i8] c"TemplateLit\00"
@.cfkinds.2 = private unnamed_addr constant [2 x i8] c"s\00"
@.cname.3 = private unnamed_addr constant [15 x i8] c"TemplateInterp\00"
@.cfkinds.3 = private unnamed_addr constant [2 x i8] c"s\00"
@.cname.4 = private unnamed_addr constant [15 x i8] c"StringTemplate\00"
@.cfkinds.4 = private unnamed_addr constant [2 x i8] c"p\00"
@.cname.5 = private unnamed_addr constant [4 x i8] c"Nil\00"
@.cfkinds.5 = private unnamed_addr constant [1 x i8] c"\00"
@.cname.6 = private unnamed_addr constant [5 x i8] c"Cons\00"
@.cfkinds.6 = private unnamed_addr constant [3 x i8] c"_p\00"
@.cname.7 = private unnamed_addr constant [3 x i8] c"Ok\00"
@.cfkinds.7 = private unnamed_addr constant [2 x i8] c"_\00"
@.cname.8 = private unnamed_addr constant [4 x i8] c"Err\00"
@.cfkinds.8 = private unnamed_addr constant [2 x i8] c"_\00"
@.cname.9 = private unnamed_addr constant [10 x i8] c"DivByZero\00"
@.cfkinds.9 = private unnamed_addr constant [1 x i8] c"\00"
@.cname.10 = private unnamed_addr constant [4 x i8] c"Vec\00"
@.cfkinds.10 = private unnamed_addr constant [2 x i8] c"p\00"
@.cname.11 = private unnamed_addr constant [5 x i8] c"Dict\00"
@.cfkinds.11 = private unnamed_addr constant [2 x i8] c"p\00"
@.cname.12 = private unnamed_addr constant [4 x i8] c"Set\00"
@.cfkinds.12 = private unnamed_addr constant [2 x i8] c"p\00"
@.cname.13 = private unnamed_addr constant [9 x i8] c"IntRange\00"
@.cfkinds.13 = private unnamed_addr constant [4 x i8] c"iii\00"
@.cname.14 = private unnamed_addr constant [29 x i8] c"stdlib.bytes.Utf8DecodeError\00"
@.cfkinds.14 = private unnamed_addr constant [2 x i8] c"s\00"

define i64 @fold(i64 %step, i64 %init, i64 %xs, i64 %__tc_Foldable_0_fold_values) {
entry:
  %t$1 = alloca i64
  store i64 %xs, ptr %t$1
  %t$2 = call i64 @sprout_gc_push_i64_root(ptr %t$1)
  %t$3 = alloca i64
  store i64 %step, ptr %t$3
  %t$4 = call i64 @sprout_gc_push_i64_root(ptr %t$3)
  %t$5 = alloca i64
  store i64 %init, ptr %t$5
  %t$6 = call i64 @sprout_gc_push_i64_root(ptr %t$5)
  %t$7 = alloca i64
  store i64 %__tc_Foldable_0_fold_values, ptr %t$7
  %t$8 = call i64 @sprout_gc_push_i64_root(ptr %t$7)
  %t$0 = call i64 @__cm_Foldable_fold_values(i64 %step, i64 %init, i64 %xs, i64 %__tc_Foldable_0_fold_values)
  %t$9 = call i64 @sprout_gc_pop_roots(i64 4)
  ret i64 %t$0
}

define i64 @__sprout_ir_lambda_0(i64 %env$, i64 %acc, i64 %x) {
entry:
  %t$0$env_ptr = inttoptr i64 %env$ to ptr
  %t$0$slot_ptr = getelementptr i64, ptr %t$0$env_ptr, i64 1
  %t$0 = load i64, ptr %t$0$slot_ptr
  %t$7 = alloca i64
  store i64 %acc, ptr %t$7
  %t$8 = call i64 @sprout_gc_push_i64_root(ptr %t$7)
  call void @sprout_closure_arity_check(i64 %t$0, i64 1)
  %t$1$env_ptr = inttoptr i64 %t$0 to ptr
  %t$1$code = load ptr, ptr %t$1$env_ptr
  %t$1 = call i64 (i64, i64) %t$1$code(i64 %t$0, i64 %x)
  %t$6 = trunc i64 %t$1 to i1
  %t$9 = call i64 @sprout_gc_pop_roots(i64 1)
  br i1 %t$6, label %then_2, label %else_2
then_2:
  %t$4 = add i64 0, 1
  %t$5 = add i64 %acc, %t$4
  br label %join_2
else_2:
  br label %join_2
join_2:
  %t$3 = phi i64 [%t$5, %then_2], [%acc, %else_2]
  ret i64 %t$3
}

define i64 @count(i64 %pred, i64 %xs, i64 %__tc_Foldable_0_fold_values) {
entry:
  %t$3 = alloca i64
  store i64 %xs, ptr %t$3
  %t$4 = call i64 @sprout_gc_push_i64_root(ptr %t$3)
  %t$5 = alloca i64
  store i64 %pred, ptr %t$5
  %t$6 = call i64 @sprout_gc_push_i64_root(ptr %t$5)
  %t$7 = alloca i64
  store i64 %__tc_Foldable_0_fold_values, ptr %t$7
  %t$8 = call i64 @sprout_gc_push_i64_root(ptr %t$7)
  %t$0 = call i64 @sprout_alloc_closure(i64 16, i64 2)
  %t$0$raw = inttoptr i64 %t$0 to ptr
  store ptr @__sprout_ir_lambda_0, ptr %t$0$raw
  %t$0$raw$slot$1 = getelementptr i64, ptr %t$0$raw, i64 1
  store i64 %pred, ptr %t$0$raw$slot$1
  %t$1 = add i64 0, 0
  %t$9 = alloca i64
  store i64 %t$0, ptr %t$9
  %t$10 = call i64 @sprout_gc_push_i64_root(ptr %t$9)
  %t$2 = call i64 @fold(i64 %t$0, i64 %t$1, i64 %xs, i64 %__tc_Foldable_0_fold_values)
  %t$11 = call i64 @sprout_gc_pop_roots(i64 4)
  ret i64 %t$2
}

define i64 @stdlib.bytes.length(i64 %value) {
entry:
  %t$1 = alloca i64
  store i64 %value, ptr %t$1
  %t$2 = call i64 @sprout_gc_push_i64_root(ptr %t$1)
  %t$0 = call i64 @bytes_length(i64 %value)
  %t$3 = call i64 @sprout_gc_pop_roots(i64 1)
  ret i64 %t$0
}

define i64 @stdlib.bytes.get(i64 %value, i64 %index) {
entry:
  %t$1 = alloca i64
  store i64 %value, ptr %t$1
  %t$2 = call i64 @sprout_gc_push_i64_root(ptr %t$1)
  %t$0 = call i64 @bytes_get(i64 %value, i64 %index)
  %t$3 = call i64 @sprout_gc_pop_roots(i64 1)
  ret i64 %t$0
}

define i64 @stdlib.bytes.slice(i64 %value, i64 %start, i64 %count) {
entry:
  %t$1 = alloca i64
  store i64 %value, ptr %t$1
  %t$2 = call i64 @sprout_gc_push_i64_root(ptr %t$1)
  %t$0 = call i64 @bytes_slice(i64 %value, i64 %start, i64 %count)
  %t$3 = call i64 @sprout_gc_pop_roots(i64 1)
  ret i64 %t$0
}

define i64 @stdlib.bytes.from_string(i64 %raw) {
entry:
  %t$1 = alloca i64
  store i64 %raw, ptr %t$1
  %t$2 = call i64 @sprout_gc_push_i64_root(ptr %t$1)
  %t$0 = call i64 @bytes_from_utf8(i64 %raw)
  %t$3 = call i64 @sprout_gc_pop_roots(i64 1)
  ret i64 %t$0
}

define i64 @stdlib.bytes.to_string(i64 %value) {
entry:
  %t$1 = alloca i64
  store i64 %value, ptr %t$1
  %t$2 = call i64 @sprout_gc_push_i64_root(ptr %t$1)
  %t$0 = call i64 @bytes_to_utf8(i64 %value)
  %t$3 = call i64 @sprout_gc_pop_roots(i64 1)
  ret i64 %t$0
}

define i64 @stdlib.string.concat(i64 %left, i64 %right) {
entry:
  %t$0 = call i64 @str_concat(i64 %left, i64 %right)
  ret i64 %t$0
}

define i64 @stdlib.string.is_ws_byte(i64 %b) {
entry:
  %t$0 = add i64 0, 32
  %t$1 = icmp eq i64 %b, %t$0
  %t$2 = zext i1 %t$1 to i64
  %t$9 = trunc i64 %t$2 to i1
  br i1 %t$9, label %then_3, label %else_3
then_3:
  %t$5 = add i64 0, 1
  br label %join_3
else_3:
  %t$6 = add i64 0, 9
  %t$7 = icmp eq i64 %b, %t$6
  %t$8 = zext i1 %t$7 to i64
  br label %join_3
join_3:
  %t$4 = phi i64 [%t$5, %then_3], [%t$8, %else_3]
  %t$16 = trunc i64 %t$4 to i1
  br i1 %t$16, label %then_10, label %else_10
then_10:
  %t$12 = add i64 0, 1
  br label %join_10
else_10:
  %t$13 = add i64 0, 10
  %t$14 = icmp eq i64 %b, %t$13
  %t$15 = zext i1 %t$14 to i64
  br label %join_10
join_10:
  %t$11 = phi i64 [%t$12, %then_10], [%t$15, %else_10]
  %t$23 = trunc i64 %t$11 to i1
  br i1 %t$23, label %then_17, label %else_17
then_17:
  %t$19 = add i64 0, 1
  br label %join_17
else_17:
  %t$20 = add i64 0, 13
  %t$21 = icmp eq i64 %b, %t$20
  %t$22 = zext i1 %t$21 to i64
  br label %join_17
join_17:
  %t$18 = phi i64 [%t$19, %then_17], [%t$22, %else_17]
  ret i64 %t$18
}

define i64 @stdlib.string.byte_at_or0(i64 %b, i64 %index) {
entry:
  %t$0$st = call { i64, i64 } @stdlib.bytes.get_worker(i64 %b, i64 %index)
  %t$0 = extractvalue { i64, i64 } %t$0$st, 0
  %t$1 = extractvalue { i64, i64 } %t$0$st, 1
  br label %arm_0_2
arm_0_2:
  %t$4 = add i64 0, 1
  %t$5 = icmp eq i64 %t$0, %t$4
  br i1 %t$5, label %body_0_2, label %arm_1_2
body_0_2:
  br label %join_2
arm_1_2:
  %t$6 = add i64 0, 0
  %t$7 = icmp eq i64 %t$0, %t$6
  br i1 %t$7, label %body_1_2, label %arm_2_2
body_1_2:
  %t$8 = add i64 0, 0
  br label %join_2
arm_2_2:
  call void @sprout_abort_match()
  unreachable
join_2:
  %t$3 = phi i64 [%t$1, %body_0_2], [%t$8, %body_1_2]
  ret i64 %t$3
}

define i64 @stdlib.string.scan_ws_fwd(i64 %b$in, i64 %i$in, i64 %n$in) {
entry:
  %t$13 = alloca i64
  store i64 %b$in, ptr %t$13
  %t$14 = alloca i64
  store i64 %i$in, ptr %t$14
  %t$15 = alloca i64
  store i64 %n$in, ptr %t$15
  %t$16 = call ptr @llvm.stacksave()
  br label %tco_loop
tco_loop:
  %b = load i64, ptr %t$13
  %i = load i64, ptr %t$14
  %n = load i64, ptr %t$15
  %t$0 = icmp sge i64 %i, %n
  %t$1 = zext i1 %t$0 to i64
  %t$12 = trunc i64 %t$1 to i1
  br i1 %t$12, label %then_2, label %else_2
then_2:
  br label %join_2
else_2:
  %t$4 = call i64 @stdlib.string.byte_at_or0(i64 %b, i64 %i)
  %t$5 = call i64 @stdlib.string.is_ws_byte(i64 %t$4)
  %t$11 = trunc i64 %t$5 to i1
  br i1 %t$11, label %then_6, label %else_6
then_6:
  %t$8 = add i64 0, 1
  %t$9 = add i64 %i, %t$8
  store i64 %b, ptr %t$13
  store i64 %t$9, ptr %t$14
  store i64 %n, ptr %t$15
  call void @llvm.stackrestore(ptr %t$16)
  br label %tco_loop
else_6:
  br label %join_6
join_6:
  %t$7 = phi i64 [%i, %else_6]
  br label %join_2
join_2:
  %t$3 = phi i64 [%n, %then_2], [%t$7, %join_6]
  ret i64 %t$3
}

define i64 @stdlib.string.scan_ws_bwd(i64 %b$in, i64 %i$in) {
entry:
  %t$16 = alloca i64
  store i64 %b$in, ptr %t$16
  %t$17 = alloca i64
  store i64 %i$in, ptr %t$17
  %t$18 = call ptr @llvm.stacksave()
  br label %tco_loop
tco_loop:
  %b = load i64, ptr %t$16
  %i = load i64, ptr %t$17
  %t$0 = add i64 0, 0
  %t$1 = icmp slt i64 %i, %t$0
  %t$2 = zext i1 %t$1 to i64
  %t$15 = trunc i64 %t$2 to i1
  br i1 %t$15, label %then_3, label %else_3
then_3:
  %t$5 = add i64 0, 1
  %t$6 = sub i64 0, %t$5
  br label %join_3
else_3:
  %t$7 = call i64 @stdlib.string.byte_at_or0(i64 %b, i64 %i)
  %t$8 = call i64 @stdlib.string.is_ws_byte(i64 %t$7)
  %t$14 = trunc i64 %t$8 to i1
  br i1 %t$14, label %then_9, label %else_9
then_9:
  %t$11 = add i64 0, 1
  %t$12 = sub i64 %i, %t$11
  store i64 %b, ptr %t$16
  store i64 %t$12, ptr %t$17
  call void @llvm.stackrestore(ptr %t$18)
  br label %tco_loop
else_9:
  br label %join_9
join_9:
  %t$10 = phi i64 [%i, %else_9]
  br label %join_3
join_3:
  %t$4 = phi i64 [%t$6, %then_3], [%t$10, %join_9]
  ret i64 %t$4
}

define i64 @stdlib.string.byte_range_string(i64 %b, i64 %start, i64 %endx) {
entry:
  %t$0 = sub i64 %endx, %start
  %t$12 = alloca i64
  store i64 %b, ptr %t$12
  %t$13 = call i64 @sprout_gc_push_i64_root(ptr %t$12)
  %t$1 = call i64 @stdlib.bytes.slice(i64 %b, i64 %start, i64 %t$0)
  %t$14 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$15 = alloca i64
  store i64 %t$1, ptr %t$15
  %t$16 = call i64 @sprout_gc_push_i64_root(ptr %t$15)
  %t$2$st = call { i64, i64 } @stdlib.bytes.to_string_worker(i64 %t$1)
  %t$2 = extractvalue { i64, i64 } %t$2$st, 0
  %t$3 = extractvalue { i64, i64 } %t$2$st, 1
  %t$17 = call i64 @sprout_gc_pop_roots(i64 1)
  br label %arm_0_4
arm_0_4:
  %t$6 = add i64 0, 7
  %t$7 = icmp eq i64 %t$2, %t$6
  br i1 %t$7, label %body_0_4, label %arm_1_4
body_0_4:
  br label %join_4
arm_1_4:
  %t$8 = add i64 0, 8
  %t$9 = icmp eq i64 %t$2, %t$8
  br i1 %t$9, label %body_1_4, label %arm_2_4
body_1_4:
  %t$10 = getelementptr inbounds { i64, [1 x i8] }, ptr @.str.0, i64 0, i32 1, i64 0
  %t$11 = ptrtoint ptr %t$10 to i64
  br label %join_4
arm_2_4:
  call void @sprout_abort_match()
  unreachable
join_4:
  %t$5 = phi i64 [%t$3, %body_0_4], [%t$11, %body_1_4]
  ret i64 %t$5
}

define i64 @stdlib.string.trim(i64 %raw) {
entry:
  %t$25 = alloca i64
  store i64 %raw, ptr %t$25
  %t$26 = call i64 @sprout_gc_push_i64_root(ptr %t$25)
  %t$0 = call i64 @stdlib.bytes.from_string(i64 %raw)
  %t$27 = call i64 @sprout_gc_pop_roots(i64 1)
  br label %arm_0_1
arm_0_1:
  %t$28 = alloca i64
  store i64 %t$0, ptr %t$28
  %t$29 = call i64 @sprout_gc_push_i64_root(ptr %t$28)
  %t$3 = call i64 @stdlib.bytes.length(i64 %t$0)
  %t$30 = call i64 @sprout_gc_pop_roots(i64 1)
  br label %arm_0_4
arm_0_4:
  %t$6 = add i64 0, 0
  %t$7 = call i64 @stdlib.string.scan_ws_fwd(i64 %t$0, i64 %t$6, i64 %t$3)
  br label %arm_0_8
arm_0_8:
  %t$10 = add i64 0, 1
  %t$11 = sub i64 %t$3, %t$10
  %t$12 = call i64 @stdlib.string.scan_ws_bwd(i64 %t$0, i64 %t$11)
  br label %arm_0_13
arm_0_13:
  %t$15 = icmp sgt i64 %t$7, %t$12
  %t$16 = zext i1 %t$15 to i64
  %t$24 = trunc i64 %t$16 to i1
  br i1 %t$24, label %then_17, label %else_17
then_17:
  %t$19 = getelementptr inbounds { i64, [1 x i8] }, ptr @.str.1, i64 0, i32 1, i64 0
  %t$20 = ptrtoint ptr %t$19 to i64
  br label %join_17
else_17:
  %t$21 = add i64 0, 1
  %t$22 = add i64 %t$12, %t$21
  %t$31 = alloca i64
  store i64 %t$0, ptr %t$31
  %t$32 = call i64 @sprout_gc_push_i64_root(ptr %t$31)
  %t$23 = call i64 @stdlib.string.byte_range_string(i64 %t$0, i64 %t$7, i64 %t$22)
  %t$33 = call i64 @sprout_gc_pop_roots(i64 1)
  br label %join_17
join_17:
  %t$18 = phi i64 [%t$20, %then_17], [%t$23, %else_17]
  br label %join_13
arm_1_13:
  call void @sprout_abort_match()
  unreachable
join_13:
  %t$14 = phi i64 [%t$18, %join_17]
  br label %join_8
arm_1_8:
  call void @sprout_abort_match()
  unreachable
join_8:
  %t$9 = phi i64 [%t$14, %join_13]
  br label %join_4
arm_1_4:
  call void @sprout_abort_match()
  unreachable
join_4:
  %t$5 = phi i64 [%t$9, %join_8]
  br label %join_1
arm_1_1:
  call void @sprout_abort_match()
  unreachable
join_1:
  %t$2 = phi i64 [%t$5, %join_4]
  ret i64 %t$2
}

define i64 @stdlib.env.get(i64 %name) {
entry:
  %t$1 = alloca i64
  store i64 %name, ptr %t$1
  %t$2 = call i64 @sprout_gc_push_i64_root(ptr %t$1)
  %t$0 = call i64 @env_get(i64 %name)
  %t$3 = call i64 @sprout_gc_pop_roots(i64 1)
  ret i64 %t$0
}

define i64 @examples.io_do_demo.configured_name() {
entry:
  %t$0 = getelementptr inbounds { i64, [12 x i8] }, ptr @.str.2, i64 0, i32 1, i64 0
  %t$1 = ptrtoint ptr %t$0 to i64
  %t$2$ptr = inttoptr i64 %t$1 to ptr
  %t$2 = call i64 @print_str(ptr %t$2$ptr)
  %t$3 = getelementptr inbounds { i64, [20 x i8] }, ptr @.str.3, i64 0, i32 1, i64 0
  %t$4 = ptrtoint ptr %t$3 to i64
  %t$5$ptr = inttoptr i64 %t$4 to ptr
  %t$5 = call i64 @print_str(ptr %t$5$ptr)
  %t$6 = getelementptr inbounds { i64, [12 x i8] }, ptr @.str.4, i64 0, i32 1, i64 0
  %t$7 = ptrtoint ptr %t$6 to i64
  %t$8$st = call { i64, i64 } @stdlib.env.get_worker(i64 %t$7)
  %t$8 = extractvalue { i64, i64 } %t$8$st, 0
  %t$9 = extractvalue { i64, i64 } %t$8$st, 1
  %t$10 = add i64 0, 0
  %t$11 = icmp eq i64 %t$8, %t$10
  br i1 %t$11, label %do_short_10, label %do_cont_10
do_short_10:
  %t$13 = call i64 @sprout_alloc_obj(i64 0, i64 0)
  br label %do_done_10
do_cont_10:
  %t$17 = alloca i64
  store i64 %t$9, ptr %t$17
  %t$18 = call i64 @sprout_gc_push_i64_root(ptr %t$17)
  %t$14 = call i64 @stdlib.string.trim(i64 %t$9)
  %t$19 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$20 = alloca i64
  store i64 %t$14, ptr %t$20
  %t$21 = call i64 @sprout_gc_push_i64_root(ptr %t$20)
  %t$15 = call i64 @sprout_alloc_obj(i64 1, i64 1)
  %t$15$ptr = inttoptr i64 %t$15 to ptr
  %t$15$f0 = getelementptr i64, ptr %t$15$ptr, i64 0
  store i64 %t$14, ptr %t$15$f0
  %t$22 = call i64 @sprout_gc_pop_roots(i64 1)
  br label %do_done_10
do_done_10:
  %t$16 = phi i64 [%t$13, %do_short_10], [%t$15, %do_cont_10]
  ret i64 %t$16
}

define i64 @__sprout_user_main() {
entry:
  %t$0$st = call { i64, i64 } @examples.io_do_demo.configured_name_worker()
  %t$0 = extractvalue { i64, i64 } %t$0$st, 0
  %t$1 = extractvalue { i64, i64 } %t$0$st, 1
  br label %arm_0_2
arm_0_2:
  %t$4 = add i64 0, 1
  %t$5 = icmp eq i64 %t$0, %t$4
  br i1 %t$5, label %body_0_2, label %arm_1_2
body_0_2:
  %t$6 = getelementptr inbounds { i64, [12 x i8] }, ptr @.str.5, i64 0, i32 1, i64 0
  %t$7 = ptrtoint ptr %t$6 to i64
  %t$15 = alloca i64
  store i64 %t$1, ptr %t$15
  %t$16 = call i64 @sprout_gc_push_i64_root(ptr %t$15)
  %t$17 = alloca i64
  store i64 %t$7, ptr %t$17
  %t$18 = call i64 @sprout_gc_push_i64_root(ptr %t$17)
  %t$8 = call i64 @stdlib.string.concat(i64 %t$7, i64 %t$1)
  %t$19 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$9$ptr = inttoptr i64 %t$8 to ptr
  %t$9 = call i64 @print_str(ptr %t$9$ptr)
  br label %join_2
arm_1_2:
  %t$10 = add i64 0, 0
  %t$11 = icmp eq i64 %t$0, %t$10
  br i1 %t$11, label %body_1_2, label %arm_2_2
body_1_2:
  %t$12 = getelementptr inbounds { i64, [21 x i8] }, ptr @.str.6, i64 0, i32 1, i64 0
  %t$13 = ptrtoint ptr %t$12 to i64
  %t$14$ptr = inttoptr i64 %t$13 to ptr
  %t$14 = call i64 @print_str(ptr %t$14$ptr)
  br label %join_2
arm_2_2:
  call void @sprout_abort_match()
  unreachable
join_2:
  %t$3 = phi i64 [%t$9, %body_0_2], [%t$14, %body_1_2]
  ret i64 %t$3
}

define i64 @__cm_Foldable_fold_values(i64 %step, i64 %init, i64 %xs, i64 %__tc_Foldable_0_fold_values) {
entry:
  call void @sprout_closure_arity_check(i64 %__tc_Foldable_0_fold_values, i64 3)
  %t$0$env_ptr = inttoptr i64 %__tc_Foldable_0_fold_values to ptr
  %t$0$code = load ptr, ptr %t$0$env_ptr
  %t$0 = call i64 (i64, i64, i64, i64) %t$0$code(i64 %__tc_Foldable_0_fold_values, i64 %step, i64 %init, i64 %xs)
  ret i64 %t$0
}

define { i64, i64 } @examples.io_do_demo.configured_name_worker() {
entry:
  %t$0 = getelementptr inbounds { i64, [12 x i8] }, ptr @.str.7, i64 0, i32 1, i64 0
  %t$1 = ptrtoint ptr %t$0 to i64
  %t$2$ptr = inttoptr i64 %t$1 to ptr
  %t$2 = call i64 @print_str(ptr %t$2$ptr)
  %t$3 = getelementptr inbounds { i64, [20 x i8] }, ptr @.str.8, i64 0, i32 1, i64 0
  %t$4 = ptrtoint ptr %t$3 to i64
  %t$5$ptr = inttoptr i64 %t$4 to ptr
  %t$5 = call i64 @print_str(ptr %t$5$ptr)
  %t$6 = getelementptr inbounds { i64, [12 x i8] }, ptr @.str.9, i64 0, i32 1, i64 0
  %t$7 = ptrtoint ptr %t$6 to i64
  %t$8$st = call { i64, i64 } @stdlib.env.get_worker(i64 %t$7)
  %t$8 = extractvalue { i64, i64 } %t$8$st, 0
  %t$9 = extractvalue { i64, i64 } %t$8$st, 1
  %t$10 = add i64 0, 0
  %t$11 = icmp eq i64 %t$8, %t$10
  br i1 %t$11, label %do_short_10, label %do_cont_10
do_short_10:
  %t$13 = call i64 @sprout_alloc_obj(i64 0, i64 0)
  br label %do_done_10
do_cont_10:
  %t$26 = alloca i64
  store i64 %t$9, ptr %t$26
  %t$27 = call i64 @sprout_gc_push_i64_root(ptr %t$26)
  %t$14 = call i64 @stdlib.string.trim(i64 %t$9)
  %t$28 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$29 = alloca i64
  store i64 %t$14, ptr %t$29
  %t$30 = call i64 @sprout_gc_push_i64_root(ptr %t$29)
  %t$15 = call i64 @sprout_alloc_obj(i64 1, i64 1)
  %t$15$ptr = inttoptr i64 %t$15 to ptr
  %t$15$f0 = getelementptr i64, ptr %t$15$ptr, i64 0
  store i64 %t$14, ptr %t$15$f0
  %t$31 = call i64 @sprout_gc_pop_roots(i64 1)
  br label %do_done_10
do_done_10:
  %t$16 = phi i64 [%t$13, %do_short_10], [%t$15, %do_cont_10]
  %t$17 = call i64 @sprout_tag(i64 %t$16)
  %t$18 = add i64 0, 0
  %t$19 = icmp eq i64 %t$17, %t$18
  br i1 %t$19, label %wrepack_hit_18, label %wrepack_next_18
wrepack_hit_18:
  %t$21$r0 = insertvalue { i64, i64 } undef, i64 %t$17, 0
  %t$21$r1 = insertvalue { i64, i64 } %t$21$r0, i64 0, 1
  ret { i64, i64 } %t$21$r1
wrepack_next_18:
  %t$22 = add i64 0, 1
  %t$23 = icmp eq i64 %t$17, %t$22
  br i1 %t$23, label %wrepack_hit_22, label %wrepack_next_22
wrepack_hit_22:
  %t$24 = call i64 @sprout_field(i64 %t$16, i64 0)
  %t$25$r0 = insertvalue { i64, i64 } undef, i64 %t$17, 0
  %t$25$r1 = insertvalue { i64, i64 } %t$25$r0, i64 %t$24, 1
  ret { i64, i64 } %t$25$r1
wrepack_next_22:
  call void @sprout_abort_match()
  unreachable
}

define { i64, i64 } @stdlib.bytes.get_worker(i64 %value, i64 %index) {
entry:
  %t$0$st = call { i64, i64 } @bytes_get_unboxed(i64 %value, i64 %index)
  %t$0 = extractvalue { i64, i64 } %t$0$st, 0
  %t$1 = extractvalue { i64, i64 } %t$0$st, 1
  %t$2$r0 = insertvalue { i64, i64 } undef, i64 %t$0, 0
  %t$2$r1 = insertvalue { i64, i64 } %t$2$r0, i64 %t$1, 1
  ret { i64, i64 } %t$2$r1
}

define { i64, i64 } @stdlib.bytes.to_string_worker(i64 %value) {
entry:
  %t$10 = alloca i64
  store i64 %value, ptr %t$10
  %t$11 = call i64 @sprout_gc_push_i64_root(ptr %t$10)
  %t$0 = call i64 @bytes_to_utf8(i64 %value)
  %t$12 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$1 = call i64 @sprout_tag(i64 %t$0)
  %t$2 = add i64 0, 7
  %t$3 = icmp eq i64 %t$1, %t$2
  br i1 %t$3, label %wrepack_hit_2, label %wrepack_next_2
wrepack_hit_2:
  %t$4 = call i64 @sprout_field(i64 %t$0, i64 0)
  %t$5$r0 = insertvalue { i64, i64 } undef, i64 %t$1, 0
  %t$5$r1 = insertvalue { i64, i64 } %t$5$r0, i64 %t$4, 1
  ret { i64, i64 } %t$5$r1
wrepack_next_2:
  %t$6 = add i64 0, 8
  %t$7 = icmp eq i64 %t$1, %t$6
  br i1 %t$7, label %wrepack_hit_6, label %wrepack_next_6
wrepack_hit_6:
  %t$8 = call i64 @sprout_field(i64 %t$0, i64 0)
  %t$9$r0 = insertvalue { i64, i64 } undef, i64 %t$1, 0
  %t$9$r1 = insertvalue { i64, i64 } %t$9$r0, i64 %t$8, 1
  ret { i64, i64 } %t$9$r1
wrepack_next_6:
  call void @sprout_abort_match()
  unreachable
}

define { i64, i64 } @stdlib.env.get_worker(i64 %name) {
entry:
  %t$0$st = call { i64, i64 } @env_get_unboxed(i64 %name)
  %t$0 = extractvalue { i64, i64 } %t$0$st, 0
  %t$1 = extractvalue { i64, i64 } %t$0$st, 1
  %t$2$r0 = insertvalue { i64, i64 } undef, i64 %t$0, 0
  %t$2$r1 = insertvalue { i64, i64 } %t$2$r0, i64 %t$1, 1
  ret { i64, i64 } %t$2$r1
}

define i32 @main(i32 %argc, ptr %argv) {
entry:
  %argv_set = call i64 @sprout_set_argv(i32 %argc, ptr %argv)
  %cname_ptr_0 = getelementptr inbounds [8 x i8], ptr @.cname.0, i64 0, i64 0
  %cfkinds_ptr_0 = getelementptr inbounds [1 x i8], ptr @.cfkinds.0, i64 0, i64 0
  %creg_0 = call i64 @sprout_register_ctor(i64 0, ptr %cname_ptr_0, i64 0, ptr %cfkinds_ptr_0)
  %cname_ptr_1 = getelementptr inbounds [5 x i8], ptr @.cname.1, i64 0, i64 0
  %cfkinds_ptr_1 = getelementptr inbounds [2 x i8], ptr @.cfkinds.1, i64 0, i64 0
  %creg_1 = call i64 @sprout_register_ctor(i64 1, ptr %cname_ptr_1, i64 1, ptr %cfkinds_ptr_1)
  %cname_ptr_2 = getelementptr inbounds [12 x i8], ptr @.cname.2, i64 0, i64 0
  %cfkinds_ptr_2 = getelementptr inbounds [2 x i8], ptr @.cfkinds.2, i64 0, i64 0
  %creg_2 = call i64 @sprout_register_ctor(i64 2, ptr %cname_ptr_2, i64 1, ptr %cfkinds_ptr_2)
  %cname_ptr_3 = getelementptr inbounds [15 x i8], ptr @.cname.3, i64 0, i64 0
  %cfkinds_ptr_3 = getelementptr inbounds [2 x i8], ptr @.cfkinds.3, i64 0, i64 0
  %creg_3 = call i64 @sprout_register_ctor(i64 3, ptr %cname_ptr_3, i64 1, ptr %cfkinds_ptr_3)
  %cname_ptr_4 = getelementptr inbounds [15 x i8], ptr @.cname.4, i64 0, i64 0
  %cfkinds_ptr_4 = getelementptr inbounds [2 x i8], ptr @.cfkinds.4, i64 0, i64 0
  %creg_4 = call i64 @sprout_register_ctor(i64 4, ptr %cname_ptr_4, i64 1, ptr %cfkinds_ptr_4)
  %cname_ptr_5 = getelementptr inbounds [4 x i8], ptr @.cname.5, i64 0, i64 0
  %cfkinds_ptr_5 = getelementptr inbounds [1 x i8], ptr @.cfkinds.5, i64 0, i64 0
  %creg_5 = call i64 @sprout_register_ctor(i64 5, ptr %cname_ptr_5, i64 0, ptr %cfkinds_ptr_5)
  %cname_ptr_6 = getelementptr inbounds [5 x i8], ptr @.cname.6, i64 0, i64 0
  %cfkinds_ptr_6 = getelementptr inbounds [3 x i8], ptr @.cfkinds.6, i64 0, i64 0
  %creg_6 = call i64 @sprout_register_ctor(i64 6, ptr %cname_ptr_6, i64 2, ptr %cfkinds_ptr_6)
  %cname_ptr_7 = getelementptr inbounds [3 x i8], ptr @.cname.7, i64 0, i64 0
  %cfkinds_ptr_7 = getelementptr inbounds [2 x i8], ptr @.cfkinds.7, i64 0, i64 0
  %creg_7 = call i64 @sprout_register_ctor(i64 7, ptr %cname_ptr_7, i64 1, ptr %cfkinds_ptr_7)
  %cname_ptr_8 = getelementptr inbounds [4 x i8], ptr @.cname.8, i64 0, i64 0
  %cfkinds_ptr_8 = getelementptr inbounds [2 x i8], ptr @.cfkinds.8, i64 0, i64 0
  %creg_8 = call i64 @sprout_register_ctor(i64 8, ptr %cname_ptr_8, i64 1, ptr %cfkinds_ptr_8)
  %cname_ptr_9 = getelementptr inbounds [10 x i8], ptr @.cname.9, i64 0, i64 0
  %cfkinds_ptr_9 = getelementptr inbounds [1 x i8], ptr @.cfkinds.9, i64 0, i64 0
  %creg_9 = call i64 @sprout_register_ctor(i64 9, ptr %cname_ptr_9, i64 0, ptr %cfkinds_ptr_9)
  %cname_ptr_10 = getelementptr inbounds [4 x i8], ptr @.cname.10, i64 0, i64 0
  %cfkinds_ptr_10 = getelementptr inbounds [2 x i8], ptr @.cfkinds.10, i64 0, i64 0
  %creg_10 = call i64 @sprout_register_ctor(i64 10, ptr %cname_ptr_10, i64 1, ptr %cfkinds_ptr_10)
  %cname_ptr_11 = getelementptr inbounds [5 x i8], ptr @.cname.11, i64 0, i64 0
  %cfkinds_ptr_11 = getelementptr inbounds [2 x i8], ptr @.cfkinds.11, i64 0, i64 0
  %creg_11 = call i64 @sprout_register_ctor(i64 11, ptr %cname_ptr_11, i64 1, ptr %cfkinds_ptr_11)
  %cname_ptr_12 = getelementptr inbounds [4 x i8], ptr @.cname.12, i64 0, i64 0
  %cfkinds_ptr_12 = getelementptr inbounds [2 x i8], ptr @.cfkinds.12, i64 0, i64 0
  %creg_12 = call i64 @sprout_register_ctor(i64 12, ptr %cname_ptr_12, i64 1, ptr %cfkinds_ptr_12)
  %cname_ptr_13 = getelementptr inbounds [9 x i8], ptr @.cname.13, i64 0, i64 0
  %cfkinds_ptr_13 = getelementptr inbounds [4 x i8], ptr @.cfkinds.13, i64 0, i64 0
  %creg_13 = call i64 @sprout_register_ctor(i64 13, ptr %cname_ptr_13, i64 3, ptr %cfkinds_ptr_13)
  %cname_ptr_14 = getelementptr inbounds [29 x i8], ptr @.cname.14, i64 0, i64 0
  %cfkinds_ptr_14 = getelementptr inbounds [2 x i8], ptr @.cfkinds.14, i64 0, i64 0
  %creg_14 = call i64 @sprout_register_ctor(i64 14, ptr %cname_ptr_14, i64 1, ptr %cfkinds_ptr_14)
  call i64 @__sprout_user_main()
  ret i32 0
}

