; Generated by sprout ir_lowering.sprout (M2 PR 2.3)
target triple = "unknown-unknown-unknown"
declare i64 @str_concat(i64, i64)
declare i1 @str_eq(ptr, ptr)
declare i64 @str_compare(i64, i64)
declare i64 @str_slice(i64, i64, i64)
declare i64 @int_to_string(i64)
declare i64 @char_to_string(i64)
declare i64 @sprout_gc_push_i64_root(ptr)
declare i64 @sprout_gc_pop_roots(i64)
declare i64 @sprout_gc_register_i64_root(ptr)
declare i64 @sprout_alloc_closure(i64, i64)
declare void @sprout_closure_arity_check(i64, i64)
declare i64 @sprout_alloc_tuple_blob(i64)
declare i64 @sprout_register_ctor(i64, ptr, i64, ptr)
declare i64 @sprout_tag(i64)
declare i64 @sprout_field(i64, i64)
declare void @sprout_abort_match() noreturn
declare i64 @panic(i64)
declare ptr @llvm.stacksave()
declare void @llvm.stackrestore(ptr)
declare { i64, i1 } @llvm.sadd.with.overflow.i64(i64, i64)
declare { i64, i1 } @llvm.ssub.with.overflow.i64(i64, i64)
declare { i64, i1 } @llvm.smul.with.overflow.i64(i64, i64)
declare i64 @sprout_alloc_obj(i64, i64)
declare { i64, i64 } @vector_get_unboxed(i64, i64)
declare { i64, i64 } @map_get_unboxed(i64, i64)
declare { i64, i64 } @map_nth_key_unboxed(i64, i64)
declare { i64, i64 } @map_nth_value_unboxed(i64, i64)
declare { i64, i64 } @bytes_get_unboxed(i64, i64)
declare { i64, i64 } @str_char_at_unboxed(i64, i64)
declare { i64, i64 } @argv_get_unboxed(i64)
declare { i64, i64 } @env_get_unboxed(i64)
declare i64 @print_str(ptr)
declare i64 @print_value(i64)
declare i64 @eprint_str(ptr)
declare i64 @argv_get(i64)
declare i64 @sprout_set_argv(i32, ptr)
declare i64 @analysis_check_source(ptr)
declare i64 @analysis_declared_names_in_source(ptr)
declare i64 @analysis_exported_names_in_source(ptr)
declare i64 @analysis_symbol_inventory_in_source(ptr)
declare i64 @analysis_diagnostics_in_source(ptr)
declare i64 @analysis_symbol_locations_in_source(ptr)
declare i64 @analysis_type_of_in_source(ptr, ptr)
declare i64 @analysis_eval_expr_in_source(ptr, ptr)
declare i64 @analysis_instances_in_source(ptr, ptr)
declare i64 @analysis_complete_in_state(ptr, ptr, ptr)

declare i64 @double_to_string(i64)
declare i64 @char_to_str(i64)
declare i64 @char_from_codepoint(i64)
declare i64 @to_double(i64)
declare i64 @string_concat_many(i64)
declare i64 @str_len(i64)
declare i64 @str_char_at(i64, i64)
declare i64 @str_find(i64, i64)
declare i64 @str_starts_with(i64, i64)
declare i64 @vector_empty()
declare i64 @vector_length(i64)
declare i64 @vector_get(i64, i64)
declare i64 @vector_set(i64, i64, i64)
declare i64 @vector_append(i64, i64)
declare i64 @vector_concat(i64, i64)
declare i64 @vector_from_list(i64)
declare i64 @map_empty()
declare i64 @map_get(i64, i64)
declare i64 @map_set(i64, i64, i64)
declare i64 @map_remove(i64, i64)
declare i64 @map_size(i64)
declare i64 @map_nth_key(i64, i64)
declare i64 @map_nth_value(i64, i64)
declare i64 @native_set_empty()
declare i64 @native_set_insert(i64, i64)
declare i64 @native_set_member(i64, i64)
declare i64 @native_set_to_list(i64)
declare i64 @native_set_size(i64)
declare i64 @ref_new(i64)
declare i64 @ref_read(i64)
declare i64 @ref_write(i64, i64)
@.str.0 = private unnamed_addr constant { i64, [39 x i8] } { i64 622602, [39 x i8] c"Int overflow in - (line 52, column 25)\00" }
@.str.1 = private unnamed_addr constant { i64, [39 x i8] } { i64 622602, [39 x i8] c"Int overflow in - (line 52, column 47)\00" }
@.str.2 = private unnamed_addr constant { i64, [41 x i8] } { i64 655370, [41 x i8] c"Int overflow in - (line 1721, column 10)\00" }
@.str.3 = private unnamed_addr constant { i64, [17 x i8] } { i64 262154, [17 x i8] c"division by zero\00" }
@.str.4 = private unnamed_addr constant { i64, [41 x i8] } { i64 655370, [41 x i8] c"Int overflow in / (line 1726, column 39)\00" }
@.str.5 = private unnamed_addr constant { i64, [41 x i8] } { i64 655370, [41 x i8] c"Int overflow in + (line 1748, column 33)\00" }
@.str.6 = private unnamed_addr constant { i64, [41 x i8] } { i64 655370, [41 x i8] c"Int overflow in * (line 1748, column 43)\00" }
@.str.7 = private unnamed_addr constant { i64, [41 x i8] } { i64 655370, [41 x i8] c"Int overflow in - (line 1748, column 49)\00" }
@.str.8 = private unnamed_addr constant { i64, [41 x i8] } { i64 655370, [41 x i8] c"Int overflow in - (line 1756, column 58)\00" }
@.str.9 = private unnamed_addr constant { i64, [6 x i8] } { i64 81930, [6 x i8] c"user=\00" }
@.str.10 = private unnamed_addr constant { i64, [9 x i8] } { i64 131082, [9 x i8] c" unread=\00" }
@.str.11 = private unnamed_addr constant { i64, [7 x i8] } { i64 98314, [7 x i8] c" next=\00" }
@.str.12 = private unnamed_addr constant { i64, [39 x i8] } { i64 622602, [39 x i8] c"Int overflow in + (line 24, column 23)\00" }
@.str.13 = private unnamed_addr constant { i64, [6 x i8] } { i64 81930, [6 x i8] c"user=\00" }
@.str.14 = private unnamed_addr constant { i64, [9 x i8] } { i64 131082, [9 x i8] c" unread=\00" }
@.str.15 = private unnamed_addr constant { i64, [7 x i8] } { i64 98314, [7 x i8] c" next=\00" }
@.str.16 = private unnamed_addr constant { i64, [39 x i8] } { i64 622602, [39 x i8] c"Int overflow in + (line 29, column 48)\00" }
@.str.17 = private unnamed_addr constant { i64, [4 x i8] } { i64 49162, [4 x i8] c"Ada\00" }
@.str.18 = private unnamed_addr constant { i64, [2 x i8] } { i64 16394, [2 x i8] c"3\00" }
@.str.19 = private unnamed_addr constant { i64, [8 x i8] } { i64 114698, [8 x i8] c"Hello, \00" }
@.str.20 = private unnamed_addr constant { i64, [4 x i8] } { i64 49162, [4 x i8] c" ! \00" }
@.str.21 = private unnamed_addr constant { i64, [18 x i8] } { i64 278538, [18 x i8] c"template status: \00" }
@.str.22 = private unnamed_addr constant { i64, [20 x i8] } { i64 311306, [20 x i8] c"concat equivalent: \00" }
@.str.23 = private unnamed_addr constant { i64, [31 x i8] } { i64 491530, [31 x i8] c"buffered line: %tmp = add i64 \00" }
@.str.24 = private unnamed_addr constant { i64, [3 x i8] } { i64 32778, [3 x i8] c", \00" }
@.str.25 = private unnamed_addr constant { i64, [39 x i8] } { i64 622602, [39 x i8] c"Int overflow in + (line 52, column 70)\00" }
@.cname.0 = private unnamed_addr constant [8 x i8] c"Nothing\00"
@.cfkinds.0 = private unnamed_addr constant [1 x i8] c"\00"
@.cname.1 = private unnamed_addr constant [5 x i8] c"Just\00"
@.cfkinds.1 = private unnamed_addr constant [2 x i8] c"_\00"
@.cname.2 = private unnamed_addr constant [12 x i8] c"TemplateLit\00"
@.cfkinds.2 = private unnamed_addr constant [2 x i8] c"s\00"
@.cname.3 = private unnamed_addr constant [15 x i8] c"TemplateInterp\00"
@.cfkinds.3 = private unnamed_addr constant [2 x i8] c"s\00"
@.cname.4 = private unnamed_addr constant [15 x i8] c"StringTemplate\00"
@.cfkinds.4 = private unnamed_addr constant [2 x i8] c"p\00"
@.cname.5 = private unnamed_addr constant [4 x i8] c"Nil\00"
@.cfkinds.5 = private unnamed_addr constant [1 x i8] c"\00"
@.cname.6 = private unnamed_addr constant [5 x i8] c"Cons\00"
@.cfkinds.6 = private unnamed_addr constant [3 x i8] c"_p\00"
@.cname.7 = private unnamed_addr constant [3 x i8] c"Ok\00"
@.cfkinds.7 = private unnamed_addr constant [2 x i8] c"_\00"
@.cname.8 = private unnamed_addr constant [4 x i8] c"Err\00"
@.cfkinds.8 = private unnamed_addr constant [2 x i8] c"_\00"
@.cname.9 = private unnamed_addr constant [10 x i8] c"DivByZero\00"
@.cfkinds.9 = private unnamed_addr constant [1 x i8] c"\00"
@.cname.10 = private unnamed_addr constant [4 x i8] c"Vec\00"
@.cfkinds.10 = private unnamed_addr constant [2 x i8] c"p\00"
@.cname.11 = private unnamed_addr constant [5 x i8] c"Dict\00"
@.cfkinds.11 = private unnamed_addr constant [2 x i8] c"p\00"
@.cname.12 = private unnamed_addr constant [4 x i8] c"Set\00"
@.cfkinds.12 = private unnamed_addr constant [2 x i8] c"p\00"
@.cname.13 = private unnamed_addr constant [9 x i8] c"IntRange\00"
@.cfkinds.13 = private unnamed_addr constant [4 x i8] c"iii\00"
@pow10_clamp = private constant i64 400

define i64 @template_to_string(i64 %p$t) {
entry:
  %t$0 = call i64 @sprout_tag(i64 %p$t)
  br label %arm_0_1
arm_0_1:
  %t$3 = add i64 0, 4
  %t$4 = icmp eq i64 %t$0, %t$3
  br i1 %t$4, label %body_0_1, label %arm_1_1
body_0_1:
  %t$5 = call i64 @sprout_field(i64 %p$t, i64 0)
  %t$8 = alloca i64
  store i64 %t$5, ptr %t$8
  %t$9 = call i64 @sprout_gc_push_i64_root(ptr %t$8)
  %t$6 = call i64 @template_parts_to_strings(i64 %t$5)
  %t$10 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$11 = alloca i64
  store i64 %t$6, ptr %t$11
  %t$12 = call i64 @sprout_gc_push_i64_root(ptr %t$11)
  %t$7 = call i64 @string_concat_many(i64 %t$6)
  %t$13 = call i64 @sprout_gc_pop_roots(i64 1)
  br label %join_1
arm_1_1:
  call void @sprout_abort_match()
  unreachable
join_1:
  %t$2 = phi i64 [%t$7, %body_0_1]
  ret i64 %t$2
}

define i64 @template_parts_to_strings(i64 %p$parts) {
entry:
  %t$0 = call i64 @sprout_tag(i64 %p$parts)
  br label %arm_0_1
arm_0_1:
  %t$3 = add i64 0, 5
  %t$4 = icmp eq i64 %t$0, %t$3
  br i1 %t$4, label %body_0_1, label %arm_1_1
body_0_1:
  %t$5 = call i64 @sprout_alloc_obj(i64 5, i64 0)
  br label %join_1
arm_1_1:
  %t$6 = add i64 0, 6
  %t$7 = icmp eq i64 %t$0, %t$6
  br i1 %t$7, label %body_1_1, label %arm_2_1
body_1_1:
  %t$8 = call i64 @sprout_field(i64 %p$parts, i64 0)
  %t$9 = call i64 @sprout_field(i64 %p$parts, i64 1)
  %t$10 = call i64 @sprout_tag(i64 %t$8)
  br label %arm_0_11
arm_0_11:
  %t$13 = add i64 0, 2
  %t$14 = icmp eq i64 %t$10, %t$13
  br i1 %t$14, label %body_0_11, label %arm_1_11
body_0_11:
  %t$15 = call i64 @sprout_field(i64 %t$8, i64 0)
  %t$23 = alloca i64
  store i64 %t$9, ptr %t$23
  %t$24 = call i64 @sprout_gc_push_i64_root(ptr %t$23)
  %t$25 = alloca i64
  store i64 %t$15, ptr %t$25
  %t$26 = call i64 @sprout_gc_push_i64_root(ptr %t$25)
  %t$16 = call i64 @template_parts_to_strings(i64 %t$9)
  %t$27 = alloca i64
  store i64 %t$16, ptr %t$27
  %t$28 = call i64 @sprout_gc_push_i64_root(ptr %t$27)
  %t$17 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$17$ptr = inttoptr i64 %t$17 to ptr
  %t$17$f0 = getelementptr i64, ptr %t$17$ptr, i64 0
  store i64 %t$15, ptr %t$17$f0
  %t$17$f1 = getelementptr i64, ptr %t$17$ptr, i64 1
  store i64 %t$16, ptr %t$17$f1
  %t$29 = call i64 @sprout_gc_pop_roots(i64 3)
  br label %join_11
arm_1_11:
  %t$18 = add i64 0, 3
  %t$19 = icmp eq i64 %t$10, %t$18
  br i1 %t$19, label %body_1_11, label %arm_2_11
body_1_11:
  %t$20 = call i64 @sprout_field(i64 %t$8, i64 0)
  %t$30 = alloca i64
  store i64 %t$9, ptr %t$30
  %t$31 = call i64 @sprout_gc_push_i64_root(ptr %t$30)
  %t$32 = alloca i64
  store i64 %t$20, ptr %t$32
  %t$33 = call i64 @sprout_gc_push_i64_root(ptr %t$32)
  %t$21 = call i64 @template_parts_to_strings(i64 %t$9)
  %t$34 = alloca i64
  store i64 %t$21, ptr %t$34
  %t$35 = call i64 @sprout_gc_push_i64_root(ptr %t$34)
  %t$22 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$22$ptr = inttoptr i64 %t$22 to ptr
  %t$22$f0 = getelementptr i64, ptr %t$22$ptr, i64 0
  store i64 %t$20, ptr %t$22$f0
  %t$22$f1 = getelementptr i64, ptr %t$22$ptr, i64 1
  store i64 %t$21, ptr %t$22$f1
  %t$36 = call i64 @sprout_gc_pop_roots(i64 3)
  br label %join_11
arm_2_11:
  call void @sprout_abort_match()
  unreachable
join_11:
  %t$12 = phi i64 [%t$17, %body_0_11], [%t$22, %body_1_11]
  br label %join_1
arm_2_1:
  call void @sprout_abort_match()
  unreachable
join_1:
  %t$2 = phi i64 [%t$5, %body_0_1], [%t$12, %join_11]
  ret i64 %t$2
}

define i64 @min_int() {
entry:
  %t$0 = add i64 0, 0
  %t$1 = add i64 0, 9223372036854775807
  %t$2$agg = call { i64, i1 } @llvm.ssub.with.overflow.i64(i64 %t$0, i64 %t$1)
  %t$2 = extractvalue { i64, i1 } %t$2$agg, 0
  %t$2$ovf = extractvalue { i64, i1 } %t$2$agg, 1
  br i1 %t$2$ovf, label %ovfpanic_2, label %ovfok_2
ovfpanic_2:
  %t$3 = getelementptr inbounds { i64, [39 x i8] }, ptr @.str.0, i64 0, i32 1, i64 0
  %t$4 = ptrtoint ptr %t$3 to i64
  call i64 @panic(i64 %t$4)
  unreachable
ovfok_2:
  %t$5 = add i64 0, 1
  %t$6$agg = call { i64, i1 } @llvm.ssub.with.overflow.i64(i64 %t$2, i64 %t$5)
  %t$6 = extractvalue { i64, i1 } %t$6$agg, 0
  %t$6$ovf = extractvalue { i64, i1 } %t$6$agg, 1
  br i1 %t$6$ovf, label %ovfpanic_6, label %ovfok_6
ovfpanic_6:
  %t$7 = getelementptr inbounds { i64, [39 x i8] }, ptr @.str.1, i64 0, i32 1, i64 0
  %t$8 = ptrtoint ptr %t$7 to i64
  call i64 @panic(i64 %t$8)
  unreachable
ovfok_6:
  ret i64 %t$6
}

define i64 @digit_value(i64 %p$c) {
entry:
  %t$0 = add i64 0, 48
  %t$1 = icmp eq i64 %p$c, %t$0
  %t$2 = zext i1 %t$1 to i64
  %t$74 = trunc i64 %t$2 to i1
  br i1 %t$74, label %then_3, label %else_3
then_3:
  %t$5 = add i64 0, 0
  br label %join_3
else_3:
  %t$6 = add i64 0, 49
  %t$7 = icmp eq i64 %p$c, %t$6
  %t$8 = zext i1 %t$7 to i64
  %t$73 = trunc i64 %t$8 to i1
  br i1 %t$73, label %then_9, label %else_9
then_9:
  %t$11 = add i64 0, 1
  br label %join_9
else_9:
  %t$12 = add i64 0, 50
  %t$13 = icmp eq i64 %p$c, %t$12
  %t$14 = zext i1 %t$13 to i64
  %t$72 = trunc i64 %t$14 to i1
  br i1 %t$72, label %then_15, label %else_15
then_15:
  %t$17 = add i64 0, 2
  br label %join_15
else_15:
  %t$18 = add i64 0, 51
  %t$19 = icmp eq i64 %p$c, %t$18
  %t$20 = zext i1 %t$19 to i64
  %t$71 = trunc i64 %t$20 to i1
  br i1 %t$71, label %then_21, label %else_21
then_21:
  %t$23 = add i64 0, 3
  br label %join_21
else_21:
  %t$24 = add i64 0, 52
  %t$25 = icmp eq i64 %p$c, %t$24
  %t$26 = zext i1 %t$25 to i64
  %t$70 = trunc i64 %t$26 to i1
  br i1 %t$70, label %then_27, label %else_27
then_27:
  %t$29 = add i64 0, 4
  br label %join_27
else_27:
  %t$30 = add i64 0, 53
  %t$31 = icmp eq i64 %p$c, %t$30
  %t$32 = zext i1 %t$31 to i64
  %t$69 = trunc i64 %t$32 to i1
  br i1 %t$69, label %then_33, label %else_33
then_33:
  %t$35 = add i64 0, 5
  br label %join_33
else_33:
  %t$36 = add i64 0, 54
  %t$37 = icmp eq i64 %p$c, %t$36
  %t$38 = zext i1 %t$37 to i64
  %t$68 = trunc i64 %t$38 to i1
  br i1 %t$68, label %then_39, label %else_39
then_39:
  %t$41 = add i64 0, 6
  br label %join_39
else_39:
  %t$42 = add i64 0, 55
  %t$43 = icmp eq i64 %p$c, %t$42
  %t$44 = zext i1 %t$43 to i64
  %t$67 = trunc i64 %t$44 to i1
  br i1 %t$67, label %then_45, label %else_45
then_45:
  %t$47 = add i64 0, 7
  br label %join_45
else_45:
  %t$48 = add i64 0, 56
  %t$49 = icmp eq i64 %p$c, %t$48
  %t$50 = zext i1 %t$49 to i64
  %t$66 = trunc i64 %t$50 to i1
  br i1 %t$66, label %then_51, label %else_51
then_51:
  %t$53 = add i64 0, 8
  br label %join_51
else_51:
  %t$54 = add i64 0, 57
  %t$55 = icmp eq i64 %p$c, %t$54
  %t$56 = zext i1 %t$55 to i64
  %t$65 = trunc i64 %t$56 to i1
  br i1 %t$65, label %then_57, label %else_57
then_57:
  %t$59 = add i64 0, 9
  br label %join_57
else_57:
  %t$60 = add i64 0, 0
  %t$61 = add i64 0, 1
  %t$62$agg = call { i64, i1 } @llvm.ssub.with.overflow.i64(i64 %t$60, i64 %t$61)
  %t$62 = extractvalue { i64, i1 } %t$62$agg, 0
  %t$62$ovf = extractvalue { i64, i1 } %t$62$agg, 1
  br i1 %t$62$ovf, label %ovfpanic_62, label %ovfok_62
ovfpanic_62:
  %t$63 = getelementptr inbounds { i64, [41 x i8] }, ptr @.str.2, i64 0, i32 1, i64 0
  %t$64 = ptrtoint ptr %t$63 to i64
  call i64 @panic(i64 %t$64)
  unreachable
ovfok_62:
  br label %join_57
join_57:
  %t$58 = phi i64 [%t$59, %then_57], [%t$62, %ovfok_62]
  br label %join_51
join_51:
  %t$52 = phi i64 [%t$53, %then_51], [%t$58, %join_57]
  br label %join_45
join_45:
  %t$46 = phi i64 [%t$47, %then_45], [%t$52, %join_51]
  br label %join_39
join_39:
  %t$40 = phi i64 [%t$41, %then_39], [%t$46, %join_45]
  br label %join_33
join_33:
  %t$34 = phi i64 [%t$35, %then_33], [%t$40, %join_39]
  br label %join_27
join_27:
  %t$28 = phi i64 [%t$29, %then_27], [%t$34, %join_33]
  br label %join_21
join_21:
  %t$22 = phi i64 [%t$23, %then_21], [%t$28, %join_27]
  br label %join_15
join_15:
  %t$16 = phi i64 [%t$17, %then_15], [%t$22, %join_21]
  br label %join_9
join_9:
  %t$10 = phi i64 [%t$11, %then_9], [%t$16, %join_15]
  br label %join_3
join_3:
  %t$4 = phi i64 [%t$5, %then_3], [%t$10, %join_9]
  ret i64 %t$4
}

define i64 @min_int_div10() {
entry:
  %t$0 = call i64 @min_int()
  %t$1 = add i64 0, 10
  %t$2 = icmp eq i64 %t$1, 0
  br i1 %t$2, label %divpanic_2, label %divchk2_2
divpanic_2:
  %t$3 = getelementptr inbounds { i64, [17 x i8] }, ptr @.str.3, i64 0, i32 1, i64 0
  %t$4 = ptrtoint ptr %t$3 to i64
  call i64 @panic(i64 %t$4)
  unreachable
divchk2_2:
  %t$5 = icmp eq i64 %t$1, -1
  br i1 %t$5, label %divovfchk_2, label %divok_2
divovfchk_2:
  %t$6 = icmp eq i64 %t$0, -9223372036854775808
  br i1 %t$6, label %divovfpanic_2, label %divok_2
divovfpanic_2:
  %t$7 = getelementptr inbounds { i64, [41 x i8] }, ptr @.str.4, i64 0, i32 1, i64 0
  %t$8 = ptrtoint ptr %t$7 to i64
  call i64 @panic(i64 %t$8)
  unreachable
divok_2:
  %t$9 = sdiv i64 %t$0, %t$1
  ret i64 %t$9
}

define i64 @accum_digits(i64 %p$s$in, i64 %p$i$in, i64 %p$acc$in, i64 %p$seen$in) {
entry:
  %t$57 = alloca i64
  store i64 %p$s$in, ptr %t$57
  %t$58 = alloca i64
  store i64 %p$i$in, ptr %t$58
  %t$59 = alloca i64
  store i64 %p$acc$in, ptr %t$59
  %t$60 = alloca i64
  store i64 %p$seen$in, ptr %t$60
  %t$61 = call ptr @llvm.stacksave()
  br label %tco_loop
tco_loop:
  %p$s = load i64, ptr %t$57
  %p$i = load i64, ptr %t$58
  %p$acc = load i64, ptr %t$59
  %p$seen = load i64, ptr %t$60
  %t$0$st = call { i64, i64 } @str_char_at_unboxed(i64 %p$s, i64 %p$i)
  %t$0 = extractvalue { i64, i64 } %t$0$st, 0
  %t$1 = extractvalue { i64, i64 } %t$0$st, 1
  br label %arm_0_2
arm_0_2:
  %t$4 = add i64 0, 0
  %t$5 = icmp eq i64 %t$0, %t$4
  br i1 %t$5, label %body_0_2, label %arm_1_2
body_0_2:
  %t$10 = trunc i64 %p$seen to i1
  br i1 %t$10, label %then_6, label %else_6
then_6:
  %t$8 = call i64 @sprout_alloc_obj(i64 1, i64 1)
  %t$8$ptr = inttoptr i64 %t$8 to ptr
  %t$8$f0 = getelementptr i64, ptr %t$8$ptr, i64 0
  store i64 %p$acc, ptr %t$8$f0
  br label %join_6
else_6:
  %t$9 = call i64 @sprout_alloc_obj(i64 0, i64 0)
  br label %join_6
join_6:
  %t$7 = phi i64 [%t$8, %then_6], [%t$9, %else_6]
  br label %join_2
arm_1_2:
  %t$11 = add i64 0, 1
  %t$12 = icmp eq i64 %t$0, %t$11
  br i1 %t$12, label %body_1_2, label %arm_2_2
body_1_2:
  %t$13 = call i64 @digit_value(i64 %t$1)
  br label %arm_0_14
arm_0_14:
  %t$16 = add i64 0, 0
  %t$17 = icmp slt i64 %t$13, %t$16
  %t$18 = zext i1 %t$17 to i64
  %t$56 = trunc i64 %t$18 to i1
  br i1 %t$56, label %then_19, label %else_19
then_19:
  %t$21 = call i64 @sprout_alloc_obj(i64 0, i64 0)
  br label %join_19
else_19:
  %t$22 = call i64 @min_int_div10()
  %t$23 = icmp slt i64 %p$acc, %t$22
  %t$24 = zext i1 %t$23 to i64
  %t$55 = trunc i64 %t$24 to i1
  br i1 %t$55, label %then_25, label %else_25
then_25:
  %t$27 = call i64 @sprout_alloc_obj(i64 0, i64 0)
  br label %join_25
else_25:
  %t$28 = call i64 @min_int_div10()
  %t$29 = icmp eq i64 %p$acc, %t$28
  %t$30 = zext i1 %t$29 to i64
  %t$37 = trunc i64 %t$30 to i1
  br i1 %t$37, label %then_31, label %else_31
then_31:
  %t$33 = add i64 0, 8
  %t$34 = icmp sgt i64 %t$13, %t$33
  %t$35 = zext i1 %t$34 to i64
  br label %join_31
else_31:
  %t$36 = add i64 0, 0
  br label %join_31
join_31:
  %t$32 = phi i64 [%t$35, %then_31], [%t$36, %else_31]
  %t$54 = trunc i64 %t$32 to i1
  br i1 %t$54, label %then_38, label %else_38
then_38:
  %t$40 = call i64 @sprout_alloc_obj(i64 0, i64 0)
  br label %join_38
else_38:
  %t$41 = add i64 0, 1
  %t$42$agg = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %p$i, i64 %t$41)
  %t$42 = extractvalue { i64, i1 } %t$42$agg, 0
  %t$42$ovf = extractvalue { i64, i1 } %t$42$agg, 1
  br i1 %t$42$ovf, label %ovfpanic_42, label %ovfok_42
ovfpanic_42:
  %t$43 = getelementptr inbounds { i64, [41 x i8] }, ptr @.str.5, i64 0, i32 1, i64 0
  %t$44 = ptrtoint ptr %t$43 to i64
  call i64 @panic(i64 %t$44)
  unreachable
ovfok_42:
  %t$45 = add i64 0, 10
  %t$46$agg = call { i64, i1 } @llvm.smul.with.overflow.i64(i64 %p$acc, i64 %t$45)
  %t$46 = extractvalue { i64, i1 } %t$46$agg, 0
  %t$46$ovf = extractvalue { i64, i1 } %t$46$agg, 1
  br i1 %t$46$ovf, label %ovfpanic_46, label %ovfok_46
ovfpanic_46:
  %t$47 = getelementptr inbounds { i64, [41 x i8] }, ptr @.str.6, i64 0, i32 1, i64 0
  %t$48 = ptrtoint ptr %t$47 to i64
  call i64 @panic(i64 %t$48)
  unreachable
ovfok_46:
  %t$49$agg = call { i64, i1 } @llvm.ssub.with.overflow.i64(i64 %t$46, i64 %t$13)
  %t$49 = extractvalue { i64, i1 } %t$49$agg, 0
  %t$49$ovf = extractvalue { i64, i1 } %t$49$agg, 1
  br i1 %t$49$ovf, label %ovfpanic_49, label %ovfok_49
ovfpanic_49:
  %t$50 = getelementptr inbounds { i64, [41 x i8] }, ptr @.str.7, i64 0, i32 1, i64 0
  %t$51 = ptrtoint ptr %t$50 to i64
  call i64 @panic(i64 %t$51)
  unreachable
ovfok_49:
  %t$52 = add i64 0, 1
  store i64 %p$s, ptr %t$57
  store i64 %t$42, ptr %t$58
  store i64 %t$49, ptr %t$59
  store i64 %t$52, ptr %t$60
  call void @llvm.stackrestore(ptr %t$61)
  br label %tco_loop
join_38:
  %t$39 = phi i64 [%t$40, %then_38]
  br label %join_25
join_25:
  %t$26 = phi i64 [%t$27, %then_25], [%t$39, %join_38]
  br label %join_19
join_19:
  %t$20 = phi i64 [%t$21, %then_19], [%t$26, %join_25]
  br label %join_14
arm_1_14:
  call void @sprout_abort_match()
  unreachable
join_14:
  %t$15 = phi i64 [%t$20, %join_19]
  br label %join_2
arm_2_2:
  call void @sprout_abort_match()
  unreachable
join_2:
  %t$3 = phi i64 [%t$7, %join_6], [%t$15, %join_14]
  ret i64 %t$3
}

define i64 @positive_from_neg_magnitude(i64 %p$m) {
entry:
  %t$0 = call i64 @sprout_tag(i64 %p$m)
  br label %arm_0_1
arm_0_1:
  %t$3 = add i64 0, 0
  %t$4 = icmp eq i64 %t$0, %t$3
  br i1 %t$4, label %body_0_1, label %arm_1_1
body_0_1:
  %t$5 = call i64 @sprout_alloc_obj(i64 0, i64 0)
  br label %join_1
arm_1_1:
  %t$6 = add i64 0, 1
  %t$7 = icmp eq i64 %t$0, %t$6
  br i1 %t$7, label %body_1_1, label %arm_2_1
body_1_1:
  %t$8 = call i64 @sprout_field(i64 %p$m, i64 0)
  %t$9 = call i64 @min_int()
  %t$10 = icmp eq i64 %t$8, %t$9
  %t$11 = zext i1 %t$10 to i64
  %t$20 = trunc i64 %t$11 to i1
  br i1 %t$20, label %then_12, label %else_12
then_12:
  %t$14 = call i64 @sprout_alloc_obj(i64 0, i64 0)
  br label %join_12
else_12:
  %t$15 = add i64 0, 0
  %t$16$agg = call { i64, i1 } @llvm.ssub.with.overflow.i64(i64 %t$15, i64 %t$8)
  %t$16 = extractvalue { i64, i1 } %t$16$agg, 0
  %t$16$ovf = extractvalue { i64, i1 } %t$16$agg, 1
  br i1 %t$16$ovf, label %ovfpanic_16, label %ovfok_16
ovfpanic_16:
  %t$17 = getelementptr inbounds { i64, [41 x i8] }, ptr @.str.8, i64 0, i32 1, i64 0
  %t$18 = ptrtoint ptr %t$17 to i64
  call i64 @panic(i64 %t$18)
  unreachable
ovfok_16:
  %t$19 = call i64 @sprout_alloc_obj(i64 1, i64 1)
  %t$19$ptr = inttoptr i64 %t$19 to ptr
  %t$19$f0 = getelementptr i64, ptr %t$19$ptr, i64 0
  store i64 %t$16, ptr %t$19$f0
  br label %join_12
join_12:
  %t$13 = phi i64 [%t$14, %then_12], [%t$19, %ovfok_16]
  br label %join_1
arm_2_1:
  call void @sprout_abort_match()
  unreachable
join_1:
  %t$2 = phi i64 [%t$5, %body_0_1], [%t$13, %join_12]
  ret i64 %t$2
}

define i64 @parse_int(i64 %p$s) {
entry:
  %t$0 = add i64 0, 0
  %t$1$st = call { i64, i64 } @str_char_at_unboxed(i64 %p$s, i64 %t$0)
  %t$1 = extractvalue { i64, i64 } %t$1$st, 0
  %t$2 = extractvalue { i64, i64 } %t$1$st, 1
  br label %arm_0_3
arm_0_3:
  %t$5 = add i64 0, 0
  %t$6 = icmp eq i64 %t$1, %t$5
  br i1 %t$6, label %body_0_3, label %arm_1_3
body_0_3:
  %t$7 = call i64 @sprout_alloc_obj(i64 0, i64 0)
  br label %join_3
arm_1_3:
  %t$8 = add i64 0, 1
  %t$9 = icmp eq i64 %t$1, %t$8
  br i1 %t$9, label %body_1_3, label %arm_2_3
body_1_3:
  %t$10 = add i64 0, 45
  %t$11 = icmp eq i64 %t$2, %t$10
  %t$12 = zext i1 %t$11 to i64
  %t$24 = trunc i64 %t$12 to i1
  br i1 %t$24, label %then_13, label %else_13
then_13:
  %t$15 = add i64 0, 1
  %t$16 = add i64 0, 0
  %t$17 = add i64 0, 0
  %t$25 = alloca i64
  store i64 %p$s, ptr %t$25
  %t$26 = call i64 @sprout_gc_push_i64_root(ptr %t$25)
  %t$18 = call i64 @accum_digits(i64 %p$s, i64 %t$15, i64 %t$16, i64 %t$17)
  %t$27 = call i64 @sprout_gc_pop_roots(i64 1)
  br label %join_13
else_13:
  %t$19 = add i64 0, 0
  %t$20 = add i64 0, 0
  %t$21 = add i64 0, 0
  %t$28 = alloca i64
  store i64 %p$s, ptr %t$28
  %t$29 = call i64 @sprout_gc_push_i64_root(ptr %t$28)
  %t$22 = call i64 @accum_digits(i64 %p$s, i64 %t$19, i64 %t$20, i64 %t$21)
  %t$30 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$31 = alloca i64
  store i64 %t$22, ptr %t$31
  %t$32 = call i64 @sprout_gc_push_i64_root(ptr %t$31)
  %t$23 = call i64 @positive_from_neg_magnitude(i64 %t$22)
  %t$33 = call i64 @sprout_gc_pop_roots(i64 1)
  br label %join_13
join_13:
  %t$14 = phi i64 [%t$18, %then_13], [%t$23, %else_13]
  br label %join_3
arm_2_3:
  call void @sprout_abort_match()
  unreachable
join_3:
  %t$4 = phi i64 [%t$7, %body_0_3], [%t$14, %join_13]
  ret i64 %t$4
}

define i64 @examples.string_templates.arg_or(i64 %p$index, i64 %p$fallback) {
entry:
  %t$0$st = call { i64, i64 } @argv_get_unboxed(i64 %p$index)
  %t$0 = extractvalue { i64, i64 } %t$0$st, 0
  %t$1 = extractvalue { i64, i64 } %t$0$st, 1
  br label %arm_0_2
arm_0_2:
  %t$4 = add i64 0, 0
  %t$5 = icmp eq i64 %t$0, %t$4
  br i1 %t$5, label %body_0_2, label %arm_1_2
body_0_2:
  br label %join_2
arm_1_2:
  %t$6 = add i64 0, 1
  %t$7 = icmp eq i64 %t$0, %t$6
  br i1 %t$7, label %body_1_2, label %arm_2_2
body_1_2:
  br label %join_2
arm_2_2:
  call void @sprout_abort_match()
  unreachable
join_2:
  %t$3 = phi i64 [%p$fallback, %body_0_2], [%t$1, %body_1_2]
  ret i64 %t$3
}

define i64 @examples.string_templates.concat_status_string(i64 %p$user, i64 %p$unread) {
entry:
  %t$0 = getelementptr inbounds { i64, [6 x i8] }, ptr @.str.9, i64 0, i32 1, i64 0
  %t$1 = ptrtoint ptr %t$0 to i64
  %t$17 = alloca i64
  store i64 %p$user, ptr %t$17
  %t$18 = call i64 @sprout_gc_push_i64_root(ptr %t$17)
  %t$19 = alloca i64
  store i64 %t$1, ptr %t$19
  %t$20 = call i64 @sprout_gc_push_i64_root(ptr %t$19)
  %t$2 = call i64 @__tc_Semigroup_String_append(i64 %t$1, i64 %p$user)
  %t$21 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$3 = getelementptr inbounds { i64, [9 x i8] }, ptr @.str.10, i64 0, i32 1, i64 0
  %t$4 = ptrtoint ptr %t$3 to i64
  %t$22 = alloca i64
  store i64 %t$2, ptr %t$22
  %t$23 = call i64 @sprout_gc_push_i64_root(ptr %t$22)
  %t$24 = alloca i64
  store i64 %t$4, ptr %t$24
  %t$25 = call i64 @sprout_gc_push_i64_root(ptr %t$24)
  %t$5 = call i64 @__tc_Semigroup_String_append(i64 %t$2, i64 %t$4)
  %t$26 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$27 = alloca i64
  store i64 %t$5, ptr %t$27
  %t$28 = call i64 @sprout_gc_push_i64_root(ptr %t$27)
  %t$6 = call i64 @__tc_ToString_Int_to_string(i64 %p$unread)
  %t$29 = alloca i64
  store i64 %t$6, ptr %t$29
  %t$30 = call i64 @sprout_gc_push_i64_root(ptr %t$29)
  %t$7 = call i64 @__tc_Semigroup_String_append(i64 %t$5, i64 %t$6)
  %t$31 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$8 = getelementptr inbounds { i64, [7 x i8] }, ptr @.str.11, i64 0, i32 1, i64 0
  %t$9 = ptrtoint ptr %t$8 to i64
  %t$32 = alloca i64
  store i64 %t$7, ptr %t$32
  %t$33 = call i64 @sprout_gc_push_i64_root(ptr %t$32)
  %t$34 = alloca i64
  store i64 %t$9, ptr %t$34
  %t$35 = call i64 @sprout_gc_push_i64_root(ptr %t$34)
  %t$10 = call i64 @__tc_Semigroup_String_append(i64 %t$7, i64 %t$9)
  %t$36 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$11 = add i64 0, 1
  %t$12$agg = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %p$unread, i64 %t$11)
  %t$12 = extractvalue { i64, i1 } %t$12$agg, 0
  %t$12$ovf = extractvalue { i64, i1 } %t$12$agg, 1
  br i1 %t$12$ovf, label %ovfpanic_12, label %ovfok_12
ovfpanic_12:
  %t$13 = getelementptr inbounds { i64, [39 x i8] }, ptr @.str.12, i64 0, i32 1, i64 0
  %t$14 = ptrtoint ptr %t$13 to i64
  call i64 @panic(i64 %t$14)
  unreachable
ovfok_12:
  %t$37 = alloca i64
  store i64 %t$10, ptr %t$37
  %t$38 = call i64 @sprout_gc_push_i64_root(ptr %t$37)
  %t$15 = call i64 @__tc_ToString_Int_to_string(i64 %t$12)
  %t$39 = alloca i64
  store i64 %t$15, ptr %t$39
  %t$40 = call i64 @sprout_gc_push_i64_root(ptr %t$39)
  %t$16 = call i64 @__tc_Semigroup_String_append(i64 %t$10, i64 %t$15)
  %t$41 = call i64 @sprout_gc_pop_roots(i64 2)
  ret i64 %t$16
}

define i64 @examples.string_templates.template_status_string(i64 %p$user, i64 %p$unread) {
entry:
  %t$0 = getelementptr inbounds { i64, [6 x i8] }, ptr @.str.13, i64 0, i32 1, i64 0
  %t$1 = ptrtoint ptr %t$0 to i64
  %t$2 = call i64 @__tc_ToString_String_to_string(i64 %p$user)
  %t$3 = getelementptr inbounds { i64, [9 x i8] }, ptr @.str.14, i64 0, i32 1, i64 0
  %t$4 = ptrtoint ptr %t$3 to i64
  %t$21 = alloca i64
  store i64 %t$1, ptr %t$21
  %t$22 = call i64 @sprout_gc_push_i64_root(ptr %t$21)
  %t$23 = alloca i64
  store i64 %t$2, ptr %t$23
  %t$24 = call i64 @sprout_gc_push_i64_root(ptr %t$23)
  %t$25 = alloca i64
  store i64 %t$4, ptr %t$25
  %t$26 = call i64 @sprout_gc_push_i64_root(ptr %t$25)
  %t$5 = call i64 @__tc_ToString_Int_to_string(i64 %p$unread)
  %t$6 = getelementptr inbounds { i64, [7 x i8] }, ptr @.str.15, i64 0, i32 1, i64 0
  %t$7 = ptrtoint ptr %t$6 to i64
  %t$8 = add i64 0, 1
  %t$9$agg = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %p$unread, i64 %t$8)
  %t$9 = extractvalue { i64, i1 } %t$9$agg, 0
  %t$9$ovf = extractvalue { i64, i1 } %t$9$agg, 1
  %t$27 = call i64 @sprout_gc_pop_roots(i64 3)
  br i1 %t$9$ovf, label %ovfpanic_9, label %ovfok_9
ovfpanic_9:
  %t$10 = getelementptr inbounds { i64, [39 x i8] }, ptr @.str.16, i64 0, i32 1, i64 0
  %t$11 = ptrtoint ptr %t$10 to i64
  call i64 @panic(i64 %t$11)
  unreachable
ovfok_9:
  %t$28 = alloca i64
  store i64 %t$7, ptr %t$28
  %t$29 = call i64 @sprout_gc_push_i64_root(ptr %t$28)
  %t$30 = alloca i64
  store i64 %t$5, ptr %t$30
  %t$31 = call i64 @sprout_gc_push_i64_root(ptr %t$30)
  %t$32 = alloca i64
  store i64 %t$4, ptr %t$32
  %t$33 = call i64 @sprout_gc_push_i64_root(ptr %t$32)
  %t$34 = alloca i64
  store i64 %t$2, ptr %t$34
  %t$35 = call i64 @sprout_gc_push_i64_root(ptr %t$34)
  %t$36 = alloca i64
  store i64 %t$1, ptr %t$36
  %t$37 = call i64 @sprout_gc_push_i64_root(ptr %t$36)
  %t$12 = call i64 @__tc_ToString_Int_to_string(i64 %t$9)
  %t$38 = alloca i64
  store i64 %t$12, ptr %t$38
  %t$39 = call i64 @sprout_gc_push_i64_root(ptr %t$38)
  %t$13 = call i64 @sprout_alloc_obj(i64 5, i64 0)
  %t$40 = alloca i64
  store i64 %t$13, ptr %t$40
  %t$41 = call i64 @sprout_gc_push_i64_root(ptr %t$40)
  %t$14 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$14$ptr = inttoptr i64 %t$14 to ptr
  %t$14$f0 = getelementptr i64, ptr %t$14$ptr, i64 0
  store i64 %t$12, ptr %t$14$f0
  %t$14$f1 = getelementptr i64, ptr %t$14$ptr, i64 1
  store i64 %t$13, ptr %t$14$f1
  %t$42 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$43 = alloca i64
  store i64 %t$14, ptr %t$43
  %t$44 = call i64 @sprout_gc_push_i64_root(ptr %t$43)
  %t$15 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$15$ptr = inttoptr i64 %t$15 to ptr
  %t$15$f0 = getelementptr i64, ptr %t$15$ptr, i64 0
  store i64 %t$7, ptr %t$15$f0
  %t$15$f1 = getelementptr i64, ptr %t$15$ptr, i64 1
  store i64 %t$14, ptr %t$15$f1
  %t$45 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$46 = alloca i64
  store i64 %t$15, ptr %t$46
  %t$47 = call i64 @sprout_gc_push_i64_root(ptr %t$46)
  %t$16 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$16$ptr = inttoptr i64 %t$16 to ptr
  %t$16$f0 = getelementptr i64, ptr %t$16$ptr, i64 0
  store i64 %t$5, ptr %t$16$f0
  %t$16$f1 = getelementptr i64, ptr %t$16$ptr, i64 1
  store i64 %t$15, ptr %t$16$f1
  %t$48 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$49 = alloca i64
  store i64 %t$16, ptr %t$49
  %t$50 = call i64 @sprout_gc_push_i64_root(ptr %t$49)
  %t$17 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$17$ptr = inttoptr i64 %t$17 to ptr
  %t$17$f0 = getelementptr i64, ptr %t$17$ptr, i64 0
  store i64 %t$4, ptr %t$17$f0
  %t$17$f1 = getelementptr i64, ptr %t$17$ptr, i64 1
  store i64 %t$16, ptr %t$17$f1
  %t$51 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$52 = alloca i64
  store i64 %t$17, ptr %t$52
  %t$53 = call i64 @sprout_gc_push_i64_root(ptr %t$52)
  %t$18 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$18$ptr = inttoptr i64 %t$18 to ptr
  %t$18$f0 = getelementptr i64, ptr %t$18$ptr, i64 0
  store i64 %t$2, ptr %t$18$f0
  %t$18$f1 = getelementptr i64, ptr %t$18$ptr, i64 1
  store i64 %t$17, ptr %t$18$f1
  %t$54 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$55 = alloca i64
  store i64 %t$18, ptr %t$55
  %t$56 = call i64 @sprout_gc_push_i64_root(ptr %t$55)
  %t$19 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$19$ptr = inttoptr i64 %t$19 to ptr
  %t$19$f0 = getelementptr i64, ptr %t$19$ptr, i64 0
  store i64 %t$1, ptr %t$19$f0
  %t$19$f1 = getelementptr i64, ptr %t$19$ptr, i64 1
  store i64 %t$18, ptr %t$19$f1
  %t$57 = call i64 @sprout_gc_pop_roots(i64 6)
  %t$58 = alloca i64
  store i64 %t$19, ptr %t$58
  %t$59 = call i64 @sprout_gc_push_i64_root(ptr %t$58)
  %t$20 = call i64 @string_concat_many(i64 %t$19)
  %t$60 = call i64 @sprout_gc_pop_roots(i64 1)
  ret i64 %t$20
}

define i64 @examples.string_templates.emit_buffered(i64 %p$line) {
entry:
  %t$2 = alloca i64
  store i64 %p$line, ptr %t$2
  %t$3 = call i64 @sprout_gc_push_i64_root(ptr %t$2)
  %t$0 = call i64 @template_to_string(i64 %p$line)
  %t$4 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$1$ptr = inttoptr i64 %t$0 to ptr
  %t$1 = call i64 @print_str(ptr %t$1$ptr)
  ret i64 %t$1
}

define i64 @examples.string_templates.int_or_zero(i64 %p$m) {
entry:
  %t$0 = call i64 @sprout_tag(i64 %p$m)
  br label %arm_0_1
arm_0_1:
  %t$3 = add i64 0, 1
  %t$4 = icmp eq i64 %t$0, %t$3
  br i1 %t$4, label %body_0_1, label %arm_1_1
body_0_1:
  %t$5 = call i64 @sprout_field(i64 %p$m, i64 0)
  br label %join_1
arm_1_1:
  %t$6 = add i64 0, 0
  %t$7 = icmp eq i64 %t$0, %t$6
  br i1 %t$7, label %body_1_1, label %arm_2_1
body_1_1:
  %t$8 = add i64 0, 0
  br label %join_1
arm_2_1:
  call void @sprout_abort_match()
  unreachable
join_1:
  %t$2 = phi i64 [%t$5, %body_0_1], [%t$8, %body_1_1]
  ret i64 %t$2
}

define i64 @__sprout_user_main() {
entry:
  %t$0 = add i64 0, 0
  %t$1 = getelementptr inbounds { i64, [4 x i8] }, ptr @.str.17, i64 0, i32 1, i64 0
  %t$2 = ptrtoint ptr %t$1 to i64
  %t$3 = call i64 @examples.string_templates.arg_or(i64 %t$0, i64 %t$2)
  %t$4 = add i64 0, 1
  %t$5 = getelementptr inbounds { i64, [2 x i8] }, ptr @.str.18, i64 0, i32 1, i64 0
  %t$6 = ptrtoint ptr %t$5 to i64
  %t$7 = call i64 @examples.string_templates.arg_or(i64 %t$4, i64 %t$6)
  %t$60 = alloca i64
  store i64 %t$3, ptr %t$60
  %t$61 = call i64 @sprout_gc_push_i64_root(ptr %t$60)
  %t$62 = alloca i64
  store i64 %t$7, ptr %t$62
  %t$63 = call i64 @sprout_gc_push_i64_root(ptr %t$62)
  %t$8 = call i64 @parse_int(i64 %t$7)
  %t$64 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$9 = call i64 @examples.string_templates.int_or_zero(i64 %t$8)
  %t$10 = call i64 @examples.string_templates.template_status_string(i64 %t$3, i64 %t$9)
  %t$65 = alloca i64
  store i64 %t$10, ptr %t$65
  %t$66 = call i64 @sprout_gc_push_i64_root(ptr %t$65)
  %t$11 = call i64 @examples.string_templates.concat_status_string(i64 %t$3, i64 %t$9)
  %t$12 = getelementptr inbounds { i64, [8 x i8] }, ptr @.str.19, i64 0, i32 1, i64 0
  %t$13 = ptrtoint ptr %t$12 to i64
  %t$14 = call i64 @__tc_ToString_String_to_string(i64 %t$3)
  %t$15 = getelementptr inbounds { i64, [4 x i8] }, ptr @.str.20, i64 0, i32 1, i64 0
  %t$16 = ptrtoint ptr %t$15 to i64
  %t$67 = alloca i64
  store i64 %t$11, ptr %t$67
  %t$68 = call i64 @sprout_gc_push_i64_root(ptr %t$67)
  %t$69 = alloca i64
  store i64 %t$13, ptr %t$69
  %t$70 = call i64 @sprout_gc_push_i64_root(ptr %t$69)
  %t$71 = alloca i64
  store i64 %t$14, ptr %t$71
  %t$72 = call i64 @sprout_gc_push_i64_root(ptr %t$71)
  %t$73 = alloca i64
  store i64 %t$16, ptr %t$73
  %t$74 = call i64 @sprout_gc_push_i64_root(ptr %t$73)
  %t$17 = call i64 @sprout_alloc_obj(i64 5, i64 0)
  %t$75 = alloca i64
  store i64 %t$17, ptr %t$75
  %t$76 = call i64 @sprout_gc_push_i64_root(ptr %t$75)
  %t$18 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$18$ptr = inttoptr i64 %t$18 to ptr
  %t$18$f0 = getelementptr i64, ptr %t$18$ptr, i64 0
  store i64 %t$16, ptr %t$18$f0
  %t$18$f1 = getelementptr i64, ptr %t$18$ptr, i64 1
  store i64 %t$17, ptr %t$18$f1
  %t$77 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$78 = alloca i64
  store i64 %t$18, ptr %t$78
  %t$79 = call i64 @sprout_gc_push_i64_root(ptr %t$78)
  %t$19 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$19$ptr = inttoptr i64 %t$19 to ptr
  %t$19$f0 = getelementptr i64, ptr %t$19$ptr, i64 0
  store i64 %t$14, ptr %t$19$f0
  %t$19$f1 = getelementptr i64, ptr %t$19$ptr, i64 1
  store i64 %t$18, ptr %t$19$f1
  %t$80 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$81 = alloca i64
  store i64 %t$19, ptr %t$81
  %t$82 = call i64 @sprout_gc_push_i64_root(ptr %t$81)
  %t$20 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$20$ptr = inttoptr i64 %t$20 to ptr
  %t$20$f0 = getelementptr i64, ptr %t$20$ptr, i64 0
  store i64 %t$13, ptr %t$20$f0
  %t$20$f1 = getelementptr i64, ptr %t$20$ptr, i64 1
  store i64 %t$19, ptr %t$20$f1
  %t$83 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$84 = alloca i64
  store i64 %t$20, ptr %t$84
  %t$85 = call i64 @sprout_gc_push_i64_root(ptr %t$84)
  %t$21 = call i64 @string_concat_many(i64 %t$20)
  %t$86 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$22$ptr = inttoptr i64 %t$21 to ptr
  %t$22 = call i64 @print_str(ptr %t$22$ptr)
  %t$23 = getelementptr inbounds { i64, [18 x i8] }, ptr @.str.21, i64 0, i32 1, i64 0
  %t$24 = ptrtoint ptr %t$23 to i64
  %t$25 = call i64 @__tc_ToString_String_to_string(i64 %t$10)
  %t$87 = alloca i64
  store i64 %t$24, ptr %t$87
  %t$88 = call i64 @sprout_gc_push_i64_root(ptr %t$87)
  %t$89 = alloca i64
  store i64 %t$25, ptr %t$89
  %t$90 = call i64 @sprout_gc_push_i64_root(ptr %t$89)
  %t$26 = call i64 @sprout_alloc_obj(i64 5, i64 0)
  %t$91 = alloca i64
  store i64 %t$26, ptr %t$91
  %t$92 = call i64 @sprout_gc_push_i64_root(ptr %t$91)
  %t$27 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$27$ptr = inttoptr i64 %t$27 to ptr
  %t$27$f0 = getelementptr i64, ptr %t$27$ptr, i64 0
  store i64 %t$25, ptr %t$27$f0
  %t$27$f1 = getelementptr i64, ptr %t$27$ptr, i64 1
  store i64 %t$26, ptr %t$27$f1
  %t$93 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$94 = alloca i64
  store i64 %t$27, ptr %t$94
  %t$95 = call i64 @sprout_gc_push_i64_root(ptr %t$94)
  %t$28 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$28$ptr = inttoptr i64 %t$28 to ptr
  %t$28$f0 = getelementptr i64, ptr %t$28$ptr, i64 0
  store i64 %t$24, ptr %t$28$f0
  %t$28$f1 = getelementptr i64, ptr %t$28$ptr, i64 1
  store i64 %t$27, ptr %t$28$f1
  %t$96 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$97 = alloca i64
  store i64 %t$28, ptr %t$97
  %t$98 = call i64 @sprout_gc_push_i64_root(ptr %t$97)
  %t$29 = call i64 @string_concat_many(i64 %t$28)
  %t$99 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$30$ptr = inttoptr i64 %t$29 to ptr
  %t$30 = call i64 @print_str(ptr %t$30$ptr)
  %t$31 = getelementptr inbounds { i64, [20 x i8] }, ptr @.str.22, i64 0, i32 1, i64 0
  %t$32 = ptrtoint ptr %t$31 to i64
  %t$33 = call i64 @__tc_ToString_String_to_string(i64 %t$11)
  %t$100 = alloca i64
  store i64 %t$32, ptr %t$100
  %t$101 = call i64 @sprout_gc_push_i64_root(ptr %t$100)
  %t$102 = alloca i64
  store i64 %t$33, ptr %t$102
  %t$103 = call i64 @sprout_gc_push_i64_root(ptr %t$102)
  %t$34 = call i64 @sprout_alloc_obj(i64 5, i64 0)
  %t$104 = alloca i64
  store i64 %t$34, ptr %t$104
  %t$105 = call i64 @sprout_gc_push_i64_root(ptr %t$104)
  %t$35 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$35$ptr = inttoptr i64 %t$35 to ptr
  %t$35$f0 = getelementptr i64, ptr %t$35$ptr, i64 0
  store i64 %t$33, ptr %t$35$f0
  %t$35$f1 = getelementptr i64, ptr %t$35$ptr, i64 1
  store i64 %t$34, ptr %t$35$f1
  %t$106 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$107 = alloca i64
  store i64 %t$35, ptr %t$107
  %t$108 = call i64 @sprout_gc_push_i64_root(ptr %t$107)
  %t$36 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$36$ptr = inttoptr i64 %t$36 to ptr
  %t$36$f0 = getelementptr i64, ptr %t$36$ptr, i64 0
  store i64 %t$32, ptr %t$36$f0
  %t$36$f1 = getelementptr i64, ptr %t$36$ptr, i64 1
  store i64 %t$35, ptr %t$36$f1
  %t$109 = call i64 @sprout_gc_pop_roots(i64 5)
  %t$110 = alloca i64
  store i64 %t$36, ptr %t$110
  %t$111 = call i64 @sprout_gc_push_i64_root(ptr %t$110)
  %t$37 = call i64 @string_concat_many(i64 %t$36)
  %t$112 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$38$ptr = inttoptr i64 %t$37 to ptr
  %t$38 = call i64 @print_str(ptr %t$38$ptr)
  %t$39 = getelementptr inbounds { i64, [31 x i8] }, ptr @.str.23, i64 0, i32 1, i64 0
  %t$40 = ptrtoint ptr %t$39 to i64
  %t$113 = alloca i64
  store i64 %t$40, ptr %t$113
  %t$114 = call i64 @sprout_gc_push_i64_root(ptr %t$113)
  %t$41 = call i64 @sprout_alloc_obj(i64 2, i64 1)
  %t$41$ptr = inttoptr i64 %t$41 to ptr
  %t$41$f0 = getelementptr i64, ptr %t$41$ptr, i64 0
  store i64 %t$40, ptr %t$41$f0
  %t$115 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$116 = alloca i64
  store i64 %t$41, ptr %t$116
  %t$117 = call i64 @sprout_gc_push_i64_root(ptr %t$116)
  %t$42 = call i64 @__tc_ToString_Int_to_string(i64 %t$9)
  %t$118 = alloca i64
  store i64 %t$42, ptr %t$118
  %t$119 = call i64 @sprout_gc_push_i64_root(ptr %t$118)
  %t$43 = call i64 @sprout_alloc_obj(i64 3, i64 1)
  %t$43$ptr = inttoptr i64 %t$43 to ptr
  %t$43$f0 = getelementptr i64, ptr %t$43$ptr, i64 0
  store i64 %t$42, ptr %t$43$f0
  %t$120 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$44 = getelementptr inbounds { i64, [3 x i8] }, ptr @.str.24, i64 0, i32 1, i64 0
  %t$45 = ptrtoint ptr %t$44 to i64
  %t$121 = alloca i64
  store i64 %t$43, ptr %t$121
  %t$122 = call i64 @sprout_gc_push_i64_root(ptr %t$121)
  %t$123 = alloca i64
  store i64 %t$45, ptr %t$123
  %t$124 = call i64 @sprout_gc_push_i64_root(ptr %t$123)
  %t$46 = call i64 @sprout_alloc_obj(i64 2, i64 1)
  %t$46$ptr = inttoptr i64 %t$46 to ptr
  %t$46$f0 = getelementptr i64, ptr %t$46$ptr, i64 0
  store i64 %t$45, ptr %t$46$f0
  %t$125 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$47 = add i64 0, 1
  %t$48$agg = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %t$9, i64 %t$47)
  %t$48 = extractvalue { i64, i1 } %t$48$agg, 0
  %t$48$ovf = extractvalue { i64, i1 } %t$48$agg, 1
  %t$126 = call i64 @sprout_gc_pop_roots(i64 2)
  br i1 %t$48$ovf, label %ovfpanic_48, label %ovfok_48
ovfpanic_48:
  %t$49 = getelementptr inbounds { i64, [39 x i8] }, ptr @.str.25, i64 0, i32 1, i64 0
  %t$50 = ptrtoint ptr %t$49 to i64
  call i64 @panic(i64 %t$50)
  unreachable
ovfok_48:
  %t$127 = alloca i64
  store i64 %t$46, ptr %t$127
  %t$128 = call i64 @sprout_gc_push_i64_root(ptr %t$127)
  %t$129 = alloca i64
  store i64 %t$43, ptr %t$129
  %t$130 = call i64 @sprout_gc_push_i64_root(ptr %t$129)
  %t$131 = alloca i64
  store i64 %t$41, ptr %t$131
  %t$132 = call i64 @sprout_gc_push_i64_root(ptr %t$131)
  %t$51 = call i64 @__tc_ToString_Int_to_string(i64 %t$48)
  %t$133 = alloca i64
  store i64 %t$51, ptr %t$133
  %t$134 = call i64 @sprout_gc_push_i64_root(ptr %t$133)
  %t$52 = call i64 @sprout_alloc_obj(i64 3, i64 1)
  %t$52$ptr = inttoptr i64 %t$52 to ptr
  %t$52$f0 = getelementptr i64, ptr %t$52$ptr, i64 0
  store i64 %t$51, ptr %t$52$f0
  %t$135 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$136 = alloca i64
  store i64 %t$52, ptr %t$136
  %t$137 = call i64 @sprout_gc_push_i64_root(ptr %t$136)
  %t$53 = call i64 @sprout_alloc_obj(i64 5, i64 0)
  %t$138 = alloca i64
  store i64 %t$53, ptr %t$138
  %t$139 = call i64 @sprout_gc_push_i64_root(ptr %t$138)
  %t$54 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$54$ptr = inttoptr i64 %t$54 to ptr
  %t$54$f0 = getelementptr i64, ptr %t$54$ptr, i64 0
  store i64 %t$52, ptr %t$54$f0
  %t$54$f1 = getelementptr i64, ptr %t$54$ptr, i64 1
  store i64 %t$53, ptr %t$54$f1
  %t$140 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$141 = alloca i64
  store i64 %t$54, ptr %t$141
  %t$142 = call i64 @sprout_gc_push_i64_root(ptr %t$141)
  %t$55 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$55$ptr = inttoptr i64 %t$55 to ptr
  %t$55$f0 = getelementptr i64, ptr %t$55$ptr, i64 0
  store i64 %t$46, ptr %t$55$f0
  %t$55$f1 = getelementptr i64, ptr %t$55$ptr, i64 1
  store i64 %t$54, ptr %t$55$f1
  %t$143 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$144 = alloca i64
  store i64 %t$55, ptr %t$144
  %t$145 = call i64 @sprout_gc_push_i64_root(ptr %t$144)
  %t$56 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$56$ptr = inttoptr i64 %t$56 to ptr
  %t$56$f0 = getelementptr i64, ptr %t$56$ptr, i64 0
  store i64 %t$43, ptr %t$56$f0
  %t$56$f1 = getelementptr i64, ptr %t$56$ptr, i64 1
  store i64 %t$55, ptr %t$56$f1
  %t$146 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$147 = alloca i64
  store i64 %t$56, ptr %t$147
  %t$148 = call i64 @sprout_gc_push_i64_root(ptr %t$147)
  %t$57 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$57$ptr = inttoptr i64 %t$57 to ptr
  %t$57$f0 = getelementptr i64, ptr %t$57$ptr, i64 0
  store i64 %t$41, ptr %t$57$f0
  %t$57$f1 = getelementptr i64, ptr %t$57$ptr, i64 1
  store i64 %t$56, ptr %t$57$f1
  %t$149 = call i64 @sprout_gc_pop_roots(i64 4)
  %t$150 = alloca i64
  store i64 %t$57, ptr %t$150
  %t$151 = call i64 @sprout_gc_push_i64_root(ptr %t$150)
  %t$58 = call i64 @sprout_alloc_obj(i64 4, i64 1)
  %t$58$ptr = inttoptr i64 %t$58 to ptr
  %t$58$f0 = getelementptr i64, ptr %t$58$ptr, i64 0
  store i64 %t$57, ptr %t$58$f0
  %t$152 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$153 = alloca i64
  store i64 %t$58, ptr %t$153
  %t$154 = call i64 @sprout_gc_push_i64_root(ptr %t$153)
  %t$59 = call i64 @examples.string_templates.emit_buffered(i64 %t$58)
  %t$155 = call i64 @sprout_gc_pop_roots(i64 1)
  ret i64 %t$59
}

define i64 @__tc_Semigroup_String_append(i64 %p$left, i64 %p$right) {
entry:
  %t$0 = call i64 @str_concat(i64 %p$left, i64 %p$right)
  ret i64 %t$0
}

define i64 @__tc_ToString_Int_to_string(i64 %p$value) {
entry:
  %t$0 = call i64 @int_to_string(i64 %p$value)
  ret i64 %t$0
}

define i64 @__tc_ToString_String_to_string(i64 %p$value) {
entry:
  ret i64 %p$value
}

define i32 @main(i32 %argc, ptr %argv) {
entry:
  %argv_set = call i64 @sprout_set_argv(i32 %argc, ptr %argv)
  %cname_ptr_0 = getelementptr inbounds [8 x i8], ptr @.cname.0, i64 0, i64 0
  %cfkinds_ptr_0 = getelementptr inbounds [1 x i8], ptr @.cfkinds.0, i64 0, i64 0
  %creg_0 = call i64 @sprout_register_ctor(i64 0, ptr %cname_ptr_0, i64 0, ptr %cfkinds_ptr_0)
  %cname_ptr_1 = getelementptr inbounds [5 x i8], ptr @.cname.1, i64 0, i64 0
  %cfkinds_ptr_1 = getelementptr inbounds [2 x i8], ptr @.cfkinds.1, i64 0, i64 0
  %creg_1 = call i64 @sprout_register_ctor(i64 1, ptr %cname_ptr_1, i64 1, ptr %cfkinds_ptr_1)
  %cname_ptr_2 = getelementptr inbounds [12 x i8], ptr @.cname.2, i64 0, i64 0
  %cfkinds_ptr_2 = getelementptr inbounds [2 x i8], ptr @.cfkinds.2, i64 0, i64 0
  %creg_2 = call i64 @sprout_register_ctor(i64 2, ptr %cname_ptr_2, i64 1, ptr %cfkinds_ptr_2)
  %cname_ptr_3 = getelementptr inbounds [15 x i8], ptr @.cname.3, i64 0, i64 0
  %cfkinds_ptr_3 = getelementptr inbounds [2 x i8], ptr @.cfkinds.3, i64 0, i64 0
  %creg_3 = call i64 @sprout_register_ctor(i64 3, ptr %cname_ptr_3, i64 1, ptr %cfkinds_ptr_3)
  %cname_ptr_4 = getelementptr inbounds [15 x i8], ptr @.cname.4, i64 0, i64 0
  %cfkinds_ptr_4 = getelementptr inbounds [2 x i8], ptr @.cfkinds.4, i64 0, i64 0
  %creg_4 = call i64 @sprout_register_ctor(i64 4, ptr %cname_ptr_4, i64 1, ptr %cfkinds_ptr_4)
  %cname_ptr_5 = getelementptr inbounds [4 x i8], ptr @.cname.5, i64 0, i64 0
  %cfkinds_ptr_5 = getelementptr inbounds [1 x i8], ptr @.cfkinds.5, i64 0, i64 0
  %creg_5 = call i64 @sprout_register_ctor(i64 5, ptr %cname_ptr_5, i64 0, ptr %cfkinds_ptr_5)
  %cname_ptr_6 = getelementptr inbounds [5 x i8], ptr @.cname.6, i64 0, i64 0
  %cfkinds_ptr_6 = getelementptr inbounds [3 x i8], ptr @.cfkinds.6, i64 0, i64 0
  %creg_6 = call i64 @sprout_register_ctor(i64 6, ptr %cname_ptr_6, i64 2, ptr %cfkinds_ptr_6)
  %cname_ptr_7 = getelementptr inbounds [3 x i8], ptr @.cname.7, i64 0, i64 0
  %cfkinds_ptr_7 = getelementptr inbounds [2 x i8], ptr @.cfkinds.7, i64 0, i64 0
  %creg_7 = call i64 @sprout_register_ctor(i64 7, ptr %cname_ptr_7, i64 1, ptr %cfkinds_ptr_7)
  %cname_ptr_8 = getelementptr inbounds [4 x i8], ptr @.cname.8, i64 0, i64 0
  %cfkinds_ptr_8 = getelementptr inbounds [2 x i8], ptr @.cfkinds.8, i64 0, i64 0
  %creg_8 = call i64 @sprout_register_ctor(i64 8, ptr %cname_ptr_8, i64 1, ptr %cfkinds_ptr_8)
  %cname_ptr_9 = getelementptr inbounds [10 x i8], ptr @.cname.9, i64 0, i64 0
  %cfkinds_ptr_9 = getelementptr inbounds [1 x i8], ptr @.cfkinds.9, i64 0, i64 0
  %creg_9 = call i64 @sprout_register_ctor(i64 9, ptr %cname_ptr_9, i64 0, ptr %cfkinds_ptr_9)
  %cname_ptr_10 = getelementptr inbounds [4 x i8], ptr @.cname.10, i64 0, i64 0
  %cfkinds_ptr_10 = getelementptr inbounds [2 x i8], ptr @.cfkinds.10, i64 0, i64 0
  %creg_10 = call i64 @sprout_register_ctor(i64 10, ptr %cname_ptr_10, i64 1, ptr %cfkinds_ptr_10)
  %cname_ptr_11 = getelementptr inbounds [5 x i8], ptr @.cname.11, i64 0, i64 0
  %cfkinds_ptr_11 = getelementptr inbounds [2 x i8], ptr @.cfkinds.11, i64 0, i64 0
  %creg_11 = call i64 @sprout_register_ctor(i64 11, ptr %cname_ptr_11, i64 1, ptr %cfkinds_ptr_11)
  %cname_ptr_12 = getelementptr inbounds [4 x i8], ptr @.cname.12, i64 0, i64 0
  %cfkinds_ptr_12 = getelementptr inbounds [2 x i8], ptr @.cfkinds.12, i64 0, i64 0
  %creg_12 = call i64 @sprout_register_ctor(i64 12, ptr %cname_ptr_12, i64 1, ptr %cfkinds_ptr_12)
  %cname_ptr_13 = getelementptr inbounds [9 x i8], ptr @.cname.13, i64 0, i64 0
  %cfkinds_ptr_13 = getelementptr inbounds [4 x i8], ptr @.cfkinds.13, i64 0, i64 0
  %creg_13 = call i64 @sprout_register_ctor(i64 13, ptr %cname_ptr_13, i64 3, ptr %cfkinds_ptr_13)
  call i64 @__sprout_user_main()
  ret i32 0
}

