; Generated by sprout ir_lowering.sprout (M2 PR 2.3)
target triple = "unknown-unknown-unknown"
declare i64 @str_concat(i64, i64)
declare i1 @str_eq(ptr, ptr)
declare i64 @str_compare(i64, i64)
declare i64 @str_slice(i64, i64, i64)
declare i64 @int_to_string(i64)
declare i64 @char_to_string(i64)
declare i64 @sprout_gc_push_i64_root(ptr)
declare i64 @sprout_gc_pop_roots(i64)
declare i64 @sprout_gc_register_i64_root(ptr)
declare i64 @sprout_alloc_closure(i64, i64)
declare void @sprout_closure_arity_check(i64, i64)
declare i64 @sprout_alloc_tuple_blob(i64)
declare i64 @sprout_register_ctor(i64, ptr, i64, ptr)
declare i64 @sprout_tag(i64)
declare i64 @sprout_field(i64, i64)
declare void @sprout_abort_match() noreturn
declare i64 @panic(i64)
declare ptr @llvm.stacksave()
declare void @llvm.stackrestore(ptr)
declare i64 @sprout_alloc_obj(i64, i64)
declare { i64, i64 } @vector_get_unboxed(i64, i64)
declare { i64, i64 } @map_get_unboxed(i64, i64)
declare { i64, i64 } @map_nth_key_unboxed(i64, i64)
declare { i64, i64 } @map_nth_value_unboxed(i64, i64)
declare { i64, i64 } @bytes_get_unboxed(i64, i64)
declare { i64, i64 } @str_char_at_unboxed(i64, i64)
declare { i64, i64 } @argv_get_unboxed(i64)
declare { i64, i64 } @env_get_unboxed(i64)
declare i64 @print_str(ptr)
declare i64 @print_value(i64)
declare i64 @eprint_str(ptr)
declare i64 @argv_get(i64)
declare i64 @sprout_set_argv(i32, ptr)
declare i64 @analysis_check_source(ptr)
declare i64 @analysis_declared_names_in_source(ptr)
declare i64 @analysis_exported_names_in_source(ptr)
declare i64 @analysis_symbol_inventory_in_source(ptr)
declare i64 @analysis_diagnostics_in_source(ptr)
declare i64 @analysis_symbol_locations_in_source(ptr)
declare i64 @analysis_type_of_in_source(ptr, ptr)
declare i64 @analysis_eval_expr_in_source(ptr, ptr)
declare i64 @analysis_instances_in_source(ptr, ptr)
declare i64 @analysis_complete_in_state(ptr, ptr, ptr)

declare i64 @double_to_string(i64)
declare i64 @char_to_str(i64)
declare i64 @char_from_codepoint(i64)
declare i64 @to_double(i64)
declare i64 @string_concat_many(i64)
declare i64 @str_len(i64)
declare i64 @str_char_at(i64, i64)
declare i64 @str_find(i64, i64)
declare i64 @str_starts_with(i64, i64)
declare i64 @vector_empty()
declare i64 @vector_length(i64)
declare i64 @vector_get(i64, i64)
declare i64 @vector_set(i64, i64, i64)
declare i64 @vector_append(i64, i64)
declare i64 @vector_concat(i64, i64)
declare i64 @vector_from_list(i64)
declare i64 @map_empty()
declare i64 @map_get(i64, i64)
declare i64 @map_set(i64, i64, i64)
declare i64 @map_remove(i64, i64)
declare i64 @map_size(i64)
declare i64 @map_nth_key(i64, i64)
declare i64 @map_nth_value(i64, i64)
declare i64 @native_set_empty()
declare i64 @native_set_insert(i64, i64)
declare i64 @native_set_member(i64, i64)
declare i64 @native_set_to_list(i64)
declare i64 @native_set_size(i64)
declare i64 @ref_new(i64)
declare i64 @ref_read(i64)
declare i64 @ref_write(i64, i64)
declare i64 @bytes_empty()
declare i64 @bytes_singleton(i64)
declare i64 @bytes_length(i64)
declare i64 @bytes_get(i64, i64)
declare i64 @bytes_slice(i64, i64, i64)
declare i64 @bytes_append(i64, i64)
declare i64 @bytes_from_utf8(i64)
declare i64 @bytes_to_utf8(i64)
declare i64 @bytes_builder_empty()
declare i64 @bytes_builder_bytes(i64)
declare i64 @bytes_builder_byte(i64)
declare i64 @bytes_builder_u16_be(i64)
declare i64 @bytes_builder_u32_be(i64)
declare i64 @bytes_builder_append(i64, i64)
declare i64 @bytes_builder_build(i64)
declare i64 @str_byte_len(i64)
declare i64 @str_slice_bytes(i64, i64, i64)
declare i64 @str_starts_with_at_byte(i64, i64, i64)
declare i64 @str_split_lines(i64)
declare i64 @split_words(i64)
declare i64 @json_stringify(i64)
@.str.0 = private unnamed_addr constant { i64, [20 x i8] } { i64 311306, [20 x i8] c"non-finite number: \00" }
@.str.1 = private unnamed_addr constant { i64, [6 x i8] } { i64 81930, [6 x i8] c"title\00" }
@.str.2 = private unnamed_addr constant { i64, [6 x i8] } { i64 81930, [6 x i8] c"hello\00" }
@.str.3 = private unnamed_addr constant { i64, [6 x i8] } { i64 81930, [6 x i8] c"count\00" }
@.str.4 = private unnamed_addr constant { i64, [6 x i8] } { i64 81930, [6 x i8] c"items\00" }
@.str.5 = private unnamed_addr constant { i64, [2 x i8] } { i64 16394, [2 x i8] c"a\00" }
@.str.6 = private unnamed_addr constant { i64, [10 x i8] } { i64 147466, [10 x i8] c"refused: \00" }
@.cname.0 = private unnamed_addr constant [8 x i8] c"Nothing\00"
@.cfkinds.0 = private unnamed_addr constant [1 x i8] c"\00"
@.cname.1 = private unnamed_addr constant [5 x i8] c"Just\00"
@.cfkinds.1 = private unnamed_addr constant [2 x i8] c"_\00"
@.cname.2 = private unnamed_addr constant [12 x i8] c"TemplateLit\00"
@.cfkinds.2 = private unnamed_addr constant [2 x i8] c"s\00"
@.cname.3 = private unnamed_addr constant [15 x i8] c"TemplateInterp\00"
@.cfkinds.3 = private unnamed_addr constant [2 x i8] c"s\00"
@.cname.4 = private unnamed_addr constant [15 x i8] c"StringTemplate\00"
@.cfkinds.4 = private unnamed_addr constant [2 x i8] c"p\00"
@.cname.5 = private unnamed_addr constant [4 x i8] c"Nil\00"
@.cfkinds.5 = private unnamed_addr constant [1 x i8] c"\00"
@.cname.6 = private unnamed_addr constant [5 x i8] c"Cons\00"
@.cfkinds.6 = private unnamed_addr constant [3 x i8] c"_p\00"
@.cname.7 = private unnamed_addr constant [3 x i8] c"Ok\00"
@.cfkinds.7 = private unnamed_addr constant [2 x i8] c"_\00"
@.cname.8 = private unnamed_addr constant [4 x i8] c"Err\00"
@.cfkinds.8 = private unnamed_addr constant [2 x i8] c"_\00"
@.cname.9 = private unnamed_addr constant [10 x i8] c"DivByZero\00"
@.cfkinds.9 = private unnamed_addr constant [1 x i8] c"\00"
@.cname.10 = private unnamed_addr constant [4 x i8] c"Vec\00"
@.cfkinds.10 = private unnamed_addr constant [2 x i8] c"p\00"
@.cname.11 = private unnamed_addr constant [5 x i8] c"Dict\00"
@.cfkinds.11 = private unnamed_addr constant [2 x i8] c"p\00"
@.cname.12 = private unnamed_addr constant [4 x i8] c"Set\00"
@.cfkinds.12 = private unnamed_addr constant [2 x i8] c"p\00"
@.cname.13 = private unnamed_addr constant [9 x i8] c"IntRange\00"
@.cfkinds.13 = private unnamed_addr constant [4 x i8] c"iii\00"
@.cname.14 = private unnamed_addr constant [29 x i8] c"stdlib.bytes.Utf8DecodeError\00"
@.cfkinds.14 = private unnamed_addr constant [2 x i8] c"s\00"
@.cname.15 = private unnamed_addr constant [23 x i8] c"stdlib.json.JsonDecode\00"
@.cfkinds.15 = private unnamed_addr constant [2 x i8] c"s\00"
@.cname.16 = private unnamed_addr constant [26 x i8] c"stdlib.json.JsonNonFinite\00"
@.cfkinds.16 = private unnamed_addr constant [2 x i8] c"p\00"
@.cname.17 = private unnamed_addr constant [21 x i8] c"stdlib.json.JsonNull\00"
@.cfkinds.17 = private unnamed_addr constant [1 x i8] c"\00"
@.cname.18 = private unnamed_addr constant [21 x i8] c"stdlib.json.JsonBool\00"
@.cfkinds.18 = private unnamed_addr constant [2 x i8] c"b\00"
@.cname.19 = private unnamed_addr constant [20 x i8] c"stdlib.json.JsonInt\00"
@.cfkinds.19 = private unnamed_addr constant [2 x i8] c"i\00"
@.cname.20 = private unnamed_addr constant [22 x i8] c"stdlib.json.JsonFloat\00"
@.cfkinds.20 = private unnamed_addr constant [2 x i8] c"p\00"
@.cname.21 = private unnamed_addr constant [23 x i8] c"stdlib.json.JsonString\00"
@.cfkinds.21 = private unnamed_addr constant [2 x i8] c"s\00"
@.cname.22 = private unnamed_addr constant [22 x i8] c"stdlib.json.JsonArray\00"
@.cfkinds.22 = private unnamed_addr constant [2 x i8] c"p\00"
@.cname.23 = private unnamed_addr constant [23 x i8] c"stdlib.json.JsonObject\00"
@.cfkinds.23 = private unnamed_addr constant [2 x i8] c"p\00"
@.cname.24 = private unnamed_addr constant [26 x i8] c"stdlib.json.JsonArrayCons\00"
@.cfkinds.24 = private unnamed_addr constant [3 x i8] c"pp\00"
@.cname.25 = private unnamed_addr constant [25 x i8] c"stdlib.json.JsonArrayNil\00"
@.cfkinds.25 = private unnamed_addr constant [1 x i8] c"\00"
@.cname.26 = private unnamed_addr constant [27 x i8] c"stdlib.json.JsonObjectCons\00"
@.cfkinds.26 = private unnamed_addr constant [4 x i8] c"spp\00"
@.cname.27 = private unnamed_addr constant [26 x i8] c"stdlib.json.JsonObjectNil\00"
@.cfkinds.27 = private unnamed_addr constant [1 x i8] c"\00"
@.cname.28 = private unnamed_addr constant [26 x i8] c"stdlib.json.JsonArrayStep\00"
@.cfkinds.28 = private unnamed_addr constant [3 x i8] c"pp\00"
@.cname.29 = private unnamed_addr constant [27 x i8] c"stdlib.json.JsonObjectStep\00"
@.cfkinds.29 = private unnamed_addr constant [4 x i8] c"spp\00"

define i64 @stdlib.json.bool(i64 %value) {
entry:
  %t$0 = call i64 @sprout_alloc_obj(i64 18, i64 1)
  %t$0$ptr = inttoptr i64 %t$0 to ptr
  %t$0$f0 = getelementptr i64, ptr %t$0$ptr, i64 0
  store i64 %value, ptr %t$0$f0
  ret i64 %t$0
}

define i64 @stdlib.json.int(i64 %value) {
entry:
  %t$0 = call i64 @sprout_alloc_obj(i64 19, i64 1)
  %t$0$ptr = inttoptr i64 %t$0 to ptr
  %t$0$f0 = getelementptr i64, ptr %t$0$ptr, i64 0
  store i64 %value, ptr %t$0$f0
  ret i64 %t$0
}

define i64 @stdlib.json.string(i64 %value) {
entry:
  %t$1 = alloca i64
  store i64 %value, ptr %t$1
  %t$2 = call i64 @sprout_gc_push_i64_root(ptr %t$1)
  %t$0 = call i64 @sprout_alloc_obj(i64 21, i64 1)
  %t$0$ptr = inttoptr i64 %t$0 to ptr
  %t$0$f0 = getelementptr i64, ptr %t$0$ptr, i64 0
  store i64 %value, ptr %t$0$f0
  %t$3 = call i64 @sprout_gc_pop_roots(i64 1)
  ret i64 %t$0
}

define i64 @stdlib.json.encode(i64 %value, i64 %__tc_stdlib.json.JsonEncode_0_encode_json) {
entry:
  %t$1 = alloca i64
  store i64 %value, ptr %t$1
  %t$2 = call i64 @sprout_gc_push_i64_root(ptr %t$1)
  %t$3 = alloca i64
  store i64 %__tc_stdlib.json.JsonEncode_0_encode_json, ptr %t$3
  %t$4 = call i64 @sprout_gc_push_i64_root(ptr %t$3)
  %t$0 = call i64 @__cm_JsonEncode_encode_json(i64 %value, i64 %__tc_stdlib.json.JsonEncode_0_encode_json)
  %t$5 = call i64 @sprout_gc_pop_roots(i64 2)
  ret i64 %t$0
}

define i64 @stdlib.json.is_finite(i64 %x) {
entry:
  %t$0 = bitcast double 1.0 to i64
  %t$1 = bitcast double 0.0 to i64
  %t$2$la = bitcast i64 %t$0 to double
  %t$2$lb = bitcast i64 %t$1 to double
  %t$2$fr = fdiv double %t$2$la, %t$2$lb
  %t$2 = bitcast double %t$2$fr to i64
  br label %arm_0_3
arm_0_3:
  %t$5$fa = bitcast i64 %x to double
  %t$5$fb = bitcast i64 %x to double
  %t$5 = fcmp oeq double %t$5$fa, %t$5$fb
  %t$6 = zext i1 %t$5 to i64
  %t$12 = trunc i64 %t$6 to i1
  br i1 %t$12, label %then_7, label %else_7
then_7:
  %t$9$fa = bitcast i64 %x to double
  %t$9$fb = bitcast i64 %t$2 to double
  %t$9 = fcmp olt double %t$9$fa, %t$9$fb
  %t$10 = zext i1 %t$9 to i64
  br label %join_7
else_7:
  %t$11 = add i64 0, 0
  br label %join_7
join_7:
  %t$8 = phi i64 [%t$10, %then_7], [%t$11, %else_7]
  %t$20 = trunc i64 %t$8 to i1
  br i1 %t$20, label %then_13, label %else_13
then_13:
  %t$15 = bitcast double 0.0 to i64
  %t$16$la = bitcast i64 %t$15 to double
  %t$16$lb = bitcast i64 %t$2 to double
  %t$16$fr = fsub double %t$16$la, %t$16$lb
  %t$16 = bitcast double %t$16$fr to i64
  %t$17$fa = bitcast i64 %x to double
  %t$17$fb = bitcast i64 %t$16 to double
  %t$17 = fcmp ogt double %t$17$fa, %t$17$fb
  %t$18 = zext i1 %t$17 to i64
  br label %join_13
else_13:
  %t$19 = add i64 0, 0
  br label %join_13
join_13:
  %t$14 = phi i64 [%t$18, %then_13], [%t$19, %else_13]
  br label %join_3
arm_1_3:
  call void @sprout_abort_match()
  unreachable
join_3:
  %t$4 = phi i64 [%t$14, %join_13]
  ret i64 %t$4
}

define i64 @stdlib.json.first_non_finite(i64 %value) {
entry:
  %t$0 = call i64 @sprout_tag(i64 %value)
  br label %arm_0_1
arm_0_1:
  %t$3 = add i64 0, 20
  %t$4 = icmp eq i64 %t$0, %t$3
  br i1 %t$4, label %body_0_1, label %arm_1_1
body_0_1:
  %t$5 = call i64 @sprout_field(i64 %value, i64 0)
  %t$6 = call i64 @stdlib.json.is_finite(i64 %t$5)
  %t$11 = trunc i64 %t$6 to i1
  br i1 %t$11, label %then_7, label %else_7
then_7:
  %t$9 = call i64 @sprout_alloc_obj(i64 0, i64 0)
  br label %join_7
else_7:
  %t$21 = alloca i64
  store i64 %t$5, ptr %t$21
  %t$22 = call i64 @sprout_gc_push_i64_root(ptr %t$21)
  %t$10 = call i64 @sprout_alloc_obj(i64 1, i64 1)
  %t$10$ptr = inttoptr i64 %t$10 to ptr
  %t$10$f0 = getelementptr i64, ptr %t$10$ptr, i64 0
  store i64 %t$5, ptr %t$10$f0
  %t$23 = call i64 @sprout_gc_pop_roots(i64 1)
  br label %join_7
join_7:
  %t$8 = phi i64 [%t$9, %then_7], [%t$10, %else_7]
  br label %join_1
arm_1_1:
  %t$12 = add i64 0, 22
  %t$13 = icmp eq i64 %t$0, %t$12
  br i1 %t$13, label %body_1_1, label %arm_2_1
body_1_1:
  %t$14 = call i64 @sprout_field(i64 %value, i64 0)
  %t$24 = alloca i64
  store i64 %t$14, ptr %t$24
  %t$25 = call i64 @sprout_gc_push_i64_root(ptr %t$24)
  %t$15 = call i64 @stdlib.json.first_non_finite_array(i64 %t$14)
  %t$26 = call i64 @sprout_gc_pop_roots(i64 1)
  br label %join_1
arm_2_1:
  %t$16 = add i64 0, 23
  %t$17 = icmp eq i64 %t$0, %t$16
  br i1 %t$17, label %body_2_1, label %arm_3_1
body_2_1:
  %t$18 = call i64 @sprout_field(i64 %value, i64 0)
  %t$27 = alloca i64
  store i64 %t$18, ptr %t$27
  %t$28 = call i64 @sprout_gc_push_i64_root(ptr %t$27)
  %t$19 = call i64 @stdlib.json.first_non_finite_object(i64 %t$18)
  %t$29 = call i64 @sprout_gc_pop_roots(i64 1)
  br label %join_1
arm_3_1:
  %t$20 = call i64 @sprout_alloc_obj(i64 0, i64 0)
  br label %join_1
arm_4_1:
  call void @sprout_abort_match()
  unreachable
join_1:
  %t$2 = phi i64 [%t$8, %join_7], [%t$15, %body_1_1], [%t$19, %body_2_1], [%t$20, %arm_3_1]
  ret i64 %t$2
}

define i64 @stdlib.json.first_non_finite_array(i64 %arr$in) {
entry:
  %t$20 = alloca i64
  store i64 %arr$in, ptr %t$20
  %t$21 = call ptr @llvm.stacksave()
  br label %tco_loop
tco_loop:
  %arr = load i64, ptr %t$20
  %t$0 = call i64 @sprout_tag(i64 %arr)
  br label %arm_0_1
arm_0_1:
  %t$3 = add i64 0, 25
  %t$4 = icmp eq i64 %t$0, %t$3
  br i1 %t$4, label %body_0_1, label %arm_1_1
body_0_1:
  %t$5 = call i64 @sprout_alloc_obj(i64 0, i64 0)
  br label %join_1
arm_1_1:
  %t$6 = add i64 0, 24
  %t$7 = icmp eq i64 %t$0, %t$6
  br i1 %t$7, label %body_1_1, label %arm_2_1
body_1_1:
  %t$8 = call i64 @sprout_field(i64 %arr, i64 0)
  %t$9 = call i64 @sprout_field(i64 %arr, i64 1)
  %t$22 = alloca i64
  store i64 %t$8, ptr %t$22
  %t$23 = call i64 @sprout_gc_push_i64_root(ptr %t$22)
  %t$24 = alloca i64
  store i64 %t$9, ptr %t$24
  %t$25 = call i64 @sprout_gc_push_i64_root(ptr %t$24)
  %t$10$st = call { i64, i64 } @stdlib.json.first_non_finite_worker(i64 %t$8)
  %t$10 = extractvalue { i64, i64 } %t$10$st, 0
  %t$11 = extractvalue { i64, i64 } %t$10$st, 1
  %t$26 = call i64 @sprout_gc_pop_roots(i64 2)
  br label %arm_0_12
arm_0_12:
  %t$14 = add i64 0, 1
  %t$15 = icmp eq i64 %t$10, %t$14
  br i1 %t$15, label %body_0_12, label %arm_1_12
body_0_12:
  %t$27 = alloca i64
  store i64 %t$11, ptr %t$27
  %t$28 = call i64 @sprout_gc_push_i64_root(ptr %t$27)
  %t$16 = call i64 @sprout_alloc_obj(i64 1, i64 1)
  %t$16$ptr = inttoptr i64 %t$16 to ptr
  %t$16$f0 = getelementptr i64, ptr %t$16$ptr, i64 0
  store i64 %t$11, ptr %t$16$f0
  %t$29 = call i64 @sprout_gc_pop_roots(i64 1)
  br label %join_12
arm_1_12:
  %t$17 = add i64 0, 0
  %t$18 = icmp eq i64 %t$10, %t$17
  br i1 %t$18, label %body_1_12, label %arm_2_12
body_1_12:
  store i64 %t$9, ptr %t$20
  call void @llvm.stackrestore(ptr %t$21)
  br label %tco_loop
arm_2_12:
  call void @sprout_abort_match()
  unreachable
join_12:
  %t$13 = phi i64 [%t$16, %body_0_12]
  br label %join_1
arm_2_1:
  call void @sprout_abort_match()
  unreachable
join_1:
  %t$2 = phi i64 [%t$5, %body_0_1], [%t$13, %join_12]
  ret i64 %t$2
}

define i64 @stdlib.json.first_non_finite_object(i64 %obj$in) {
entry:
  %t$20 = alloca i64
  store i64 %obj$in, ptr %t$20
  %t$21 = call ptr @llvm.stacksave()
  br label %tco_loop
tco_loop:
  %obj = load i64, ptr %t$20
  %t$0 = call i64 @sprout_tag(i64 %obj)
  br label %arm_0_1
arm_0_1:
  %t$3 = add i64 0, 27
  %t$4 = icmp eq i64 %t$0, %t$3
  br i1 %t$4, label %body_0_1, label %arm_1_1
body_0_1:
  %t$5 = call i64 @sprout_alloc_obj(i64 0, i64 0)
  br label %join_1
arm_1_1:
  %t$6 = add i64 0, 26
  %t$7 = icmp eq i64 %t$0, %t$6
  br i1 %t$7, label %body_1_1, label %arm_2_1
body_1_1:
  %t$8 = call i64 @sprout_field(i64 %obj, i64 1)
  %t$9 = call i64 @sprout_field(i64 %obj, i64 2)
  %t$22 = alloca i64
  store i64 %t$8, ptr %t$22
  %t$23 = call i64 @sprout_gc_push_i64_root(ptr %t$22)
  %t$24 = alloca i64
  store i64 %t$9, ptr %t$24
  %t$25 = call i64 @sprout_gc_push_i64_root(ptr %t$24)
  %t$10$st = call { i64, i64 } @stdlib.json.first_non_finite_worker(i64 %t$8)
  %t$10 = extractvalue { i64, i64 } %t$10$st, 0
  %t$11 = extractvalue { i64, i64 } %t$10$st, 1
  %t$26 = call i64 @sprout_gc_pop_roots(i64 2)
  br label %arm_0_12
arm_0_12:
  %t$14 = add i64 0, 1
  %t$15 = icmp eq i64 %t$10, %t$14
  br i1 %t$15, label %body_0_12, label %arm_1_12
body_0_12:
  %t$27 = alloca i64
  store i64 %t$11, ptr %t$27
  %t$28 = call i64 @sprout_gc_push_i64_root(ptr %t$27)
  %t$16 = call i64 @sprout_alloc_obj(i64 1, i64 1)
  %t$16$ptr = inttoptr i64 %t$16 to ptr
  %t$16$f0 = getelementptr i64, ptr %t$16$ptr, i64 0
  store i64 %t$11, ptr %t$16$f0
  %t$29 = call i64 @sprout_gc_pop_roots(i64 1)
  br label %join_12
arm_1_12:
  %t$17 = add i64 0, 0
  %t$18 = icmp eq i64 %t$10, %t$17
  br i1 %t$18, label %body_1_12, label %arm_2_12
body_1_12:
  store i64 %t$9, ptr %t$20
  call void @llvm.stackrestore(ptr %t$21)
  br label %tco_loop
arm_2_12:
  call void @sprout_abort_match()
  unreachable
join_12:
  %t$13 = phi i64 [%t$16, %body_0_12]
  br label %join_1
arm_2_1:
  call void @sprout_abort_match()
  unreachable
join_1:
  %t$2 = phi i64 [%t$5, %body_0_1], [%t$13, %join_12]
  ret i64 %t$2
}

define i64 @stdlib.json.stringify(i64 %value) {
entry:
  %t$12 = alloca i64
  store i64 %value, ptr %t$12
  %t$13 = call i64 @sprout_gc_push_i64_root(ptr %t$12)
  %t$0$st = call { i64, i64 } @stdlib.json.first_non_finite_worker(i64 %value)
  %t$0 = extractvalue { i64, i64 } %t$0$st, 0
  %t$1 = extractvalue { i64, i64 } %t$0$st, 1
  %t$14 = call i64 @sprout_gc_pop_roots(i64 1)
  br label %arm_0_2
arm_0_2:
  %t$4 = add i64 0, 1
  %t$5 = icmp eq i64 %t$0, %t$4
  br i1 %t$5, label %body_0_2, label %arm_1_2
body_0_2:
  %t$15 = alloca i64
  store i64 %t$1, ptr %t$15
  %t$16 = call i64 @sprout_gc_push_i64_root(ptr %t$15)
  %t$6 = call i64 @sprout_alloc_obj(i64 16, i64 1)
  %t$6$ptr = inttoptr i64 %t$6 to ptr
  %t$6$f0 = getelementptr i64, ptr %t$6$ptr, i64 0
  store i64 %t$1, ptr %t$6$f0
  %t$17 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$18 = alloca i64
  store i64 %t$6, ptr %t$18
  %t$19 = call i64 @sprout_gc_push_i64_root(ptr %t$18)
  %t$7 = call i64 @sprout_alloc_obj(i64 8, i64 1)
  %t$7$ptr = inttoptr i64 %t$7 to ptr
  %t$7$f0 = getelementptr i64, ptr %t$7$ptr, i64 0
  store i64 %t$6, ptr %t$7$f0
  %t$20 = call i64 @sprout_gc_pop_roots(i64 1)
  br label %join_2
arm_1_2:
  %t$8 = add i64 0, 0
  %t$9 = icmp eq i64 %t$0, %t$8
  br i1 %t$9, label %body_1_2, label %arm_2_2
body_1_2:
  %t$21 = alloca i64
  store i64 %value, ptr %t$21
  %t$22 = call i64 @sprout_gc_push_i64_root(ptr %t$21)
  %t$10 = call i64 @json_stringify(i64 %value)
  %t$23 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$24 = alloca i64
  store i64 %t$10, ptr %t$24
  %t$25 = call i64 @sprout_gc_push_i64_root(ptr %t$24)
  %t$11 = call i64 @sprout_alloc_obj(i64 7, i64 1)
  %t$11$ptr = inttoptr i64 %t$11 to ptr
  %t$11$f0 = getelementptr i64, ptr %t$11$ptr, i64 0
  store i64 %t$10, ptr %t$11$f0
  %t$26 = call i64 @sprout_gc_pop_roots(i64 1)
  br label %join_2
arm_2_2:
  call void @sprout_abort_match()
  unreachable
join_2:
  %t$3 = phi i64 [%t$7, %body_0_2], [%t$11, %body_1_2]
  ret i64 %t$3
}

define i64 @stdlib.json.json_error_message(i64 %err) {
entry:
  %t$0 = call i64 @sprout_tag(i64 %err)
  br label %arm_0_1
arm_0_1:
  %t$3 = add i64 0, 15
  %t$4 = icmp eq i64 %t$0, %t$3
  br i1 %t$4, label %body_0_1, label %arm_1_1
body_0_1:
  %t$5 = call i64 @sprout_field(i64 %err, i64 0)
  br label %join_1
arm_1_1:
  %t$6 = add i64 0, 16
  %t$7 = icmp eq i64 %t$0, %t$6
  br i1 %t$7, label %body_1_1, label %arm_2_1
body_1_1:
  %t$8 = call i64 @sprout_field(i64 %err, i64 0)
  %t$9 = getelementptr inbounds { i64, [20 x i8] }, ptr @.str.0, i64 0, i32 1, i64 0
  %t$10 = ptrtoint ptr %t$9 to i64
  %t$13 = alloca i64
  store i64 %t$8, ptr %t$13
  %t$14 = call i64 @sprout_gc_push_i64_root(ptr %t$13)
  %t$15 = alloca i64
  store i64 %t$10, ptr %t$15
  %t$16 = call i64 @sprout_gc_push_i64_root(ptr %t$15)
  %t$11 = call i64 @double_to_string(i64 %t$8)
  %t$17 = alloca i64
  store i64 %t$11, ptr %t$17
  %t$18 = call i64 @sprout_gc_push_i64_root(ptr %t$17)
  %t$12 = call i64 @__tc_Semigroup_String_append(i64 %t$10, i64 %t$11)
  %t$19 = call i64 @sprout_gc_pop_roots(i64 3)
  br label %join_1
arm_2_1:
  call void @sprout_abort_match()
  unreachable
join_1:
  %t$2 = phi i64 [%t$5, %body_0_1], [%t$12, %body_1_1]
  ret i64 %t$2
}

define i64 @stdlib.json.json_array_from_list(i64 %items) {
entry:
  %t$0 = call i64 @sprout_tag(i64 %items)
  br label %arm_0_1
arm_0_1:
  %t$3 = add i64 0, 5
  %t$4 = icmp eq i64 %t$0, %t$3
  br i1 %t$4, label %body_0_1, label %arm_1_1
body_0_1:
  %t$5 = call i64 @sprout_alloc_obj(i64 25, i64 0)
  br label %join_1
arm_1_1:
  %t$6 = add i64 0, 6
  %t$7 = icmp eq i64 %t$0, %t$6
  br i1 %t$7, label %body_1_1, label %arm_2_1
body_1_1:
  %t$8 = call i64 @sprout_field(i64 %items, i64 0)
  %t$9 = call i64 @sprout_field(i64 %items, i64 1)
  %t$12 = alloca i64
  store i64 %t$8, ptr %t$12
  %t$13 = call i64 @sprout_gc_push_i64_root(ptr %t$12)
  %t$14 = alloca i64
  store i64 %t$9, ptr %t$14
  %t$15 = call i64 @sprout_gc_push_i64_root(ptr %t$14)
  %t$10 = call i64 @stdlib.json.json_array_from_list(i64 %t$9)
  %t$16 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$17 = alloca i64
  store i64 %t$10, ptr %t$17
  %t$18 = call i64 @sprout_gc_push_i64_root(ptr %t$17)
  %t$11 = call i64 @sprout_alloc_obj(i64 24, i64 2)
  %t$11$ptr = inttoptr i64 %t$11 to ptr
  %t$11$f0 = getelementptr i64, ptr %t$11$ptr, i64 0
  store i64 %t$8, ptr %t$11$f0
  %t$11$f1 = getelementptr i64, ptr %t$11$ptr, i64 1
  store i64 %t$10, ptr %t$11$f1
  %t$19 = call i64 @sprout_gc_pop_roots(i64 2)
  br label %join_1
arm_2_1:
  call void @sprout_abort_match()
  unreachable
join_1:
  %t$2 = phi i64 [%t$5, %body_0_1], [%t$11, %body_1_1]
  ret i64 %t$2
}

define i64 @stdlib.json.array_from_list(i64 %items) {
entry:
  %t$2 = alloca i64
  store i64 %items, ptr %t$2
  %t$3 = call i64 @sprout_gc_push_i64_root(ptr %t$2)
  %t$0 = call i64 @stdlib.json.json_array_from_list(i64 %items)
  %t$4 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$5 = alloca i64
  store i64 %t$0, ptr %t$5
  %t$6 = call i64 @sprout_gc_push_i64_root(ptr %t$5)
  %t$1 = call i64 @sprout_alloc_obj(i64 22, i64 1)
  %t$1$ptr = inttoptr i64 %t$1 to ptr
  %t$1$f0 = getelementptr i64, ptr %t$1$ptr, i64 0
  store i64 %t$0, ptr %t$1$f0
  %t$7 = call i64 @sprout_gc_pop_roots(i64 1)
  ret i64 %t$1
}

define i64 @stdlib.json.json_object_from_pairs(i64 %items, i64 %__tc_stdlib.json.JsonEncode_0_encode_json) {
entry:
  %t$0 = call i64 @sprout_tag(i64 %items)
  br label %arm_0_1
arm_0_1:
  %t$3 = add i64 0, 5
  %t$4 = icmp eq i64 %t$0, %t$3
  br i1 %t$4, label %body_0_1, label %arm_1_1
body_0_1:
  %t$5 = call i64 @sprout_alloc_obj(i64 27, i64 0)
  br label %join_1
arm_1_1:
  %t$6 = add i64 0, 6
  %t$7 = icmp eq i64 %t$0, %t$6
  br i1 %t$7, label %body_1_1, label %arm_2_1
body_1_1:
  %t$8 = call i64 @sprout_field(i64 %items, i64 0)
  %t$9 = call i64 @sprout_field(i64 %items, i64 1)
  br label %arm_0_10
arm_0_10:
  %t$12$ptr = inttoptr i64 %t$8 to ptr
  %t$12$gep = getelementptr i64, ptr %t$12$ptr, i64 0
  %t$12 = load i64, ptr %t$12$gep
  %t$13$ptr = inttoptr i64 %t$8 to ptr
  %t$13$gep = getelementptr i64, ptr %t$13$ptr, i64 1
  %t$13 = load i64, ptr %t$13$gep
  %t$17 = alloca i64
  store i64 %t$9, ptr %t$17
  %t$18 = call i64 @sprout_gc_push_i64_root(ptr %t$17)
  %t$19 = alloca i64
  store i64 %__tc_stdlib.json.JsonEncode_0_encode_json, ptr %t$19
  %t$20 = call i64 @sprout_gc_push_i64_root(ptr %t$19)
  %t$21 = alloca i64
  store i64 %t$12, ptr %t$21
  %t$22 = call i64 @sprout_gc_push_i64_root(ptr %t$21)
  %t$23 = alloca i64
  store i64 %t$13, ptr %t$23
  %t$24 = call i64 @sprout_gc_push_i64_root(ptr %t$23)
  %t$14 = call i64 @stdlib.json.encode(i64 %t$13, i64 %__tc_stdlib.json.JsonEncode_0_encode_json)
  %t$25 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$26 = alloca i64
  store i64 %t$14, ptr %t$26
  %t$27 = call i64 @sprout_gc_push_i64_root(ptr %t$26)
  %t$15 = call i64 @stdlib.json.json_object_from_pairs(i64 %t$9, i64 %__tc_stdlib.json.JsonEncode_0_encode_json)
  %t$28 = alloca i64
  store i64 %t$15, ptr %t$28
  %t$29 = call i64 @sprout_gc_push_i64_root(ptr %t$28)
  %t$16 = call i64 @sprout_alloc_obj(i64 26, i64 3)
  %t$16$ptr = inttoptr i64 %t$16 to ptr
  %t$16$f0 = getelementptr i64, ptr %t$16$ptr, i64 0
  store i64 %t$12, ptr %t$16$f0
  %t$16$f1 = getelementptr i64, ptr %t$16$ptr, i64 1
  store i64 %t$14, ptr %t$16$f1
  %t$16$f2 = getelementptr i64, ptr %t$16$ptr, i64 2
  store i64 %t$15, ptr %t$16$f2
  %t$30 = call i64 @sprout_gc_pop_roots(i64 5)
  br label %join_10
arm_1_10:
  call void @sprout_abort_match()
  unreachable
join_10:
  %t$11 = phi i64 [%t$16, %arm_0_10]
  br label %join_1
arm_2_1:
  call void @sprout_abort_match()
  unreachable
join_1:
  %t$2 = phi i64 [%t$5, %body_0_1], [%t$11, %join_10]
  ret i64 %t$2
}

define i64 @stdlib.json.object_from_pairs(i64 %items, i64 %__tc_stdlib.json.JsonEncode_0_encode_json) {
entry:
  %t$2 = alloca i64
  store i64 %items, ptr %t$2
  %t$3 = call i64 @sprout_gc_push_i64_root(ptr %t$2)
  %t$4 = alloca i64
  store i64 %__tc_stdlib.json.JsonEncode_0_encode_json, ptr %t$4
  %t$5 = call i64 @sprout_gc_push_i64_root(ptr %t$4)
  %t$0 = call i64 @stdlib.json.json_object_from_pairs(i64 %items, i64 %__tc_stdlib.json.JsonEncode_0_encode_json)
  %t$6 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$7 = alloca i64
  store i64 %t$0, ptr %t$7
  %t$8 = call i64 @sprout_gc_push_i64_root(ptr %t$7)
  %t$1 = call i64 @sprout_alloc_obj(i64 23, i64 1)
  %t$1$ptr = inttoptr i64 %t$1 to ptr
  %t$1$f0 = getelementptr i64, ptr %t$1$ptr, i64 0
  store i64 %t$0, ptr %t$1$f0
  %t$9 = call i64 @sprout_gc_pop_roots(i64 1)
  ret i64 %t$1
}

define i64 @__sprout_ir_eta___tc_stdlib.json.JsonEncode_stdlib_json_Json_encode_json_0(i64 %env$, i64 %a0) {
entry:
  %ret = call i64 @__tc_stdlib.json.JsonEncode_stdlib_json_Json_encode_json(i64 %a0)
  ret i64 %ret
}

define i64 @examples.json_demo.payload() {
entry:
  %t$0 = getelementptr inbounds { i64, [6 x i8] }, ptr @.str.1, i64 0, i32 1, i64 0
  %t$1 = ptrtoint ptr %t$0 to i64
  %t$2 = getelementptr inbounds { i64, [6 x i8] }, ptr @.str.2, i64 0, i32 1, i64 0
  %t$3 = ptrtoint ptr %t$2 to i64
  %t$29 = alloca i64
  store i64 %t$1, ptr %t$29
  %t$30 = call i64 @sprout_gc_push_i64_root(ptr %t$29)
  %t$31 = alloca i64
  store i64 %t$3, ptr %t$31
  %t$32 = call i64 @sprout_gc_push_i64_root(ptr %t$31)
  %t$4 = call i64 @stdlib.json.string(i64 %t$3)
  %t$33 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$34 = alloca i64
  store i64 %t$4, ptr %t$34
  %t$35 = call i64 @sprout_gc_push_i64_root(ptr %t$34)
  %t$5 = call i64 @sprout_alloc_tuple_blob(i64 16)
  %t$5$ptr = inttoptr i64 %t$5 to ptr
  %t$5$s0 = getelementptr i64, ptr %t$5$ptr, i64 0
  store i64 %t$1, ptr %t$5$s0
  %t$5$s1 = getelementptr i64, ptr %t$5$ptr, i64 1
  store i64 %t$4, ptr %t$5$s1
  %t$36 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$6 = getelementptr inbounds { i64, [6 x i8] }, ptr @.str.3, i64 0, i32 1, i64 0
  %t$7 = ptrtoint ptr %t$6 to i64
  %t$8 = add i64 0, 2
  %t$37 = alloca i64
  store i64 %t$5, ptr %t$37
  %t$38 = call i64 @sprout_gc_push_i64_root(ptr %t$37)
  %t$39 = alloca i64
  store i64 %t$7, ptr %t$39
  %t$40 = call i64 @sprout_gc_push_i64_root(ptr %t$39)
  %t$9 = call i64 @stdlib.json.int(i64 %t$8)
  %t$41 = alloca i64
  store i64 %t$9, ptr %t$41
  %t$42 = call i64 @sprout_gc_push_i64_root(ptr %t$41)
  %t$10 = call i64 @sprout_alloc_tuple_blob(i64 16)
  %t$10$ptr = inttoptr i64 %t$10 to ptr
  %t$10$s0 = getelementptr i64, ptr %t$10$ptr, i64 0
  store i64 %t$7, ptr %t$10$s0
  %t$10$s1 = getelementptr i64, ptr %t$10$ptr, i64 1
  store i64 %t$9, ptr %t$10$s1
  %t$43 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$11 = getelementptr inbounds { i64, [6 x i8] }, ptr @.str.4, i64 0, i32 1, i64 0
  %t$12 = ptrtoint ptr %t$11 to i64
  %t$13 = getelementptr inbounds { i64, [2 x i8] }, ptr @.str.5, i64 0, i32 1, i64 0
  %t$14 = ptrtoint ptr %t$13 to i64
  %t$44 = alloca i64
  store i64 %t$10, ptr %t$44
  %t$45 = call i64 @sprout_gc_push_i64_root(ptr %t$44)
  %t$46 = alloca i64
  store i64 %t$12, ptr %t$46
  %t$47 = call i64 @sprout_gc_push_i64_root(ptr %t$46)
  %t$48 = alloca i64
  store i64 %t$14, ptr %t$48
  %t$49 = call i64 @sprout_gc_push_i64_root(ptr %t$48)
  %t$15 = call i64 @stdlib.json.string(i64 %t$14)
  %t$50 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$16 = add i64 0, 1
  %t$51 = alloca i64
  store i64 %t$15, ptr %t$51
  %t$52 = call i64 @sprout_gc_push_i64_root(ptr %t$51)
  %t$17 = call i64 @stdlib.json.bool(i64 %t$16)
  %t$53 = alloca i64
  store i64 %t$17, ptr %t$53
  %t$54 = call i64 @sprout_gc_push_i64_root(ptr %t$53)
  %t$18 = call i64 @sprout_alloc_obj(i64 5, i64 0)
  %t$55 = alloca i64
  store i64 %t$18, ptr %t$55
  %t$56 = call i64 @sprout_gc_push_i64_root(ptr %t$55)
  %t$19 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$19$ptr = inttoptr i64 %t$19 to ptr
  %t$19$f0 = getelementptr i64, ptr %t$19$ptr, i64 0
  store i64 %t$17, ptr %t$19$f0
  %t$19$f1 = getelementptr i64, ptr %t$19$ptr, i64 1
  store i64 %t$18, ptr %t$19$f1
  %t$57 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$58 = alloca i64
  store i64 %t$19, ptr %t$58
  %t$59 = call i64 @sprout_gc_push_i64_root(ptr %t$58)
  %t$20 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$20$ptr = inttoptr i64 %t$20 to ptr
  %t$20$f0 = getelementptr i64, ptr %t$20$ptr, i64 0
  store i64 %t$15, ptr %t$20$f0
  %t$20$f1 = getelementptr i64, ptr %t$20$ptr, i64 1
  store i64 %t$19, ptr %t$20$f1
  %t$60 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$61 = alloca i64
  store i64 %t$20, ptr %t$61
  %t$62 = call i64 @sprout_gc_push_i64_root(ptr %t$61)
  %t$21 = call i64 @stdlib.json.array_from_list(i64 %t$20)
  %t$63 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$64 = alloca i64
  store i64 %t$21, ptr %t$64
  %t$65 = call i64 @sprout_gc_push_i64_root(ptr %t$64)
  %t$22 = call i64 @sprout_alloc_tuple_blob(i64 16)
  %t$22$ptr = inttoptr i64 %t$22 to ptr
  %t$22$s0 = getelementptr i64, ptr %t$22$ptr, i64 0
  store i64 %t$12, ptr %t$22$s0
  %t$22$s1 = getelementptr i64, ptr %t$22$ptr, i64 1
  store i64 %t$21, ptr %t$22$s1
  %t$66 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$67 = alloca i64
  store i64 %t$22, ptr %t$67
  %t$68 = call i64 @sprout_gc_push_i64_root(ptr %t$67)
  %t$23 = call i64 @sprout_alloc_obj(i64 5, i64 0)
  %t$69 = alloca i64
  store i64 %t$23, ptr %t$69
  %t$70 = call i64 @sprout_gc_push_i64_root(ptr %t$69)
  %t$24 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$24$ptr = inttoptr i64 %t$24 to ptr
  %t$24$f0 = getelementptr i64, ptr %t$24$ptr, i64 0
  store i64 %t$22, ptr %t$24$f0
  %t$24$f1 = getelementptr i64, ptr %t$24$ptr, i64 1
  store i64 %t$23, ptr %t$24$f1
  %t$71 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$72 = alloca i64
  store i64 %t$24, ptr %t$72
  %t$73 = call i64 @sprout_gc_push_i64_root(ptr %t$72)
  %t$25 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$25$ptr = inttoptr i64 %t$25 to ptr
  %t$25$f0 = getelementptr i64, ptr %t$25$ptr, i64 0
  store i64 %t$10, ptr %t$25$f0
  %t$25$f1 = getelementptr i64, ptr %t$25$ptr, i64 1
  store i64 %t$24, ptr %t$25$f1
  %t$74 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$75 = alloca i64
  store i64 %t$25, ptr %t$75
  %t$76 = call i64 @sprout_gc_push_i64_root(ptr %t$75)
  %t$26 = call i64 @sprout_alloc_obj(i64 6, i64 2)
  %t$26$ptr = inttoptr i64 %t$26 to ptr
  %t$26$f0 = getelementptr i64, ptr %t$26$ptr, i64 0
  store i64 %t$5, ptr %t$26$f0
  %t$26$f1 = getelementptr i64, ptr %t$26$ptr, i64 1
  store i64 %t$25, ptr %t$26$f1
  %t$77 = call i64 @sprout_gc_pop_roots(i64 2)
  %t$78 = alloca i64
  store i64 %t$26, ptr %t$78
  %t$79 = call i64 @sprout_gc_push_i64_root(ptr %t$78)
  %t$27 = call i64 @sprout_alloc_closure(i64 8, i64 1)
  %t$27$raw = inttoptr i64 %t$27 to ptr
  store ptr @__sprout_ir_eta___tc_stdlib.json.JsonEncode_stdlib_json_Json_encode_json_0, ptr %t$27$raw
  %t$80 = alloca i64
  store i64 %t$27, ptr %t$80
  %t$81 = call i64 @sprout_gc_push_i64_root(ptr %t$80)
  %t$28 = call i64 @stdlib.json.object_from_pairs(i64 %t$26, i64 %t$27)
  %t$82 = call i64 @sprout_gc_pop_roots(i64 2)
  ret i64 %t$28
}

define i64 @examples.json_demo.unwritable() {
entry:
  %t$0 = bitcast double 1.0 to i64
  %t$1 = bitcast double 0.0 to i64
  %t$2$la = bitcast i64 %t$0 to double
  %t$2$lb = bitcast i64 %t$1 to double
  %t$2$fr = fdiv double %t$2$la, %t$2$lb
  %t$2 = bitcast double %t$2$fr to i64
  %t$3 = call i64 @sprout_alloc_obj(i64 20, i64 1)
  %t$3$ptr = inttoptr i64 %t$3 to ptr
  %t$3$f0 = getelementptr i64, ptr %t$3$ptr, i64 0
  store i64 %t$2, ptr %t$3$f0
  ret i64 %t$3
}

define i64 @examples.json_demo.render(i64 %value) {
entry:
  %t$12 = alloca i64
  store i64 %value, ptr %t$12
  %t$13 = call i64 @sprout_gc_push_i64_root(ptr %t$12)
  %t$0$st = call { i64, i64 } @stdlib.json.stringify_worker(i64 %value)
  %t$0 = extractvalue { i64, i64 } %t$0$st, 0
  %t$1 = extractvalue { i64, i64 } %t$0$st, 1
  %t$14 = call i64 @sprout_gc_pop_roots(i64 1)
  br label %arm_0_2
arm_0_2:
  %t$4 = add i64 0, 7
  %t$5 = icmp eq i64 %t$0, %t$4
  br i1 %t$5, label %body_0_2, label %arm_1_2
body_0_2:
  br label %join_2
arm_1_2:
  %t$6 = add i64 0, 8
  %t$7 = icmp eq i64 %t$0, %t$6
  br i1 %t$7, label %body_1_2, label %arm_2_2
body_1_2:
  %t$8 = getelementptr inbounds { i64, [10 x i8] }, ptr @.str.6, i64 0, i32 1, i64 0
  %t$9 = ptrtoint ptr %t$8 to i64
  %t$15 = alloca i64
  store i64 %t$1, ptr %t$15
  %t$16 = call i64 @sprout_gc_push_i64_root(ptr %t$15)
  %t$17 = alloca i64
  store i64 %t$9, ptr %t$17
  %t$18 = call i64 @sprout_gc_push_i64_root(ptr %t$17)
  %t$10 = call i64 @stdlib.json.json_error_message(i64 %t$1)
  %t$19 = alloca i64
  store i64 %t$10, ptr %t$19
  %t$20 = call i64 @sprout_gc_push_i64_root(ptr %t$19)
  %t$11 = call i64 @__tc_Semigroup_String_append(i64 %t$9, i64 %t$10)
  %t$21 = call i64 @sprout_gc_pop_roots(i64 3)
  br label %join_2
arm_2_2:
  call void @sprout_abort_match()
  unreachable
join_2:
  %t$3 = phi i64 [%t$1, %body_0_2], [%t$11, %body_1_2]
  ret i64 %t$3
}

define i64 @__sprout_user_main() {
entry:
  %t$0 = call i64 @examples.json_demo.payload()
  %t$6 = alloca i64
  store i64 %t$0, ptr %t$6
  %t$7 = call i64 @sprout_gc_push_i64_root(ptr %t$6)
  %t$1 = call i64 @examples.json_demo.render(i64 %t$0)
  %t$8 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$2$ptr = inttoptr i64 %t$1 to ptr
  %t$2 = call i64 @print_str(ptr %t$2$ptr)
  %t$3 = call i64 @examples.json_demo.unwritable()
  %t$9 = alloca i64
  store i64 %t$3, ptr %t$9
  %t$10 = call i64 @sprout_gc_push_i64_root(ptr %t$9)
  %t$4 = call i64 @examples.json_demo.render(i64 %t$3)
  %t$11 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$5$ptr = inttoptr i64 %t$4 to ptr
  %t$5 = call i64 @print_str(ptr %t$5$ptr)
  ret i64 %t$5
}

define i64 @__cm_JsonEncode_encode_json(i64 %value, i64 %__tc_stdlib.json.JsonEncode_0_encode_json) {
entry:
  call void @sprout_closure_arity_check(i64 %__tc_stdlib.json.JsonEncode_0_encode_json, i64 1)
  %t$0$env_ptr = inttoptr i64 %__tc_stdlib.json.JsonEncode_0_encode_json to ptr
  %t$0$code = load ptr, ptr %t$0$env_ptr
  %t$0 = call i64 (i64, i64) %t$0$code(i64 %__tc_stdlib.json.JsonEncode_0_encode_json, i64 %value)
  ret i64 %t$0
}

define i64 @__tc_Semigroup_String_append(i64 %left, i64 %right) {
entry:
  %t$0 = call i64 @str_concat(i64 %left, i64 %right)
  ret i64 %t$0
}

define i64 @__tc_stdlib.json.JsonEncode_stdlib_json_Json_encode_json(i64 %value) {
entry:
  ret i64 %value
}

define { i64, i64 } @stdlib.json.first_non_finite_worker(i64 %value) {
entry:
  %t$0 = call i64 @sprout_tag(i64 %value)
  br label %arm_0_1
arm_0_1:
  %t$3 = add i64 0, 20
  %t$4 = icmp eq i64 %t$0, %t$3
  br i1 %t$4, label %body_0_1, label %arm_1_1
body_0_1:
  %t$5 = call i64 @sprout_field(i64 %value, i64 0)
  %t$6 = call i64 @stdlib.json.is_finite(i64 %t$5)
  %t$11 = trunc i64 %t$6 to i1
  br i1 %t$11, label %then_7, label %else_7
then_7:
  %t$9 = call i64 @sprout_alloc_obj(i64 0, i64 0)
  br label %join_7
else_7:
  %t$30 = alloca i64
  store i64 %t$5, ptr %t$30
  %t$31 = call i64 @sprout_gc_push_i64_root(ptr %t$30)
  %t$10 = call i64 @sprout_alloc_obj(i64 1, i64 1)
  %t$10$ptr = inttoptr i64 %t$10 to ptr
  %t$10$f0 = getelementptr i64, ptr %t$10$ptr, i64 0
  store i64 %t$5, ptr %t$10$f0
  %t$32 = call i64 @sprout_gc_pop_roots(i64 1)
  br label %join_7
join_7:
  %t$8 = phi i64 [%t$9, %then_7], [%t$10, %else_7]
  br label %join_1
arm_1_1:
  %t$12 = add i64 0, 22
  %t$13 = icmp eq i64 %t$0, %t$12
  br i1 %t$13, label %body_1_1, label %arm_2_1
body_1_1:
  %t$14 = call i64 @sprout_field(i64 %value, i64 0)
  %t$33 = alloca i64
  store i64 %t$14, ptr %t$33
  %t$34 = call i64 @sprout_gc_push_i64_root(ptr %t$33)
  %t$15 = call i64 @stdlib.json.first_non_finite_array(i64 %t$14)
  %t$35 = call i64 @sprout_gc_pop_roots(i64 1)
  br label %join_1
arm_2_1:
  %t$16 = add i64 0, 23
  %t$17 = icmp eq i64 %t$0, %t$16
  br i1 %t$17, label %body_2_1, label %arm_3_1
body_2_1:
  %t$18 = call i64 @sprout_field(i64 %value, i64 0)
  %t$36 = alloca i64
  store i64 %t$18, ptr %t$36
  %t$37 = call i64 @sprout_gc_push_i64_root(ptr %t$36)
  %t$19 = call i64 @stdlib.json.first_non_finite_object(i64 %t$18)
  %t$38 = call i64 @sprout_gc_pop_roots(i64 1)
  br label %join_1
arm_3_1:
  %t$20 = call i64 @sprout_alloc_obj(i64 0, i64 0)
  br label %join_1
arm_4_1:
  call void @sprout_abort_match()
  unreachable
join_1:
  %t$2 = phi i64 [%t$8, %join_7], [%t$15, %body_1_1], [%t$19, %body_2_1], [%t$20, %arm_3_1]
  %t$21 = call i64 @sprout_tag(i64 %t$2)
  %t$22 = add i64 0, 0
  %t$23 = icmp eq i64 %t$21, %t$22
  br i1 %t$23, label %wrepack_hit_22, label %wrepack_next_22
wrepack_hit_22:
  %t$25$r0 = insertvalue { i64, i64 } undef, i64 %t$21, 0
  %t$25$r1 = insertvalue { i64, i64 } %t$25$r0, i64 0, 1
  ret { i64, i64 } %t$25$r1
wrepack_next_22:
  %t$26 = add i64 0, 1
  %t$27 = icmp eq i64 %t$21, %t$26
  br i1 %t$27, label %wrepack_hit_26, label %wrepack_next_26
wrepack_hit_26:
  %t$28 = call i64 @sprout_field(i64 %t$2, i64 0)
  %t$29$r0 = insertvalue { i64, i64 } undef, i64 %t$21, 0
  %t$29$r1 = insertvalue { i64, i64 } %t$29$r0, i64 %t$28, 1
  ret { i64, i64 } %t$29$r1
wrepack_next_26:
  call void @sprout_abort_match()
  unreachable
}

define { i64, i64 } @stdlib.json.stringify_worker(i64 %value) {
entry:
  %t$21 = alloca i64
  store i64 %value, ptr %t$21
  %t$22 = call i64 @sprout_gc_push_i64_root(ptr %t$21)
  %t$0$st = call { i64, i64 } @stdlib.json.first_non_finite_worker(i64 %value)
  %t$0 = extractvalue { i64, i64 } %t$0$st, 0
  %t$1 = extractvalue { i64, i64 } %t$0$st, 1
  %t$23 = call i64 @sprout_gc_pop_roots(i64 1)
  br label %arm_0_2
arm_0_2:
  %t$4 = add i64 0, 1
  %t$5 = icmp eq i64 %t$0, %t$4
  br i1 %t$5, label %body_0_2, label %arm_1_2
body_0_2:
  %t$24 = alloca i64
  store i64 %t$1, ptr %t$24
  %t$25 = call i64 @sprout_gc_push_i64_root(ptr %t$24)
  %t$6 = call i64 @sprout_alloc_obj(i64 16, i64 1)
  %t$6$ptr = inttoptr i64 %t$6 to ptr
  %t$6$f0 = getelementptr i64, ptr %t$6$ptr, i64 0
  store i64 %t$1, ptr %t$6$f0
  %t$26 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$27 = alloca i64
  store i64 %t$6, ptr %t$27
  %t$28 = call i64 @sprout_gc_push_i64_root(ptr %t$27)
  %t$7 = call i64 @sprout_alloc_obj(i64 8, i64 1)
  %t$7$ptr = inttoptr i64 %t$7 to ptr
  %t$7$f0 = getelementptr i64, ptr %t$7$ptr, i64 0
  store i64 %t$6, ptr %t$7$f0
  %t$29 = call i64 @sprout_gc_pop_roots(i64 1)
  br label %join_2
arm_1_2:
  %t$8 = add i64 0, 0
  %t$9 = icmp eq i64 %t$0, %t$8
  br i1 %t$9, label %body_1_2, label %arm_2_2
body_1_2:
  %t$30 = alloca i64
  store i64 %value, ptr %t$30
  %t$31 = call i64 @sprout_gc_push_i64_root(ptr %t$30)
  %t$10 = call i64 @json_stringify(i64 %value)
  %t$32 = call i64 @sprout_gc_pop_roots(i64 1)
  %t$33 = alloca i64
  store i64 %t$10, ptr %t$33
  %t$34 = call i64 @sprout_gc_push_i64_root(ptr %t$33)
  %t$11 = call i64 @sprout_alloc_obj(i64 7, i64 1)
  %t$11$ptr = inttoptr i64 %t$11 to ptr
  %t$11$f0 = getelementptr i64, ptr %t$11$ptr, i64 0
  store i64 %t$10, ptr %t$11$f0
  %t$35 = call i64 @sprout_gc_pop_roots(i64 1)
  br label %join_2
arm_2_2:
  call void @sprout_abort_match()
  unreachable
join_2:
  %t$3 = phi i64 [%t$7, %body_0_2], [%t$11, %body_1_2]
  %t$12 = call i64 @sprout_tag(i64 %t$3)
  %t$13 = add i64 0, 7
  %t$14 = icmp eq i64 %t$12, %t$13
  br i1 %t$14, label %wrepack_hit_13, label %wrepack_next_13
wrepack_hit_13:
  %t$15 = call i64 @sprout_field(i64 %t$3, i64 0)
  %t$16$r0 = insertvalue { i64, i64 } undef, i64 %t$12, 0
  %t$16$r1 = insertvalue { i64, i64 } %t$16$r0, i64 %t$15, 1
  ret { i64, i64 } %t$16$r1
wrepack_next_13:
  %t$17 = add i64 0, 8
  %t$18 = icmp eq i64 %t$12, %t$17
  br i1 %t$18, label %wrepack_hit_17, label %wrepack_next_17
wrepack_hit_17:
  %t$19 = call i64 @sprout_field(i64 %t$3, i64 0)
  %t$20$r0 = insertvalue { i64, i64 } undef, i64 %t$12, 0
  %t$20$r1 = insertvalue { i64, i64 } %t$20$r0, i64 %t$19, 1
  ret { i64, i64 } %t$20$r1
wrepack_next_17:
  call void @sprout_abort_match()
  unreachable
}

define i32 @main(i32 %argc, ptr %argv) {
entry:
  %argv_set = call i64 @sprout_set_argv(i32 %argc, ptr %argv)
  %cname_ptr_0 = getelementptr inbounds [8 x i8], ptr @.cname.0, i64 0, i64 0
  %cfkinds_ptr_0 = getelementptr inbounds [1 x i8], ptr @.cfkinds.0, i64 0, i64 0
  %creg_0 = call i64 @sprout_register_ctor(i64 0, ptr %cname_ptr_0, i64 0, ptr %cfkinds_ptr_0)
  %cname_ptr_1 = getelementptr inbounds [5 x i8], ptr @.cname.1, i64 0, i64 0
  %cfkinds_ptr_1 = getelementptr inbounds [2 x i8], ptr @.cfkinds.1, i64 0, i64 0
  %creg_1 = call i64 @sprout_register_ctor(i64 1, ptr %cname_ptr_1, i64 1, ptr %cfkinds_ptr_1)
  %cname_ptr_2 = getelementptr inbounds [12 x i8], ptr @.cname.2, i64 0, i64 0
  %cfkinds_ptr_2 = getelementptr inbounds [2 x i8], ptr @.cfkinds.2, i64 0, i64 0
  %creg_2 = call i64 @sprout_register_ctor(i64 2, ptr %cname_ptr_2, i64 1, ptr %cfkinds_ptr_2)
  %cname_ptr_3 = getelementptr inbounds [15 x i8], ptr @.cname.3, i64 0, i64 0
  %cfkinds_ptr_3 = getelementptr inbounds [2 x i8], ptr @.cfkinds.3, i64 0, i64 0
  %creg_3 = call i64 @sprout_register_ctor(i64 3, ptr %cname_ptr_3, i64 1, ptr %cfkinds_ptr_3)
  %cname_ptr_4 = getelementptr inbounds [15 x i8], ptr @.cname.4, i64 0, i64 0
  %cfkinds_ptr_4 = getelementptr inbounds [2 x i8], ptr @.cfkinds.4, i64 0, i64 0
  %creg_4 = call i64 @sprout_register_ctor(i64 4, ptr %cname_ptr_4, i64 1, ptr %cfkinds_ptr_4)
  %cname_ptr_5 = getelementptr inbounds [4 x i8], ptr @.cname.5, i64 0, i64 0
  %cfkinds_ptr_5 = getelementptr inbounds [1 x i8], ptr @.cfkinds.5, i64 0, i64 0
  %creg_5 = call i64 @sprout_register_ctor(i64 5, ptr %cname_ptr_5, i64 0, ptr %cfkinds_ptr_5)
  %cname_ptr_6 = getelementptr inbounds [5 x i8], ptr @.cname.6, i64 0, i64 0
  %cfkinds_ptr_6 = getelementptr inbounds [3 x i8], ptr @.cfkinds.6, i64 0, i64 0
  %creg_6 = call i64 @sprout_register_ctor(i64 6, ptr %cname_ptr_6, i64 2, ptr %cfkinds_ptr_6)
  %cname_ptr_7 = getelementptr inbounds [3 x i8], ptr @.cname.7, i64 0, i64 0
  %cfkinds_ptr_7 = getelementptr inbounds [2 x i8], ptr @.cfkinds.7, i64 0, i64 0
  %creg_7 = call i64 @sprout_register_ctor(i64 7, ptr %cname_ptr_7, i64 1, ptr %cfkinds_ptr_7)
  %cname_ptr_8 = getelementptr inbounds [4 x i8], ptr @.cname.8, i64 0, i64 0
  %cfkinds_ptr_8 = getelementptr inbounds [2 x i8], ptr @.cfkinds.8, i64 0, i64 0
  %creg_8 = call i64 @sprout_register_ctor(i64 8, ptr %cname_ptr_8, i64 1, ptr %cfkinds_ptr_8)
  %cname_ptr_9 = getelementptr inbounds [10 x i8], ptr @.cname.9, i64 0, i64 0
  %cfkinds_ptr_9 = getelementptr inbounds [1 x i8], ptr @.cfkinds.9, i64 0, i64 0
  %creg_9 = call i64 @sprout_register_ctor(i64 9, ptr %cname_ptr_9, i64 0, ptr %cfkinds_ptr_9)
  %cname_ptr_10 = getelementptr inbounds [4 x i8], ptr @.cname.10, i64 0, i64 0
  %cfkinds_ptr_10 = getelementptr inbounds [2 x i8], ptr @.cfkinds.10, i64 0, i64 0
  %creg_10 = call i64 @sprout_register_ctor(i64 10, ptr %cname_ptr_10, i64 1, ptr %cfkinds_ptr_10)
  %cname_ptr_11 = getelementptr inbounds [5 x i8], ptr @.cname.11, i64 0, i64 0
  %cfkinds_ptr_11 = getelementptr inbounds [2 x i8], ptr @.cfkinds.11, i64 0, i64 0
  %creg_11 = call i64 @sprout_register_ctor(i64 11, ptr %cname_ptr_11, i64 1, ptr %cfkinds_ptr_11)
  %cname_ptr_12 = getelementptr inbounds [4 x i8], ptr @.cname.12, i64 0, i64 0
  %cfkinds_ptr_12 = getelementptr inbounds [2 x i8], ptr @.cfkinds.12, i64 0, i64 0
  %creg_12 = call i64 @sprout_register_ctor(i64 12, ptr %cname_ptr_12, i64 1, ptr %cfkinds_ptr_12)
  %cname_ptr_13 = getelementptr inbounds [9 x i8], ptr @.cname.13, i64 0, i64 0
  %cfkinds_ptr_13 = getelementptr inbounds [4 x i8], ptr @.cfkinds.13, i64 0, i64 0
  %creg_13 = call i64 @sprout_register_ctor(i64 13, ptr %cname_ptr_13, i64 3, ptr %cfkinds_ptr_13)
  %cname_ptr_14 = getelementptr inbounds [29 x i8], ptr @.cname.14, i64 0, i64 0
  %cfkinds_ptr_14 = getelementptr inbounds [2 x i8], ptr @.cfkinds.14, i64 0, i64 0
  %creg_14 = call i64 @sprout_register_ctor(i64 14, ptr %cname_ptr_14, i64 1, ptr %cfkinds_ptr_14)
  %cname_ptr_15 = getelementptr inbounds [23 x i8], ptr @.cname.15, i64 0, i64 0
  %cfkinds_ptr_15 = getelementptr inbounds [2 x i8], ptr @.cfkinds.15, i64 0, i64 0
  %creg_15 = call i64 @sprout_register_ctor(i64 15, ptr %cname_ptr_15, i64 1, ptr %cfkinds_ptr_15)
  %cname_ptr_16 = getelementptr inbounds [26 x i8], ptr @.cname.16, i64 0, i64 0
  %cfkinds_ptr_16 = getelementptr inbounds [2 x i8], ptr @.cfkinds.16, i64 0, i64 0
  %creg_16 = call i64 @sprout_register_ctor(i64 16, ptr %cname_ptr_16, i64 1, ptr %cfkinds_ptr_16)
  %cname_ptr_17 = getelementptr inbounds [21 x i8], ptr @.cname.17, i64 0, i64 0
  %cfkinds_ptr_17 = getelementptr inbounds [1 x i8], ptr @.cfkinds.17, i64 0, i64 0
  %creg_17 = call i64 @sprout_register_ctor(i64 17, ptr %cname_ptr_17, i64 0, ptr %cfkinds_ptr_17)
  %cname_ptr_18 = getelementptr inbounds [21 x i8], ptr @.cname.18, i64 0, i64 0
  %cfkinds_ptr_18 = getelementptr inbounds [2 x i8], ptr @.cfkinds.18, i64 0, i64 0
  %creg_18 = call i64 @sprout_register_ctor(i64 18, ptr %cname_ptr_18, i64 1, ptr %cfkinds_ptr_18)
  %cname_ptr_19 = getelementptr inbounds [20 x i8], ptr @.cname.19, i64 0, i64 0
  %cfkinds_ptr_19 = getelementptr inbounds [2 x i8], ptr @.cfkinds.19, i64 0, i64 0
  %creg_19 = call i64 @sprout_register_ctor(i64 19, ptr %cname_ptr_19, i64 1, ptr %cfkinds_ptr_19)
  %cname_ptr_20 = getelementptr inbounds [22 x i8], ptr @.cname.20, i64 0, i64 0
  %cfkinds_ptr_20 = getelementptr inbounds [2 x i8], ptr @.cfkinds.20, i64 0, i64 0
  %creg_20 = call i64 @sprout_register_ctor(i64 20, ptr %cname_ptr_20, i64 1, ptr %cfkinds_ptr_20)
  %cname_ptr_21 = getelementptr inbounds [23 x i8], ptr @.cname.21, i64 0, i64 0
  %cfkinds_ptr_21 = getelementptr inbounds [2 x i8], ptr @.cfkinds.21, i64 0, i64 0
  %creg_21 = call i64 @sprout_register_ctor(i64 21, ptr %cname_ptr_21, i64 1, ptr %cfkinds_ptr_21)
  %cname_ptr_22 = getelementptr inbounds [22 x i8], ptr @.cname.22, i64 0, i64 0
  %cfkinds_ptr_22 = getelementptr inbounds [2 x i8], ptr @.cfkinds.22, i64 0, i64 0
  %creg_22 = call i64 @sprout_register_ctor(i64 22, ptr %cname_ptr_22, i64 1, ptr %cfkinds_ptr_22)
  %cname_ptr_23 = getelementptr inbounds [23 x i8], ptr @.cname.23, i64 0, i64 0
  %cfkinds_ptr_23 = getelementptr inbounds [2 x i8], ptr @.cfkinds.23, i64 0, i64 0
  %creg_23 = call i64 @sprout_register_ctor(i64 23, ptr %cname_ptr_23, i64 1, ptr %cfkinds_ptr_23)
  %cname_ptr_24 = getelementptr inbounds [26 x i8], ptr @.cname.24, i64 0, i64 0
  %cfkinds_ptr_24 = getelementptr inbounds [3 x i8], ptr @.cfkinds.24, i64 0, i64 0
  %creg_24 = call i64 @sprout_register_ctor(i64 24, ptr %cname_ptr_24, i64 2, ptr %cfkinds_ptr_24)
  %cname_ptr_25 = getelementptr inbounds [25 x i8], ptr @.cname.25, i64 0, i64 0
  %cfkinds_ptr_25 = getelementptr inbounds [1 x i8], ptr @.cfkinds.25, i64 0, i64 0
  %creg_25 = call i64 @sprout_register_ctor(i64 25, ptr %cname_ptr_25, i64 0, ptr %cfkinds_ptr_25)
  %cname_ptr_26 = getelementptr inbounds [27 x i8], ptr @.cname.26, i64 0, i64 0
  %cfkinds_ptr_26 = getelementptr inbounds [4 x i8], ptr @.cfkinds.26, i64 0, i64 0
  %creg_26 = call i64 @sprout_register_ctor(i64 26, ptr %cname_ptr_26, i64 3, ptr %cfkinds_ptr_26)
  %cname_ptr_27 = getelementptr inbounds [26 x i8], ptr @.cname.27, i64 0, i64 0
  %cfkinds_ptr_27 = getelementptr inbounds [1 x i8], ptr @.cfkinds.27, i64 0, i64 0
  %creg_27 = call i64 @sprout_register_ctor(i64 27, ptr %cname_ptr_27, i64 0, ptr %cfkinds_ptr_27)
  %cname_ptr_28 = getelementptr inbounds [26 x i8], ptr @.cname.28, i64 0, i64 0
  %cfkinds_ptr_28 = getelementptr inbounds [3 x i8], ptr @.cfkinds.28, i64 0, i64 0
  %creg_28 = call i64 @sprout_register_ctor(i64 28, ptr %cname_ptr_28, i64 2, ptr %cfkinds_ptr_28)
  %cname_ptr_29 = getelementptr inbounds [27 x i8], ptr @.cname.29, i64 0, i64 0
  %cfkinds_ptr_29 = getelementptr inbounds [4 x i8], ptr @.cfkinds.29, i64 0, i64 0
  %creg_29 = call i64 @sprout_register_ctor(i64 29, ptr %cname_ptr_29, i64 3, ptr %cfkinds_ptr_29)
  call i64 @__sprout_user_main()
  ret i32 0
}

