; Generated by sprout ir_lowering.sprout (M2 PR 2.3)
target triple = "unknown-unknown-unknown"
declare i64 @str_concat(i64, i64)
declare i1 @str_eq(ptr, ptr)
declare i64 @str_compare(i64, i64)
declare i64 @str_slice(i64, i64, i64)
declare i64 @int_to_string(i64)
declare i64 @char_to_string(i64)
declare i64 @sprout_gc_push_i64_root(ptr)
declare i64 @sprout_gc_pop_roots(i64)
declare i64 @sprout_alloc_closure_env(i64)
declare i64 @sprout_alloc_tuple_blob(i64)
declare i64 @sprout_register_ctor(i64, ptr, i64, ptr)
declare i64 @sprout_tag(i64)
declare i64 @sprout_field(i64, i64)
declare void @sprout_abort_match() noreturn
declare i64 @sprout_make0(i64)
declare i64 @sprout_make1(i64, i64)
declare i64 @sprout_make2(i64, i64, i64)
declare i64 @sprout_make3(i64, i64, i64, i64)
declare i64 @sprout_make4(i64, i64, i64, i64, i64)
declare i64 @sprout_make5(i64, i64, i64, i64, i64, i64)
declare i64 @sprout_make6(i64, i64, i64, i64, i64, i64, i64)
declare i64 @sprout_make7(i64, i64, i64, i64, i64, i64, i64, i64)
declare i64 @sprout_make8(i64, i64, i64, i64, i64, i64, i64, i64, i64)
declare i64 @sprout_make9(i64, i64, i64, i64, i64, i64, i64, i64, i64, i64)
declare i64 @print_str(ptr)
declare i64 @print_value(i64)
declare i64 @eprint_str(ptr)
declare i64 @argv_get(i64)
declare i64 @int_range(i64, i64)
declare i64 @analysis_check_source(ptr)
declare i64 @analysis_declared_names_in_source(ptr)
declare i64 @analysis_exported_names_in_source(ptr)
declare i64 @analysis_symbol_inventory_in_source(ptr)
declare i64 @analysis_diagnostics_in_source(ptr)
declare i64 @analysis_symbol_locations_in_source(ptr)
declare i64 @analysis_type_of_in_source(ptr, ptr)
declare i64 @analysis_eval_expr_in_source(ptr, ptr)
declare i64 @analysis_instances_in_source(ptr, ptr)
declare i64 @analysis_complete_in_state(ptr, ptr, ptr)

@.str.0 = private unnamed_addr constant [6 x i8] c"hello\00"
@.str.1 = private unnamed_addr constant [6 x i8] c"world\00"

define i64 @cat(i64 %a, i64 %b) {
entry:
  %t$0 = call i64 @str_concat(i64 %a, i64 %b)
  ret i64 %t$0
}

define i64 @__sprout_user_main() {
entry:
  %t$0 = getelementptr inbounds [6 x i8], ptr @.str.0, i64 0, i64 0
  %t$1 = ptrtoint ptr %t$0 to i64
  %t$2 = getelementptr inbounds [6 x i8], ptr @.str.1, i64 0, i64 0
  %t$3 = ptrtoint ptr %t$2 to i64
  %t$4 = call i64 @cat(i64 %t$1, i64 %t$3)
  %t$5$ptr = inttoptr i64 %t$4 to ptr
  %t$5 = call i64 @print_str(ptr %t$5$ptr)
  ret i64 %t$5
}

define i32 @main(i32 %argc, ptr %argv) {
entry:
  call i64 @__sprout_user_main()
  ret i32 0
}

