"""
Stage-2 emit-IR smoke tests.

Stage-2 is compile_driver_bin_stage2 — the Sprout compiler compiled by stage-1.
Tests skip gracefully when the binary is absent (run `just build-stage2` to produce it).

Three shapes cover distinct code paths (intentionally lightweight — the self-compile
test is the heavy-weight gate):

  noparam     — top-level fn with no parameters; baseline
  strconcat   — ++ with function parameters; exercises str_concat path
  adtmatch    — fn taking an ADT and doing a pattern match; exercises emit_branches
"""
from __future__ import annotations

import os
import subprocess
import tempfile
import textwrap
import unittest
from pathlib import Path

from tests.ir_health import assert_valid_ir

ROOT = Path(__file__).resolve().parent.parent
STDLIB = ROOT / "stdlib"
STAGE2_BINARY = ROOT / "compile_driver_bin_stage2"

STAGE2_SKIP_MSG = "compile_driver_bin_stage2 not found; run: just build-stage2"

# ---------------------------------------------------------------------------
# Source snippets
# ---------------------------------------------------------------------------

SHAPES: dict[str, str] = {
    "noparam": textwrap.dedent("""\
        fn val() -> Int = 42
        fn main() -> Unit !{IO} = print(val())
    """),
    "strconcat": textwrap.dedent("""\
        fn greet(name: String) -> String = "Hello, " ++ name
        fn main() -> Unit !{IO} = print(greet("world"))
    """),
    "adtmatch": textwrap.dedent("""\
        type Color = Red | Green | Blue
        fn code(c: Color) -> Int =
          match c with
          | Red   -> 0
          | Green -> 1
          | Blue  -> 2
        fn main() -> Unit !{IO} = print(code(Green))
    """),
}


# ---------------------------------------------------------------------------
# Shared helper
# ---------------------------------------------------------------------------

def _run_emit_ir(source: str) -> subprocess.CompletedProcess[str]:
    """Write source to a temp file and run stage-2 --emit-ir stdlib <file>."""
    with tempfile.NamedTemporaryFile(
        suffix=".spr", mode="w", delete=False, encoding="utf-8"
    ) as f:
        f.write(source)
        tmp_path = f.name
    try:
        return subprocess.run(
            [str(STAGE2_BINARY), "--emit-ir", str(STDLIB), tmp_path],
            capture_output=True,
            encoding="utf-8",
            errors="replace",
            cwd=str(ROOT),
            timeout=60,
        )
    finally:
        os.unlink(tmp_path)


# ---------------------------------------------------------------------------
# Stage-2 emit-IR tests
# ---------------------------------------------------------------------------

class Stage2EmitIrTests(unittest.TestCase):
    """compile_driver_bin_stage2 --emit-ir smoke tests (requires just build-stage2)."""

    @classmethod
    def setUpClass(cls) -> None:
        if not STAGE2_BINARY.exists():
            raise unittest.SkipTest(STAGE2_SKIP_MSG)


def _make_stage2_shape_test(shape_name: str, source: str):
    def test(self: unittest.TestCase) -> None:
        result = _run_emit_ir(source)
        if result.returncode != 0:
            self.fail(
                f"stage-2/{shape_name}: emit-ir exited {result.returncode}\n"
                f"stderr: {result.stderr[:2000]}\n"
                f"stdout: {result.stdout[:500]}"
            )
        assert_valid_ir(self, result.stdout, f"stage-2/{shape_name}")
    test.__name__ = f"test_{shape_name}"
    return test


for _name, _src in SHAPES.items():
    setattr(Stage2EmitIrTests, f"test_{_name}", _make_stage2_shape_test(_name, _src))


# ---------------------------------------------------------------------------
# Stage-2 self-compile test
# ---------------------------------------------------------------------------

class Stage2SelfCompileTests(unittest.TestCase):
    """Stage-2 compiles compile_driver.sprout without errors."""

    @classmethod
    def setUpClass(cls) -> None:
        if not STAGE2_BINARY.exists():
            raise unittest.SkipTest(STAGE2_SKIP_MSG)

    def test_self_compile(self) -> None:
        """Stage-2 compiles the compiler source without errors."""
        compile_driver = ROOT / "stdlib" / "compiler" / "compile_driver.sprout"
        r = subprocess.run(
            [str(STAGE2_BINARY), "--emit-ir", str(STDLIB), str(compile_driver)],
            capture_output=True,
            encoding="utf-8",
            errors="replace",
            cwd=str(ROOT),
            timeout=120,
        )
        error_lines = [line for line in r.stderr.splitlines() if "ERROR:" in line]
        self.assertEqual(
            error_lines,
            [],
            msg="self_compile: unexpected errors:\n" + "\n".join(error_lines),
        )
        self.assertEqual(r.returncode, 0, msg=f"self_compile: exit {r.returncode}\n{r.stderr[:500]}")
        self.assertIn("; Generated by sprout codegen.sprout", r.stdout[:200],
                      msg="self_compile: stdout does not look like valid LLVM IR")


if __name__ == "__main__":
    unittest.main()
