#!/usr/bin/env bash
# Benchmark: `++` chain vs backtick template, across part count x part length.
#
# Produces the measurement table in docs/string-building-v0.md. Run it when you
# want to re-verify those numbers, or after a change to the template lowering
# (ast_to_ir), to `str_concat` / `string_concat_many`, or to the GC's allocation
# path — any of those can move the crossover.
#
# Deliberately NOT a gate. The output is a timing, which is machine- and
# load-dependent; asserting a threshold on it would produce a flaky red that says
# nothing about correctness. It is a measurement tool, run on purpose.
#
# Usage:  just bench-string-concat            (defaults below)
#         ITERS=50000 just bench-string-concat
#
# Env:
#   DRIVER  stage-1 compiler          (default build/compile_driver_bin_stage1)
#   ITERS   loop iterations per cell  (default 200000)
#   REPS    timed repeats per binary  (default 3; best-of is reported)
#
# LOWERING ITERS MAKES THE RESULT NOISE, NOT A FASTER MEASUREMENT. At
# ITERS=20000 REPS=1 the cells land in the 16-60ms range, where scheduling jitter
# is a larger effect than the thing being measured: one such run reported
# "template faster 2.27x" for 8 short parts, a cell the default settings show as
# `++` faster 1.39x — i.e. it inverted the winner. The script warns below when the
# settings are too low to trust; treat a sub-100ms cell as unmeasured.
set -uo pipefail

DRIVER="${DRIVER:-build/compile_driver_bin_stage1}"
ITERS="${ITERS:-200000}"
REPS="${REPS:-3}"
STDLIB="${STDLIB:-stdlib}"
CLANG_EXTRA="${CLANG_EXTRA:-}"

if [[ ! -x "$DRIVER" ]]; then
  echo "bench-string-concat: $DRIVER not found — run: just bootstrap-from-seed" >&2
  exit 1
fi

TMPD=$(mktemp -d /tmp/sprout_bench_concat_XXXXXX)
trap 'rm -rf "$TMPD"' EXIT

PART_COUNTS=(2 4 8 16 32)
PART_LENS=(4 40 400)

# A part of exactly $1 characters.
mk_part() {
  local n="$1" s=""
  while (( ${#s} < n )); do s="${s}abcdefghij"; done
  printf '%s' "${s:0:n}"
}

# Emit one benchmark program. $1=form (append|template) $2=parts $3=part length.
#
# Parts are pre-bound `String` values, so the measurement isolates the CONCAT
# mechanism — no int_to_string in the loop. The accumulator sums str_len of each
# result so the work cannot be optimized away.
gen() {
  local form="$1" n="$2" ln="$3" val expr binds i
  val="$(mk_part "$ln")"
  binds=""
  expr=""
  for (( i = 0; i < n; i++ )); do
    binds="${binds}    p${i} = \"${val}\"
"
    if [[ "$form" == "append" ]]; then
      [[ -n "$expr" ]] && expr="${expr} ++ "
      expr="${expr}p${i}"
    else
      expr="${expr}\${p${i}}"
    fi
  done
  [[ "$form" == "template" ]] && expr="\`${expr}\`"

  cat <<EOF
# ${form}: ${n} parts x ${ln} chars — generated by scripts/bench_string_concat.sh
fn build() -> String =
  ${expr}
  where
${binds}
fn loop(i: Int, acc: Int) -> Int =
  if i <= 0 then acc else loop(i - 1, acc + str_len(build()))

fn main() -> Unit !{IO} = print(loop(${ITERS}, 0))
EOF
}

now_ms() { python3 -c 'import time;print(int(time.time()*1000))'; }

# Best-of-$REPS wall clock. Best-of, not mean: a background hiccup can only
# inflate a sample, so the minimum is the least-noisy achievable time.
best_ms() {
  local bin="$1" best=99999999 s e t r
  for (( r = 0; r < REPS; r++ )); do
    s=$(now_ms); "$bin" >/dev/null 2>&1; e=$(now_ms)
    t=$(( e - s ))
    (( t < best )) && best=$t
  done
  printf '%s' "$best"
}

build_one() {
  # Split declarations: `local a=$1 b=${a}` would trip `set -u`, because `local`
  # brings every name into scope BEFORE assigning any of them, so `a` is
  # declared-but-unset while `b`'s initializer is evaluated.
  local form="$1" n="$2" ln="$3"
  local base="${form}_n${n}_l${ln}"
  gen "$form" "$n" "$ln" > "$TMPD/$base.spr"
  if ! "$DRIVER" --emit-ir "$STDLIB" "$TMPD/$base.spr" > "$TMPD/$base.ll" 2>"$TMPD/$base.err"; then
    echo "bench-string-concat: emit-IR failed for $base" >&2
    head -3 "$TMPD/$base.err" >&2
    return 1
  fi
  # shellcheck disable=SC2086
  if ! clang "$TMPD/$base.ll" runtime/*.c -O2 $CLANG_EXTRA -o "$TMPD/$base.bin" 2>"$TMPD/$base.link"; then
    echo "bench-string-concat: link failed for $base" >&2
    head -3 "$TMPD/$base.link" >&2
    return 1
  fi
  printf '%s' "$TMPD/$base.bin"
}

echo "==> bench-string-concat: ITERS=$ITERS REPS=$REPS (best-of-$REPS wall clock)"
echo

printf '%6s %9s %11s | %9s %9s | %s\n' \
  "parts" "part len" "result" "++ (ms)" "tpl (ms)" "winner"
printf '%6s-%9s-%11s-+-%9s-%9s-+-%s\n' \
  "------" "---------" "-----------" "---------" "---------" "----------------------"

fail=0
noisy=0
for n in "${PART_COUNTS[@]}"; do
  for ln in "${PART_LENS[@]}"; do
    abin=$(build_one append   "$n" "$ln") || { fail=1; continue; }
    tbin=$(build_one template "$n" "$ln") || { fail=1; continue; }

    # Correctness guard: both forms must compute the same thing, or the timing
    # compares two different programs.
    aout=$("$abin"); tout=$("$tbin")
    if [[ "$aout" != "$tout" ]]; then
      echo "bench-string-concat: MISMATCH at n=$n len=$ln ('$aout' vs '$tout') — not comparable" >&2
      fail=1; continue
    fi

    a=$(best_ms "$abin"); t=$(best_ms "$tbin")
    if (( a < t )); then
      w="++ faster ($(python3 -c "print(f'{$t/max($a,1):.2f}x')"))"
    elif (( t < a )); then
      w="template faster ($(python3 -c "print(f'{$a/max($t,1):.2f}x')"))"
    else
      w="tie"
    fi
    # Flag cells too short to be signal. Under ~100ms, scheduling jitter can
    # exceed the difference and has been observed inverting the winner, so the
    # row is reported but marked rather than quietly believed.
    if (( a < 100 || t < 100 )); then
      w="$w  [NOISY: <100ms, raise ITERS]"
      noisy=$(( noisy + 1 ))
    fi
    printf '%6d %9d %11d | %9d %9d | %s\n' "$n" "$ln" "$(( n * ln ))" "$a" "$t" "$w"
  done
done

echo
if (( fail )); then
  echo "==> bench-string-concat: completed with failures" >&2
  exit 1
fi
if (( noisy )); then
  echo "==> $noisy of 15 cells ran under 100ms and are NOT trustworthy." >&2
  echo "    Re-run with a higher ITERS (default 200000) before believing them;" >&2
  echo "    a sub-100ms cell has been seen reporting the wrong winner." >&2
fi
echo "==> bench-string-concat ✓  (interpretation: docs/string-building-v0.md)"
