from __future__ import annotations

from dataclasses import dataclass

from . import ast


class CodegenError(ValueError):
    pass


@dataclass(frozen=True)
class LLType:
    text: str


I64 = LLType("i64")
I1 = LLType("i1")


@dataclass
class FnSig:
    name: str
    params: list[LLType]
    ret: LLType


EXTERN_SIGS: dict[str, FnSig] = {
    "print_int": FnSig(name="print_int", params=[I64], ret=I64),
}


@dataclass
class Value:
    typ: LLType
    ir: str


class Emitter:
    def __init__(self) -> None:
        self.lines: list[str] = []
        self.next_tmp = 0
        self.next_block = 0

    def emit(self, line: str) -> None:
        self.lines.append(line)

    def tmp(self) -> str:
        name = f"%t{self.next_tmp}"
        self.next_tmp += 1
        return name

    def block(self, prefix: str) -> str:
        name = f"{prefix}{self.next_block}"
        self.next_block += 1
        return name


def _type_from_ast(node: ast.TypeExpr | None) -> LLType:
    if node is None:
        raise CodegenError("Function return type annotation is required for native codegen")
    if isinstance(node, ast.TypeName):
        if node.name == "Int":
            return I64
        if node.name == "Bool":
            return I1
    raise CodegenError(f"Unsupported type for LLVM backend: {node}")


def _check_param_type(node: ast.TypeExpr) -> LLType:
    if isinstance(node, ast.TypeName):
        if node.name == "Int":
            return I64
        if node.name == "Bool":
            return I1
    raise CodegenError(f"Unsupported parameter type for LLVM backend: {node}")


def compile_to_llvm(program: ast.Program) -> str:
    fn_decls = [d for d in program.declarations if isinstance(d, ast.FnDecl)]
    other = [d for d in program.declarations if not isinstance(d, ast.FnDecl)]
    if other:
        raise CodegenError("LLVM backend currently supports function declarations only")

    sigs: dict[str, FnSig] = {}
    for fn in fn_decls:
        if fn.name in sigs:
            raise CodegenError(f"Duplicate function {fn.name}")
        params = [_check_param_type(p.type_expr) for p in fn.params]
        ret = _type_from_ast(fn.return_type)
        sigs[fn.name] = FnSig(fn.name, params, ret)

    emitter = Emitter()
    emitter.emit("; Generated by sprout LLVM backend (v0)")
    emitter.emit("target triple = \"unknown-unknown-unknown\"")
    emitter.emit("")
    for ext in EXTERN_SIGS.values():
        params = ", ".join(t.text for t in ext.params)
        emitter.emit(f"declare {ext.ret.text} @{ext.name}({params})")
    emitter.emit("")

    for fn in fn_decls:
        _emit_fn(fn, sigs, emitter)
        emitter.emit("")

    return "\n".join(emitter.lines).rstrip() + "\n"


def _emit_fn(fn: ast.FnDecl, sigs: dict[str, FnSig], emitter: Emitter) -> None:
    sig = sigs[fn.name]
    params = []
    locals_: dict[str, Value] = {}
    for p, typ in zip(fn.params, sig.params):
        pname = f"%{p.name}"
        params.append(f"{typ.text} {pname}")
        locals_[p.name] = Value(typ=typ, ir=pname)

    emitter.emit(f"define {sig.ret.text} @{fn.name}({', '.join(params)}) {{")
    emitter.emit("entry:")
    ret = _emit_expr(fn.body, locals_, sigs, emitter)
    if ret.typ != sig.ret:
        raise CodegenError(f"Function {fn.name} body type mismatch in backend: {ret.typ.text} vs {sig.ret.text}")
    emitter.emit(f"  ret {ret.typ.text} {ret.ir}")
    emitter.emit("}")


def _emit_expr(expr: ast.Expr, locals_: dict[str, Value], sigs: dict[str, FnSig], emitter: Emitter) -> Value:
    if isinstance(expr, ast.IntExpr):
        return Value(I64, str(expr.value))
    if isinstance(expr, ast.BoolExpr):
        return Value(I1, "1" if expr.value else "0")
    if isinstance(expr, ast.VarExpr):
        val = locals_.get(expr.name)
        if val is None:
            raise CodegenError(f"Unknown local variable in backend: {expr.name}")
        return val
    if isinstance(expr, ast.UnaryExpr):
        operand = _emit_expr(expr.operand, locals_, sigs, emitter)
        if expr.op == "-":
            if operand.typ != I64:
                raise CodegenError("Unary '-' backend supports Int only")
            tmp = emitter.tmp()
            emitter.emit(f"  {tmp} = sub i64 0, {operand.ir}")
            return Value(I64, tmp)
        raise CodegenError(f"Unsupported unary op in backend: {expr.op}")
    if isinstance(expr, ast.BinaryExpr):
        return _emit_binary(expr, locals_, sigs, emitter)
    if isinstance(expr, ast.IfExpr):
        return _emit_if(expr, locals_, sigs, emitter)
    if isinstance(expr, ast.CallExpr):
        return _emit_call(expr, locals_, sigs, emitter)

    raise CodegenError(f"Unsupported expression in LLVM backend: {expr.__class__.__name__}")


def _emit_binary(expr: ast.BinaryExpr, locals_: dict[str, Value], sigs: dict[str, FnSig], emitter: Emitter) -> Value:
    if expr.op in {"&&", "||"}:
        raise CodegenError("Logical short-circuit ops are not yet supported by LLVM backend")

    left = _emit_expr(expr.left, locals_, sigs, emitter)
    right = _emit_expr(expr.right, locals_, sigs, emitter)

    if expr.op in {"+", "-", "*", "/"}:
        if left.typ != I64 or right.typ != I64:
            raise CodegenError(f"Arithmetic op {expr.op} expects Int")
        tmp = emitter.tmp()
        inst = {"+": "add", "-": "sub", "*": "mul", "/": "sdiv"}[expr.op]
        emitter.emit(f"  {tmp} = {inst} i64 {left.ir}, {right.ir}")
        return Value(I64, tmp)

    if expr.op in {"<", "<=", ">", ">=", "==", "!="}:
        if left.typ != right.typ:
            raise CodegenError("Comparison operands must have same type")
        tmp = emitter.tmp()
        pred = {
            "<": "slt",
            "<=": "sle",
            ">": "sgt",
            ">=": "sge",
            "==": "eq",
            "!=": "ne",
        }[expr.op]
        emitter.emit(f"  {tmp} = icmp {pred} {left.typ.text} {left.ir}, {right.ir}")
        return Value(I1, tmp)

    raise CodegenError(f"Unsupported binary op in backend: {expr.op}")


def _emit_if(expr: ast.IfExpr, locals_: dict[str, Value], sigs: dict[str, FnSig], emitter: Emitter) -> Value:
    cond = _emit_expr(expr.condition, locals_, sigs, emitter)
    if cond.typ != I1:
        raise CodegenError("if condition must be Bool")

    then_label = emitter.block("if_then")
    else_label = emitter.block("if_else")
    done_label = emitter.block("if_done")
    emitter.emit(f"  br i1 {cond.ir}, label %{then_label}, label %{else_label}")

    emitter.emit(f"{then_label}:")
    then_val = _emit_expr(expr.then_branch, locals_, sigs, emitter)
    emitter.emit(f"  br label %{done_label}")

    emitter.emit(f"{else_label}:")
    else_val = _emit_expr(expr.else_branch, locals_, sigs, emitter)
    emitter.emit(f"  br label %{done_label}")

    if then_val.typ != else_val.typ:
        raise CodegenError("if branches must have same type")

    emitter.emit(f"{done_label}:")
    phi = emitter.tmp()
    emitter.emit(
        f"  {phi} = phi {then_val.typ.text} [ {then_val.ir}, %{then_label} ], [ {else_val.ir}, %{else_label} ]"
    )
    return Value(then_val.typ, phi)


def _emit_call(expr: ast.CallExpr, locals_: dict[str, Value], sigs: dict[str, FnSig], emitter: Emitter) -> Value:
    if not isinstance(expr.callee, ast.VarExpr):
        raise CodegenError("Backend supports direct function calls only")
    fn_name = expr.callee.name
    sig = sigs.get(fn_name)
    if sig is None:
        sig = EXTERN_SIGS.get(fn_name)
    if sig is None:
        raise CodegenError(f"Unknown function in backend call: {fn_name}")
    if len(expr.args) != len(sig.params):
        raise CodegenError(f"Function {fn_name} expects {len(sig.params)} args, got {len(expr.args)}")

    args_ir: list[str] = []
    for arg_expr, param_type in zip(expr.args, sig.params):
        arg_val = _emit_expr(arg_expr, locals_, sigs, emitter)
        if arg_val.typ != param_type:
            raise CodegenError(f"Call type mismatch for {fn_name}")
        args_ir.append(f"{param_type.text} {arg_val.ir}")

    tmp = emitter.tmp()
    emitter.emit(f"  {tmp} = call {sig.ret.text} @{fn_name}({', '.join(args_ir)})")
    return Value(sig.ret, tmp)
