from __future__ import annotations

from dataclasses import dataclass

from . import ast


class CodegenError(ValueError):
    pass


@dataclass(frozen=True)
class LLType:
    text: str


I64 = LLType("i64")
I1 = LLType("i1")


@dataclass
class FnSig:
    name: str
    params: list[LLType]
    ret: LLType


EXTERN_SIGS: dict[str, FnSig] = {
    "print_int": FnSig(name="print_int", params=[I64], ret=I64),
}


@dataclass
class Value:
    typ: LLType
    ir: str


@dataclass
class GlobalConst:
    typ: LLType
    value_ir: str


class Emitter:
    def __init__(self) -> None:
        self.lines: list[str] = []
        self.next_tmp = 0
        self.next_block = 0
        self.current_block: str | None = None

    def emit(self, line: str) -> None:
        self.lines.append(line)

    def label(self, name: str) -> None:
        self.lines.append(f"{name}:")
        self.current_block = name

    def tmp(self) -> str:
        name = f"%t{self.next_tmp}"
        self.next_tmp += 1
        return name

    def block(self, prefix: str) -> str:
        name = f"{prefix}{self.next_block}"
        self.next_block += 1
        return name


def _type_from_ast(node: ast.TypeExpr | None) -> LLType:
    if node is None:
        raise CodegenError("Function return type annotation is required for native codegen")
    if isinstance(node, ast.TypeName):
        if node.name == "Int":
            return I64
        if node.name == "Bool":
            return I1
    raise CodegenError(f"Unsupported type for LLVM backend: {node}")


def _check_param_type(node: ast.TypeExpr) -> LLType:
    if isinstance(node, ast.TypeName):
        if node.name == "Int":
            return I64
        if node.name == "Bool":
            return I1
    raise CodegenError(f"Unsupported parameter type for LLVM backend: {node}")


def compile_to_llvm(program: ast.Program) -> str:
    fn_decls = [d for d in program.declarations if isinstance(d, ast.FnDecl)]
    let_decls = [d for d in program.declarations if isinstance(d, ast.LetDecl)]
    other = [
        d
        for d in program.declarations
        if not isinstance(d, ast.FnDecl) and not isinstance(d, ast.LetDecl)
    ]
    if other:
        raise CodegenError("LLVM backend currently supports function declarations and top-level let only")

    sigs: dict[str, FnSig] = {}
    for fn in fn_decls:
        if fn.name in sigs:
            raise CodegenError(f"Duplicate function {fn.name}")
        params = [_check_param_type(p.type_expr) for p in fn.params]
        ret = _type_from_ast(fn.return_type)
        sigs[fn.name] = FnSig(fn.name, params, ret)

    globals_: dict[str, GlobalConst] = {}
    for let_decl in let_decls:
        if let_decl.name in globals_:
            raise CodegenError(f"Duplicate global let {let_decl.name}")
        globals_[let_decl.name] = _eval_const_expr(let_decl.value, globals_)

    emitter = Emitter()
    emitter.emit("; Generated by sprout LLVM backend (v0)")
    emitter.emit("target triple = \"unknown-unknown-unknown\"")
    emitter.emit("")
    for name, glob in globals_.items():
        emitter.emit(f"@{name} = private constant {glob.typ.text} {glob.value_ir}")
    if globals_:
        emitter.emit("")
    for ext in EXTERN_SIGS.values():
        params = ", ".join(t.text for t in ext.params)
        emitter.emit(f"declare {ext.ret.text} @{ext.name}({params})")
    emitter.emit("")

    for fn in fn_decls:
        _emit_fn(fn, sigs, globals_, emitter)
        emitter.emit("")

    return "\n".join(emitter.lines).rstrip() + "\n"


def _eval_const_expr(expr: ast.Expr, globals_: dict[str, GlobalConst]) -> GlobalConst:
    if isinstance(expr, ast.IntExpr):
        return GlobalConst(I64, str(expr.value))
    if isinstance(expr, ast.BoolExpr):
        return GlobalConst(I1, "1" if expr.value else "0")
    if isinstance(expr, ast.VarExpr):
        ref = globals_.get(expr.name)
        if ref is None:
            raise CodegenError(f"Global let constant references unknown name: {expr.name}")
        return ref
    if isinstance(expr, ast.UnaryExpr) and expr.op == "-":
        operand = _eval_const_expr(expr.operand, globals_)
        if operand.typ != I64:
            raise CodegenError("Global let unary '-' expects Int")
        return GlobalConst(I64, str(-int(operand.value_ir)))
    if isinstance(expr, ast.BinaryExpr):
        left = _eval_const_expr(expr.left, globals_)
        right = _eval_const_expr(expr.right, globals_)
        if expr.op in {"+", "-", "*", "/"}:
            if left.typ != I64 or right.typ != I64:
                raise CodegenError(f"Global let arithmetic op {expr.op} expects Int")
            a = int(left.value_ir)
            b = int(right.value_ir)
            if expr.op == "+":
                return GlobalConst(I64, str(a + b))
            if expr.op == "-":
                return GlobalConst(I64, str(a - b))
            if expr.op == "*":
                return GlobalConst(I64, str(a * b))
            return GlobalConst(I64, str(a // b))
        if expr.op in {"<", "<=", ">", ">=", "==", "!="}:
            if left.typ != right.typ:
                raise CodegenError("Global let comparison operands must have same type")
            if left.typ == I64:
                a = int(left.value_ir)
                b = int(right.value_ir)
            elif left.typ == I1:
                a = left.value_ir == "1"
                b = right.value_ir == "1"
            else:
                raise CodegenError("Unsupported global let comparison type")
            out = {
                "<": a < b,
                "<=": a <= b,
                ">": a > b,
                ">=": a >= b,
                "==": a == b,
                "!=": a != b,
            }[expr.op]
            return GlobalConst(I1, "1" if out else "0")
        if expr.op in {"&&", "||"}:
            if left.typ != I1 or right.typ != I1:
                raise CodegenError(f"Global let logical op {expr.op} expects Bool")
            a = left.value_ir == "1"
            b = right.value_ir == "1"
            out = (a and b) if expr.op == "&&" else (a or b)
            return GlobalConst(I1, "1" if out else "0")
    if isinstance(expr, ast.IfExpr):
        cond = _eval_const_expr(expr.condition, globals_)
        if cond.typ != I1:
            raise CodegenError("Global let if condition must be Bool")
        branch = expr.then_branch if cond.value_ir == "1" else expr.else_branch
        return _eval_const_expr(branch, globals_)
    raise CodegenError("Top-level let in LLVM backend must be compile-time constant expression")


def _emit_fn(
    fn: ast.FnDecl,
    sigs: dict[str, FnSig],
    globals_: dict[str, GlobalConst],
    emitter: Emitter,
) -> None:
    sig = sigs[fn.name]
    params = []
    locals_: dict[str, Value] = {}
    for p, typ in zip(fn.params, sig.params):
        pname = f"%{p.name}"
        params.append(f"{typ.text} {pname}")
        locals_[p.name] = Value(typ=typ, ir=pname)

    emitter.emit(f"define {sig.ret.text} @{fn.name}({', '.join(params)}) {{")
    emitter.label("entry")
    ret = _emit_expr(fn.body, locals_, globals_, sigs, emitter)
    if ret.typ != sig.ret:
        raise CodegenError(f"Function {fn.name} body type mismatch in backend: {ret.typ.text} vs {sig.ret.text}")
    emitter.emit(f"  ret {ret.typ.text} {ret.ir}")
    emitter.emit("}")


def _emit_expr(
    expr: ast.Expr,
    locals_: dict[str, Value],
    globals_: dict[str, GlobalConst],
    sigs: dict[str, FnSig],
    emitter: Emitter,
) -> Value:
    if isinstance(expr, ast.IntExpr):
        return Value(I64, str(expr.value))
    if isinstance(expr, ast.BoolExpr):
        return Value(I1, "1" if expr.value else "0")
    if isinstance(expr, ast.VarExpr):
        val = locals_.get(expr.name)
        if val is not None:
            return val
        global_const = globals_.get(expr.name)
        if global_const is not None:
            tmp = emitter.tmp()
            emitter.emit(f"  {tmp} = load {global_const.typ.text}, ptr @{expr.name}")
            return Value(global_const.typ, tmp)
        raise CodegenError(f"Unknown variable in backend: {expr.name}")
    if isinstance(expr, ast.UnaryExpr):
        operand = _emit_expr(expr.operand, locals_, globals_, sigs, emitter)
        if expr.op == "-":
            if operand.typ != I64:
                raise CodegenError("Unary '-' backend supports Int only")
            tmp = emitter.tmp()
            emitter.emit(f"  {tmp} = sub i64 0, {operand.ir}")
            return Value(I64, tmp)
        raise CodegenError(f"Unsupported unary op in backend: {expr.op}")
    if isinstance(expr, ast.BinaryExpr):
        return _emit_binary(expr, locals_, globals_, sigs, emitter)
    if isinstance(expr, ast.IfExpr):
        return _emit_if(expr, locals_, globals_, sigs, emitter)
    if isinstance(expr, ast.CallExpr):
        return _emit_call(expr, locals_, globals_, sigs, emitter)

    raise CodegenError(f"Unsupported expression in LLVM backend: {expr.__class__.__name__}")


def _emit_binary(
    expr: ast.BinaryExpr,
    locals_: dict[str, Value],
    globals_: dict[str, GlobalConst],
    sigs: dict[str, FnSig],
    emitter: Emitter,
) -> Value:
    if expr.op in {"&&", "||"}:
        return _emit_short_circuit(expr, locals_, globals_, sigs, emitter)

    left = _emit_expr(expr.left, locals_, globals_, sigs, emitter)
    right = _emit_expr(expr.right, locals_, globals_, sigs, emitter)

    if expr.op in {"+", "-", "*", "/"}:
        if left.typ != I64 or right.typ != I64:
            raise CodegenError(f"Arithmetic op {expr.op} expects Int")
        tmp = emitter.tmp()
        inst = {"+": "add", "-": "sub", "*": "mul", "/": "sdiv"}[expr.op]
        emitter.emit(f"  {tmp} = {inst} i64 {left.ir}, {right.ir}")
        return Value(I64, tmp)

    if expr.op in {"<", "<=", ">", ">=", "==", "!="}:
        if left.typ != right.typ:
            raise CodegenError("Comparison operands must have same type")
        tmp = emitter.tmp()
        pred = {
            "<": "slt",
            "<=": "sle",
            ">": "sgt",
            ">=": "sge",
            "==": "eq",
            "!=": "ne",
        }[expr.op]
        emitter.emit(f"  {tmp} = icmp {pred} {left.typ.text} {left.ir}, {right.ir}")
        return Value(I1, tmp)

    raise CodegenError(f"Unsupported binary op in backend: {expr.op}")


def _emit_short_circuit(
    expr: ast.BinaryExpr,
    locals_: dict[str, Value],
    globals_: dict[str, GlobalConst],
    sigs: dict[str, FnSig],
    emitter: Emitter,
) -> Value:
    left = _emit_expr(expr.left, locals_, globals_, sigs, emitter)
    if left.typ != I1:
        raise CodegenError(f"Logical op {expr.op} expects Bool")
    left_block = emitter.current_block
    if left_block is None:
        raise CodegenError("Internal backend error: missing current block for logical op")

    rhs_label = emitter.block("logic_rhs")
    done_label = emitter.block("logic_done")
    if expr.op == "&&":
        emitter.emit(f"  br i1 {left.ir}, label %{rhs_label}, label %{done_label}")
        const_on_short = "0"
    else:
        emitter.emit(f"  br i1 {left.ir}, label %{done_label}, label %{rhs_label}")
        const_on_short = "1"

    emitter.label(rhs_label)
    right = _emit_expr(expr.right, locals_, globals_, sigs, emitter)
    if right.typ != I1:
        raise CodegenError(f"Logical op {expr.op} expects Bool")
    rhs_end = emitter.current_block
    if rhs_end is None:
        raise CodegenError("Internal backend error: missing rhs block for logical op")
    emitter.emit(f"  br label %{done_label}")

    emitter.label(done_label)
    phi = emitter.tmp()
    emitter.emit(
        f"  {phi} = phi i1 [ {const_on_short}, %{left_block} ], [ {right.ir}, %{rhs_end} ]"
    )
    return Value(I1, phi)


def _emit_if(
    expr: ast.IfExpr,
    locals_: dict[str, Value],
    globals_: dict[str, GlobalConst],
    sigs: dict[str, FnSig],
    emitter: Emitter,
) -> Value:
    cond = _emit_expr(expr.condition, locals_, globals_, sigs, emitter)
    if cond.typ != I1:
        raise CodegenError("if condition must be Bool")

    then_label = emitter.block("if_then")
    else_label = emitter.block("if_else")
    done_label = emitter.block("if_done")
    emitter.emit(f"  br i1 {cond.ir}, label %{then_label}, label %{else_label}")

    emitter.label(then_label)
    then_val = _emit_expr(expr.then_branch, locals_, globals_, sigs, emitter)
    then_end = emitter.current_block
    if then_end is None:
        raise CodegenError("Internal backend error: missing then block")
    emitter.emit(f"  br label %{done_label}")

    emitter.label(else_label)
    else_val = _emit_expr(expr.else_branch, locals_, globals_, sigs, emitter)
    else_end = emitter.current_block
    if else_end is None:
        raise CodegenError("Internal backend error: missing else block")
    emitter.emit(f"  br label %{done_label}")

    if then_val.typ != else_val.typ:
        raise CodegenError("if branches must have same type")

    emitter.label(done_label)
    phi = emitter.tmp()
    emitter.emit(
        f"  {phi} = phi {then_val.typ.text} [ {then_val.ir}, %{then_end} ], [ {else_val.ir}, %{else_end} ]"
    )
    return Value(then_val.typ, phi)


def _emit_call(
    expr: ast.CallExpr,
    locals_: dict[str, Value],
    globals_: dict[str, GlobalConst],
    sigs: dict[str, FnSig],
    emitter: Emitter,
) -> Value:
    if not isinstance(expr.callee, ast.VarExpr):
        raise CodegenError("Backend supports direct function calls only")
    fn_name = expr.callee.name
    sig = sigs.get(fn_name)
    if sig is None:
        sig = EXTERN_SIGS.get(fn_name)
    if sig is None:
        raise CodegenError(f"Unknown function in backend call: {fn_name}")
    if len(expr.args) != len(sig.params):
        raise CodegenError(f"Function {fn_name} expects {len(sig.params)} args, got {len(expr.args)}")

    args_ir: list[str] = []
    for arg_expr, param_type in zip(expr.args, sig.params):
        arg_val = _emit_expr(arg_expr, locals_, globals_, sigs, emitter)
        if arg_val.typ != param_type:
            raise CodegenError(f"Call type mismatch for {fn_name}")
        args_ir.append(f"{param_type.text} {arg_val.ir}")

    tmp = emitter.tmp()
    emitter.emit(f"  {tmp} = call {sig.ret.text} @{fn_name}({', '.join(args_ir)})")
    return Value(sig.ret, tmp)
